### PR TITLE
DietPi-Software | Bazarr

### LINKED ISSUE #2045: DietPi-Software | Bazarr
#### Give us some formal software information:
- Software title | Bazarr
- Short description | Manage and download subtitles, companion to Sonarr and Radarr.
- GitHub URL (if available) | https://github.com/morpheus65535/bazarr
- (Official) install documentation | https://github.com/morpheus65535/bazarr/wiki/Installation#linux

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
- It needs git and jpeg support, and python with pip requirements

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.
- Yes, I could help out with this

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Testing**:
- [x] VM Buster
- [x] VM Bullseye
- [x] VM Stretch: 🈴 No support due to Python >=3.7.0 requirement
- [x] RPi Buster

**Commit list/description**:
+ DietPi-Software | Bazarr: Companion application to Sonarr and Radarr to automatically download and manage subtitles, now available for install via dietpi-software

### CODE REVIEW

**Comment by MichaIng** [comment]
I would love to skip the Windows, MacOS and i386 binaries (ffmpeg + unrar) which make ~300 of 500 MiB of the repository size. But Git does not allow to skip parts of a repository, especially when `--depth 1` and similar cannot be used to keep allow switching branch for the updater. And we don't want to break any of the documented functionality.

**Comment by MichaIng** [comment]
Sadly the Python requirement is strict:
```
Sep 29 13:54:59 VM-Stretch systemd[1]: Started Bazarr Daemon (DietPi).
Sep 29 13:54:59 VM-Stretch Bazarr[2095]: Python 3.7.0 or greater required. Current version is 3.5.3. Please upgrade Python.
Sep 29 13:54:59 VM-Stretch systemd[1]: bazarr.service: Main process exited, code=exited, status=1/FAILURE
```
This means we cannot support it on Debian Stretch. Only possibility would be to go with a pyenv environment, means >=1 hour Python compiling (on RPi1 and Zero at least) etc, like with Home Assistant, a large overhead. Since we do not offer any Stretch image anymore, I'd leave our Stretch support for now unless there are many requests.

**Comment by MichaIng** [comment]
Online docs: https://dietpi.com/phpbb/viewtopic.php?p=27577#p27577

**Comment by MichaIng** [comment]
Idea:
- Configure Sonarr and Radarr automatically, when found, probably even configure Bazarr automatically, when found, during Sonarr and Radarr are installed (so both ways).
- Starting the Bazarr service temporarily allows to pre-create the default config file, which can then be manipulated.
- host/IP: `127.0.0.1`, port: `8787` (Sonarr) / `7878` (Radarr) would be it for our default Sonarr and Radarr setup.

**Done.** Especially API keys were required. This is now only done on fresh Bazarr installs to not risk manipulating custom settings, e.g. user configured connection to Sonarr on different server, now installs it on Bazarr machine but for testing only, and scenarios like that. Better be conservative in this case, especially since manual config is pretty simple as well.

**Comment by Joulinar** [comment]
@MichaIng 
I tried installation of Bazarr with beta branch on my RPi3b+, but it fails with following error
`unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory`

It's needed to perform `apt install gcc-arm-linux-gnueabihf` to get it working.

**Comment by MichaIng** [comment]
Do you see on while module/wheel build this happened? Looks like we need to install build-essentails to assure that all eventual dependency builds work on ARM.

**Comment by Joulinar** [comment]
Yep indeed it's happening during build. Do you need full log/error message?

Edit: There you go
<details>
  <summary>Logfile attached. Click to expand!</summary>

```
[  OK  ] DietPi-Software | cd /opt/bazarr
[ INFO ] DietPi-Software | pip3 install -r requirements.txt, please wait...
Requirement already satisfied: lxml>=4.3.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (4.3.2)
Requirement already satisfied: numpy>=1.12.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.16.2)
Collecting webrtcvad-wheels>=2.0.10
  Downloading webrtcvad-wheels-2.0.10.post2.tar.gz (67 kB)
Building wheels for collected packages: webrtcvad-wheels
  Building wheel for webrtcvad-wheels (setup.py): started
  Building wheel for webrtcvad-wheels (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kmgjlfbp/webrtcvad-wheels/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kmgjlfbp/webrtcvad-wheels/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mvc9aufx
       cwd: /tmp/pip-install-kmgjlfbp/webrtcvad-wheels/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.7
  copying webrtcvad.py -> build/lib.linux-armv7l-3.7
  running build_ext
  building '_webrtcvad' extension
  creating build/temp.linux-armv7l-3.7
  creating build/temp.linux-armv7l-3.7/cbits
  creating build/temp.linux-armv7l-3.7/cbits/webrtc
  creating build/temp.linux-armv7l-3.7/cbits/webrtc/common_audio
  creating build/temp.linux-armv7l-3.7/cbits/webrtc/common_audio/signal_processing
  creating build/temp.linux-armv7l-3.7/cbits/webrtc/common_audio/vad
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWEBRTC_POSIX -Icbits -I/usr/include/python3.7m -c cbits/pywebrtcvad.c -o build/temp.linux-armv7l-3.7/cbits/pywebrtcvad.o
  unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for webrtcvad-wheels
  Running setup.py clean for webrtcvad-wheels
Failed to build webrtcvad-wheels
Installing collected packages: webrtcvad-wheels
    Running setup.py install for webrtcvad-wheels: started
    Running setup.py install for webrtcvad-wheels: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kmgjlfbp/webrtcvad-wheels/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kmgjlfbp/webrtcvad-wheels/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v6emey3q/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/webrtcvad-wheels
         cwd: /tmp/pip-install-kmgjlfbp/webrtcvad-wheels/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    copying webrtcvad.py -> build/lib.linux-armv7l-3.7
    running build_ext
    building '_webrtcvad' extension
    creating build/temp.linux-armv7l-3.7
    creating build/temp.linux-armv7l-3.7/cbits
    creating build/temp.linux-armv7l-3.7/cbits/webrtc
    creating build/temp.linux-armv7l-3.7/cbits/webrtc/common_audio
    creating build/temp.linux-armv7l-3.7/cbits/webrtc/common_audio/signal_processing
    creating build/temp.linux-armv7l-3.7/cbits/webrtc/common_audio/vad
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWEBRTC_POSIX -Icbits -I/usr/include/python3.7m -c cbits/pywebrtcvad.c -o build/temp.linux-armv7l-3.7/cbits/pywebrtcvad.o
    unable to execute 'arm-linux-gnueabihf-gcc': No such file or directory
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kmgjlfbp/webrtcvad-wheels/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kmgjlfbp/webrtcvad-wheels/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v6emey3q/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/webrtcvad-wheels Check the logs for full command output.
[FAILED] DietPi-Software | pip3 install -r requirements.txt
```
</details>

**Comment by MichaIng** [comment]
What does Bazarr require WebRTC for?
...
https://github.com/morpheus65535/bazarr/commit/0209d1558aa970eaef35499422bc284f64129ad8
New with v0.9.0.4. It could even be skipped since the code contains a fallback to old method, but lets simply install build-essentials on ARM to be prepared for other possibly added Python dependencies.

Self-reminder: https://github.com/MichaIng/DietPi/pull/3796#issuecomment-700566595
- [x] Open an issue at Bazarr repo to request for optional binary downloads but excluding/.gitignoring them from the default clone.

**Comment by MichaIng** [comment]
Fixed with: https://github.com/MichaIng/DietPi/commit/e9ad60b1143cd8a4fdc5e5b0f35fb710c24a24e6
___________
Okay the ffmpeg + unrar binaries have been added as a reaction to users complaining when those are missing, obviously unable to install themselves. Since, before me, noone complained about non-required extra 300 MiB, those will stay 😉. By times I'll think about a workaround or even a nice solution for Bazarr so that those binaries are pulled as part of install/firstrun step, when not present on the system, but for now it's fine as it is.

**Pull request merged**
