### PR TITLE
DietPi | Switch from rc.local to dietpi-postboot.service

### PR DESCRIPTION
**Pull request by MichaIng**
https://github.com/Fourdee/DietPi/issues/1376

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

Legend 👍 Thank you.

I'am aiming to get v6.2 finished up and released in the next few days. I'll flag this for v6.3 now.

**Comment by MichaIng** [comment]
@Fourdee 
Jep, thus is okay, since it is a bid deeper change (many scripts involved) and the actual reason a minor one (visual).

**Comment by Fourdee** [comment]
@MichaIng 
Great work on this, impressive 👍 

We can probably simplify the patch, by running ```/dietpi/func/dietpi-set_core_environment```, we can also move the ```rc.local``` creation into that script, and automatically make a backup.

I'll merge and take a look.

**Review by Fourdee — APPROVED** [review]
👍

**Comment by Fourdee** [comment]
Quick test for postboot.d (very impressive @MichaIng 👍 )
```
mkdir -p /DietPi/dietpi/postboot.d
cat << _EOF_ > /DietPi/dietpi/postboot.d/beammeupscotty
#!/bin/bash
echo 1 > /root/completed
_EOF_
```

Script not executed, ```/DietPi/dietpi/postboot.d``` missing after ramdisk stop/start. I'd prefer to have this in ```/var/lib/dietpi``` anyway, and, keep ```/DietPi/dietpi``` as clean as we can, without user additions.

🈯️ 
```
mkdir -p /var/lib/dietpi/postboot.d
cat << _EOF_ >/var/lib/dietpi/postboot.d/beammeupscotty
#!/bin/bash
echo 1 > /root/completed
_EOF_
```

**Comment by MichaIng** [comment]
@Fourdee 
I thought the same about moving this to `/var/lib` to have clear separation between static and variable DietPi parts 👍.
Maybe `/var/lib/dietpi/dietpi-software/services/kill-ssh-user-sessions-before-network.sh` could be moved as static service script into `/DietPi/dietpi/func` instead, as well as `fs_partition_resize.sh`? Or you have other reason to keep this in `/var/lib`?

Jep good point to just execute subscripts instead of sourcing 👍. It was just the first 100% identical to prior solution, as moode script was directly inside rc.local. But not necessary and also safer to just execute.

**Comment by Fourdee** [comment]
@MichaIng 

> could be moved as static service script into /DietPi/dietpi/func instead, as well as fs_partition_resize.sh? Or you have other reason to keep this in /var/lib?

Reduce size of RAMdisk and mem usage 😃 

Generally, I aim for:
- Scripts for services = ```/var/lib/dietpi```
- Keep ```/DietPi/dietpi``` static and untouched from user (aside from ```.configs``` used in our scripts, faster loading in ram etc). This should be an exact copy of whats on github.
- Consider the trade-off with performance gain for scripts in ```/DietPi```, against how much they are used, and, how much memory they will consume on RAMdisk. In cases such as ```/var/lib/dietpi/dietpi-software/services/kill-ssh-user-sessions-before-network.sh```, this only runs during shutdown and having it on disk seems the best solution? Same for ```fs_partition_resize.sh``` which only runs once.

**Comment by MichaIng** [comment]
@Fourdee 
In that case postboot and boot main scripts would also be better on disk and way more important: All the /DietPi/dietpi/conf|misc just touched one time on software installation and in most cases never, if not installed by user 😉. Latter is already on my minds list: Move all specific software configs/functions/installation/configuration/uninstallation scripts/parts finally into /var/lib/dietpi, as they are really never or just once touched on a systems lifetime.

But: I like to have all files directly available on github and not created within a script. That makes updating easier as well, as we don't need to cat the whole new/changed script via patch_file. Instead we could on dietpi-update move these files to /var/lib/dietpi instead. Maybe create a new directory tree `/var/lib/dietpi/...` within github for static content, that is not used regularly.

Actually:
At the moment `kill-ssh-user-sessions-before-network.sh` is on ramdisk anyway, as `dietpi-set_core_environment` is, holding it's content: https://github.com/Fourdee/DietPi/blob/testing/dietpi/func/dietpi-set_core_environment#L264-L277
As moving as separate file into ramdisk allows to remove it from `dietpi-set_core_environment`, the RAM usage remains moreless the same 😜. But yeah, generally I agree that it does not make sense to keep whole DietPi code in ramdisk, consistently e.g. by method above.

But in the end, we are talking about:
```
2018-02-20 20:28:50 root@micha:~# G_TREESIZE /DietPi/dietpi/
1.4 MB /DietPi/dietpi/
```
Even for 256M devices, any of our decisions makes any real difference, thanks to low resource bash scripting 💯 😃.

**Pull request merged**
