### PR TITLE
DietPi-Software | myMPD: Install latest master + fixes

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Testing
- [x] Reinstall on v6.25 patch to update existing instances, requires removal (+backup) of config file due to new required settings section
- [x] Changelog
- [x] Wiki software list update

**Reference**: https://github.com/MichaIng/DietPi/issues/2156#issuecomment-497513129

**Commit list/description**:
+ DietPi-Software | ympd: Use official non-capital letters naming
+ DietPi-Software | ympd: On uninstall, unmask and disable service to remove all possible traces
+ DietPi-Software | myMPD: Do not apply wrong "group" setting
+ DietPi-Software | myMPD: Add libmediainfo to dependencies to support internal album covers
+ DietPi-Software | myMPD: Install latest master release, which works well now

### CODE REVIEW

**Comment by MichaIng** [comment]
Strange magic is going on sometimes...
#### EDIT: Nope, explanation is that the service file cam from pre-PR version of myMPD which did not yet contain the bug 🙂!
- Found `/usr/lib/systemd/system/mympd.service` being installed by installer and working nice. I actually didn't know that this path is read by systemd.
- Since, besides "dietpi" group, the systemd unit is identical to ours, I reverted code to skip creating an own one, but applying "dietpi" group via drop-in config.
- Testing this PR: systemd unit was NOT pre-created....
- Ran installer manually:
```
...
Checking status of mympd system user and group
Installing systemd service
Failed to enable unit: File mympd.service: No such file or directory
mympd.conf installed as mympd.conf.dist
Fixing ownership of /var/lib/mympd
Certificates already created
myMPD installed
Edit /etc/mympd/mympd.conf before starting myMPD
root@VM-Stretch:/tmp/myMPD-master# getent passwd mympd
mympd:x:999:999::/var/lib/mympd:/usr/sbin/nologin
root@VM-Stretch:/tmp/myMPD-master# groups mympd
mympd : mympd audio dietpi
root@VM-Stretch:/tmp/myMPD-master# l /usr/lib/systemd/system/
total 0
```
- So it states to install the service but it doesn't.
- But it did well just 2 hours ago, when I tested the previous state... 😕
_______
```
if [ -d /etc/systemd ]
then
  echo "Installing systemd service"
  [ -d /usr/lib/systemd/system ] || mkdir -p /usr/lib/systemd/system
  if [ ${SHAREDIR}/mympd.service -nt /usr/lib/systemd/system/mympd.service ]
  then
    cp ${SHAREDIR}/mympd.service /usr/lib/systemd/system/
    systemctl daemon-reload
  fi
  systemctl enable mympd
fi
```
```
root@VM-Stretch:/tmp/myMPD-master# l /usr/share/mympd/
total 16
-rwxr-xr-x 1 root root 2004 May 24 00:48 crcert.sh
drwxr-xr-x 5 root root 4096 Jun  2 02:00 htdocs
drwxr-xr-x 2 root root 4096 Jun  2 02:00 lib
-rw-r--r-- 1 root root  195 May 24 00:48 mympd.service
root@VM-Stretch:/tmp/myMPD-master# [ /usr/share/mympd/mympd.service -nt /usr/lib/systemd/system/mympd.service ] && echo yes
yes
root@VM-Stretch:/tmp/myMPD-master# cp /usr/share/mympd/mympd.service /usr/lib/systemd/system/
root@VM-Stretch:/tmp/myMPD-master# [ /usr/share/mympd/mympd.service -nt /usr/lib/systemd/system/mympd.service ] && echo yes
root@VM-Stretch:/tmp/myMPD-master# systemctl daemon-reload
root@VM-Stretch:/tmp/myMPD-master# systemctl start mympd # works well
```
- I don't get it... Will check back tomorrow.

**Comment by MichaIng** [comment]
Above issue identified: https://github.com/jcorporation/myMPD/issues/124
Resolved with: https://github.com/jcorporation/myMPD/pull/125

Lets hope for soon merge to master, so we don't need to do a workaround.

**Comment by jcorporation** [comment]
I merged your pull request into master. Don't hesitate to open issues, if some install behaviour of myMPD creates problems with DietPi. I like to support DietPi.

**Comment by MichaIng** [comment]
@jcorporation 
Very nice, many thanks! I already added a workaround, as I thought you will release the fix with 5.4.0. But wonderful, then the install code will be finally what it should be 😃.

> Don't hesitate to open issues, if some install behaviour of myMPD creates problems with DietPi. I like to support DietPi.

Many thanks, it works flawlessly now, but I will forward any issues/suggestions we find.

**Pull request merged**
