### PR TITLE
DietPi-Update | Check GitHub repo first

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Update | Check GitHub repo first
  - Reduce dietpi.com load. Just found the max Apache spaws up, most of them update checks. Apache (mod_php) is not the best for many small requests, as every access spawns a new process. For this nginx/lighttpd (php-fpm) would do better job.
  - When users adjust `GIT_OWNER` in dietpi.txt, this is just ignored on dietpi.com repo, thus is ignored until now in most cases.
+ DietPi-Update | Minor codeing
  - No active array unset done (also not needed) and no tmp file removal needed due to G_EXIT().

### CODE REVIEW

**Comment by mrmajik45** [comment]
Am I allowed to codefactor this?

**Comment by MichaIng** [comment]
@mrmajik45 
Of course you are, but take into account Fourdee's remarks on your opened PR. Some of the codefactor issues have to be ignored to follow our coding style.

**Comment by Fourdee** [comment]
@MichaIng 

Was actually thinking about doing this yesterday lol 👍 

Anything to reduce our server load is a good thing.

**Review by Fourdee — APPROVED** [review]
Looking good, thanking you 👍

**Comment by Fourdee** [comment]
Will merge.

@mrmajik45 By all means, send a PR for any coding improvements, please just bear in mind our coding style as discussed in the other ticket.

**Comment by MichaIng** [comment]
@Fourdee 
> Was actually thinking about doing this yesterday lol 👍

😄 Also this resolves the tiny issue, that with testing branch the update never succeeded on dietpi.com and needed to do second loop.

**Pull request merged**
