### PR TITLE
DietPi-Software | Box64

### LINKED ISSUE #3957: DietPi-Software | Box86 / Box64
#### Formal software information
- Software title | 
Box86
- Short description | 
x86 userspace emulation
- GitHub URL (if available) | 
https://github.com/ptitSeb/box86
- (Official) install documentation | 
https://github.com/ptitSeb/box86/blob/master/COMPILE.md

#### Are there similar/alternative software titles available with DietPi-Software?

- No

#### What makes your requested software better than the above solutions, if available?

- N/A

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?

- Different install procedures for different platforms

#### Can you provide the installation steps that you would suggest DietPi-Software to do?

1. Build/Install

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.

- Probably

### PR DESCRIPTION
**Pull request by nonnorm**
**Status**: Testing

- [x] Test on RPi Aarch64
- [ ] Test on PBP

**Reference**: https://github.com/MichaIng/DietPi/issues/3957

**Commit list/description**:

- DietPi-Software | Begin to add Box64

### CODE REVIEW

**Comment by MichaIng** [comment]
Oh, nice, didn't saw this coming. Coincidentally I stumbled above a Steam on RPi guide today and verified that it contains precisely the steps and hints we do and found. So nothing to update, so far.

So Box64 allows to run x86_64 software and related Steam games, that is awesome news.

**Comment by ravenclaw900** [comment]
@MichaIng, could you rebuild the Steam package for both ARMv7 and ARMv8?

**Comment by ravenclaw900** [comment]
Ah, right, Steam is 32-bit.

**Comment by MichaIng** [comment]
Hmm, that's actually a problem. I mean I could pack an aarch64 package, but the `/usr/lib/games/steam/steam` binary stays i386 and the question is whether Box64 can execute it the same way a 64-bit CPU can execute 32-bit executables (being backwards-compatible)?

Actually I'm wondering why ARMv8 CPUs cannot execute Box86 🤔. For Steam, finally Box86 and Box64 both could be installed in parallel to run i386 and x86_64 binaries, and probably then 64-bit games through Steam.

**Comment by ravenclaw900** [comment]
I had trouble compiling the Box86 binary on ARMv8, though I didn't try to make any modifications.
```
Scanning dependencies of target PRINTER
Scanning dependencies of target WRAPPERS
Scanning dependencies of target dynarec_arm
[  0%] Built target PRINTER
[  0%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm.c.o
[  0%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o
[  0%] Built target WRAPPERS
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:82: CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm_functions.c.o
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:95: CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm.c.o] Error 1
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/arm_printer.c.o
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:108: CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm_functions.c.o] Error 1
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:121: CMakeFiles/dynarec_arm.dir/src/dynarec/arm_printer.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/dynarec_arm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target arm_pass0
[  2%] Building C object CMakeFiles/arm_pass0.dir/src/dynarec/dynarec_arm_helper.c.o
Scanning dependencies of target arm_pass1
cc: error: unrecognized command-line option ‘-marm’
[  2%] Building C object CMakeFiles/arm_pass0.dir/src/dynarec/dynarec_arm_emit_tests.c.o
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
Scanning dependencies of target arm_pass2
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass0.dir/build.make:82: CMakeFiles/arm_pass0.dir/src/dynarec/dynarec_arm_helper.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass0.dir/build.make:95: CMakeFiles/arm_pass0.dir/src/dynarec/dynarec_arm_emit_tests.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:191: CMakeFiles/arm_pass0.dir/all] Error 2
[  2%] Building C object CMakeFiles/arm_pass1.dir/src/dynarec/dynarec_arm_helper.c.o
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass1.dir/build.make:82: CMakeFiles/arm_pass1.dir/src/dynarec/dynarec_arm_helper.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  3%] Building C object CMakeFiles/arm_pass1.dir/src/dynarec/dynarec_arm_emit_math.c.o
[  3%] Building C object CMakeFiles/arm_pass1.dir/src/dynarec/dynarec_arm_emit_tests.c.o
cc: error: unrecognized command-line option ‘-marm’
[  3%] Building C object CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_helper.c.o
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
[  4%] Building C object CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_emit_tests.c.o
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass1.dir/build.make:95: CMakeFiles/arm_pass1.dir/src/dynarec/dynarec_arm_emit_tests.c.o] Error 1
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass1.dir/build.make:108: CMakeFiles/arm_pass1.dir/src/dynarec/dynarec_arm_emit_math.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:249: CMakeFiles/arm_pass1.dir/all] Error 2
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass2.dir/build.make:82: CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_helper.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass2.dir/build.make:95: CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_emit_tests.c.o] Error 1
[  5%] Building C object CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_emit_logic.c.o
[  5%] Building C object CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_emit_math.c.o
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass2.dir/build.make:121: CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_emit_logic.c.o] Error 1
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/arm_pass2.dir/build.make:108: CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_emit_math.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:359: CMakeFiles/arm_pass2.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by MichaIng** [comment]
Does Steam actually execute with Box64, when its i386? Didn't find time to test it yet.

**Comment by MichaIng** [comment]
I hope you're okay with postponing this to v7.6, so we have some time to test and get it running with Steam.

**Comment by ravenclaw900** [comment]
No problem.

**Comment by MichaIng** [comment]
Builds fine on `aarch64`. One minor quirk is that despite we pass `-DNOGIT=1`:
```
[ 37%] Generating ../src/git_head.h
bash: line 1: git: command not found
```
But it does not break the build. `-DNOGIT=1` and `-DNOGIT=ON` are 100% equivalent, aren't they? (yes it is)
Probably this flag is only about whether the source has been pulled via Git, not about whether Box64 itself will have Git support or not (for whatever is uses this)? Not sure, however, ignoring for now.

I packed `aarch64` Steam packages. Now testing whether Box64 is i386 backwards-compatible like x86_64 is. Box86 cannot build or run on `aarch64`, as of the README:
> You NEED a 32-bit subsystem to run and build Box86. Box86 is useless on 64-bit only systems. Also, you NEED a 32-bit toolchain to build Box86. A toolchain that only supports 64-bit will not compile Box86, and you'll get errors (typically on aarch64, you get "-marm" not recognized, and you'll need a multiarch or chroot environnement).

**Comment by MichaIng** [comment]
```
# box64 /root/.steam/debian-installation/ubuntu12_32/steam
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.4 nogit built on Sep 14 2021 19:06:35
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 17 Env var
Looking for /root/.steam/debian-installation/ubuntu12_32/steam
steam detected, forcing emulated libudev
This is a 32bits ELF! box64 can only run 64bits ELF (/root/.steam/debian-installation/ubuntu12_32/steam)!
Error: reading elf header of /root/.steam/debian-installation/ubuntu12_32/steam, try to launch natively instead
```

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
I'll merge. We can do further testing during remaining beta phase. I need to think about some good x86_64 binaries/software to test 🤔.

**Pull request merged**
