### PR TITLE
Beta v6.29.0

### PR DESCRIPTION
**Pull request by MichaIng**
### Beta v6.29.0
_(01/04/20)_

#### API Changes
- Hardware info | The hardware info file /DietPi/dietpi/.hw_model should be now accessed at /boot/dietpi/.hw_model (see DietPi-RAMdisk removal below) and contains info now as NAME=VALUE like lines, which can be sourced from shell scripts.
- Flag/Info files | /DietPi/dietpi/.update_available, /DietPi/dietpi/.timesync_exit_status, /DietPi/dietpi/.network and /tmp/.dietpi_motd have all been moved into a new runtime directory: /run/dietpi/
- DietPi-Globals | The global variables G_HW_ARCH_DESCRIPTION and G_HW_MODEL_DESCRIPTION have been renamed to G_HW_ARCH_NAME and G_HW_MODEL_NAME. The new variables G_HW_UUID (DietPi-internal device UUID) and G_ROOTFS_DEV (RootFS device path) are available. On RPi additionally G_HW_REVISION, G_HW_PCB_REVISION, G_HW_MEMORY_SIZE and G_HW_MANUFACTURER are available, the revision code and its decoded information: https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md
- DietPi-Globals | G_RUN_CMD and G_ERROR_HANDLER have been removed and replaced with G_EXEC. Basically G_EXEC can be used the same way G_RUN_CMD was before and it is wider configurable to make manual G_ERROR_HANDLER usage obsolete where custom solution menu entries or command output parsing is required, e.g. to check for errors that do not produce exit codes. Visual change for regular DietPi users is that every error handled command can be retried, a subshell can be opened to investigate or fix the originating issue and, for experienced users, the command can be altered, e.g. if a download link has changed or an expected file has been moved manually to a new path. Further details can be found in the script: /boot/dietpi/func/dietpi-globals
- DietPi-Globals | G_FILE_EXISTS has been removed, as it was used only a single time in our code and usually it needs to be checked and handled explicitly, whether it is a file, directory, symlink with or without existing target.

#### Changes / Improvements / Optimisations
- NanoPi M4v2 | Initial hardware identifier (ID: 58) and support for this device has been added to DietPi. Many thanks to `@purist` doing this request: https://dietpi.com/phpbb/viewtopic.php?f=12&t=6451
- Pine H64 | Initial hardware identifier (ID: 45) and support for this device has been added to DietPi. Many thanks to @unixino for doing this request: https://github.com/MichaIng/DietPi/issues/3286
- ROCK Pi S | Initial hardware identifier (ID: 73) and support for this device has been added to DietPi. Many thanks to @lwqcz for doing this request: https://github.com/MichaIng/DietPi/issues/3365
- Sparky SBC | Updated kernel drivers and SBC-specific service and config files
- General | Switched to C.UTF-8 as default locale and for DietPi scripts. It is shipped statically by APT package, international and more lightweight compared to en_GB.UTF-8.
- DietPi-RAMdisk | Removed from DietPi, which means that one can edit config files in /boot directory directly now. To keep performance for our scripts up, vmtouch is installed instead, which allows to lock files in native file system cache, configured to lock /boot/dietpi and /boot/dietpi.txt in cache by default. More info: https://github.com/MichaIng/DietPi/issues/3288
- DietPi-LED_control | LED trigger choices are now applied via udev rules, existing settings are migrated on DietPi-Update. This allows to skip running this script at boot and simplify the preboot script, which both reduces boot time a bid. Additionally, applied LED triggers can now be reset to system defaults, which removes related udev rules. Since the script is now for interactive usage only, it has been moved to /boot/dietpi/dietpi-led_control and an alias has been added to call it from console via "dietpi-led_control" command.
- DietPi-Cron | Allows now to set the cron job output mail recipient. Cron mails are disabled by default since no MTA is preconfigured on DietPi. Additionally the execution times are now shown more clearly in 24h format.
- DietPi-Autostart | When selecting a non-root autologin user, some required tasks, like permissions, are now applied automatically, based on autostart option. This especially allows non-root users to launch Kodi without applying permissions manually. Many thanks to @sbrl for requesting this feature: https://github.com/MichaIng/DietPi/issues/3351
- DietPi-Drive_Manager | GlusterFS fstab entries are now preserved. Many thanks to @Sudrien for implementing this addition: https://github.com/MichaIng/DietPi/issues/3374
- DietPi-Software | Domoticz: open-source home automation platform is now available for install. Many thanks to `@AndyB` for doing this request a long time ago: https://dietpi.com/phpbb/viewtopic.php?f=12&t=222
- DietPi-Software | phpBB: Updated to v3.3.0 which has PHP7.3 support, hence can be installed on all hardware models and distro versions.
- DietPi-Software | Sonarr/Radarr/Lidarr: Enhanced install and uninstall steps. On reinstalls, the install dir is left unchanged now, suggesting to use the internal updater instead, which is generally safer and now does not require a manual service restart (see bug fix below). In case of a broken instance, the install dir /opt/<name> needs to be removed manually now, to have reinstalls downloading and installing the newest binaries.
- DietPi-Software | Sonarr/Radarr/Lidarr: The service now runs with hardened permissions, by default blocking access to directories outside of /opt/<name> /mnt /var/log/<name> and /tmp. If writing to other directories is wanted, the service file needs to be edited, easiest with "dietpi-services" > "<name>" > "Edit" and adding an additional "ReadWritePaths=/path/to/custom/dir".
- DietPi-Software | Chromium: Unlocked install on ARMv6 RPi models: RPi1/Zero/Zero W. Browsing performance will not be perfect, but for kiosk mode or light usage there are use cases. Many thanks to @kmplngj for requesting and testing: https://github.com/MichaIng/DietPi/issues/3364
- DietPi-Software | myMPD: Updated installer according to next upstream release v6.2.0. Many thanks to @jcorporation for informing us about the new version: https://github.com/MichaIng/DietPi/issues/3382
- DietPi-Software | MPD: Assured that UNIX domain socket and systemd unit for socket activation is present on Stretch systems. As well the obsolete cache dir symlinks in "/var/lib/mpd" will not be present anymore. Any custom scripts must use the absolute paths in "/mnt/dietpi_userdata/.mpd_cache" from now on.
- DietPi-Software | Pi-hole: Enabled support for Pi-hole v5. Many thanks to @maartenlangeveld for reporting the required change: https://github.com/MichaIng/DietPi/issues/3391
- DietPi-Software | Shairport-Sync: Updated to new version 3.3.6, using self-compiled deb packages. Many thanks to @kmplngj for doing this request: https://github.com/MichaIng/DietPi/issues/3216
- DietPi-Software | HAProxy: Updated to newest stable upstream version 2.1.3 and the sysvinit service has been replaced with the officially provided systemd service. It will be reinstalled on all systems via DietPi-Update, your config files will not be touched on any reinstall.
- DietPi-Software | rTorrent: Further rework and update of the default config file. Many thanks to @bbsixzz for this contribution: https://github.com/MichaIng/DietPi/issues/3332

#### Bug Fixes
- Raspberry Pi | Resolved an issue where RPi models could be incorrectly identified in case of warranty, overvoltage or OTP bits set in revision code. Many thanks to @LeeMenHin for reporting this issue: https://github.com/MichaIng/DietPi/issues/2979#issuecomment-598906749
- DietPi-Banner | Resolved an issue where clearing the screen fails due to missing G_TERM_CLEAR command. Many thanks to @Joulinar for reporting this issue: https://github.com/MichaIng/DietPi/issues/3313
- DietPi-Config | Resolved an issue where, on RPi with vc4-fkms-v3d overlay/driver enabled, soundcard selection went wrong. Many thanks to @Cybolic for reporting this issue: https://github.com/MichaIng/DietPi/issues/3356
- DietPi-Globals | CPU temperature readout on Intel Mini PCs has been fixed. Many thanks to @Iv711 and @kt1024 for reporting this issue: https://github.com/MichaIng/DietPi/issues/3172, https://github.com/MichaIng/DietPi/issues/3412
- DietPi-Drive_Manager | Resolved an issue where the chosen spindown timeout was not applied correctly on boot. Many thanks to @tesseract241 and @lukaszm89 for reporting this issue: https://github.com/MichaIng/DietPi/issues/3309, https://github.com/MichaIng/DietPi/issues/3420
- DietPi-Drive_Manager | Resolved an issue where NFS pre-v3 mounts could have failed on boot. They are now automounted on first mountpoint access, like NFSv3 and Samba shares do already. Many thanks to @Joulinar for reporting and debugging this issue: https://github.com/MichaIng/DietPi/issues/1898#issuecomment-604412425
- DietPi-Software | Resolved an issue where extraction of zip archives to current directory failed. Many thanks to @en0rism for reporting this issue: https://github.com/MichaIng/DietPi/issues/3320
- DietPi-Software | Redis: Resolved an issue where service start fails on Stretch systems. Many thanks to @drieksje for reporting this issue: https://github.com/MichaIng/DietPi/issues/3314
- DietPi-Software | Sonarr/Radarr/Lidarr: Resolved an issue where a manual service restart was required after the internal updater has been used.
- DietPi-Software | myMPD: Resolved MPD connection issues on Stetch systems. Many thanks to @jcorporation for informing us on upstream changes, helping with debug and fixing the issues: https://github.com/MichaIng/DietPi/issues/3382
- DietPi-Software | O!MPD: Resolved an issue where YouTube support was not functional by default due to missing youtube-dl execute permissions. Many thanks to @ArturSierzant for reporting this issue: https://github.com/MichaIng/DietPi/issues/3413
- DietPi-Software | GMediaRender: Resolved an issue where the wrong sound device could have been used. Many thanks to @kikigarel for reporting this issue: https://github.com/MichaIng/DietPi/issues/3348
- DietPi-Software | Chromium: Resolved an issue where non-root users were not able to use the Chromium autostart option due to wrong permissions. Many thanks to @lasers and @promofu for reporting this issue: https://github.com/MichaIng/DietPi/issues/3322
- DietPi-Software | RPi Cam Control: Resolved an issue where camera through the web UI failed because of missing permissions. Many thanks to @arkhub for reporting this issue: https://github.com/MichaIng/DietPi/issues/3431

#### Known/Outstanding Issues
- DietPi-Config | Enabling WiFi + Ethernet adapters, both on different subnets, breaks WiFi connection in some cases: https://github.com/MichaIng/DietPi/issues/2103
- RPi | On TigerVNC virtual desktop, LXAppearance hangs on dbus-launch: https://github.com/MichaIng/DietPi/issues/1791
- Odroid C2 | Some WiFi adapters do no work as hotspot: https://github.com/MichaIng/DietPi/issues/1955
- Odroid XU4 | Kodi freezes shortly on video playback: https://github.com/MichaIng/DietPi/issues/2584
- Rock64 | 3.5mm A/V jack is currently not functional: https://github.com/MichaIng/DietPi/issues/2522
- DietPi-Software | Node-RED: Pre-installed modules cannot be updated via web UI: https://github.com/MichaIng/DietPi/issues/2073
- DietPi-Software | Raspimjpeg: With Lighttpd, streaming mjpeg does not work: https://github.com/MichaIng/DietPi/issues/1747
- DietPi-Software | MATE desktop: When logging in as root, desktop items and right-clock context menu is missing: https://github.com/MichaIng/DietPi/issues/3160
- DietPi-Software | Sonarr/Mono: With current Mono version 6, import to a file system without UNIX permissions support (exFAT, FAT32/vfat and NTFS without "permissions" option) fails, regardless of user/umask mount options: https://github.com/MichaIng/DietPi/issues/3179

### CODE REVIEW

**Comment by MichaIng** [comment]
### ToDo:
- [x] Update Allo GUI and reinstall on DietPi update

**Comment by Joulinar** [comment]
@MichaIng 
let me know once I should test it

**Comment by drieksje** [comment]
Hi.
Have a good running dietpi stretch on odroid C2 , so i made an other micro
SD with the Buster distro, (testing) so i can't install dietpi software,
xf86- bturbo error, so do i make a clone of my strech SD An update via thé
distro update or is there a solution for the xf86-.....
Thnxxx:kind regards dirk

Op ma 30 mrt. 2020 19:27 schreef Joulinar <notifications@github.com>:

**Comment by MichaIng** [comment]
@drieksje 
Could you paste the exact error you face? The related APT packages were missing on Buster but were added some days ago actually, so at least the packages should install fine. But it might be possible that the new build require an xorg.conf adjustment.

**Comment by drieksje** [comment]
Will do tomorw.😴😴😴 girlfriend 🤔

Op di 31 mrt. 2020 00:25 schreef MichaIng <notifications@github.com>:

**Comment by drieksje** [comment]
Hi back again, here a picture of the message i get, then the only thing i
can do is a minimal install of dietpi!!
Grtz: dirk

Op di 31 mrt. 2020 00:35 schreef dirk decru <drieksje@gmail.com>:

**Comment by MichaIng** [comment]
@drieksje 
No picture arrived here, I guess you have to upload via web browser as GitHub likely does not provide appends via email. But might you please open a new issue about this? It is related to Debian Buster on Odroid C2, not so much to DietPi v6.29.

**Comment by drieksje** [comment]
Okay i will do, sorry i thought this was the Buster testing distro?

Op di 31 mrt. 2020 10:11 schreef MichaIng <notifications@github.com>:

**Comment by MichaIng** [comment]
@drieksje 
Nope, DietPi supports Stretch and Buster for a long time, Bullseye mostly as well. It was by chance that we updated most Stretch images to Buster during v6.29 dev phase.

**Comment by MichaIng** [comment]
@Joulinar 
I made final tests and fine tuning for what I found. From my end ready for a first beta candidate. If you find time for some testing, I would be happy. Especially the smooth update is something that needs to be taken a special eye on, due to the large amount of core changes, RAMdisk remove, info/flag file location and format, changed global functions etc.

**Comment by Joulinar** [comment]
@MichaIng 
it's still dev branch against I can test right?

**Comment by MichaIng** [comment]
@Joulinar 
Yes it's still `dev`.

**Comment by Joulinar** [comment]
@MichaIng 
I did 3 test for now

1. Buster VM
2. Stretch VM
3. Buster RPi3B+

so for so good. I attached all 3 logs. One thing I spotted on my RPi system

```
 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Applying incremental patches

[ INFO ] DietPi-Update | Current version : v6.28.0 (branch: MichaIng/master)
[ INFO ] DietPi-Update | Latest version  : v6.29.0 (branch: MichaIng/dev)
[ INFO ] DietPi-Update | Patching 6.28 to 6.29
Removed /etc/systemd/system/multi-user.target.wants/dietpi-ramdisk.service.
/DietPi/dietpi/patch_file: line 150: /etc/.dietpi_hw_model_identifier: No such file or directory
[  OK  ] DietPi-Patch | Restarting DietPi-Update with new code...
```

Rest seems to be fine

[stretchVM.txt](https://github.com/MichaIng/DietPi/files/4411708/stretchVM.txt)
[busterRPi3Bplus.txt](https://github.com/MichaIng/DietPi/files/4411709/busterRPi3Bplus.txt)
[busterVM.txt](https://github.com/MichaIng/DietPi/files/4411710/busterVM.txt)

**Comment by MichaIng** [comment]
@Joulinar 
Great, ah yeah indeed we check the HW model identifier file even if it does not exist (on RPi). I fixed it: https://github.com/MichaIng/DietPi/commit/2cce23bb8f2fe6b329c0ee7fcdc85b0627e10d4e

**Comment by MichaIng** [comment]
I went through dietpi-software and updated some download links, mostly the fallback URLs only, but YaCy has a few years newer version now: https://github.com/MichaIng/DietPi/commit/64ea12cb619779bc5849708c237de109248bf076
It's a subsubversion raise only, but I am not sure about the actual development/changes since the last official release is still dated 2016... I'll do some test install just to be sure, then merge this as first beta candidate.

**Pull request merged**
