### PR TITLE
DietPi-Globals | Working directory rework

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready
- [x] Adjust scripts to assign `$FP_WORK_DIR` as their temporary working directory, before calling `G_INIT()`, to automatically create and navigate into it.
- [x] Optional: `G_EXIT()` or `G_CLEAN()` to remove `$FP_WORK_DIR`?

**Commit list/description**:
+ DietPi-Globals | Move automated dir navigation to `G_INIT()` to prevent messing with current terminal session
+ DietPi-Globals | Only navigate to $HOME dir, if it is assigned
  - **Currently, many error messages about unassigned `$HOME` show up during boot.**
+ DietPi-Globals | Allow automated creation and navigation into `$FP_WORK_DIR`, if assigned within script, e.g. /tmp/dietpi-*
+ DietPi-Globals | Minor coding
  - Make use of more selective file checking, file types, read/write-ability etc: https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html
+ DietPi-Globals | Syntax fix; Always attempt to go to `$HOME`, if assigned and any step with `$FP_WORK_DIR` failed.
+ DietPi-Globals | G_DIETPI-NOTIFY: Reset color in front of right bracket, in case "\e[90m" is not supported by terminal
+ DietPi-Globals | Automatically add a trap exit function, to purge existing working dir. Allow custom additional exit commands via declaring G_EXIT_CUSTOM() within the actual script.
+ DietPi-Software | Leave $FP_WORK_DIR handling to G_INIT() and G_EXIT() trap
+ DietPi-Software | Turn Software_Arrays_Destroy() into G_EXIT_CUSTOM() trap addition, to be executed on every kind of script exit
+ DietPi-Software | Reboot banner reorder, avoid doubled $DISABLE_REBOOT check, sync to fs before printing banner + sleep 3, to allow using the time for file sync
+ DietPi-Software | Remove DietPi-Survey call within first run setup, as this is already called after first run update and install.
+ DietPi-Software | Optimize marking software titles on automated first run install, to call grep + sed just once and directly pass indices to loop.
+ DietPi-Survey | Rely on G_INIT() > G_EXIT() to create and purge tmp $FP_WORK_DIR
+ DietPi-Globals | G_DIETPI-NOTIFY: Remove race condition between checking and creating /tmp/dietpi-process.pid: https://www.davidpashley.com/articles/writing-robust-shell-scripts/
+ DietPi-Globals | G_DIETPI-NOTIFY: Allow processing animation, if G_USER_INPUTS=0 was set manually, only verify input terminal
+ DietPi-Update | Rely on G_INIT() and G_EXIT() to handle working directory
+ DietPi-Bugreport | Rely on G_INIT() and G_EXIT() to handle working directory
+ DietPi-Drive_Manager | Use G_INIT() and G_EXIT() to enter and exit+purge /tmp working directory, to create tmp files inside
+ DietPi-Globals | G_DIETPI-NOTIFY: Avoid creating subshells, as this takes relatively much time: https://github.com/Fourdee/DietPi/issues/1510#issuecomment-407512160
+ DietPi-Globals | G_CHECK_ROOTFS_RW(): Do not decrease $HIERARCHY by 1, as this will let scripts start with $HIERARCHY == -1, leading to wrong output. export $HIERARCHY within dietpi-drive_manager does not have any influence on $HIERARCHY declaration or value within parent script/shell.
_______________________
Use this within all scripts, that produce temporary files? We could further increase automation/consistency via `FP_WORK_DIR="/tmp/$G_PROGRAM_NAME"`, but this would include capital letters.

Further idea: Use "trap" to clean temp working dir as well on error or `<ctrl>+<c>` cancel: http://redsymbol.net/articles/bash-exit-traps/
🈯️ `trap 'G_EXIT' EXIT`
___________________
Testing:
🈯️ Software installation via cmd
🈯️ Software installation via menu
🈯️ Bugreport
🈯️ dietpi-update
🈯️ dietpi-drive_manager
🈯️ dietpi-survey

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
Actually I would also like during `G_INIT` to check, if the script is already running.
Easiest would be to make `$G_PROGRAM_NAME` always match the actual script name (no capital letters any more, or use `$G_SCRIPT_NAME`?), pgrep for it and in case exit with error/info message. By this we'd prevent parallel executions to disturb each other, e.g. removing `$FP_WORK_DIR` while the other script uses it and such.

Or hmm, before the script goes on with unexpected behaviour due to missing sub script execution, it could also prompt user to wait for the parallel execution to stop or stop it actively, before going on. Not sure which is best here.

**Comment by MichaIng** [comment]
@Fourdee 
Ready to review 😃
I guess it's implemented into the most obvious tmp file creating scripts.

Do you know some reliable way to check, whether we are inside a script or terminal session? Would be good to only declare `G_INIT` inside scripts, otherwise an accidental call within terminal messes up the terminal session. This could also help to "hide" some more global functions from user session.

One idea, although not 100% bullet prove, to only run G_INIT(), if $G_PROGRAM_NAME is declared. On the other hand, we maybe do not want to do this in every case, where G_INIT should be executed. Also nothing prevents from declaring it inside terminal, perhaps even via accidentally sourcing a script.

**€: Check whether we are in terminal session or inside a script**
🈴 `$BASH_SOURCE`, exists as well/shows the same, if script is sourced or executed.
```
2018-07-24 16:05:27 root@DietPi:/tmp# cat test
#!/bin/bash
echo $BASH_SOURCE
2018-07-24 16:05:33 root@DietPi:/tmp# ./test
./test
2018-07-24 16:05:37 root@DietPi:/tmp# echo $BASH_SOURCE

2018-07-24 16:09:52 root@DietPi:/tmp# . ./test
./test
```
🈺 `$0`, works, but at least is defined as well within terminal session. This would rely on terminal session always has the same output. I doubt this being the case on all systems and especially also for terminal emulators, `screen` etc.
```
2018-07-24 16:12:25 root@DietPi:/tmp# cat test
#!/bin/bash
echo $0
2018-07-24 16:12:27 root@DietPi:/tmp# ./test
./test
2018-07-24 16:12:34 root@DietPi:/tmp# . ./test
-bash
2018-07-24 16:12:37 root@DietPi:/tmp# echo $0
-bash
```
🈯️ type dietpi-*, aliases are defined within terminal session only. Not a direct "question", but the most reliable check, for my impression.
```
2018-07-24 16:54:26 root@DietPi:/tmp# cat test
#!/bin/bash
type dietpi-software
2018-07-24 16:54:39 root@DietPi:/tmp# type dietpi-software
dietpi-software is aliased to `/DietPi/dietpi/dietpi-software'
2018-07-24 16:54:47 root@DietPi:/tmp# ./test
./test: line 2: type: dietpi-software: not found
2018-07-24 16:54:51 root@DietPi:/tmp# . ./test
dietpi-software is aliased to `/DietPi/dietpi/dietpi-software'
```

**Comment by Fourdee** [comment]
@MichaIng 

> Do you know some reliable way to check, whether we are inside a script or terminal session? 

To detect script, check the PID of current process, against its result of bash?:
```
root@DietPi:~# echo $$
1445

root@DietPi:~# ps aux | grep 1445 | grep bash
root      1445  0.7  0.3   7476  5448 pts/0    Ss   21:46   0:00 -bash

```


---

```
#!/bin/bash
if (( $(ps aux | grep "$$" | grep -ci -m1 '/bin/bash') )); then

        echo yes

fi
```

**Review by Fourdee — APPROVED** [review]
Looks good 👍 

Nice work, please merge when ready.

**Comment by MichaIng** [comment]
@Fourdee 
> To detect script, check the PID of current process, against its result of bash?:

Hmm, but the terminal session is also bash. Usually the process is called `-bash` there, but if you manually run `/bin/bash`, you cannot know any more via this method, if it's a running script, or a terminal session waiting for user input 🤔.
Usually:
```
2018-07-24 23:38:04 root@DietPi:/tmp# ps aux | grep "$$" | grep 'bash'
root      1110  0.2  0.6  22432  6472 pts/0    Ss   19:01   0:45 -bash
```
But after running `/bin/bash`:
```
2018-07-24 23:37:38 root@DietPi:/tmp# ps aux | grep "$$" | grep '/bin/bash'
root     10319  1.4  0.5  22064  5856 pts/0    S    23:37   0:00 /bin/bash
```
______________
Played around a bid with subshells, command groups, how to best hiding background process output etc. I think I found now the most bullet prove solution with least performance impact.
______________
Okay let's merge to be able to have a look during other tasks/tests/development.

**Pull request merged**
