### PR TITLE
DietPi-Config | Adjust IPv related settings

### PR DESCRIPTION
**Pull request by MichaIng**
+ DietPi-Config | Adjust IPv related settings: https://github.com/Fourdee/DietPi/issues/472#issuecomment-356444922

### CODE REVIEW

**Review by k-plan — COMMENTED** [review]
@MichaIng 

- looks good for me, but Dan and  your "coding stuff" do overstrained me.  Can't really check it for syntax errors. Sorry, I only will notice, if something in the end doesn't work as expected.

**Comment by MichaIng** [comment]
Ah, I accidentally added the last commit to this PR branch. Should have become a separate PR:

DietPi-Globals | G_DIETPI-NOTIFY: Final hardenings of processing notifications
+ Fixes hung process animations in every thinkable case: https://github.com/Fourdee/DietPi/issues/1385#issuecomment-357011919
+ In case of processing notification takes several terminal lines: Animation will now start at right position and [ INFO ]/[FAILED]/[  OK  ] will overwrite/clear the whole processing notification.
+ Minor tweaks, based on https://www.shellcheck.net/

And I double researched and checked: `ainput_string`, defined as local variable, will be definitely removed  when G_DIETPI-NOTIFY function ends, so no manual unset necessary here (as well as aprocess_string) 😉.

**Review by Fourdee — APPROVED** [review]
👍

**Comment by Fourdee** [comment]
@MichaIng 

Looks good, many thanks 👍 

Merged for testing.

**Comment by Fourdee** [comment]
@MichaIng 
Just noticed this throughout Sparky SBC Stretch using PREP
```
[  OK  ] Step 7: Prep system for DietPi ENV:
[ INFO ] ./dietpi-globals: line 201: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]

###

[  OK  ] CPU gov applied: performance


[ INFO ] ./dietpi-globals: line 201: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]

###

[  OK  ] Step 8: Finalise system for first run of DietPi:
[ INFO ] ./dietpi-globals: line 201: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]

```

**Comment by MichaIng** [comment]
@Fourdee 
Jep, can replicate:
```
 printf '-----------------------------------'
-bash: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]
root@VM-Stretch:~# echo -ne '-----------------------------------'
-----------------------------------
```
printf seem to not like printing a hyphen line. Actually a hyphen as first character seems to be interpreted as option, even with single quotes:
 ```
printf '-a---------------------------------'
-bash: printf: -a: invalid option
printf: usage: printf [-v var] format [arguments]
```
And people say, that printf is more predictable/reliable than echo 😆. I will revert (everything, just in case) to `echo -ne`, never change a running system...
**_€: Done: https://github.com/Fourdee/DietPi/pull/1389_**
______________________
But besides:
Do you wan't to keep the step headers printed as info and ok? Maybe G_DIETPI-NOTIFY 3 with e.g. capital letters and an extra line (to make it dominant compared to other dietpi scripts starting)?

**Pull request merged**
