### PR TITLE
Fix dietpi-logclear fails when ARRAY_LOGFILE_TRUNCATE empty

### PR DESCRIPTION
**Pull request by Timoses**
We unfortunately missed this during our PR:
https://github.com/MichaIng/DietPi/pull/6507#discussion_r1278143854

### CODE REVIEW

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Ah right, thanks! Visual only, i.e. `truncate` throws an errors about the missing/empty argument, but the script goes on regardless.

**Comment by MichaIng** [comment]
Ah, please open PRs again `dev`. I'll leave it in master now as well, but actually nothing but live patches should be merged into master outside of a DietPi release.

**Comment by Joulinar** [comment]
Guys, can this be related? https://dietpi.com/forum/t/cron-root-dietpi-cd-run-parts-report-etc-cron-hourly/17530

**Comment by MichaIng** [comment]
Yes it is.

**Comment by Joulinar** [comment]
As this has bin pushed to master already, would it be enough for the user to reapply the DietPi update to get this fixed?

**Comment by MichaIng** [comment]
I already gave him the command to just re-download the script.

**Pull request merged**
