### PR TITLE
Use latest version of Pydio (8.0.1)

### PR DESCRIPTION
**Pull request by noplanman**

### CODE REVIEW

**Comment by Fourdee** [comment]
@noplanman 

Many thanks for this, however, this is being sent to the live (```master```) branch. 

Please could you create another pull request using the active dev (```testing```) branch?
https://github.com/Fourdee/DietPi#dietpi-project-contribution

**Comment by noplanman** [comment]
Ok, done 👍 

Sorry, didn't realise your `testing` branch was the one you actively work on.

(FYI, you can also create a pull request template to make sure everybody sees that before making a PR)

**Comment by Fourdee** [comment]
@noplanman 

Legend, thanks.

> you can also create a pull request template to make sure everybody sees that before making a PR

Good to know, i'll take a look 👍

**Comment by noplanman** [comment]
It seems that Pydio only works properly with Apache, as Nginx needs a separate configuration.

How would a custom Nginx config be best implemented using DietPi?
I'm still quite new to this amazing project but already have it running on most of my little rascals, albeit managed via Ansible, not the dietpi-software way (which I'm thinking of using in the future).

**Comment by Fourdee** [comment]
> How would a custom Nginx config be best implemented using DietPi?

As long as the config does not break other webserver usage (eg: nextcloud, ```/var/www```), we could install this along with Pydio, if Nginx is detected.

Just tested our DietPi-Software install with Nginx, appears to run fine, however, does complain regarding data directory permissions during initial setup.

**Comment by noplanman** [comment]
> Just tested our DietPi-Software install with Nginx, appears to run fine

Just the web version does, but the URL rewriting doesn't, so connecting pydio-sync doesn't work (says 404 as it doesn't load the correct rewrite).
To test this, get [pydio-sync](https://pydio.com/en/get-pydio/downloads/pydiosync-desktop-app) and try to add the DietPi installation.

And then you can also read more here: https://pydio.com/en/docs/v8/checking-apis

They do provide a sample config for Nginx, but I haven't tested it properly yet 😁

**Pull request merged**
