### PR TITLE
DietPi-Set_CPU_fan | Allows to adjust CPU fan speed PWM control

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: WIP
- [x] **Finish menus, currently working on this**
- [x] Add config whip menu to `DietPi-Set_CPU_fan` script, to have it in one place. Non-interactive settings apply: `DietPi-Set_CPU_fan 1`
- [ ] Add entry to DietPi-Config > Performance Options to start script interactively
- [ ] Needs testing across SBCs, should work at least on Odroid XU3/4, if fan is attached
  - USB fans are available for devices without dedicated fan connector. Control interface e.g. via /sys files needs to be checked.
- [ ] Execute within DietPi-Boot, if settings file exists
- [ ] Add changelog entry

**Reference**: https://github.com/Fourdee/DietPi/issues/1818

**Commit list/description**:
+ DietPi-Set_CPU_fan | Allows to adjust CPU fan speed PWM control
+ DietPi-Set_CPU_fan | Prepare to include interactive settings menu + further rework
+ DietPi-Set_CPU_fan | Further work on it, main menu text and entry creation
+ DietPi-Set_CPU_fan | Finish whiptail menus

### CODE REVIEW

**Comment by MichaIng** [comment]
For dry-run testing with faked control files:
```
mkdir -p /root/devices/platform/pwm-fan/hwmon/hwmon0
echo 1 > /root/devices/platform/pwm-fan/hwmon/hwmon0/automatic
echo 220 > /root/devices/platform/pwm-fan/hwmon/hwmon0/pwm1
echo '0 120 180 240' > /root/devices/platform/pwm-fan/hwmon/hwmon0/fan_speed
for ((i=0;i<$G_HW_CPU_CORES;i++)); do
mkdir -p "/root/devices/virtual/thermal/thermal_zone${i}"
echo 35000 > "/root/devices/virtual/thermal/thermal_zone${i}/trip_point_0_temp"
echo 50000 > "/root/devices/virtual/thermal/thermal_zone${i}/trip_point_1_temp"
echo 65000 > "/root/devices/virtual/thermal/thermal_zone${i}/trip_point_2_temp"
sed -i 's|/sys|/root|g' /DietPi/dietpi/func/dietpi-set_cpu_fan
/DietPi/dietpi/func/dietpi-set_cpu_fan
```

**Comment by Fourdee** [comment]
@MichaIng 

> Needs testing across SBCs, should work at least on Odroid XU3/4, if fan is attached

I can test a few of the following:
- NanoPC T2/T3 
- Native PC 

Just let me know when this is ready for testing 👍

**Comment by MichaIng** [comment]
@Fourdee 
Testing can be done with this. Makes sense to test the script itself first, before implementing into boot script etc.

I read some more about all of this. Sadly this really just works for boards with special fan connector. USB fans, as well as GPIO connected fans (RPi e.g.) just run on constant speed. There is a separate board with transistor needed to control the fan, e.g. based on temps -> gpio signal -> separate board -> fan.

**Comment by Fourdee** [comment]
@MichaIng 

> Testing can be done with this. Makes sense to test the script itself first, before implementing into boot script etc.

Yep, great work 👍 

Will merge and test.

**Pull request merged**
