### PR TITLE
DietPi-Set_Hardware | I-Sabre-K2M: Fix module source build, add informational comments

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Testing
- [x] Changelog
- [x] `ln -s /usr/bin/gcc-4.9 /usr/bin/gcc` and `ln -s /usr/bin/g++-4.9 /usr/bin/g++`
  - The 4.9 packages do not place that symlink.
  - But those would override/fail if other gcc/g++ versions are installed, e.g. simply gcc/g++ packages from repo (via build-essential)...
  - At best we find a way to tell  `make` to use the /usr/bin/gcc-4.9/g++-4.9 binaries
**EDIT: `make CC=gcc-4.9 CXX=g++-4.9`, but needs check if this is handed over to the sub `make` calls as well.**
- [x] Is `g++` actually required? User reported success without `g++` binary linked.
  - For my personal understanding: https://stackoverflow.com/questions/172587/what-is-the-difference-between-g-and-gcc#172592

**Reference**: https://github.com/Fourdee/DietPi/issues/2547

**Commit list/description**:
+ DietPi-Set_Hardware | I-Sabre-K2M: Fix module source build, add informational comments
+ DietPi-Set_Hardware | I-Sabre-K2M: "gcc-4.9" should be sufficient for build
+ DietPi-Set_Hardware | I-Sabre-K2M: Add correct gcc binary to make commands

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
Did you do manual edits compared to https://github.com/SatoruKawase/I-Sabre-K2M according to the README.md contained in your provided archive?
There have been quite some commits done from our version on: https://github.com/SatoruKawase/I-Sabre-K2M/commits/master

Otherwise use the GitHub archive directly instead of hosting it ourself?
________
Okay `gcc` should be sufficient and according to research, `make CC=gcc-4,9` should apply this binary to all sub make calls. However some final test should be done.

Question about `g++` forwarded: https://github.com/SatoruKawase/I-Sabre-K2M/issues/3

**Comment by Fourdee** [comment]
@MichaIng 

> Did you do manual edits compared to https://github.com/SatoruKawase/I-Sabre-K2M according to the README.md contained in your provided archive?

No manual edits, used the source code provided by Audiophonics directly for the DAC.

**Comment by Fourdee** [comment]
@MichaIng 

Thanks for fixing this 👍 

Will merge and test.

**Comment by Fourdee** [comment]
🈯️ Works a charm, nice one @MichaIng 👍

**Comment by MichaIng** [comment]
@Fourdee 
> No manual edits, used the source code provided by Audiophonics directly for the DAC.

Okay, then we might want to update our source due to the commits that have been done in between.

> 🈯️ Works a charm, nice one @MichaIng 👍

Perfect, so it's proven that `g++` is not required, `gcc` sufficient.

**Pull request merged**
