### PR TITLE
Update youtube-dl install url to nightly build fork

### PR DESCRIPTION
**Pull request by pulpe**
As stated in ytdl-org/youtube-dl#31585 new release depends on solving certain issues.

Until then they "recommend" to update with a few solutions https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611

I think that simplest for us is to use nightly build fork. (it's one of the solutions)

### CODE REVIEW

**Comment by Joulinar** [comment]
thx for creating this PR. It's related to https://dietpi.com/forum/t/youtube-dl-uploaded-id-error/16816

**Comment by MichaIng** [comment]
Sorry but I do not think it is great to generally ship untested nightly versions by default only because the current stable release has currently an issue.

I see the problem that it is very good maintained, given that the last release is from 1.5 years ago, but probably it is better to migrate to a well maintained fork with actually tested releases? There is already a request for this: https://github.com/MichaIng/DietPi/discussions/5670

Last release from this March: https://github.com/yt-dlp/yt-dlp/releases
41k stars => trusted, compared to the 61 stars of the young nightly fork used here.

Can be implemented via `api.github.com` like we do for other GitHub release downloads.

**Comment by pulpe** [comment]
Ok, i understand.

Can we than add yt-dlp to dietpi-software and leave youtube-dl there, maybe they will arise again someday?

I was thinking about symlink youtube-dl to yt-dlp, but there are some differences https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior , so maybe not...

**Comment by MichaIng** [comment]
I would prefer to stick with one fork. I mean its simple to download another binary if really required. As there are some differences, we can show a warning to users on next DietPi update that `youtube-dl` will be replaced with `yt-dlp` when reinstalled, and add a link to these differences. For new installs it shouldn't matter anyway as the core functionality of course is the same.

**Pull request closed without merging**
