### PR TITLE
DietPi-Software | MariaDB as new default and remove MySQL option on Stretch

### PR DESCRIPTION
**Pull request by MichaIng**
https://github.com/Fourdee/DietPi/issues/1269
https://github.com/Fourdee/DietPi/issues/1032#issuecomment-312274155
https://github.com/Fourdee/DietPi/issues/894

We could think about force migration via patchfile or encourage people to do it. It is still easily possible (did it by myself some months ago) and should be harmless: https://mariadb.com/de/node/546

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

Yep agree with switching to MariaDB.

Note to self:
- We also need to remove ```L*M*``` titles from Stretch???

Tests:
- NextCloud + Stretch
- NextCloud + Jessie

**Comment by MichaIng** [comment]
@Fourdee 
Yes would be good. I see no harm to just remove the meta packages and install mariadb-server instead. On Stretch images this should not change anything. Then we can manually switch .installed on for mariadb and mysql.
If for any reason someone has really a MySQL package installed (from old Jessie, manually upgraded to Stretch, ppa or something), then this will do the migration to mariadb automatically as intended on their website. So should also go well.

Only difference we did on "chosen" mysql stack:
```
	#Optimize for reduced memory use: https://github.com/Fourdee/DietPi/issues/605#issue-188930987
	cat << _EOF_ > /etc/mysql/conf.d/reduce_resources.cnf
[mysqld]
key_buffer_size=8M
max_connections=30
query_cache_size=8M
query_cache_limit=512K
thread_stack=128K
_EOF_
```
Is there some reason this was only applied for MySQL and not for MariaDB?

**Comment by Fourdee** [comment]
@MichaIng 

> Is there some reason this was only applied for MySQL and not for MariaDB?

Was untested with MariaDB 😄

**Comment by MichaIng** [comment]
https://github.com/Fourdee/DietPi/pull/1280
Needed to create separate pull request, as I accidentally modified master instead of testing.

**Comment by Fourdee** [comment]
@MichaIng 

Many thanks, looks good 👍

**Pull request merged**
