### PR TITLE
Update BRANCH_SYSTEM.md

### PR DESCRIPTION
**Pull request by Joulinar**
**Status**:  Ready
- [x] update BRANCH_SYSTEM.md

**Reference**: https://github.com/MichaIng/DietPi/blob/master/BRANCH_SYSTEM.md

**Commit list/description**:
- update `/DietPi/dietpi.txt` to `/boot/dietpi.txt`

### CODE REVIEW

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
First PR, right? 😃
Many thanks, totally missed that one!

Please open/edit always files in `dev` branch. In this case it is actually good to have it in beta immediately 🤔, since at least new images do not have `/DietPi` symlink anymore. However I'll link the dev version in beta announcement issue instead.

**Comment by Joulinar** [comment]
yap correct. My first one. Actually I just tried to edit the file without knowing what to do 🤣 and it end up in this PR. I just did it on the web interface. Until now I did not checked how to use any desktop clients. Even I don't know how you simulate all the different platforms/ SBC's. Still a lot to learn on all this 🙄

**Comment by MichaIng** [comment]
Jep, this is how you easily open a PR for a quick change. Select "dev" branch, navigate to your file, edit, use the quite usable (if you ask me) web editor and once you commit/merge, it creates a new branch and offers you to open a related pull request.

There are desktop clients for Git in general or GitHub specifically but one needs to dig into all of them as well, the principles and wording of maintaining a local Git repository and such. I personally do everything over GitHub web UI and for larger changes I copy the affected files/content into `notepad++` and then copy back into GitHub web UI once finished. Other Git developers might laugh, however the benefit of a local Git repository is that you can build and test your code and software locally and then push once you're sure everything works fine. However that is exactly not possible with DietPi since there is nothing to build and the files themselves are not usable standalone but need to be placed into a system, in case with related patches on configs and such. So only left benefit is local editor.

**Comment by Joulinar** [comment]
uh yeah using web ui could be tricky on lager files like `dietpi-software` . I will try to play around on smaller thinks. So be patient if I do strange thinks. 🤣

**Pull request merged**
