### PR TITLE
DietPi-Software | Exclude Roon Extension Manager on ARMv6

### PR DESCRIPTION
**Pull request by JanKoudijs**
**Status**: Ready 

**Reference**: none

**Commit list/description**:

- DietPi-Software | Exclude Roon Extension Manager on ARMv6

I had a few days spanning troubleshooting session with a Roon Extension Manager user and in the end it turned out that he was using a Raspberry Pi 1, which is not supported.

This pull request adds the exclusion of ARMV6 to the DietPi-Software entry, to avoid similar troubleshooting sessions in the future.

### CODE REVIEW

**Comment by MichaIng** [comment]
Many thanks. Is this a question of using the Alpine `linux/arm/v6` or a Raspbian-based container/toolkit for compiling/to ship REM, or are there other reasons why it cannot work on ARMv6?

While having a look over our code, I'm wondering whether we should install REM as dedicated `roon-extension-manager` service user, with e.g. `/mnt/dietpi_userdata/roon-extension-manager` as home directory. I see the installer adds it to the `docker` group already. `sudo -u roon-extension-manager sudo ./rem-setup.sh` would do in theory, given we add temporary sudo permissions for this user. We can then also store `rem-setup.sh` in this home directory, so we are sure to uninstall with the same script it was installed with. Currently it is downloaded the script again on uninstall.

Can you think of any issues doing it this way?

**Comment by MichaIng** [comment]
Merging this now, would be still interested what you think about the above, to be in case done in a dedicated PR.

**Comment by JanKoudijs** [comment]
There are a couple of reasons for not supporting ARMv6. The Extension Manager provides an ecosystem, meaning that every provided extension should be available for the supported architectures. To prevent that every extension developer has to build images on the native platforms I created a tool that can cross build. The basis for this build tool are the [multiarch](https://hub.docker.com/u/multiarch) images, specifically the alpine and the debian-debootstrap ones. `multiarch/alpine` is not provided for ARMv6. There are also extensions that demand a bit more power, I have for example a collection of extensions that host web radio streams. To have some certainty that running a couple of extensions doesn't exhaust a Pi 1, I choose not to support it.

The REM setup scripts detects if it is running with sudo and then installs for the sudo user, so your suggestion should work.

Thanks for including this PR in the v8.1 release!

**Comment by MichaIng** [comment]
Okay sounds reasonable regarding ARMv6, also its right that running Docker engine with applications on an ARMv6 RPi model with 256 MiB or 512 MiB max is anyway not performing so well, respectively consumes too much resources quickly.

Jep, we recognised the `SUDO_USER` handling, something we need to unset to assure that when users start `sudo dietpi-software` it still installs with expected root user 😄. But generally running services as non-root service user is what we aim for in all cases, so we can make use of `SUDO_USER` for this. Actually no need for `sudo -u roon-extension-manager sudo ./rem-setup.sh`, but `SUDO_USER='roon-extension-manager' ./rem-setup.sh` should work. I'll create an issue to test and implement with next release.

**Comment by JanKoudijs** [comment]
> something we need to unset to assure that when users start sudo dietpi-software it still installs with expected root user

Now that we are at it, there have indeed issues been reported when taking this approach:

https://community.roonlabs.com/t/let-me-introduce-roon-extension-manager-1-0-currently-v1-1-1/161624/7

On the other hand the `rem-setup.sh` script should keep its functionality when used on other Linux'es...

**Comment by MichaIng** [comment]
> Now that we are at it, there have indeed issues been reported when taking this approach:

Yes exactly this was the reason why we now unset `SUDO_USER` to assure consistency and intended setup regardless whether users install via `sudo dietpi-software` as different user or via native root user session. But it is perfectly fine to keep the script like that, as it is a common concept to setup software to run as originating non-root user, quite clever using `SUDO_USER` to achieve that while allowing to do the steps within the installer which require root. And it allows us to easily make use of this feature to run REM as non-root user as well, though as dedicated service user (instead of regular login user), like we do in most other cases.

**Pull request merged**
