### PR TITLE
DietPi-Software | Migrate documentation URLs

### LINKED ISSUE #4089: Output of "dietpi-software list" prints out links to outdated dietpi.com/phpbb instead of dietpi.com/docs
#### Is your feature request related to a problem? Please describe:

If `dietpi-software list` is executed, a list of software packages is generated.

Example:
```
root@dietpi:~# dietpi-software list | grep ' =2'
id 5 | =2 | alsa: linux sound system |
id 16 | =2 | build-essentials: common packages for compile |
id 103 | =2 | dietpi-ramlog: minimal, optimised logging | | https://dietpi.com/phpbb/viewtopic.php?p=68#p68
id 104 | =2 | dropbear: lightweight ssh server | | https://dietpi.com/phpbb/viewtopic.php?p=62#p62
```

This list output contains links to dietpi.com/phpbb. The phpbb software area is outdated and is replaced by the dietpi.com/docs area.

#### Describe the solution you'd like:

The links shall direct to dietpi.com/docs. The example above e.g. should link to

- https://dietpi.com/docs/software/log_system/#dietpi-ramlog
- https://dietpi.com/docs/software/ssh/#dropbear

The solution is somehow a rework of the `aSOFTWARE_...` structure in `dietpi-software`: 

```
software_id=103
aSOFTWARE_NAME[$software_id]='DietPi-RAMlog'
aSOFTWARE_DESC[$software_id]='minimal, optimised logging'
aSOFTWARE_TYPE[$software_id]=-1
aSOFTWARE_CATEGORY_INDEX[$software_id]=0
aSOFTWARE_ONLINEDOC_URL[$software_id]='p=68#p68'
```

which is evaluated in 

```
# - Online docs
[[ ${aSOFTWARE_ONLINEDOC_URL[$i]} ]] && string+=" | \e[90m$FP_ONLINEDOC_URL${aSOFTWARE_ONLINEDOC_URL[$i]}\e[0m"
```

I could support in changing all the `aSOFTWARE_...` entries if the general scripting is changed.

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Software | Migrate documentation URLs shown by dietpi-software to our new documentation site and add a few missing URLs: https://dietpi.com/docs/
+ DietPi-Software | Xfce Power Manager: Rename it so that it matches how the name is shown within its GUI
+ DietPi-Software | X.Org X Server: Rename it to include the actual implementation we install
+ DietPi-Software | Rephrase or extend a few software descriptions, which were a bit short or nor precise

### CODE REVIEW

**Comment by MichaIng** [comment]
The change is trivial, so I added reviewers mostly to inform that also script-wise the phpBB-based docs have now been deprecated. I hope I didn't add much typos 😅.

**Comment by Joulinar** [comment]
I checked it briefly. Looks fine so fare. If needed we will adjust over time 🤣

**Review by Joulinar — APPROVED** [review]

**Review by nonnorm — APPROVED** [review]

**Comment by StephanStS** [comment]
@MichaIng: Should also the wiki site https://github.com/MichaIng/DietPi/wiki/How-to-add-a-new-software-title be changed from phpbb to docs?

**Comment by MichaIng** [comment]
Indeed, I'm on it. **EDIT: Done!**

**Pull request merged**
