### PR TITLE
Release v6.30

### LINKED ISSUE #3505: dietpi-update fails to set files/file permissions in /run/dietpi
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`

G_DIETPI_VERSION_CORE=6
G_DIETPI_VERSION_SUB=29
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version | `echo $G_DISTRO_NAME` or `cat /etc/debian_version`

buster

- Kernel version | `uname -a`

Linux hostname 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux

- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)

RPi Zero W (armv6l) 

(as well as rpi3b+/armv7l and another rpi zero w - it's all the same)

- Power supply used | (EG: 5V 1A RAVpower)

5V / 2A dedicated

- SDcard used | (EG: SanDisk ultra)

SanDisk Extreme 64GB

#### Additional Information (if applicable)
- Can this issue be replicated on a fresh installation of DietPi?

not sure

#### Steps to reproduce

1. `sudo dietpi-update`
2. `reboot`
3. login (via ssh)

#### Expected behaviour

1. the actual file(s) should exist (or be touched)
2. the permissions should be "right" (depends on the files, but .network definitely needs 666)
(maybe: 3. ownership should be right)

#### Actual behaviour

error message: 

/boot/dietpi/func/dietpi-banner: line 222: /run/dietpi/.dietpi_motd: no permission
/boot/dietpi/func/obtain_network_details: line 143: /run/dietpi/.network: no permission

#### Extra details

Nothing to declare ;-)

### LINKED ISSUE #3509: dietpi-ramlog: No such file or directory
#### Details:
- Date           | Tue May  5 14:59:38 BST 2020
- DietPi version | v6.29.2 (Fourdee/master)
- Image creator    | DietPi Core Team
- Pre-image          | FriendlyARM
- Hardware           | NanoPi NEO (armv7l) (ID=60)
- Kernel version   | Linux DietPi 4.14.0 #1 SMP Mon Dec 18 11:43:22 CST 2017 armv7l GNU/Linux
- Distro                 | stretch (ID=4)
- Command          | /boot/dietpi/func/dietpi-ramlog 1
- Exit code            | 127
- Software title      | DietPi-Software
#### Steps to reproduce:

1. Download DietPi_v6.14_NanoPiNEO-ARMv7-Stretch.img
2. Write the image to SD-Card
3. Adjust both the software password and user passwords to the same password
4. Don't keep p7zip-full
5. Opt Out of DietPi-survey
6. Log in after reboot
7. Don't select any software
8. Select install
#### Expected behaviour:
- DietPi should be installed
#### Actual behaviour:
- The error mentioned in `Additional logs` is happening
#### Extra details:
- It works with the new buster image.
#### Additional logs:
```
/boot/dietpi/func/dietpi-globals: line 939: /boot/dietpi/func/dietpi-ramlog: No such file or directory
```

### LINKED ISSUE #3510: RPi 3 b+ Wifi Hardware not found
#### Required Information
- DietPi version | v6.29.2
- Distro version | Buster
- Kernel version | `Linux DietPi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux`
- SBC model | RPi 3 Model B+ (armv7l)
- Power supply used | 5V
- SDcard used | Samsung EVO 32 GB

#### Additional Information (if applicable)
- Software title | NONE
- Was the software title installed freshly or updated/migrated? NONE
- Can this issue be replicated on a fresh installation of DietPi? YES, tried on another board, same issue

- Bug report ID | 96edd9cc-fb67-4662-ada7-59515d679138

#### Steps to reproduce

1. This is a clean version of DietPi installed from the website.
2. After flashing, switched on the rpi3 b+ with ethernet cable connected. OpenSSH
3. I am not sure about this step. Either first, it updated to the latest DietPi 6.29.2 then prompted global password change or first prompt global password change then updated to latest version.
4. Ran Dietpi-update to confirm it is updated or not.
5. Ran dietpi-config to configure the wifi. 
6. Issues found(Check the screenshot attached below)

#### Expected behaviour

Duh!! Once enabled, I can scan Wifi in my area, connect to my wifi by adding a password.

#### Actual behaviour

No supported WiFi hardware was found. Then it prompts me to "Would you like to disable Wifi?"

#### Extra details

- The previous version of DietPi never had such issues. It would be preferred that the users get the option to upgrade or not.
- To confirm its a hardware problem or not, I checked with another RPi3 b+ board and faced the same issue. Please help!!! 
- I mostly use this for Media Server : Emby.

wifi => Not Enabled(before installing)
Annotation 2020-05-05 211627 - Copy
after installing wifi thingy => No hardware found (Even after rebooting same issue)
image

### LINKED ISSUE #3511: RootFS is currently Read Only (R/O) mounted. Aborting...
ADMIN EDIT:

A possible workaround could be:

1. login as `root`
2. `mount -o remount,rw /`
3. `nano /etc/fstab`
4. add the line for rootFS > `PARTUUID=<YOUR-ID>-02 / ext4 noatime,lazytime,rw 0 1`
5. `PARTUUID` needs to be adjusted, should be same like `/boot` if you use SD card. Be careful and use the right partition `-02`
6. save and exit
7. `reboot`

To get/verify the ID just use `blkid`. You can identify the rootFS by the lable `LABEL="rootfs"`

```
root@DietPi3:~# blkid
/dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="5203-DB74" TYPE="vfat" PARTUUID="6c586e13-01"
/dev/mmcblk0p2: LABEL="rootfs" UUID="2ab3f8e1-7dc6-43f5-b0db-dd5759d51d4e" TYPE="ext4" PARTUUID="6c586e13-02"
/dev/mmcblk0: PTUUID="6c586e13" PTTYPE="dos"
```

It should looks like this afterwards (just with your PARTUUID)
```
#----------------------------------------------------------------
# PHYSICAL DRIVES
#----------------------------------------------------------------
PARTUUID=6c586e13-02 / ext4 noatime,lazytime,rw 0 1
PARTUUID=6c586e13-01 /boot vfat noatime,lazytime,rw 0 2
```

---

#### Required Information
- DietPi version | v6.29.2
- Distro version | buster
- Kernel version | Linux DietPi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- SBC model | RPi 4 Model B (armv7l)
- Power supply used | 5V 1A RAVpower
- SDcard used | 32 GB SanDisk ultra

#### Additional Information (if applicable)
- The software title installed freshly
- Can this issue be replicated on a fresh installation of DietPi? **YES**.

#### Steps to reproduce

1. Installed Fresh version of DietPi from website
2. Flashed SD Card with image
3. Instlled Sonarr, Nzbget, Deluge
4. Set a static IP address
6. Installed Open VPN client with `sudo apt-get install -y openvpn`
7. mounted my NAS via NFS

#### Expected behaviour
- Running as usual 
- Softwares working

#### Actual behaviour
-  After rebooting RootFS becomes Read only
- All Software stops working
- Unable to use dietpi-_______ commands except for dietpi-explorer and dietpi-drive_manager
- When I try and run dietpi-Software for example I get:

> RootFS is currently Read Only (R/O) mounted. Aborting
>DietPi requires RootFS to be Read/Write (R/W) mounted. Please run "dietpi-drive_manager" to re-enable.

image

When I run dietpi-drive_manager it notices all mounted drives but at the end it says:
> cp: cannot create regular file '/etc/fstab': Read-only file system

image

in the dietpi-drive_manager it says
> Please select a drive to see available options.
>      - User data location: RootFS (/mnt/dietpi_userdata)

image

image

When I choose the `/boot` option and select `Transfer RootFS` it says:

> It says [WARNING] Partition must be unmounted, before format and RootFS transfer can begin.
Please unmount the partition, then try again.

image

I tried doing a fresh install 3 times and still have the same problem. This only started occurring after updating was working fine before.

Any help to fix this will be appreciated.

### LINKED ISSUE #3513: Update to 6.29.2 failed
#### Required Information
- Date           | Wed  6 May 21:08:41 EDT 2020
- Bug report     | N/A
- DietPi version | v6.25.3 (MichaIng/master)
- Img creator    | DietPi Core Team
- Pre-image      | Raspbian Lite
- SBC device     | RPi 3 Model B+ (armv7l) (index=3)
- Kernel version | `#1253 SMP Thu Aug 15 11:49:46 BST 2019`
- Distro         | stretch (index=4)
- Command        | /DietPi/dietpi/func/dietpi-ramdisk 1
- Exit code      | 127
- Power supply used | 5V 2.5A
- SDcard used | Samsung 32GB EVO

#### Additional Information (if applicable)
- Software title | DietPi-Update

#### Steps to reproduce

1. ran sudo dietpi-update

#### Expected behaviour

Successful installed

#### Actual behaviour

Failed install

#### Extra details:
[FAILED] DietPi-Update | /DietPi/dietpi/func/dietpi-ramdisk 1
[FAILED] DietPi-Update | /DietPi/dietpi/func/dietpi-ramdisk 1
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
[FAILED] DietPi-Update | /DietPi/dietpi/func/dietpi-ramdisk 1

#### Additional logs:
```
Log file contents:
/DietPi/dietpi/func/dietpi-globals: line 1316: /DietPi/dietpi/func/dietpi-ramdisk: No such file or directory
```

--------------------------------------------------------------------

[FAILED] DietPi-Update | Unable to continue, DietPi-Update will now terminate.

### LINKED ISSUE #3524: DietPi-Software | qBittorrent: Set 775 permissions/002 UMask by default on install
#### Is your feature request related to a problem? Please describe:

- radarr/sonarr can't hardlink downloaded files from qbittorrent

#### Describe the solution you'd like:

- add UMask=002 in qbittorrent.service

#### Additional context

- [https://github.com/MichaIng/DietPi/issues/2339](https://github.com/MichaIng/DietPi/issues/2339)

### PR DESCRIPTION
**Pull request by MichaIng**
### v6.30
_(10/05/30 Hotfix)_

#### Changes / Improvements / Optimisations
- DietPi-Software | qBittorrent: Changed default download file permissions so that Sonarr/Radarr/Lidarr/.. are able to manipulate the downloads after import. Many thanks to @compdealer for doing this suggestion: https://github.com/MichaIng/DietPi/issues/3524

#### Bug Fixes
- DietPi-Config | Resolved an issue where on RPi3/4/Zero W onboard WiFi could not be enabled. Many thanks to @elitearmedforce for reporting this issue: https://github.com/MichaIng/DietPi/issues/3510
- DietPi-Drive_Manager | Resolved an issue on Raspberry Pi where, after running DietPi-Drive_Manager, the root file system was mount read-only. Many thanks to @Adsouza98 for reporting this issue: https://github.com/MichaIng/DietPi/issues/3511
- DietPi-Banner | Resolved an issue where non-root users were unable to download a new MOTD (message of the day). Many thanks to @PeterLacknase and @fnsnyc for reporting this issue: https://github.com/MichaIng/DietPi/issues/3505, https://github.com/MichaIng/DietPi/issues/3520
- DietPi-Boot | Resolved an issue where non-root users were unable to read or update DietPi-internal network info, which lead to e.g. error messages on login. Many thanks to @PeterLacknase for reporting this issue: https://github.com/MichaIng/DietPi/issues/3505
- DietPi-Update | Resolved an issue where on DietPi pre-v6.16 system some DietPi scripts were accidentally removed during update. Many thanks to @Vec7or and @littis for reporting this issue: https://github.com/MichaIng/DietPi/issues/3509, https://github.com/MichaIng/DietPi/issues/3513

### CODE REVIEW

**Comment by MichaIng** [comment]
@Joulinar 
Anything urgent I forgot?

**Comment by Joulinar** [comment]
Within the forum we have some message that sonarr and radarr have issues after the update. Not sure what is the cause. All have different symptoms. 

https://dietpi.com/phpbb/viewtopic.php?f=11&t=7598

But more important to have Drive Manager fixed as well as the missing files

**Comment by MichaIng** [comment]
@Joulinar 
I had a look into it. Indeed doesn't look like an obvious bug our side, especially since the DietPi update does not touch existing Sonarr/Radarr/Lidarr/Jackett instances and the errors are so very different. Probably it is/was a faulty mono version. Sometimes the many APT package updates and/or service restarts trigger errors that have nothing to do with the actual update but e.g. a faulty APT package or existing disk corruption that becomes apparent due to physically moved data, server restart or such. So I'll not defer v6.30 until tomorrow, but we'll keep investigating those issues of course 👍.

**Comment by Joulinar** [comment]
@MichaIng 
yap I assume the same. Possibly due to `apt` or the triggert `restart` some issue came into the picture that are unknown before. 

I know it's wrong place but maybe we can think on some `apt update/upgrade` and do a `restart`, before going to implement new DietPi Release. But honestly I even have no idea how to implement in theory, because users would need to be involved actively and test their application after `apt` and right before DietPi update. I guess it would be way to complicated and far away from DietPi philosophy to take a lot of load from users and automate as much as possible. 🤔

**Comment by MichaIng** [comment]
@Joulinar 
There is an open request, planned for next release, to do daily automated APT upgrades via `dietpi-update`, optionally of course.
So one can do update checks only, or automated APT update && upgrade afterwards. This basically is a lightweight replacement for [unattended-upgrades](https://packages.debian.org/buster/unattended-upgrades) which for our end does not randomly block APT.
I think many users do not regularly upgrade their APT packages, and then the DietPi update contains a high amount of them, raising the risk that something does not end smoothly. This feature would keep the amount of upgraded packages per session low, and if any issue appears it can quickly be associated with the last daily APT upgrades.

**Comment by Joulinar** [comment]
@MichaIng 
probably it can be combined with automatic restarts? Just to have it activated as well. Maybe the user can select a time window. Not sure if this is wise idea. 🤔

**Comment by PeterLacknase** [comment]
I don't know you in person and i don't know your goals. But as a BSD-guy and on the Linux side rather a "veteran" i'd highly urge you to stay away from too much "automatism". systemd is annoying enough. :-) 

Automated daily updates are possibly ok for desktops. (And even there ... if somebody writes his scientific thesis or has to finish some business papers it's better to have a "potentially missing feature" or a "not that annoying bug" than an "up to date incompatibility".) 

It's better imho to just check if apt updates are required before dist-upgrade. If so, stop the process. Give a warning/recommendation to update packages via apt by hand. If something breaks it won't break the dist-upgrade (and leave an even bigger mess behind).

Just my 2 cents.

**Comment by MichaIng** [comment]
@Joulinar 
The daily update (check) is done as cron job, where time can be chosen via `dietpi-cron`. Generally APT upgrades are designed a way that a system restart is not required. For this reason also DietPi updates do not force a restart anymore. However of course for testing (before release) restart must be part of the schedule.

@PeterLacknase
Of course this will be an optional feature (disabled by default), for systems and users where some service/process downtime is not a big issue. The DietPi update does and will always include an APT upgrade as first step. This is the only way to assure that our scripts can use external commands and e.g. parse output reliably, when all systems are brought onto the same APT stage. `apt-get dist-upgrade` is btw not included and we will never do this aside from first boot of a fresh image. It is simply too risky and should only be done with full user attention since it can remove conflicting packages.
E.g. on Raspbian testing suite I regularly run into situations where PHP, MariaDB, the webserver or once even important system core packages would have been removed by a dist-upgrade since a package was updated in the repo but not all packages that are either dependencies or dependants of it. Raspbian repo maintainers do not pay much attention on testing suite repo consistency compared to Debian.

**Pull request merged**
