### PR TITLE
DietPi-Software | NZBGet: Migrate to new project maintainer

### PR DESCRIPTION
**Pull request by Joulinar**
Update of the download URL due to a new project maintainer.

- https://dietpi.com/forum/t/nzbget-new-maintainer-dietpi-software-already-updated/18425
- https://www.reddit.com/r/usenet/comments/17k0tda/new_nzbget_project/
- https://nzbget.com/documentation/installation-on-linux/

It seems FQDN changed from `nzbget.net` to `nzbget.com`

### CODE REVIEW

**Comment by Joulinar** [comment]
ok download URL not working yet and they don't support CPU architecture (aarch64) as of now. Therefore keeping this in draft for now.

**Comment by MichaIng** [comment]
We could pull them directly from GitHub, using the common `api.github.com` method: https://github.com/nzbgetcom/nzbget/releases

This is also where the download links on their website are pointing to, only their docs are currently wrong 😄.

**Comment by MichaIng** [comment]
Seems to work well now: https://github.com/MichaIng/DietPi/actions/runs/6932552257

I also switched form log file to journal logging the process in foreground (within the systemd service). The `nzbget.com` download URL btw seems to be a docs bug, so it seems to be not intended to keep that one, so that we need to use the GitHub API.

**Comment by Joulinar** [comment]
I see they added arm64 support recently

**Comment by MichaIng** [comment]
Yes, I pushed that a little since it seemed simple, given that `aarch64` was previously supported and is hence part of the build scripts already. He even backported the build into the current release 🙂.

**Comment by Joulinar** [comment]
Ok I might be able to test on RPI4 later the evening

**Comment by MichaIng** [comment]
Docs PR up: https://github.com/MichaIng/DietPi-Docs/pull/957

**Pull request merged**
