### PR TITLE
DietPi-Software | Syncthing: (Re)Install optimizations

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready
🈯️ Reinstall
🈯️ Uninstall
🈯️ Fresh install
- [x] Changelog

**References**:
- https://github.com/Fourdee/DietPi/pull/2278
- https://github.com/Fourdee/DietPi/issues/422

**Commit list/description**:
+ DietPi-Software | Syncthing: Switch to always up-to-date download URL
+ DietPi-Software | Syncthing: Preserve existing install dir, skipping download&install and inform user instead
+ DietPi-Software | Syncthing: Install full download dir (especially readme and license) instead of just the binary
+ DietPi-Software | Syncthing: Place sysctl setting(s) into own sysctl.d/ file

### CODE REVIEW

**Comment by MichaIng** [comment]
Question:
- Will `syncthing -generate` overwrite existing configs?
In case we should only run this, if it does not yet exist. At best then also skip touching the config file at all to not overwrite manual user adjustments?

Answer:
```
17:10:45 WARNING: Key exists; will not overwrite.
17:10:45 INFO: Device ID: XODU6FO-VHTNAAF-KMJS7AT-OUIRWIY-CUFC4MA-S2XQUCP-2TA7OQU-B7VM6QY
17:10:45 WARNING: Config exists; will not overwrite.
```
- It already handles this greatly 👍.

Do we still want to skip these steps, if the configuration file does already exist to prevent manual user settings?

**Comment by MichaIng** [comment]
NB:
- The WebUI is already reachable via HTTPS without related setting.
- The setting only forces HTTPS by doing automated redirection 👍.

Further ideas (**post v6.18 release!**):
- Actually /etc/syncthing is not the "correct" location for a binary. This is meant to be for config files, which we with reason safe in dietpi_userdata.
- `/opt/syncthing` (or `/usr/local/bin` for the binary only) would fit better, or to have everything in one place, safe the binary as well within userdata?
  - `syncthing_bin/` `syncthing_conf/` `syncthing_data/` or
  - `syncthing/bin/`, `syncthing/conf/` `syncthing/data/`?

Further ideas to add user/password and do other pre-configuration optimizations: https://github.com/Fourdee/DietPi/issues/422#issuecomment-441443135

**Comment by Fourdee** [comment]
@MichaIng 

Looks good, thanking you 👍 

Will merge and test existing install + reinstall + GUI upgrade + fresh install
🈯️

**Comment by Fourdee** [comment]
@MichaIng 

Works a charm, nice one 👍

**Pull request merged**
