### PR TITLE
v159

### PR DESCRIPTION
**Pull request by Fourdee**
**v159**
(10/12/17)

**Image Modifications:**

VMWare | Updated to Debian Stretch: https://github.com/Fourdee/DietPi/issues/1219

VirtualBox | Updated to Debian Stretch, many thanks @MichaIng: https://github.com/Fourdee/DietPi/issues/1219

RPi | Updated to Debian Stretch: https://github.com/Fourdee/DietPi/issues/475

**Changes / Improvements / Optimizations:**

General | Odroid XU3/4 images updated: Includes kernel support for EMMC 5.1 (thanks Meveric): https://github.com/Fourdee/DietPi/issues/1252

General | DietPi RPi kernel: Updated to 4.9.62.

General | DietPi RPi kernel: Will no longer re-install, if the current version is already at latest.

General | Added fahrenheit readouts for cpu_info and dietpi-config. For those "over the pond" :D : http://dietpi.com/phpbb/viewtopic.php?f=12&t=2516&p=9772#p9772

General | Sparky SBC: Kernel update to add support for USB 1.1 DACs, thanks @sudeep. This must be enabled manually, if using a USB 1.1 DAC, as this breaks Allo WiFi dongle. Edit "/DietPi/uEnv.txt" and change the value "aotg.aotg1_speed=1" (from "0"), then reboot.

General | We now define a default LD_LIBRARY_PATH for all systems, exported from /etc/bash.bashrc: https://github.com/Fourdee/DietPi/issues/475#issuecomment-350380744

DietPi-Services | Run "dietpi-services help" to see a full list of updated commands: Added support for "enable" and "disable". "disable" will stop and disable the service and prevent it from running, "enable" will enable and start the service. EG: "dietpi-services disable cron", will prevent Cron from starting. Added support for start/stop/restart a single service (eg: dietpi-services stop apache2). This is basically a symlink to systemD: https://github.com/Fourdee/DietPi/issues/1114

DietPi-Config | WiFi: Now uses the wpa_supplicant.conf method to setup WiFi connections. WEP is no longer supported by DietPi in this mode. WPA-PSK/WPA2-PSK and OPEN hosts supported: https://github.com/Fourdee/DietPi/issues/1262

DietPi-Backup | "Full Backup" Mode is now the default for fresh DietPi installations. This is mainly due to MySQL data now being in the DietPi userdata directory.

DietPi-Config | Tools > Benchmarks: Added ability to benchmark CPU performance based on bash + integer: https://github.com/Fourdee/DietPi/issues/1253#issuecomment-346881878

DietPi-Config | Time sync modes: NTP is now uninstalled when SystemD timedatectl is enabled. Reinstalled on demand. Timedatectl pool servers are now also set: https://github.com/Fourdee/DietPi/issues/1208#issuecomment-343762480

DietPi-Software | First run setup, now logged to /etc/dietpi/logs/dietpi-firstrun-setup.log.

DietPi-Software | APT log: Moved to /etc/dietpi/logs/dietpi-software_apt.log, to prevent RAMlog clearing log during automated installations.

DietPi-Software | MPD (Stretch): Install updated to 0.20.11. Also supports native DSD playback (thanks to @sudeep and PJotr), when "Native" output freq/bit is set: https://github.com/Fourdee/DietPi/issues/1236

DietPi-Software | moOde: MPD now installed via pre-built binaries. Will reduce install time: https://github.com/Fourdee/DietPi/issues/1223#issuecomment-345265290

DietPi-Software | Nextcloud: Correct database access issue for MariaDB + minor fixes: https://github.com/Fourdee/DietPi/pull/1242

DietPi-Software | ownCloud: Installation fixed, respecting different distro repos: https://github.com/Fourdee/DietPi/pull/1243

DietPi-Software | MPD (inc YMPD/O!MPD): Default data directory is now "/mnt", this will include all USB drives and network locations: https://github.com/Fourdee/DietPi/issues/1202

DietPi-Software | Mopidy: Default data directory is now "/mnt", this will include all USB drives and network locations.

DietPi-Software | Syncthing: Installation updated to version 0.14.40, for new installations only. Removal of inotify (now included in main syncthing): https://github.com/Fourdee/DietPi/issues/1260

DietPi-Software | Node-Red: Symlink created during install from ~/.node-red to DietPi user data dir: https://github.com/Fourdee/DietPi/issues/1256

DietPi-Software | YMPD: Fixed Stretch installation + Now available for all CPU archs + Upgraded to SystemD service: https://github.com/Fourdee/DietPi/issues/475

DietPi-Software | Gitea: Install updated to 1.3.1 (for new installations only). Added support for ARMv8. Now installed to /mnt/dietpi_userdata/gitea, runs as dietpi user: https://github.com/Fourdee/DietPi/issues/686 http://dietpi.com/phpbb/viewtopic.php?f=8&t=5&p=9863#p9863

**Bug Fixes:**

DietPi-Automation | Resolved an issue where SSH server choice, was not installing selected choice: https://github.com/Fourdee/DietPi/issues/1122

DietPi-Config | Nvidia driver: nouveau now disabled by default on x86_64, fix for 750Ti and possibily other Nvidia chipsets (thanks dubyazero): https://github.com/Fourdee/DietPi/issues/1244

DietPi-Config | RPi Stretch: Resolved an issue with onboard Wifi failing to scan: https://github.com/Fourdee/DietPi/issues/1262

DietPi-Config | RAM Benchmark: Resolved an issue where devices without /tmp mounted to tmpfs would fail the test. We now check for this mount, prior to allowing the test to run: https://github.com/Fourdee/DietPi/issues/1130#issuecomment-350114298

DietPi-Software | Pi-Hole: Resolved various issues with this installation. DietPi will now also detect a failed Pi-Hole script exit and flag as not installed. : https://github.com/Fourdee/DietPi/issues/1282#issuecomment-350490524

DietPi-Software | Redis: Minor un/installation/activation fixes of PHP module (Thanks to @MichaIng) : https://github.com/Fourdee/DietPi/pull/1249

DietPi-Software | moOde: Resolved an issue where dietpi-drive_manager mounted drives, would not be available in the libary: https://github.com/Fourdee/DietPi/issues/1223#issuecomment-346708298

DietPi-Software | PHP: Solve 'upload_tmp_dir' issue, if PHP service uses 'PrivateTmp': https://github.com/Fourdee/DietPi/issues/1144

DietPi-Software | Syncthing: Resolved a permissions issue with self program updates: https://github.com/Fourdee/DietPi/issues/1260

DietPi-Software | Home Assistant: Resolved an issue with ARMv8 installation, where Python build would fail due to lack of build-essential: https://github.com/Fourdee/DietPi/issues/1255

DietPi-Software | MPD: Corrected various uninstallation issues.

DietPi-Software | APT Removal: Resolved an issue in Stretch, where held packages were not being removed: https://github.com/Fourdee/DietPi/issues/475

DietPi-Software | FFMPEG: Resolved inability to install on XU4 Jessie: https://github.com/Fourdee/DietPi/issues/1273

DietPi-Software | Chromium (RPi Stretch): Resolved installation + desktop icon symlink: https://github.com/Fourdee/DietPi/issues/475#issuecomment-350111359

DietPi-Software | Resolved an issue where dietpi permissions were not being set correctly, for symlinked userdata dir.

DietPi-Update | Resolved an issue where .update_available file would still exist in no network situations: https://github.com/Fourdee/DietPi/issues/1258

Patch_File | Auto swapfile generation no longer run twice (mostly for pre v150 images): https://github.com/Fourdee/DietPi/issues/1257

**Allo Web Interface v4:**

MPD: Native DSD playback support, when "Native" output freq/bit is set in MPD settings page: https://github.com/Fourdee/DietPi/issues/1241

MPD: Default data directory is now "/mnt", this will include all USB drives and network locations.

SQUEEZELITE: Added ability to set native DSD output modes. Please note, success of selected output mode is limited to DAC and kernel capabilities. We have verified Combo 384 with u32le output mode on Sparky SBC + USB Bridge: https://github.com/Fourdee/DietPi/issues/1237#issuecomment-348241209

O!MPD: Updated to 1.03. Please make sure to update your library (Settings > Update), to rescan the new "/mnt" location which includes all networked and USB drives. Depending on your additional storage setup, the rescan may take 5-30 minutes.

RPi Image: Has been updated to Debian Stretch. This offers peformance improvements in the web interface, and newer ALSA libs. Previous installations are still supported. To upgrade, please write the new image. Upgrading to Stretch is not a requirement: http://dietpi.com/phpbb/viewtopic.php?f=8&t=2317&p=8869#p8869

Sparky SBC: We have remove the WiFi Hotspot installation by default, this is to avoid majority users having to remove this software title, before WiFi can be configured via terminal access. To reinstall this software, please connect the WiFi dongle, then run "dietpi-software install 60" via terminal.

### CODE REVIEW

**Comment by Invictaz** [comment]
@fourdee That is a big list. Congrats! I wonder why RPi is still on 4.9 kernel which is quite old. 4.12 has native Pi Zero support and 4.15 is in test now.

**Comment by Fourdee** [comment]
@Invictaz 

As i've mentioned previously, 4.9 is LTS, we will follow/match official RPi image main kernel versions, to ensure stable experience.

**Comment by MichaIng** [comment]
Jep looks good!

I suggest the two changelogs about ownCloud+Nextcloud moved into bugfixes and add the content of latest Phase II to changes/improvments. Will add this together with installation info echos and user info in forum tomorrow.

**Comment by MichaIng** [comment]
@Invictaz
https://github.com/raspberrypi/firmware/commits/master
As fourdee already mentioned in between, we are already on master instead of stable rpi firmware repo. I guess "next" would be a bid too experimental.

**Comment by Fourdee** [comment]
@MichaIng 

> I suggest the two changelogs about ownCloud+Nextcloud moved into bugfixes and add the content of latest Phase II to changes/improvments. Will add this together with installation info echos and user info in forum tomorrow.

Legend, you have admin rights on forums 👍

**Comment by MichaIng** [comment]
@Fourdee 
`Legend, you have admin rights on forums 👍`
Thanks, but hmm I don't see an option yet to edit your posts on software overview? Admin rights are there, shown at bottom, but maybe even admin is not allowed to edit another admins posts on blocked thread?

**Comment by k-plan** [comment]
@MichaIng 

> Thanks, but hmm I don't see an option yet to edit your posts on software overview? Admin rights are there, shown at bottom, but maybe even admin is not allowed to edit another admins posts on blocked thread?

Hmm ... you want to edit this?

 http://dietpi.com/phpbb/viewtopic.php?f=8&t=10

Hit `*Edit`in the top line and get started. And have fun ... 😄 



If you are Mod or Admin you can do everthing with postings or threads on forums.
That is irrelevant, if  it's `LOCKED` or who has post this.




@Fourdee 
- can you please switch me back to "green"? Thanks.

**Comment by Fourdee** [comment]
@k-plan 

> can you please switch me back to "green"? Thanks.

Done 👍

**Comment by MichaIng** [comment]
@k-plan @Fourdee 
> Hit *Editin the top line and get started. And have fun ... 😄

Yes thought so, but there is no edit button at the top, just quote and report. Just found it on my own posts, where expected, but not on any others post, as if would not be admin yet.
On user profile I see that I am member of admin group, also `[ Administer user ]` and log into admin panel is possible. But I don't see any admin features at other peoples post, whether edit nor lock or something like that. Already tried to relog, but does not help so far.
Maybe permissions on the forum need to be flushed somehow?

**Comment by k-plan** [comment]
@MichaIng 

hmm ... okay, das hört sich jetzt nicht so gut an.
Wenn ich mich noch recht entsinne, müsstest du das aber selber beheben können, solange du dich im Admin-Panel einloggen kannst. Tippe, dir fehlen die Gruppenrechte für `Global moderators`	`All forums`. Du kannst ja einmal bei `johnvick` schauen, welche Unterschiede es zu dir gibt.
Sonst müssen wir auf Fourdee warten, bis der es korrigiert.

Was ich dir noch auf die Schnelle anbieten kann, wäre du erstellst den gewünschten/geänderten Beitrag oder Thread und postest diesen in irgend einen Thread von mir. Muss darin aber bitte einen Link setzen, wo du ihn gerne hinhaben möchtest. Den Rest regele ich dann für dich. Ja, quick-and-very-dirty, nur damit es erst einmal voran geht.

**Comment by Fourdee** [comment]
@MichaIng 

> that. Already tried to relog, but does not help so far.
Maybe permissions on the forum need to be flushed somehow?

Bizarre, although, she is an old PHPbb forum (needs updating, on my list lol)

I've added you to global mods aswell, reapplied all permissions for your account. I used the "Test user permissions" feature, and I could see the edit button.

I've also flushed sessions and cache.

If problems persist, try clearing your browser cache.

**Comment by MichaIng** [comment]
Jep, browser cache seems to be the problem. Everything works on phone. Will do the editing this evening.

€: @Fourdee @k-plan 
It worked now 😃. I just added the information to ownClouds and Nextclouds software posts. I also added a topic about the whole rework to the general forum. I hope it is okay, to have this as announcement for a while? Thought this would be nice, as we have so many (especially Nextcloud) users, that might want to know what is happening to their instance 🙂: http://dietpi.com/phpbb/viewtopic.php?f=9&t=2564

**Comment by Fourdee** [comment]
@MichaIng 

> Jep, browser cache seems to be the problem.

:clinking_glasses:  😃 

> It worked now 😃. I just added the information to ownClouds and Nextclouds software posts. I also added a topic about the whole rework to the general forum. I hope it is okay, to have this as announcement for a while? Thought this would be nice, as we have so many (especially Nextcloud) users, that might want to know what is happening to their instance :slightly_smiling_face:: http://dietpi.com/phpbb/viewtopic.php?f=9&t=2564

Perfect, many thanks 👍

**Pull request merged**
