### PR TITLE
DietPi-Software | PHP, Koel, several

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: WIP
- [x] Further use aSOFTWARE_REQUIRES_PHP , where applicable
- [x] Optional: Merge `TOTAL_SOFTWARE_INDEXS` and `TOTAL_SOFTWARE_INDEXS_HARDLIMIT` or reimplement `TOTAL_SOFTWARE_INDEXS` to only count actually available software titles.

**Commit list/description**:
+ DietPi-Software | Add aSOFTWARE_REQUIRES_PHP for software that needs PHP binary, but no webserver; Add to Koel
+ DietPi-Software | PHP: Install php(5)-cli (PHP binary), if no webserver is installed
+ DietPi-Software | PHP: Revert SQLite module to be only installed, of SQLite is installed
+ DietPi-Software | Koel: (Re)install required PHP modules, to be failsafe
+ DietPi-Software | Minor code improvements and simplifications; Currently: TOTAL_SOFTWARE_INDEXS == TOTAL_SOFTWARE_INDEXS_HARDLIMIT, due to all possible indexes are initialized
+ DietPi-Software | Remove obsolete $TOTAL_SOFTWARE_INDEXS_HARDLIMIT, using $TOTAL_SOFTWARE_INDICES to loop through in every case.
+ DietPi-Software | List: Add "+PHP" string, in case of aSOFTWARE_REQUIRES_PHP
+ DietPi-Software | Download_Install: Minor coding, use direct bash var manipulation instead of "sed"
+ DietPi-Software | Download_Install: Add description to the HowTo comments

### CODE REVIEW

**Review by Fourdee — APPROVED** [review]
@MichaIng 

Nice one, looks good 👍 

Feel free to merge when your ready.

**Comment by MichaIng** [comment]
@Fourdee 
Do you have any idea how to handle that curent TOTAL_SOFTWARE_INDEXS implementation?

Generally it makes sense to skip NULL indexes, but currently those are counted as well for TOTAL_SOFTWARE_INDEXS, thus both variables are the same. I think the overhead will be not too high when loops go through NULL indexes as well, but then we don't need to make a separation between TOTAL_SOFTWARE_INDEXS and TOTAL_SOFTWARE_INDEXS_HARDLIMIT, thus we can replace the second one with the first and remove it from the script.

**Comment by Fourdee** [comment]
@MichaIng 

Yep ```TOTAL_SOFTWARE_INDEXS_HARDLIMIT``` could be removed and replace solely with ```TOTAL_SOFTWARE_INDEXS=170```

```TOTAL_SOFTWARE_INDEXS``` defines the total array size. Although we have null entries in that list, we need to define the array size so we can ensure software index's do not change.

**Comment by MichaIng** [comment]
@Fourdee 
Done. I also changed it to `TOTAL_SOFTWARE_INDICES` to have correct plural of index 😃?

€: Okay, couldn't find any other software for now with PHP but without webserver need. Maybe what I remembered was Koel. aSOFTWARE_REQUIRES_PHP is now not much in use, but I think it doesn't hurt and generally it makes sense and might be useful for future software titles.
I will leave it in place now and merge for testing.
___________________
Restest on VM Jessie:
🈺 Works, but RAM usage peak at **910M** during installation. We should assure, that low memory devices either have enough swap or run RAM intensive build processes outside of **/tmp**!

**Comment by Fourdee** [comment]
>  Works, but RAM usage peak at 910M during installation. We should assure, that low memory devices either have enough swap or run RAM intensive build processes outside of /tmp!

@MichaIng 

Koel, or multiple software titles?

**Comment by MichaIng** [comment]
@Fourdee 
I just watched it on Koel, as I am testing it installation currently on all distros. But, if we want to leave choice to user, if/how much swap is wanted, then we would need to recheck all build installations at best, especially the NodeJS ones. We already do the build process within target directory in some cases, maybe for these large build processes this is the safer default. Just do it within `/tmp`, if we know the RAM usage will never hit 200M.

Btw.: Fix was needed in case of non-webserver PHP installs: https://github.com/Fourdee/DietPi/commit/036ad6ceed6be000ac5f669fd3f1f74059f75540
_________________
Hmm, this happens on Stretch, but did not on Jessie, strange:
```
   │ G_THREAD ERROR:                                                                                             │
   │  - Command = wget https://raw.githubusercontent.com/rlerdorf/opcache-status/master/opcache.php -O           │
   │ /var/www/opcache.php                                                                                        │
   │  - Exit code = 1                                                                                            │
   │                                                                                                             │
   │ /var/www/opcache.php: No such file or directory    
```
- Same with apc.php
🈴 Next error, I didn't see on Jessie, strange: `/DietPi/dietpi/dietpi-software: line 11375: cd: /var/www/koel: No such file or directory` and related follow up error whips...
  - Earlier error is the reason: `mv: cannot move 'koel-3.7.2' to '/var/www/koel': No such file or directory` 🤔 Since when moving a directory + renaming is no possible??

Ahhhhh, without webserver, `/var/www` does not exist, thus needs to be created. I guess on my Jessie system, this was somehow in place from earlier webserver installation.
To not mess up with webserver, we anyway should move Koel to another place, e.g. dietpi_userdata/Koel?
Now I also see that we actually NOT build Koel within RAM, but already in target directory! So nothing to change here. I guess on 256M devices the build will take hours then 🤣.
_____________
Follow up PR to solve the issues, moving Koel out of /var/www: https://github.com/Fourdee/DietPi/pull/1954

**Pull request merged**
