### PR TITLE
DietPi-Software | Go

### PR DESCRIPTION
**Pull request by Joulinar**
fix error on creating `/etc/bashrc.d/go.sh`

https://dietpi.com/forum/t/installation-snowflake/6566/12

### CODE REVIEW

**Comment by fazzer4x** [comment]
Just wanting to double check, following code block is missing from the current version: 

```
> # Export Go path variables
> 			G_EXEC mkdir -p /mnt/dietpi_userdata/go/{bin,pkg,src}
> 			cat << '_EOF_' > /etc/bashrc.d/go.sh
> #!/bin/dash
> export GOPATH=/mnt/dietpi_userdata/go
> export PATH="$PATH:/usr/local/go/bin:$GOPATH/bin"
> _EOF_
> 			# shellcheck disable=SC1091
> 			. /etc/bashrc.d/go.sh
```

**Comment by Joulinar** [comment]
Go is not installed to `/mnt/dietpi_userdata/go`anymore. It is `/usr/local/go` now on new installation. Old install are not touched.

**Comment by MichaIng** [comment]
It was always installed at /usr/local/go, but the GOPATH, used as target directory when installing modules and crates, is not set anymore, defaulting to ~/go instead, so it works for any user.

**Review by MichaIng — DISMISSED** [review]

**Comment by Joulinar** [comment]
@MichaIng I will push a change log later the day once back from sea side

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Faster 😛.

**Comment by MichaIng** [comment]
Have you logged out and in or rebooted? PATH cannot be changed for a shell session from within a script, so it needs to be reloaded or a new session opened.

**Comment by MichaIng** [comment]
No, works fine here, with `root` and `dietpi` users:
```console
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
# go version
go version go1.19.3 linux/amd64
```
Ah, did you actually reinstall Go after applying the update? We do not patch this automatically on update, since the file might have been removed intentionally.

**Comment by enviousjag** [comment]
ok, oddly now go is in the path. No idea why

**Pull request merged**
