### PR TITLE
DietPi-Patch | Critical Nginx patch to apply new sites-dietpi file naming

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready
- [x] `patch_file` addition
- [x] Changelog

**Reference**: https://github.com/Fourdee/DietPi/issues/2325#issuecomment-444564109

**Commit list/description**:
+ DietPi-Patch | Critical Nginx patch to apply new sites-dietpi file naming

**Testing**
🈯️ Update from v6.19.5 master
```
root@VM-Jessie:~# dietpi-update 1
[  OK  ] DietPi-Update | Root access verified.
[  OK  ] DietPi-Update | RootFS R/W access verified.


 DietPi-Update
─────────────────────────────────────────────────────
 Mode: Checking for DietPi updates

[ INFO ] DietPi-Update | Checking mirror: https://raw.githubusercontent.com/Fourdee/DietPi/nginx_patch/dietpi/server_version-6
[  OK  ] DietPi-Update | Using update server: https://raw.githubusercontent.com/Fourdee/DietPi/nginx_patch/dietpi/server_version-6

[  OK  ] DietPi-Update | Update available
[ INFO ] DietPi-Update | Current version : v6.19.5 (branch: Fourdee/master)
[ INFO ] DietPi-Update | Latest version  : v6.19.6 (branch: Fourdee/nginx_patch)
[  OK  ] DietPi-Update | DietPi-Userdata validation: /mnt/dietpi_userdata
[  OK  ] DietPi-Update | Free space check: path=/ | available=5850 MB | required=100 MB
[  OK  ] DietPi-Update | Update is being applied, please wait...
[ SUB1 ] DietPi-Services > stop
[  OK  ] DietPi-Services | stop : cron
[  OK  ] DietPi-Services | stop : nginx
[  OK  ] DietPi-Update | wget https://raw.githubusercontent.com/Fourdee/DietPi/nginx_patch/dietpi/pre-patch_file -O pre-patch_file

 DietPi-Pre-patch
─────────────────────────────────────────────────────
[ INFO ] Applying critical pre-patches

[ INFO ] Pre-patch 2 | Nginx: Hotfix to apply new naming scheme for /etc/nginx/sites-dietpi/*.(config => conf)
[ SUB1 ] DietPi-Services > start
[  OK  ] DietPi-Services | start : php5-fpm
[  OK  ] DietPi-Services | start : nginx
[  OK  ] DietPi-Services | start : cron
[ SUB2 ] DietPi-Process_tool > Apply
[  OK  ] DietPi-Process_tool | Completed
[ INFO ] Pre-patch 3 | DietPi-Software: Resolving "systemctl force-reload" error in case of inactive services
[ INFO ] DietPi-Update will now exit. No reboot is required, no further update steps are done.
 - To apply the new version string to your terminal session, please manually run:
        source /DietPi/dietpi/func/dietpi-globals
Terminated
root@VM-Jessie:~# grep 'include.*dietpi' /etc/nginx/sites-available/default
        include /etc/nginx/sites-dietpi/*.conf;
root@VM-Jessie:~# grep -E 'G_RUN_CMD systemctl.*(nginx|lighttpd|apache2)' /DietPi/dietpi/dietpi-software
                [[ $(which lighttpd) ]] && G_RUN_CMD systemctl restart lighttpd
                [[ $(which nginx) ]] && G_RUN_CMD systemctl restart nginx
                [[ $(which apache2) ]] && G_RUN_CMD systemctl restart apache2
```
🈯️ Updating from v6.18.12 (some dev stage)
- Pre-patches skipped, full update is done.
- Same result about the dietpi-software and Nginx fix:
```
root@VM-Jessie:~# grep 'include.*dietpi' /etc/nginx/sites-available/default
        include /etc/nginx/sites-dietpi/*.conf;
root@VM-Jessie:~# grep -E 'G_RUN_CMD systemctl.*(nginx|lighttpd|apache2)' /DietPi/dietpi/dietpi-software
                [[ $(which lighttpd) ]] && G_RUN_CMD systemctl restart lighttpd
                [[ $(which nginx) ]] && G_RUN_CMD systemctl restart nginx
                [[ $(which apache2) ]] && G_RUN_CMD systemctl restart apache2
```

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
Found another issue:
```
root@VM-Jessie:~# systemctl force-reload nginx
Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.
root@VM-Jessie:~# systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; disabled)
   Active: inactive (dead)

Dec 05 21:56:31 VM-Jessie systemd[1]: Stopped A high performance web server and a reverse proxy server.
Dec 05 21:57:36 VM-Jessie systemd[1]: Unit nginx.service cannot be reloaded because it is inactive.
```
- `force-reload` is not possible, if the service does not currently run. At least for Nginx on Jessie this is the case. This leads to error prompt due to G_RUN_CMD.
- I suggest we replace `force-reload` with `restart`. I can add it to this very same hotfix.

**Comment by MichaIng** [comment]
Since pre-patch is only required for current v6.19 users and v6.20 will patch this natively, the pre-patches can be removed with v6.20 release as well. No need to keep this inside.

**Comment by Fourdee** [comment]
@MichaIng 

Strange, no error on ARM
```
#G_AGI nginx
#dietpi-services stop

root@DietPi:~# G_RUN_CMD systemctl force-reload nginx
[  OK  ] Root access verified.
[  OK  ] systemctl force-reload nginx
root@DietPi:~# systemctl status nginx -l
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: en
abled)
   Active: inactive (dead) since Thu 2018-12-06 06:22:08 GMT; 15s ago
     Docs: man:nginx(8)
```

**Comment by Fourdee** [comment]
@MichaIng 

Looks good, thanks, will merge 👍

**Comment by MichaIng** [comment]
@Fourdee 
Perhaps force-reload error only occurs on Jessie (lower systemd version), I also could not verify with other services on Buster.
Test of other services on Jessie:
- No error on cron
- Verified error on nginx again
- No error on coturn (init.d)

Check nginx systemd unit:
- Indeed there is a `ExecReload` command defined. Running it manually shows nginx daemon needs to run, since PID file is required:
```
root@VM-Jessie:~# /usr/sbin/nginx -g 'daemon on; master_process on;' -s reload
nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)
```
- So this is a Nginx on Jessie only issue.

Hmm otherwise on Stretch the `ExecReload` is the same and throws the same error, if service not up. However systemctl does not throw it. Seems to be handled somehow since Stretch.

But your new solution via `dietpi-services restart` looks cleanest to me anyway and as well covers deeper changes properly done to webservers, which are not covered by `force-reload` 👍.
______________
Btw:
- I am happy to see this new use for pre-patch: Live hotfix without pushing a whole update including all the update procedure, reboot and such. This covers partly other things I had in mind to implement end user notifications, in case of critical bugs, as well introduced externally (the raspberrypi-sys-mods update breaking APT, Xserver update breaking desktop and such).
- We can keep that in mind, if only a quick fix needs to be applied to solve a critical issue that would lead many bug reports.

To further extend this use, we could delay `dietpi-service stop` to be applied after the pre-patch, so there will be no service downtime. On dietpi-banner we could adjust the update notification accordingly to show that it is a quick hotfix only that does not lead to any service or server downtime, perhaps by using a new .update_stage flag `2`, if only RC version differs on master branch. On Beta/Dev/custom of course always a full patch should be applied.

**Pull request merged**
