### PR TITLE
DietPi-Software | Netdata: Fix critical bug that lead to netdata uninstall removing parts of the whole root directory, destroying the system

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready
- [x] Pre-patch
- [x] Changelog
- [x] RC up

**Testing**
- [x] Update from v6.19.6
```
 DietPi-Pre-patch
─────────────────────────────────────────────────────
[ INFO ] Applying critical pre-patches

[ INFO ] Pre-patch 4 | Fix a critical issue, where uninstalling netdata would break the whole system

[ INFO ] DietPi-Update will now exit. No reboot is required, no further update steps are done.
 - To apply the new version string to your terminal session, please manually run:
        source /DietPi/dietpi/func/dietpi-globals

Terminated
```
- [x] Update from v6.19.5
```
 DietPi-Pre-patch
─────────────────────────────────────────────────────
[ INFO ] Applying critical pre-patches

[ INFO ] Pre-patch 3 | DietPi-Software: Resolving "systemctl force-reload" error in case of inactive services
[ INFO ] Pre-patch 4 | Fix a critical issue, where uninstalling netdata would break the whole system

[ INFO ] DietPi-Update will now exit. No reboot is required, no further update steps are done.
 - To apply the new version string to your terminal session, please manually run:
        source /DietPi/dietpi/func/dietpi-globals

Terminated
root@VM-Stretch:~# grep 'userdel.*netdata' /DietPi/dietpi/dietpi-software
                        userdel netdata
```
- [x] Update from v6.19.4: Leads to full patch

**Reference**: https://github.com/Fourdee/DietPi/issues/2336
- Backport critical parts of: https://github.com/Fourdee/DietPi/pull/2337
- Apply `docker-ce` fix as well, see below

### CODE REVIEW

**Comment by MichaIng** [comment]
Fix docker on RPi as well, if we already push an update? https://github.com/Fourdee/DietPi/issues/2282

**Review by Fourdee — APPROVED** [review]
@MichaIng 

Thanks, looks good my end, feel free to merge if local testing is passed 👍

**Comment by MichaIng** [comment]
@MichaIng 
I'm currently testing Docker fix. Should actually work, since it did for other packages (see link to forum), but if I understood correctly it did not work for user with docker.
**€: Was due to leading `5:` in version string 🙄.**

**Comment by MichaIng** [comment]
Okay, pre-patch, usual patch works fine now.

Have to work for 2 hours, will do final testing afterwards. And switch change to RPi + Raspbian package (currently applies on Debian, for testing purpose, but on Raspbian everything else is identical).

Release definitely today.
__________
🈯️ Final test of all install/update paths passed. Will switch to raspbian and merge.

**Comment by MichaIng** [comment]
- [x] Updated dietpi.com update repo
- [x] Ported Docker related changes over to dev
- Netdata PR up with further enhancements in dev: https://github.com/Fourdee/DietPi/pull/2337

**Comment by Fourdee** [comment]
@MichaIng 

Legend, thank you 👍

**Pull request merged**
