### PR TITLE
DietPi-Software | Part 2: Merge "Optimised" and "Additional" software menus

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Review

The separation between "additional" software and "optimised" software did never follow any consistent rule:
- Partly the aim was to put non-end-user software there, which is usually pulled as dependency. But that does not apply to e.g. network tools and editors, which are clearly end-user software, never pulled as dependency.
- The other idea, probably the very initial one, was to put software titles there which are installed via APT only, without any "optimisation" done our side. But again there are many software titles in the "optimised" list, which are installed only via APT as well, sometimes simply because the APT package became better, newer of such.
- The meaning of this separation is hence not clear and may be confusing to users.

The problem with the separation is that especially development environments are degraded in a way, while we want to have programming languages, runtime environments, their packaging tools in case and such more prominent, to better target developers as well. The list becomes longer, but the "optimised" list was very long already, while the "additional" list was quite short, so merging them does not increase the list significantly, and of course to cover this, we added the search option.

The software titles from the additional list mostly have no description and no docs URLs, hence this would need to be added. Also we can think about restructuring the categories, but for now at least nothing really conflicts, so no urgent change required IMO.

**Commit list/description**:
+ DietPi-Software | Part 2: Merge "Optimised" and "Additional" software menus

### CODE REVIEW

**Comment by MichaIng** [comment]
I'm not yet sure how to show it best in the menu. We have the "Select Software" separator, so "Software selection" somehow seems doubled. "Search" and "List", "Select from List", or "Search Software" and "Select Software" and adjusting the separator a bit? Of course the right-sided text can also contain info about it, but IMO the word(s) at the left side should be as clear as possible.
```
'' '●─ Select Software '
'Search' ': Find a software title for installation'
'Software selection' ': Select software for installation'
```

**Comment by MichaIng** [comment]
Went with:
```
'Browse' ': Select software to install from the full list'
```
Feedback and suggestions are still welcome, but I'll merge this now to go on with "part 3".

**Comment by Joulinar** [comment]
what about

```
Search Software
Browse Software
```

**Comment by MichaIng** [comment]
I like that, adding it to the Go PR.

**Pull request merged**
