### PR TITLE
DietPi-Software | Kodi: Install our RPi 32-bit Kodi package on all 32-bit RPi images

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: WIP

**Commit list/description**:
+ DietPi-Software | Install our RPi 32-bit Kodi package on all 32-bit RPi images, not only on Raspbian.

### CODE REVIEW

**Comment by Joulinar** [comment]
@MichaIng 
I get following issue on ARMv7 32bit RPi3B+

```
root@DietPi3:~# startkodi
/usr/local/lib/kodi/kodi-gbm: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory
root@DietPi3:~#
```

**Comment by MichaIng** [comment]
New Kodi packages are ready, which should solve the `libmmal_core.so` errors and related ones due to the RPi VC library path changes.

While the build was running, there was another FFmpeg update to the RPi repository:
```
ffmpeg (7:4.3.2-0+rpt1+deb11u2) bullseye; urgency=medium

  * MMAL patch 9
  [ Dave Stevenson ]
  * avcodec/omx: Fix handling of fragmented buffers
```
Coincidentally it contains a MMAL patch as well, but shouldn't be related.

**Comment by Joulinar** [comment]
@MichaIng 
issue seems to be same still. Kodi expect `libmmal_core.so`, while `libmmal_core.so.0` is installed.

```
root@DietPi3:~# startkodi
/usr/local/lib/kodi/kodi-gbm: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory
```
```
root@DietPi3:~# dpkg -l kodi
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version        Architecture Description
+++-==============-==============-============-==============================================
ii  kodi           3:19.1-dietpi2 armhf        Open Source Home Theatre (executable binaries)
```
```
root@DietPi3:~# dpkg -L libraspberrypi0
/.
/lib
/lib/udev
/lib/udev/rules.d
/lib/udev/rules.d/10-local-rpi.rules
/usr
/usr/lib
/usr/lib/arm-linux-gnueabihf
/usr/lib/arm-linux-gnueabihf/libbcm_host.so.0
/usr/lib/arm-linux-gnueabihf/libcontainers.so.0
/usr/lib/arm-linux-gnueabihf/libdebug_sym.so.0
/usr/lib/arm-linux-gnueabihf/libdtovl.so.0
/usr/lib/arm-linux-gnueabihf/libmmal.so.0
/usr/lib/arm-linux-gnueabihf/libmmal_components.so.0
/usr/lib/arm-linux-gnueabihf/libmmal_core.so.0
/usr/lib/arm-linux-gnueabihf/libmmal_util.so.0
/usr/lib/arm-linux-gnueabihf/libmmal_vc_client.so.0
/usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0
/usr/lib/arm-linux-gnueabihf/libvcos.so.0
/usr/lib/arm-linux-gnueabihf/libvcsm.so.0
/usr/share
/usr/share/doc
/usr/share/doc/libraspberrypi0
/usr/share/doc/libraspberrypi0/README.md
/usr/share/doc/libraspberrypi0/changelog.Debian.gz
/etc/ld.so.conf.d/00-vmcs.conf
root@DietPi3:~#
```

As workaround, I linked the libraries manually and Kodi could start. Not sure on the error messages on the bottom

```
root@DietPi3:/usr/lib/arm-linux-gnueabihf# ln -s libmmal_core.so.0 libmmal_core.so
root@DietPi3:/usr/lib/arm-linux-gnueabihf# ln -s libmmal_util.so.0 libmmal_util.so
root@DietPi3:/usr/lib/arm-linux-gnueabihf# ln -s libmmal_vc_client.so.0 libmmal_vc_client.so
root@DietPi3:/usr/lib/arm-linux-gnueabihf# ln -s libbcm_host.so.0 libbcm_host.so
root@DietPi3:/usr/lib/arm-linux-gnueabihf# ln -s libvcsm.so.0 libvcsm.so
root@DietPi3:/usr/lib/arm-linux-gnueabihf# ln -s libvchiq_arm.so.0 libvchiq_arm.so
root@DietPi3:/usr/lib/arm-linux-gnueabihf# ln -s libvcos.so.0 libvcos.so
root@DietPi3:/usr/lib/arm-linux-gnueabihf# startkodi
libva info: VA-API version 1.10.0
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
root@DietPi3:/usr/lib/arm-linux-gnueabihf#
```

**Comment by MichaIng** [comment]
I recognised it as well... I don't even know where these paths are actually coming from, which library or headers set them during compilation. The `libraspberrypi-dev` wasn't even installed when I compiled the first package, now it was (the new version). Probably it was simply forgotten.

I'll add a `postinst` script to the package to have these symlinks created on package install, when missing, install and removed on removal.

> libva info: VA-API version 1.10.0

Strange about the v1 library, as this was last shipped with Stretch while since Buster only v2 is available. And also the development package I used ships v2 only:
```
ii  libva-dev:armhf                2.10.0-1                             armhf        Video Acceleration (VA) API for Linux -- development files
ii  libva-drm2:armhf               2.10.0-1                             armhf        Video Acceleration (VA) API for Linux -- DRM runtime
ii  libva-glx2:armhf               2.10.0-1                             armhf        Video Acceleration (VA) API for Linux -- GLX runtime
ii  libva-wayland2:armhf           2.10.0-1                             armhf        Video Acceleration (VA) API for Linux -- Wayland runtime
ii  libva-x11-2:armhf              2.10.0-1                             armhf        Video Acceleration (VA) API for Linux -- X11 runtime
ii  libva2:armhf                   2.10.0-1                             armhf        Video Acceleration (VA) API for Linux -- runtime
```
I also checked the RPi repo package list for Bullseye and there is not a single package or reference to a v1 API package.

.... actually, who says that the API version must match the package version: https://bbs.archlinux.org/viewtopic.php?id=258759
> vainfo: VA-API version: 1.10 (libva 2.9.1)

Highly non-intuitive, but okay 😄. Probably `apt install libva-glx2` helps, otherwise there may be still some incompatibility or we need to wait until some more library packages or fixes are shipped to the RPi repo Bullseye suite..

> sh: 1: nmblookup: not found

It tries to detect Samba shares. I compiled it with Samba support, of course, matching the RPi and the Debian build, and both only depend on `libsmbclient`, like ours, while that command is shipped with `samba-common-bin`. I wonder where this is called, as it is not done in any of the two startup scripts `kodi` and `kodi-standalone`, so the binary itself must spawn a shell and do that 🤔. However, not an issue and solved when someone actually installs the Samba/CIFS client.

**Comment by MichaIng** [comment]
Done.

**Comment by MichaIng** [comment]
Merging this now and will run more tests tomorrow.

**Pull request merged**
