### PR TITLE
Beta v6.22.2

### PR DESCRIPTION
**Pull request by Fourdee**
### Beta v6.22.2
_(22/03/19)_

As always, many smaller code performance and stability improvements, visual and spelling fixes have been done, too much to list all of them here. Check out all code changes of this release on GitHub: https://github.com/MichaIng/DietPi/pulls?q=is%3Aclosed+base%3Amaster

#### Changes / Improvements / Optimisations (since v6.22.1)
- DietPi-Banner | You can now customise which options to display during system login. These include CPU temps, WAN IP, free disk space and more! Simply run 'dietpi-banner': https://github.com/MichaIng/DietPi/issues/2627

#### Known/Outstanding Issues
- DietPi-Config | Enabling WiFi + Ethernet adapters, both on different subnets, breaks WiFi connection in some cases: https://github.com/MichaIng/DietPi/issues/2103
- DietPi-Config | RPi: Enabling OpenGL/VC4 causes sound card selection to be invalid: https://github.com/MichaIng/DietPi/issues/2173
- DietPi-Drive_Manager | encryptfs is currently not supported and will be removed from fstab when executing drive manager: https://github.com/MichaIng/DietPi/issues/2078
- RPi | LXAppearance (on LXDE desktop) hangs on dbus-launch: https://github.com/MichaIng/DietPi/issues/1791
- Odroid C2 | Some WiFi adapters do no work as hotspot: https://github.com/MichaIng/DietPi/issues/1955
- Odroid XU4 | Kodi freezes shortly on video playback: https://github.com/MichaIng/DietPi/issues/2584
- Rock64 | 3.5mm A/V jack is currently not functional: https://github.com/MichaIng/DietPi/issues/2522
- DietPi-Software | Node-RED: Pre-installed modules cannot be updated via web UI: https://github.com/MichaIng/DietPi/issues/2073
- DietPi-Software | Raspimjpeg: With Lighttpd, streaming mjpeg does not work: https://github.com/MichaIng/DietPi/issues/1747

For all additional issues that may appear after release, please see the following link for active tickets: https://github.com/MichaIng/DietPi/issues

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

dietpi-banner changes has passed local testing my end. Any chance we can merge this for v6.22 beta testing and release?

**Comment by MichaIng** [comment]
@Fourdee 
Jep since it's visual only I see no issue in adding this to v6.22 already.

There are two issues that I would like to resolve, but require your help due to lack of devices:
- https://github.com/MichaIng/DietPi/issues/2584
If I got it right, you could verify freezing Kodi on your XU4 as well, regardless of using the default xorg.conf from the Odroid repo package? If we cannot resolve this currently, I think we need to forward to Meveric and add this to known issues for now.
- https://github.com/MichaIng/DietPi/issues/2522
On Rock64 it looks like we need to enable overlays now for certain features like I2C, I2s, general 3.5mm jack output and such. Found the related steps from the armbian-config script (which we remove during DietPi-PREP), but needs testing if indeed the overlay files are at desired location, as on raw image (inspect via 7zip on Windows) this is not the case.

**Comment by MichaIng** [comment]
@Fourdee 
Sorry for coding so much around your banner commit 😅. I was not happy with the inconstancy between aENABLED/DESCRIPTION and aOBTAIN arrays and first wanted to add all options to the aOBTAIN array with identical indices. Sadly `$($var)` does not support any kind of redirection or piping and even has issues with single quotes that I was not able to resolve. I guess this was also the reason why you left the affected obtain commands outside the array. As I still didn't like the non-matching array indices, I now removed aOBTAIN completely, which simplifies the script a bid.

Only reliable solution I found with array usage is to write the commands to a file and source/execute it back. But that's way too complicated IMO.

**Comment by Fourdee** [comment]
@MichaIng 

> Sorry for coding so much around your banner commit

No worries, all good 👍 

> There are two issues that I would like to resolve, but require your help due to lack of devices:

The XU4, yep, we need to get in touch with Meveric. Will do that when I can.

Same for the Rock64, will run local tests and find the solution.

Regardless, the above can wait for v6.23. No need to hold up v6.22 for them?

**Comment by Fourdee** [comment]
@MichaIng 

> Only reliable solution I found with array usage is to write the commands to a file and source/execute it back. But that's way too complicated IMO.

Yep, the plan with aOBTAIN was to allow us to re-obtain on the fly without needing to have multiple copies of the command in the script. 
But yeah, obtain network was the only real one that we needed that for I believe.

**Comment by Fourdee** [comment]
@MichaIng 

>  - Custom banner entry | Hello World!

Very nice 👍 💘

**Comment by MichaIng** [comment]
@Fourdee 
> Yep, the plan with aOBTAIN was to allow us to re-obtain on the fly without needing to have multiple copies of the command in the script.

Currently there is only the main banner where we call these commands. When something in the future is  obtained on different parts of the script, I would create a function instead. This would have been the other possibility btw:
```
Obtain_1(){ command 1; }
Obtain_2(){ command 2; }
...
```
And then call via `$(Obtain_$i)`.
___________
About `domainname` command:
```
Program name:
       {yp,nis,}domainname=hostname -y
       dnsdomainname=hostname -d
...
    -y, --yp, --nis        NIS/YP domain name
```
- https://en.wikipedia.org/wiki/Network_Information_Service
- Without explicitly setting this (non-permanently via `-F`) I always have output `(none)` on all machines. I guess most users not use NIS, also since LDAP is more common for such purpose nowadays?

I changed the banner to now show the `FQDN/hostname` and `NIS domainname`, to make the difference clearer. If NIS/YP is not used, then FQDN will show everything relevant for most users. The short hostname is not too useful and already part of the console prompt string (PS1).

**Review by MichaIng — APPROVED** [review]
Looks and works great for me. Will merge into Beta

**Pull request merged**
