### PR TITLE
DietPi-Process_tool | Fix loop + other coding improvements

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Reference**: https://github.com/Fourdee/DietPi/issues/2110#issuecomment-427679598

**Commit list/description**:
+ DietPi-Process_tool | Fix while loop input being one line due to missing double quotes
+ DietPi-Process_tool | Several coding improvements
  - direct exit code check, where applicable
  - use G_EXIT_CUSTOM
  - avoid awk/sed, if direct string manipulation var=${varXXX} is possible

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

Nice 👍 

Looking good, thanking you, will merge.

**Comment by Fourdee** [comment]
@MichaIng 

```
root@DietPi:~# dietpi-process_tool 1

 DietPi-Process_tool
─────────────────────────────────────────────────────
 Mode: Apply

[  OK  ] DietPi-Process_tool | OpenSSH Server (591) : Nice      0
[  OK  ] DietPi-Process_tool | OpenSSH Server (591) : Affinity  0-5
/DietPi/dietpi/dietpi-process_tool: line 140: ((: 0 <  ||
                                                                0 > 0 : syntax error: operand expected (error token is "||
                                                                0 > 0 ")
[  OK  ] DietPi-Process_tool | OpenSSH Server (591) : Scheduler SCHED_OTHER 0
[  OK  ] DietPi-Process_tool | OpenSSH Server (6444) : Nice      0
[  OK  ] DietPi-Process_tool | OpenSSH Server (6444) : Affinity  0-5
/DietPi/dietpi/dietpi-process_tool: line 140: ((: 0 <  ||
                                                                0 > 0 : syntax error: operand expected (error token is "||
                                                                0 > 0 ")
[  OK  ] DietPi-Process_tool | OpenSSH Server (6444) : Scheduler SCHED_OTHER 0
[  OK  ] DietPi-Process_tool | OpenSSH Server (6848) : Nice      0
[  OK  ] DietPi-Process_tool | OpenSSH Server (6848) : Affinity  0-5
/DietPi/dietpi/dietpi-process_tool: line 140: ((: 0 <  ||
                                                                0 > 0 : syntax error: operand expected (error token is "||
                                                                0 > 0 ")
[  OK  ] DietPi-Process_tool | OpenSSH Server (6848) : Scheduler SCHED_OTHER 0
[  OK  ] DietPi-Process_tool | Completed
```

**Comment by MichaIng** [comment]
@Fourdee 
Jep just fixed: https://github.com/Fourdee/DietPi/commit/8bfe98de8092d6b0372b32aafb766491b27cf161
Whoopsie 🤣.

**Comment by Fourdee** [comment]
@MichaIng 

Beat me too it, just found it here lol. Thanks 👍

**Pull request merged**
