### PR TITLE
Edit Up and Down scripts from dietpi-nordvpn

### PR DESCRIPTION
**Pull request by svh1985**
Hi all,

This pull request started out because I messed up the config as seen in this issue: https://github.com/MichaIng/DietPi/issues/3045
So, I thought an integration within the dietpi-nordvpn utility would be nice.

ps this is my first pull request for DietPi, so please be nice :)

**Status**: WIP
- [x] Automatically checks if exist and creates up.sh and down.sh scripts in /var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/ folder
- [x] Sets right permissions and ownership
- [x] Menu items added
- [x] Fix list script to only include *.ovpn files
- [x] On connect the up, down and script-security settings will be written to the .ovpn file
- [x] Need to fix the exit procedure, the blue screen of the tool remains on screen when the prompt is back

**Commit list/description**:
Add way to edit up and down scripts that OpenVPN can use

### CODE REVIEW

**Comment by MichaIng** [comment]
@svh1985 
Many thanks for this! Great idea to add up/down scripts.
- I committed some change about this to have those + config entries optional, so if not required, the bash shell init overhead is skipped.
- Also when using `G_CONFIG_INJECT`, as long as the setting does not yet exist in the file, it is added to the end, so below cert and key strings. I though it's nicer to have it in the upper section. Giving it a fourth argument allows to add it below the line that matches this pattern. `auth SHA512` exist in all NordVPN client configs, thus this can be used safely.

Added some minor coding as well, that is not related to your additions or the aim of this PR, just as I fell above when viewing the code.

Will test now. What you mean by the fix you need to do? You mean after exiting "nano", something is messy on the screen? I think this cannot be influenced easily. Whether those "alternate" sessions (prompt outside of originating shell, allowing to separately scroll etc, like nano is) are cleared properly or not, is responsibility of the terminal, AFAIK. E.g. when using "screen" for SSH sessions, the nano content will remain in the bash scrollback after closing. One needs to set a special setting to avoid this.
**EDIT: No blue screen issue in my tests.**

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Can be merged IMO, aside from the blue screen issue you face?

**Comment by svh1985** [comment]
Nice improvements, much cleaner like that.
The blue screen also seems to be solved!

I'm just wrapping up with some small text improvements. 
Do you think it is good to include examples in the up and down files? 

For example NZBGet and qBittorrent:
```
# Resume NZBGet
curl --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "resumedownload" }' -H "Content-Type: application/json" -X POST http://127.0.0.1:6789/admin:PASSHERE/jsonrpc/

# Resume qBittorrent
curl -i --cookie-jar cookiefile --header 'Referer: http://127.0.0.1:1340/' --data 'username=qbittorrent&password=PASSHERE' http://127.0.0.1:1340/login
curl --cookie cookiefile http://127.0.0.1:1340/command/resumeAll
```

**Comment by svh1985** [comment]
Found one thing while testing:
The G_CONFIG_INJECT for auth-user-pass adds a second auth-user-pass all the way at the bottom of the document. Seems like the change to 'auth-user-pass[[:blank:]]' stopped it from working.

Maybe we should adjust it to (I verified it to work):
`G_CONFIG_INJECT 'auth-user-pass' "auth-user-pass $FP_SETTINGS_OVPN" $fp_ovpn`

**Comment by MichaIng** [comment]
@svh1985 
> Do you think it is good to include examples in the up and down files?

Look actually like useful commands indeed. But perhaps it makes more sense to keep that out of the code and instead add such info either to the Wiki or forum?
We could link it in the default up/down scripts then and the Wiki page/forum thread can be extended by times with such start/stop API commands for all downloaders and other probably nice things. Also it is easier for other users then to extend/contribute to this and we can link it from the software online docs (in the forum) as well.

> The G_CONFIG_INJECT for auth-user-pass adds a second auth-user-pass all the way at the bottom of the document.

Ah I know the issue, good find! In initial configs this setting has no value yet, thus the blank is not there. I added it to the pattern as a general failsafe coding style to assure that no other settings that start with the same string, e.g. `auth-user-pass-alt` or something, is matched and broken. In this case such does not exist, so your solution (revert) is safe to use. Otherwise `'auth-user-pass([[:blank:]]|$)'` should work as well, which matches either blank or end of line.
**EDIT: Added it like this for now.**
**EDIT2: Retested, working well now on fresh config file and existing as well.**

**Comment by svh1985** [comment]
Now that we touch dietpi-nordvpn, do you think it is possible to add an up-time or at least an connected time? We can then show it in the status screen.

**Comment by svh1985** [comment]
In my local branch I tried to write a log to see if the up and down scripts get executed. But for some reason nothing happens.

```
#new vars for log
FP_SETTINGS_UP_LOG='/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/up.log'
FP_SETTINGS_DOWN_LOG='/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/down.log'

--
#changes to up and down
[[ -f $FP_SETTINGS_UP ]] && G_CONFIG_INJECT 'up[[:blank:]]' "up $FP_SETTINGS_UP >> $FP_SETTINGS_UP_LOG" $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*up[[:blank:]]/d' $fp_ovpn
[[ -f $FP_SETTINGS_DOWN ]] && G_CONFIG_INJECT 'down[[:blank:]]' "down $FP_SETTINGS_DOWN >> $FP_SETTINGS_DOWN_LOG" $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*down[[:blank:]]/d' $fp_ovpn
```
@MichaIng do you have any idea?

For the uptime we could do something like described here:
https://unix.stackexchange.com/questions/169702/how-to-return-uptime-of-successful-openvpn-connection

**Comment by MichaIng** [comment]
@svh1985 
> In my local branch I tried to write a log to see if the up and down scripts get executed. But for some reason nothing happens.

Hmm, we grant root execute permissions, scripts are there, no idea currently. And I already tested it after doing the last change, AFAIK 🤔. Will retest later.

> Now that we touch dietpi-nordvpn, do you think it is possible to add an up-time or at least an connected time? We can then show it in the status screen.

Hmm, yeah would require an additional timestamp file indeed, created on up. This means that this script must exist all the time and user must not remove this line to keep uptime available. Or we somehow move the code out before allowing edit and back in afterwards. Or is it possible to add the `up` directive two times, so two dedicated scripts?
Another possibility would be to add it as `ExecStartPost` command to the systemd unit, so it is more dedicated from the up.sh script. Should only be some milliseconds difference.

We cannot rely on log files, since rsyslog is not installed by default. We could as alternative to the timestamp file use `journalctl`, but it has an internal retention time as well, so after some days, the VPN startup entry could be lost. That is true for all regular log files as well, as usually logrotate is used then.

**Comment by MichaIng** [comment]
Below two other ideas/requests for NordVPN. Probably too much to add now, but just to mention/collect them somewhere:

Add a killswitch: https://dietpi.com/phpbb/viewtopic.php?p=17823#p17823
So all traffic outside of the tun0 interface is denied. I derived it from the example on WireGuard man page: https://manpages.debian.org/unstable/wireguard-tools/wg-quick.8.en.html#EXAMPLES

The problem with this is, that is is a very simple one:
- It even blocks access to and from LAN. This makes sense for mobile devices where you use a VPN as well to hide your traffic on non-secure public networks. But for a static home device it will even break SSH.
- I first thought the "--dst-type LOCAL" would allow LAN access, but it only allows loopback access, more precisely 127.0.0.0/8 and AFAIK all addresses that are resolved to the device itself.
- Allowing LAN access requires more complicated rules, at best allowing all IPs within the range that is reserved for LANs. Regex would be: `^1(27|92.168|0|72.(1[6-9]|2[0-9]|3[0-1]))\.`, for IPv6: `^f(e[89ab].|[cd]..):`
  - This allows cross access between multiple VPNs and networks then, only from and to any IP that can be ever resolved to a WAN host would be blocked.
  - Should be optional as well, in case one does not trust or does not require LAN access.
- Another point is that it does not even allow to (re-)establish the VPN connection. So one can only enable this rule once the VPN is up. If the VPN breaks, one needs to manually e.g. disable the systemd or ifdown the tun0 interface to have the rule removed, before access to the VPN server (outside the tun0 interface) works.
  - Nice would be if once could enable this rule right after any network interface is up (or even before), so before the VPN is up, the only allowed access would be to the VPN server itself to establish the connection. However we would need to derive the IP of the chosen server then to exclude it from block.

And last but not least there was a request to allow remote access (outside of the VPN) to e.g. the webserver and such. So if one calls the devices external IP, once can access, and the connection is correctly established and answered, but any outgoing requests (that does not match an assigned LAN IP range) is forced through the VPN.
Such is no easily possible otherwise, since even if the packet reaches the device through lets say `eth0`, the route settings of OpenVPN lead to it being answered through `tun0`, so it never reaches the recipient. I created a bypass routing table to be used:
```
G_CONFIG_INJECT '42[[:blank:]]' '42 bypass_vpn' /etc/iproute2/rt_tables
ip r add default dev eth0 via 192.168.178.1 table 42
iptables -t mangle -A PREROUTING -i eth0 [-m conntrack --ctstate NEW] -j CONNMARK --set-mark 42
iptables -t mangle -A OUTPUT -m connmark --mark 42 -j MARK --set-mark 42
ip rule add fwmark 42 table 42
```
- This marks all incoming [new] connections from eth0 with "42" (just a number, can be chosen freely).
- Any outgoing packet, which belongs to this connection (thus has this connection mark) then gets a mark as well (again can be freely chosen, I used just the same 42).
- And the ip rule then applies a routing table for those 42-marked packets, which overrides the default gateway to the eth0 interface and router IP, so it is send out regularly. The routing table has again the IP 42, which again is freely chose-able. I just wanted to have all marks/IDs the same, so one knows they belong together 😉.
- It is a bid complicated since AFAIK ip rule cannot check the previously set connmark of an outgoing packet directly. So this separate iptables rule is required to check the connmark of each outgoing packet and apply the packet mark again.... On the other hand, doing some search it seems we should be able to skip this: https://mithrandi.net/blog/2011/10/nat-connection-pinning-with-iproute2-iptables/
  - Not sure why guides around the web would make things more complicated as required, however can be easily tested.
- Not sure about the `-m conntrack --ctstate NEW` as well. It checks if the connection is new. So for existing connections the mark is not set again, reducing overhead. On the other hand the check itself is an overhead as well. Not sure whether to check or not... both should work regardless.

**Comment by MichaIng** [comment]
🈯️ Just tested up/down scripts, worked in my case:
```
Aug 13 20:24:37 VM-Stretch openvpn[1833]: Tue Aug 13 20:24:37 2019 /var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/up.sh tun0 1500 1585 10.8.2.5 255.255.255.0 init
Aug 13 20:24:37 VM-Stretch openvpn[1833]: up.sh succeed
systemctl stop dietpi-nordvpn.service
Aug 13 20:26:48 VM-Stretch openvpn[1833]: Tue Aug 13 20:26:48 2019 /var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/down.sh tun0 1500 1585 10.8.2.5 255.255.255.0 init
Aug 13 20:26:48 VM-Stretch openvpn[1833]: down.sh succeed
```
- The scripts only contained `echo up.sh/down.sh succeed` 😉. Checked via `journalctl | tail` after service start/stop.
_________
@svh1985
```
G_CONFIG_INJECT 'up[[:blank:]]' "up $FP_SETTINGS_UP >> $FP_SETTINGS_UP_LOG" $fp_ovpn 'auth[[:blank:]]'
```
I believe you cannot use redirects within the .ovpn file syntax. This is not a shell script, and AFAIK the up/down directives only allow a file path. If you want to create a log file, do the redirection within the up.sh/down.sh itself.
- https://manpages.debian.org/buster/openvpn/openvpn.8.en.html Okay it can be a path to any executable or command, even with arguments, however `>>` is not an argument but a STDOUT redirection which is shell syntax. This is most likely not interpreted by OpenVPN but added as another argument to the command, where it is not used. You could add `echo $@` to your up.sh+down.sh and I believe after starting/stopping the VPN, `journalctl | tail` will show `openvpn[XXXX]: >> /var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/up.log` 🙂.

**Comment by MichaIng** [comment]
@svh1985 
Okay lets go with this state for now and add other changes with a separate PR, to not loose overview. I am very happy with this up/down script implementation, which users can use for simple killswitches, to allow inbound access and all those things that I mentioned above as ideas/requests, even uptime, according to the above code snippets already.

You agree?

**Comment by svh1985** [comment]
I agree, let's do it like this. Great improvement!

The killswitch would also be a nice addition, I tried but got locked out. 🙈

For future reference:
Option to use the route-up to write the time:
route-up "echo $(date) > ovpnTime.txt"

Also interesting read for where down script does not run on timeout. _Which I could not test._
https://forums.openvpn.net/viewtopic.php?t=19342

**Comment by MichaIng** [comment]
@svh1985 
Jep as said, this killswitch blocks everything outside the VPN, thus SSH as well, as long as you do not connect through the VPN. Too "simple" to implement.

It is good that the down script does not run on timeout. Otherwise a killswitch on that basis were meaningless, since the idea is that in case of connection loss, traffic is blocked until reconnect. However this requires to allow regular connection to the VPN provider and at best it should allow all LAN connections outside the VPN, optionally. All requires more complicated iptables rules. I wished there was a `--dst-type` that matches all LAN connections, but this seems to not exist...

Okay will merge.
Changelog: https://github.com/MichaIng/DietPi/commit/2209d6665c49cc43de9eb977e39667bb2d4ff6a0

**Pull request merged**
