### PR TITLE
DietPi-DDNS | Update FreeDNS API URL

### PR DESCRIPTION
**Pull request by ma651851384**
Recently, I tried to set up DynDNS via the substantiated provider "FreeDNS". After acceptance of the setting using the token, the error 404 was displayed. When I used the custom URL, it worked. That URL was provided, if the user was logged in into the freedns user portal.

I believe that in the meantime the URL has changed from "https://sync.afraid.org/u/<token>" to "http://freedns.afraid.org/dynamic/update.php?<token>".

The effected line would have to be changed from

`url="https://sync.afraid.org/u/$PASSWORD/"`
to
`url="https://freedns.afraid.org/dynamic/update.php?$PASSWORD"`

### CODE REVIEW

**Comment by MichaIng** [comment]
Strange, here it still shows the URL we use: https://freedns.afraid.org/

There is a link to "v2 interface", but it is hidden behind login. Is it probably that one which matches your new URL? Because the old one is still shown on this public place, I wonder whether it depends on some registration plan or option?

**Comment by ma651851384** [comment]
Hello @MichaIng 
I've registered myself for testing purpose today and set up a subdomain. After that, I could retrieve the direct URL. It corresponds to the scheme as I have reported on this issue:

`https://freedns.afraid.org/dynamic/update.php?<token>`

Find attached some relevant screenshot from the provider user account.

Your mentioned "v2 interface" seems to be only a web interface update.

If there are still questions, I can view the necessary data by my test access by 07.06.2023 at the latest.

**Review by MichaIng — APPROVED** [review]

**Comment by ma651851384** [comment]
Thank you. Also from my point of view, it would be good if other users would test my reported URL structure.

I wrote an email to the FreeDNS support a few minutes ago, and I'll get back to you when I got the answer.

**Comment by ma651851384** [comment]
Hi.
I tested the new implementation (inserting only the token in the input field) with dietpi V8.18.2. It works fine, many thanks!

In one of the previouse posts I told that I contacted the FreeDNS support. Unfortunately, no one ever answered.

This topic is closed/solved from my side.

**Comment by MichaIng** [comment]
Many thanks for testing and feedback 🙂.

**Pull request merged**
