### PR TITLE
Home Assistant Python version Update

### PR DESCRIPTION
**Pull request by sytone**
Using PYENV as the installation approach so existing python installations are not impacted and all changes and further updates are isolated.
To update users can uninstall and reinstall HA, configuration files are not touched.

### CODE REVIEW

**Comment by sytone** [comment]
Added fix for #1145 so it swtches to the stretch package. 

@hiscorebob can you validate this new change?

**Comment by hiscorebob** [comment]
I'm not sure how to validate this, but I tested with v157, and it's still  trying to install libmysqlclient-dev package

**Comment by sytone** [comment]
@hiscorebob You would need to take this pull and update your files locally and then run the install.

**Comment by Fourdee** [comment]
@sytone 

Thanks for this 👍 

I'll merge in for testing

**Pull request merged**
