### PR TITLE
DietPi-Banner | Add country + city to WAN IP info

### PR DESCRIPTION
**Pull request by sal666**
Nice to know the exit country when VPNing

### CODE REVIEW

**Comment by MichaIng** [comment]
@sal666 
Many thanks for this and good idea.

However now there are two separate curl calls, each with 2 seconds time allowed. To not have the banner hanging too much, I would prefer to implement #2832 first or add country estimation to our own myip.php script. I'll check how this can be done.
_________
Reading: https://stackoverflow.com/questions/3650006/get-country-of-ip-address-with-php
So either use a 3rd party service, which then includes as well a second connection to receive the country, or run an own service on the server to invoke. I can experiment with this a bid to see how heavy-weight it is.

**Comment by sal666** [comment]
To avoid more than one curl call another option would be to 'curl ifconfig.co/json' and then parse the output

**Comment by MichaIng** [comment]
@sal666 
We could even run an own instance of this on our own server 🤔: https://github.com/mpolden/echoip
Then create an additional page that creates the content for the banner as we need it?

On the other hand, scraping the json is simple. And the website is fast:
```
2020-03-07 22:13:21 root@micha:/tmp# time curl -s https://dietpi.com/myip.php
####
real    0m0.330s
2020-03-07 22:13:26 root@micha:/tmp# time curl -s https://ifconfig.co/json
{"ip":"####","ip_decimal":####,"country":"Germany","country_eu":true,"country_iso":"DE","hostname":"####.dynamic-pppoe.dt.ipv4.wtnet.de","latitude":51.2993,"longitude":9.491,"asn":"AS15943","asn_org":"wilhelm.tel GmbH","user_agent":{"product":"Mozilla","version":"5.0","comment":"(Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.17 Safari/537.36 OPR/68.0.3616.0 (Edition developer)","raw_value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.17 Safari/537.36 OPR/68.0.3616.0 (Edition developer)"}}
real    0m0.263s
```
I ran several tests, these example times match the average.
____________________
Okay I think I'll implement #2832 anyway first and then speed doesn't matter anyway. Basically I would like to provide such services from dietpi.com, where possible, but as initial short-term implementation https://ifconfig.co/json should be fine.

**Comment by MichaIng** [comment]
@sal666 
```
2020-03-17 11:55:05 root@micha:/tmp# time curl -sSfLm 2 https://ifconfig.co/json 2>&1 | mawk -F\" '{print $4" "$20","$10}'
149.233.157.168 Hamburg,Germany

real    0m0.277s
user    0m0.166s
sys     0m0.037s
```
Second line, what you think?

**Comment by sal666** [comment]
LGTM 👍

**Review by MichaIng — DISMISSED** [review]

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
