### PR TITLE
V116 IP_ADDRESS parse fix

### PR DESCRIPTION
**Pull request by rhkean**
corrected a parsing error when getting ipaddress for ifconfig on non-english systems.

### CODE REVIEW

**Comment by rhkean** [comment]
fixes #287

**Comment by Fourdee** [comment]
@rhkean 

Nice one Rob. :+1: 

EDIT: Moved my comment to the correct ticket for this job: https://github.com/Fourdee/DietPi/issues/287#issuecomment-211053980

**Comment by rhkean** [comment]
we can do that, too... I still recommend the 'cut' instead of the 'sed'

also, the forcing of en_GB will work, right up until someone runs 'locale-gen --purge' with en_GB not checked.

**Comment by Fourdee** [comment]
I've replied on the ticket: https://github.com/Fourdee/DietPi/issues/287#issuecomment-211055441

**Pull request merged**
