### PR TITLE
DietPi-Software | Prowlarr

### PR DESCRIPTION
**Pull request by Joulinar**
- add new software title Prowlarr `ID 151`

already tested on 
- RPi ARMv7 Bullseye
- RPi ARMv8 Bullseye
- VM x86 Bullseye

Challenges
- disabled on ARMv6 as it doesn't seems to be supported
- I'm not 100% sure if `mediainfo` package is needed
- there is no `latest` tag on `https://github.com/Prowlarr/Prowlarr` . Therefore I'm going to grab latest version from `Prowlarr/Prowlarr/tags`
- it seems still in development and has not been released as finial

### CODE REVIEW

**Comment by MichaIng** [comment]
Web UI btw is available on port 9696.

**Comment by Joulinar** [comment]
Yes, should not have any port conflict.

**Comment by MichaIng** [comment]
### Testing
🈯 Buster x86_64
🈯 Bullseye x86_64
🈯 Bookworm x86_64

**Review by MichaIng — APPROVED** [review]

**Comment by jacovdyk** [comment]
Hi Joulinar/MichaIng,

I noticed that one of the challenges just more than a year ago was:
* disabled on ARMv6 as it doesn't seems to be supported

I've been trying to get Prowlarr working on a Raspberry Pi 3 Model B Rev 1.2

And I'm failing miserably.
I've logged a ticket with the devs:
https://github.com/Prowlarr/Prowlarr/issues/1292#issuecomment-1372707484

And you can see the work that I have done trying to resolve the issue:
https://www.reddit.com/r/prowlarr/comments/zvn1k1/segmentation_fault/

I'm trying to confirm if the ARMv6 issue is still relevant?

**Comment by Joulinar** [comment]
Why are you trying to get a ARMv6 version running on a RPI3? You are able to run ARMv7 32bit or ARMv8 64bit without issue

**Comment by MichaIng** [comment]
Raspberry Pi 3 uses an ARMv8 CPU, so this is not related. Generally, if you run into such setup/startup issues, report those to us first, so we can check whether it is an implementation issue before forwarding upstream. Prowlarr developers do not necessarily know how Prowlarr is installed on DietPi, or what DietPi even is, so they cannot help without much more information.

I believe it is this bug in .NET: https://github.com/dotnet/runtime/issues/79796
- Jackett fails the same way on RPi 3 and some (but not all) other ARMv8 SBCs.
- Downgrading .NET to a specific v6 or upgrading it to v7 solves the issue. So this is what Prawlarr would need to do to solve the issue.

**Pull request merged**
