### PR TITLE
Dietpi-Backup | New commandline options

### PR DESCRIPTION
**Pull request by alpha-tango-kilo**
**Status**: Testing/Ready
I don't know and thus haven't been able to create an image to test this in full, however I've tested various snippets by making small dummy scripts and have run everything I've written through [ShellCheck](https://www.shellcheck.net/) so there shouldn't be any syntax errors, the only issues I could forsee would be with the quiet flag, as I haven't been able to fully test this. 

**Reference**: Personal want, but can also be seen [here](https://dietpi.com/phpbb/viewtopic.php?t=4426).

**Commit list/description**:

* *Added conventional commandline options* - the  bulk of my work, removes existing argument handling in favour of a getopts system with `-r`, `-b`, `-q`, and `-h` flags. See commit details for what the flags do.
* *Handled another yes/no dialogue* - this is an skip for when quiet mode is enabled that bypasses the user prompt if the space check fails, automatically cancelling the backup. This part is untested though syntactically correct.

Essentially I tried to make dietpi-backup more familiar and usable and a commandline tool to allow for easier automation. At present, as far as I've tried, you can't headlessly run dietpi-backup without having to confirm a dialogue at the end. The `-q` flag should stop all WHIP prompts, replacing messages with `echo` equivalents (to STDERR if appropriate), or if a choice, it chooses a sensible option.

Disclaimer: I'm not a fluent bash user, and this is my first time contributing to any open source project, so please forgive mistakes. I'm willing to take feedback and criticism and I apologise if I've not followed a specific coding style or failed to use DietPi built-ins, this is my first contribution to this project and so I am not overly familiar with all the built-in tools available.

### CODE REVIEW

**Comment by MichaIng** [comment]
@AtkLordOverAll 
Many thanks for this.

However the functionality you enable already exists, I believe, and if doing this change we would need to add full backwards compatibility to no break existing user scripts.

Currently:
- To run it non-interactively and skip all confirmation dialogs/prompts: `G_USER_INPUTS=0 dietpi-backup (1|-1) [/path/to/backup]`
- This includes G_CHECK_USERDATA and G_WHIP_VIEWFILE etc. In case of failure, required checks lead to an exit (with error message on echo basis), questions are answered with no/cancel (if not another default value variable given) and replaces G_WHIP_MSG content with an echo (G_DIETPI-NOFITY) already, function internally: https://github.com/MichaIng/DietPi/blob/dev/dietpi/func/dietpi-globals#L787-L796
- Within cron jobs and systemd units (all non-interactive shells), `G_USER_INPUTS=0` is set automatically, so is usually cases those whiptail menus should never break/hang scripts that were not manually called by a user from an interactive shell: https://github.com/MichaIng/DietPi/blob/dev/dietpi/func/dietpi-globals#L29-L41

Does the above cover your functional intention with the PR?

What is true is that our script options/input is a bid uncommon, compared to most UNIX binaries. However, I would rather change this for all script at once by times instead of having inconsistencies and different input mechanisms on them. Then inform users via different channels about that larger rework so that everyone is informed to check ones scripts that call DietPi scripts. Otherwise as said full backwards compatibility is required.

What indeed is missing is a help dialog. We added this to some of our scripts already, but not DietPi-Backup so far, although this is probably most used by users from within their scripts. Example for other help/usage info: https://github.com/MichaIng/DietPi/blob/dev/dietpi/misc/dietpi-arr_to_RAM#L18
We added it a way that it simply always shows up whenever a non-valid input has been done.

What as well is a very good point is to add the `G_USER_INPUTS` information to all help/usage prints., as having the possibility to run those non-interactively, even from interactive shells, is quite an important usage info!
___________
So as of above, as long as I did not oversee something, I would close your PR and instead add usage information to the existing input mechanism for now.
But do not misunderstand, I am very thankful for it, which points us to the important topic of making usage of our scripts scripts, especially non-interactively, much more visible to users.

**Comment by alpha-tango-kilo** [comment]
@MichaIng 
Thanks for your long reply. I now have an awful hunch I was using `G_USER_INPUT=0` (notably without an "S") before which may have been causing me to still experience dialogues. Shall have a poke around tomorrow and see what I find.

Shame what I've done has gone for nothing, but it's experience at least. Maybe I'll look into slowly conventionalising (for lack of a better word) the `dietpi-*` suite.

Help dialogues would go a long way for commands that do have commandline options such as `dietpi-backup`, so I may also see about incorporating this into the above idea.

As I've said, shall take a look tomorrow and see what I want to do, may ask for a couple pointers from yourself and then maybe work on some of the bits you've suggested. Shall close the PR in the mean time

**Comment by MichaIng** [comment]
@AtkLordOverAll 
> I now have an awful hunch I was using G_USER_INPUT=0 (notably without an "S") before which may have been causing me to still experience dialogues.

This happened to me as well the one or other time 😄. I was already thinking to switch it to `G_INTERACTIVE` which would be a bid clearer. Perhaps good to do that before adding anything about it to help/usage prints? Although backwards compatibility can be done easily via one single line in `dietpi-globals`.

> Shame what I've done has gone for nothing, but it's experience at least.

As said, definitely not for nothing 🙂! If I'd count how often I rewrote/developed the same code parts after mistake, feedback or learning how to do things better 😄.

> Maybe I'll look into slowly conventionalising (for lack of a better word) the dietpi-* suite.

In many cases I am open for new/better conventions, but in case of command arguments or variables I am a bid careful to not destroy user scripts and as well our own, since we do many cross-calls which would require careful update then. So a larger tasks then it might look at first view.

> As I've said, shall take a look tomorrow and see what I want to do

Okay, if you want to work on this for `dietpi-backup` then I will start on other scripts where usage print is missing as well, e.g. `dietpi-software`. All scripts (or nearly all) have usage comments in the first code lines, so this could simply be turned into a variable to print if argument is invalid + most probably some wording polish and optional aligning with usual UNIX `--help` output format.

**Comment by alpha-tango-kilo** [comment]
@MichaIng 
Okay I'm happy to take on changing `G_USER_INPUTS` to `G_INTERACTIVE`, only 37 matches across the project, so can't be bad. As for backwards compatibility, presumably dropping the `$` would allow me to pass the variable by reference, easily giving the two the same functionality by just doing something like `G_USERINPUTS=G_INTERACTIVE`. Or am I being too Pythonic/optimistic in hoping that would work?

> I am a bid careful to not destroy user scripts and as well our own

I understand your point with that, so I guess that's a "leave it or make it backwards compatible" scenario, which is entirely fair. I shall continue to toy around with `getopts` and such, see how to make long flags - like `--help` - work, and if there's anyway I could try and comply with existing standards.

> I will start on other scripts where usage print is missing as well

Don't worry about fiddling around with usage prints if you don't want, I'm sure you've got plenty more important and exciting things to be doing, but I appreciate the offer. I may look at doing them myself sometime, we'll see.

I'll see if I can get another pull request in some time :)

**Pull request closed without merging**
