### PR TITLE
updated blynk server to latest version

### PR DESCRIPTION
**Pull request by phonicmouse**

### CODE REVIEW

**Comment by Fourdee** [comment]
@phonicmouse 
Legend, thanks for the update 👍

**Comment by phonicmouse** [comment]
Thanks @Fourdee ... only one thing...how do you manage updates? This will auto update every install with the new (dietpi) version update or you have to do it manually? Sorry but actually I don't have the possibility to verify it by myself. ;)

**Comment by Fourdee** [comment]
@phonicmouse 

> how do you manage updates? 

If the software is tested to update successfully with ```dietpi-software reinstall INDEX```, we can pop that into the patch system. 
It can be risky, even after testing. So in most cases, new installations of the software are required (in ```dietpi-software```). to install the newer version.

Basically, to upgrade after the DietPi update. Run ```dietpi-software```, then:
- Uninstall
- Install

**Comment by phonicmouse** [comment]
Thank You @Fourdee 😃

**Pull request merged**
