### PR TITLE
DietPi-System | Add exFAT support

### PR DESCRIPTION
**Pull request by MichaIng**
https://github.com/Fourdee/DietPi/issues/1270
+ a typo in dietpi.txt
+ Support exFAT | **testing needed, just implemented by copying methods for e.g. f2fs**

### CODE REVIEW

**Comment by MichaIng** [comment]
@https://github.com/Fourdee/DietPi/pull/1312/commits/9cbcbeb280696b7bddd5118c45a01edf573ccfa2
Okay, order might have not been the problem, it is the missing /etc/dietpi folder that prevents generation of subfile.
Fixed by creating the folder in case, dunno if there is a more elegant way, at least cat -p (parent) or something does not seem to exist 😅.

**Comment by MichaIng** [comment]
About clearing /var/log from old packages logfiles: Which one need to be present? My cleaned dir on RPi without rsyslog and everything possible moved to journalctl looks like this:
```
/var/log# ls -l
total 816
-rwxrwxr-x 1 root root   3287 Nov 19 04:30 alternatives.log
drwxrwxr-x 2 root root   4096 Dec 12 18:17 apt
-rwxrwxr-x 1 root root     14 Dec 11 14:35 boottime
-rwxrwxr-x 1 root utmp      0 Oct  2 19:50 btmp
-rwxrwxr-x 1 root root 447116 Dec 11 14:42 dietpi-backup.log
-rwxrwxr-x 1 root root   8207 Dec 11 14:35 dietpi-boot.log
-rwxrwxr-x 1 root root 241070 Dec 12 18:18 dpkg.log
-rwxrwxr-x 1 root root    292 Dec 17 20:23 lastlog
-rwxrwxr-x 1 root utmp  78720 Dec 17 20:23 wtmp
```
So remove everything but these, excluding dietpi's own boottime + dietpi-* ?

**Comment by k-plan** [comment]
@MichaIng 

👍 

`apt-get install -y exfat-utils`

At testing, it will not work with all my test devices.

With some `apt-get install -y exfat-utils` install `exfat-fuse` as additional packages.

With some, after install `exfat-utils` it doesn't work, because `exfat-fuse` is missing.

But I can't say for sure on which it was the case. Believe it was on armbian based devices.

Thanks and have some good time with your wife.

**Comment by Fourdee** [comment]
@MichaIng 

I've made alot of changes to PREP/ENV, so, once you've finished PR, let me know and i'll sort out the conflicts.

**Comment by MichaIng** [comment]
@Fourdee 
Okay, cleaned it to only provide the typo + exFAT support for now. File generation issue was fixed by core environment script in the front.

Conflict solver brought totally mess here, thus a bid ugly commit reverts 😆.

**Comment by Fourdee** [comment]
@MichaIng 

Legend 👍 Many thanks.

I've manually added changes from this PR to a commit: https://github.com/Fourdee/DietPi/commit/d87e17b91a5b7d8cbe2586ea2e489d2cf86d3ae0
This is due to all the merge conflicts in relation to major script changes with ```dietpi-global``` etc (was easier this way)

**Comment by Fourdee** [comment]
@MichaIng 

🈯️ Tested format+mount with XU4 Stretch 👍 :
image

**Pull request closed without merging**
