### PR TITLE
DietPi-Globals | G_CONFIG_INJECT: Final fixes

### PR DESCRIPTION
**Pull request by MichaIng**
+ DietPi-Globals | G_CONFIG_INJECT: Use `|` as delimiter to allow file paths without escaping `\`

@Fourdee 
This `sed` is driving me crazy. Was no problem, until used with double matches. This is rare, but some settings files allow multiple time the same setting, adding the values (e.g. /etc/ntp.conf server/pool). Also if you use much wildcards within pattern 😉. Then G_CONFIG_INJECT shall only apply to first match to avoid double entries.

`/c` and `/a` apply to every match and I didn't find a way to only apply them to first match. Theoretically `s/^.*pattern.*$/replacement/` or `s/^.*pattern.*$/&\n addition/` should work instead, but somehow they also apply to every match, even they should not. `s/.../.../1` also does not work as every man page or guide says 😠:
```
root@DietPi:~# cat TEST
test1 = 1
test2 = 2
test3 = 3
test3 = again
test1 = jep
root@DietPi:~# sed -i 's/test3 = .*/test3 = changed/' TEST
root@DietPi:~# cat TEST
test1 = 1
test2 = 2
test3 = changed
test3 = changed
test1 = jep
root@DietPi:~# sed -i 's/test1 = .*/test1 = changed_as_well/1' TEST
root@DietPi:~# cat TEST
test1 = changed_as_well
test2 = 2
test3 = changed
test3 = changed
test1 = changed_as_well
root@DietPi:~# sed -i '0,/test3 =/s/test3 = .*/test3 = changed_at_last/' TEST
root@DietPi:~# cat TEST
test1 = changed_as_well
test2 = 2
test3 = changed_at_last
test3 = changed
test1 = changed_as_well
root@DietPi:~# ^C
root@DietPi:~# sed -i '0,/test3 =/s/test3 = .*/&\ntest4 = mal_sehen/' TEST
root@DietPi:~# cat TEST
test1 = changed_as_well
test2 = 2
test3 = changed_at_last
test4 = mal_sehen
test3 = changed
test1 = changed_as_well
```
- The last ones shows the only ugly solution I could find.
- Problem with `s/` is also that you need to escape the delimiter, which didn't matter after `/c` or `/a`. Thus this PR to allow paths without the need to escape all slashes 😉.

Do you know any cleaner `awk` solutions? The one here is quite ugly for me and I somehow lost trust in `sed` 🤣.

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

```
root@DietPi:~# sed -i "0,/test 3 = .*/s//test 3 = changed/" test
root@DietPi:~# cat test
test 1 = boo
test 2 = ha
test 3 = changed
test 4 = o0o00oo0o0
test 1 = hubba
test 3 = jubba
```

Based on https://stackoverflow.com/questions/18196791/replace-first-occurrence-of-text-using-awk

As for AWK, I don't really understand it enough past awk print etc.

**Comment by MichaIng** [comment]
@Fourdee 
Yeah, the same for me. At least `awk '{print $X}'` is no in my head, took a while until mixing up the order of braces. quotes amd $ stopped 😄.

At least your example/link is a slightly shorter version than I found 👍. Important as well, that the pattern then matches the whole line.

I always like to add `.*$` to it to disallow stopping before line ending. Seems to be not necessary, perhaps always the longest match is used, but just to be on the secure side.

**Comment by MichaIng** [comment]
@Fourdee 
Okay, implemented the shorter solution after testing. As PR already opened, I added some code improvements according to latest findings.
- `-n` is default for  `[[ ]]`, thus `[[ $VAR ]]` = `[[ -n $VAR ]]` like `(( $VAR ))` == `(( $VAR != 0 ))`
- Hmm, `[[ ! $VAR ]]` = `[[ -z $VAR ]]` as well 🈯️ Ah another time, it's just about a single character 😄.
- `for/while <condition>; do` instead of having `do` in lonely line, what you think?

Another point:
- Was wondering why APT, please wait... messages are [  OK  ] instead of [ INFO ] now. Perhaps to clearly separate them from the as well grey APT command output?
- What you think about dropping grey for [ INFO ] completely? If `$PROGRAM_NAME` exist, currently the colour reset anyway leads to info messages being printed in white, thus this would be just consistent then.

**Comment by Fourdee** [comment]
@MichaIng 

> What you think about dropping grey for [ INFO ] completely? If $PROGRAM_NAME exist, currently the colour reset anyway leads to info messages being printed in white, thus this would be just consistent then.

Not keen personally. I like the grey for "info" as its not as dominant on the screen compared to "OK" text. Its only a visual thing, but for inexperienced users, the grey should "nullify" trying to visually process non-important items.
Whilst experienced users who still want to see what DietPi is doing, can still do that.

**EDIT:** If $PROGRAM_NAME exist, currently the colour reset anyway leads to info messages being printed in white,

So it does, need to get that fixed.
image

🈴 Commit reverted, broke G_DIETPI-NOTIFY https://github.com/Fourdee/DietPi/commit/4f731d8b551ff2531e7eea1ec0ba0a82efd2c5ae

> for/while <condition>; do instead of having do in lonely line, what you think?

Personally, i prefer the current layout, fits with the way I used to code C/C++ 
```
for ( init; condition; increment ) 
{ #do
   statement(s);
} # done
```

Although saying that, our ```if``` statements should then be
```
if (( $test ))
then #{

fi #}
```

I'am leaning towards ```then``` on another line ^^ ☹️ 🤣. But yes, we should look at standardizing our code layout, open to suggestions.

**Comment by Fourdee** [comment]
@MichaIng 

I wont get a chance to review/test this PR today, although, if your happy with it please merge as needed.

**Comment by MichaIng** [comment]
@Fourdee
I will do testing of every occurrence of G_CONFIG_INJECT so far today just to assure it works as expected. And then add some comments about how to take care proper escaping of ext regex magic characters, perhaps add an usage output of less than 3 arguments are given. Although we should keep it intended as developer function so far :wink:.

On the long term we could think about if we want to actively promote our global functions for end user usage and then add help/usage output to them?

**Comment by Fourdee** [comment]
@MichaIng 

> On the long term we could think about if we want to actively promote our global functions for end user usage and then add help/usage output to them?

Adds additional maintiance, eg: if we change what one of the global functions does, we then need to update the online doc to reflect that. Users could also break their system if one of the commands has changed how it operates, and, they were not aware of the change etc.

So yes, we need to be careful which Global items we document for users.
Currently, i've added a few stable (should not change basic operation) G_ commands to the bottom of this post:
https://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p5

---

I'll merge and run some tests for owncloud/nextcloud

**Review by Fourdee — COMMENTED** [review]
Looking good 👍 

Merged for testing.

**Comment by MichaIng** [comment]
@Fourdee
Online documentation is maybe indeed too high effort. I thought about a help/usage output, e.g. G_CONFIG_INJECT --help (or just no argument)

But indeed this bears the risk of additional support/issues of those commands are used within scripts e.g. and we change behaviour.

**Comment by Fourdee** [comment]
Install tests:
- 🈴 NextCloud | appears missing permissions /var/www/nextcloud www-data at this stage, will send commit
```
[ INFO ] DietPi-Software | Enable 4-byte support for MariaDB
[  OK  ] DietPi-Software | systemctl restart mysql
Cannot write into "config" directory!
This can usually be fixed by giving the webserver write access to the config directory

See https://docs.nextcloud.com/server/13/go.php?to=admin-dir_permissions
```
image

- 🈯️ Owncloud

Reinstall tests:
- NextCloud
- 🈯️ OwnCloud

@MichaIng 
Nice work, looking great 👍 
Reinstall:
image

**Comment by Fourdee** [comment]
Retests after ncc install fix: https://github.com/Fourdee/DietPi/commit/26f6af72be922be3be8b23adfa0d20a88d628646

- 🈯️ Install Nextcloud
- 🈯️ Reinstall Nextcloud

**Comment by MichaIng** [comment]
@Fourdee 
Found something still not ideal:
```
root@DietPi:~# > TEST
root@DietPi:~# G_CONFIG_INJECT 'set2\\ =' 'set2\\ = 2' TEST
[  OK  ] Add setting set2\ = 2 to end of file TEST
root@DietPi:~# cat TEST
set2\\ = 2
```
- `echo "$setting" > "$file"` does not do resolve backslash escaping.
- But `G_DIETPI-NOTIFY 0 "$setting"` does resolve escaping.
- Made a commit to grep the result from file for message to assure that message and actual added setting match: https://github.com/Fourdee/DietPi/commit/b958eb5ac4797baff2b13f137c3ce007b3631765
```
...
root@DietPi:~# G_CONFIG_INJECT 'set2\\ =' 'set2\\ = 2' TEST
[  OK  ] Add setting set2\ = 2 to end of file TEST
root@DietPi:~# cat TEST
set2\\ = 2
set2\\ = 2
```
- `grep "$pattern"` does backslash resolving, too, thus does not identify the setting, added before.
```
...
root@DietPi:~# G_CONFIG_INJECT "set2\\ =" "set2\\ = 2" TEST
[  OK  ] Add setting set2\ = 2 to end of file TEST
root@DietPi:~# G_CONFIG_INJECT "set2\\ =" "set2\\ = 2" TEST
[  OK  ] Add setting set2\ = 2 to end of file TEST
root@DietPi:~# cat TEST
set2\\ = 2
set2\\ = 2
set2\ = 2
set2\ = 2
```
- Same for adding patterns with double quotes.
- But within double quotes, backslashes need to be escaped an additional time.
```
root@DietPi:~# G_CONFIG_INJECT 'set2\\ =' 'set2\\ = 2' TEST
[  OK  ] TEST already contains the desired setting: set2\ = 2
root@DietPi:~# G_CONFIG_INJECT 'set2\\\ =' 'set2\\\ = 2' TEST
[  OK  ] TEST already contains the desired setting: set2\\ = 2
root@DietPi:~# G_CONFIG_INJECT 'set2\\\\ =' 'set2\\\\ = 2' TEST
[  OK  ] TEST already contains the desired setting: set2\\ = 2
root@DietPi:~# G_CONFIG_INJECT 'set2\\\\\ =' 'set2\\\\\ = 2' TEST
[  OK  ] TEST already contains the desired setting: set2\\\ = 2
root@DietPi:~# G_CONFIG_INJECT 'set2\\\\\\ =' 'set2\\\\\\ = 2' TEST
[  OK  ] Add setting set2\\\ = 2 to end of file TEST
root@DietPi:~# cat TEST
set2\\ = 2
set2\\ = 2
set2\ = 2
set2\ = 2
set2\\\\\\ = 2
root@DietPi:~# grep 'set2\\ = 2' TEST
set2\ = 2
set2\ = 2
root@DietPi:~# grep 'set2\\\ = 2' TEST
set2\ = 2
set2\ = 2
root@DietPi:~# grep 'set2\\\\ = 2' TEST
set2\\ = 2
set2\\ = 2
root@DietPi:~# grep 'set2\\\\\ = 2' TEST
set2\\ = 2
set2\\ = 2
root@DietPi:~# grep 'set2\\\\\\ = 2' TEST
```
- `grep` has flexibility in how many backslashes work. The 3rd and 5th seems to be applied to the following character (white space), if present, thus has no effect in this case.
- Interestingly `G_DIETPI-NOTIFY` doesn't do this. Hmm makes also sense, as `echo -E` only has `\` (besides $ " ') as special character.
```
root@DietPi:~# cat TEST
set2\\ = 1
set2\ = 2
root@DietPi:~# G_CONFIG_INJECT 'set2\\\\ = 1' 'set2\\\\ = 3' TEST
[  OK  ] Edit existing setting set2\\ = 3 in TEST
root@DietPi:~# cat TEST
set2\\ = 3
set2\ = 2
root@DietPi:~# G_CONFIG_INJECT 'set2\\ = 2' 'set2\\ = 4' TEST
[  OK  ] Edit existing setting set2\ = 4 in TEST
root@DietPi:~# cat TEST
set2\\ = 3
set2\ = 4
root@DietPi:~# G_CONFIG_INJECT "set2\\\\\\\\ = 3" "set2\\\\\\\\ = 5" TEST
[  OK  ] Edit existing setting set2\\ = 5 in TEST
root@DietPi:~# cat TEST
set2\\ = 5
set2\ = 4
```
- Okay, so `grep` and `sed` at least handle escaping the same, and similar to `echo` at least if \ $ or quote chars are escaped.
- Double quotes logically double the need of backslashes.
________________
So as the `G_DIETPI-NOTIFY` issue is solved with commit above, the only issue that would be good to resolve is, the different result, when adding settings via `sed` and `echo`. I guess, if there is not way to somehow manually force an additional escape resolving, to use `sed` as well to add the setting to end of file?

**Comment by Fourdee** [comment]
@MichaIng 

> Found something still not ideal:
So as the G_DIETPI-NOTIFY issue is solved with commit above, the only issue that would be good to resolve is, the different result, when adding settings via sed and echo. I guess, if there is not way to somehow manually force an additional escape resolving, to use sed as well to add the setting to end of file?

Ok, no worries, i've moved release date to 8th May. I'll take indepth look at this tomorrow.

**Comment by Fourdee** [comment]
@MichaIng 

Unsure if this helps, but, i'll go through it:

> echo "$setting" > "$file" does not do resolve backslash escaping.
But G_DIETPI-NOTIFY 0 "$setting" does resolve escaping.

Due to ```G_DIETPI-NOTIFY``` using ```echo -e``` 

---

When using ```echo -e``` a double escape will allow print of 1st escape:
```
root@DietPi:~# echo -e "\\ test"
\ test
```

But if we remove the space, an additional back slash is required, to prevent expanding ```\t```
```
root@DietPi:~# echo -e "\\\test"
\test
```

if we simply ```echo``` without strings, everything is printed. So even without ```-e``` in ```echo```, a string ```""``` will expand the input.
```
root@DietPi:~# echo  "\\test"
\test

root@DietPi:~# echo  '\\test'
\\test
```

---

At times like this, I generally go full out basic ```''``` and use of backslashes for the chars that require it, eg:
```
grep -m1 '\[102\]' /DietPi/dietpi/.installed
mkdir -p /root/test\ folder
```

Allows for more control at a raw level (i believe), as long as you are aware of where backslashes are required.

**Comment by Fourdee** [comment]
Example of ```''``` and using ```\```
```
target_rate=44100
target_bitdepth=16
G_CONFIG_INJECT 'format \"' 'format \"'"$target_rate"':'"$target_bitdepth"':2\"' /etc/mpd.conf
```

```
root@DietPi:~# G_CONFIG_INJECT 'format \"' 'format \"'"$target_rate"':'"$target_bitdepth"':1\"' /etc/mpd.conf
[  OK  ] Setting in /etc/mpd.conf adjusted: format "44100:16:1"
root@DietPi:~# cat /etc/mpd.conf
format "44100:16:1"

```

**Comment by MichaIng** [comment]
@Fourdee
Okay I got it now:
- sed and grep have their own ext regex rules. Thus if one want to assure that all strings are read and written the same, echo > file cannot be used.
- Thus also if the message output via input strings should be the same, they need to be pressed through sed or grep.
- echo -e and "" both process just backslash, thus every backslash within the final value needs to be doubled before giving to G_CONFIG_INJECT, if given given within double quotes even quadrapled.

I will commit the final solutions that assure with every input the values are scraped, added to file and output to terminal exactly the same. Also escaping rules within input values are clear then and the same for all arguments.

**Pull request merged**
