### PR TITLE
DietPi-Software | FFmpeg: Fix backports dependency issues for all Odroids

### PR DESCRIPTION
**Pull request by MichaIng**
https://github.com/Fourdee/DietPi/issues/1556#issuecomment-369463910

- This is more a quick dirty fix, that is "just" working. Actually on Odroids there seem to be more overlapping pins within `/etc/apt/preferences.d` and suggest we do some cleanup there at least.
- Best would be, if we could manage installation from Meveric backports, as ffmpeg version is newer and might be a bid optimized for Odroids?
- I have no idea what actually causes this dependency issues when installing from Meverics at the moment, as the dependencies seem to be the same and all necessary available on his repo. Needs investigation if we want to have a real "solution" instead of more workaround.

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

Many thanks 👍 

I'll merge for the fix now. Leave https://github.com/Fourdee/DietPi/issues/1556#issuecomment-369572389 open and i'll take a look when I can.

**Comment by k-plan** [comment]
@MichaIng 

hier der Inhalt der original SD-Karte, auf der das von mir hoch geladene Image des Odroid C1 basiert:

```
root@Odroid-C1-v6:~# ls -lah /etc/apt/preferences.d/
insgesamt 12K
drwxr-xr-x 2 root root    4,0K Jan 18 22:43 .
drwxr-xr-x 6 root root    4,0K Jan 18 21:07 ..
-rw-r--r-- 1  501 dialout   81 Mai 26  2017 meveric-backports-pin-100
```

```
root@Odroid-C1-v6:~# cat /etc/apt/preferences.d/meveric-backports-pin-100
Package: *
Pin: release o=ODROID Debian Repository,c=backports
Pin-Priority: 100

```

**Comment by Fourdee** [comment]
@k-plan 

Same for Odroid C2:
```
root@DietPi:~# cat /etc/apt/preferences.d/meveric-backports-pin-100
Package: *
Pin: release o=ODROID Debian Repository,c=backports
Pin-Priority: 100
```

**Comment by MichaIng** [comment]
@k-plan @Fourdee 
Found this one earlier 🙂: https://github.com/Fourdee/DietPi/issues/1385#issuecomment-357755338

I am a bid confused that our `backports` files has actually any effect:
- Meverics backports are no own repo, but a subfolder of jessie repo: `deb http://fuzon.co.uk/meveric jessie main backports`
- Thus he adjust pin priority to 100 by `c=backports` instead of `Pin: release a=jessie-backports`, otherwise they would have same priority as jessie main repo.
- But obviously `Pin: release a=jessie-backports` does work as well, even is dominant 🤔.
- But to no confuse anybody, we should stay with one preference, with our proved one or:
`sed -i '/Pin-Priority:/c\Pin-Priority: 99' /etc/apt/preferences.d/meveric-backports-pin-100`
`mv /etc/apt/preferences.d/meveric-backports-pin-100 /etc/apt/preferences.d/meveric-backports-pin-99`

**Comment by Fourdee** [comment]
@MichaIng 

Yep, by default, broken deps:
```
root@DietPi:~# apt-get install build-essential make autoconf automake
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: dpkg-dev (>= 1.17.11) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


root@DietPi:~# apt-get install build-essential make autoconf automake dpkg-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dpkg-dev : Depends: libdpkg-perl (= 1.18.24~bpo8) but it is not going to be installed
            Depends: tar (>= 1.28-1) but 1.27.1-2+deb8u1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I think in terms of stability for our users and across all Odroid systems, we can simply remove ```/etc/apt/preferences.d/meveric*``` and set stock debian backports to be used in 1st instance ```/etc/apt/preferences.d/backports```
Yes, we will then lack possibly optimized ```ffmpeg``` etc, however, for now, we need compatibility and standardization across all our images. And, we only really need GPU/KODI/KERNEL packages from Meveric's repo.

**Comment by Fourdee** [comment]
Install test of Kodi and Home assistant (https://github.com/Fourdee/DietPi/commit/1db6af07cc0034f76c19886f4b918ad6480a15e9):
- 🈯️

**Comment by MichaIng** [comment]
@Fourdee 
You changed priority to 100, but as far as I know default backports priority is 100 as well, thus now both backports should have the same now? On the other hand, if it works 🤔.

**Comment by Fourdee** [comment]
@MichaIng 

> On the other hand, if it works

Lol, my thoughts exactly. 

Should be 99, i'll send commit:
🈯️ Done 
```
root@DietPi:~# apt-cache policy
Package files:
 100 /var/lib/dpkg/status
     release a=now
  99 http://fuzon.co.uk/meveric/ jessie/main arm64 Packages
     release o=ODROID Debian Repository,n=jessie,l=ODROID Debian Reposin
     origin fuzon.co.uk
  99 http://fuzon.co.uk/meveric/ jessie/backports arm64 Packages
     release o=ODROID Debian Repository,n=jessie,l=ODROID Debian Reposckports
     origin fuzon.co.uk
  99 http://fuzon.co.uk/meveric/ all/testing arm64 Packages
     release o=ODROID Debian Repository,n=all,l=ODROID Debian Repositong
     origin fuzon.co.uk
  99 http://fuzon.co.uk/meveric/ all/main arm64 Packages
     release o=ODROID Debian Repository,n=all,l=ODROID Debian Reposito
     origin fuzon.co.uk
  99 http://fuzon.co.uk/meveric/ all/c2 arm64 Packages
     release o=ODROID Debian Repository,n=all,l=ODROID Debian Reposito
     origin fuzon.co.uk
 500 http://ftp.debian.org/debian/ jessie-backports/non-free Translati
 500 http://ftp.debian.org/debian/ jessie-backports/main Translation-e
 500 http://ftp.debian.org/debian/ jessie-backports/contrib Translatio
 100 http://ftp.debian.org/debian/ jessie-backports/non-free arm64 Pac
     release o=Debian Backports,a=jessie-backports,n=jessie-backports,ackports,c=non-free
     origin ftp.debian.org
 100 http://ftp.debian.org/debian/ jessie-backports/contrib arm64 Pack
     release o=Debian Backports,a=jessie-backports,n=jessie-backports,ackports,c=contrib
     origin ftp.debian.org
 100 http://ftp.debian.org/debian/ jessie-backports/main arm64 Package
     release o=Debian Backports,a=jessie-backports,n=jessie-backports,ackports,c=main
     origin ftp.debian.org
 500 http://deb.debian.org/debian-security/ jessie/updates/non-free Tren
 500 http://deb.debian.org/debian-security/ jessie/updates/main Transl
 500 http://deb.debian.org/debian-security/ jessie/updates/contrib Tran
 500 http://deb.debian.org/debian-security/ jessie/updates/non-free ares
     release v=8,o=Debian,a=oldstable,n=jessie,l=Debian-Security,c=non
     origin deb.debian.org
 500 http://deb.debian.org/debian-security/ jessie/updates/contrib arms
     release v=8,o=Debian,a=oldstable,n=jessie,l=Debian-Security,c=con
     origin deb.debian.org
 500 http://deb.debian.org/debian-security/ jessie/updates/main arm64
     release v=8,o=Debian,a=oldstable,n=jessie,l=Debian-Security,c=mai
     origin deb.debian.org
 500 http://ftp.debian.org/debian/ jessie-updates/non-free Translation
 500 http://ftp.debian.org/debian/ jessie-updates/main Translation-en
 500 http://ftp.debian.org/debian/ jessie-updates/contrib Translation-
 500 http://ftp.debian.org/debian/ jessie-updates/non-free arm64 Packa
     release o=Debian,a=oldstable-updates,n=jessie-updates,l=Debian,c=
     origin ftp.debian.org
 500 http://ftp.debian.org/debian/ jessie-updates/contrib arm64 Packag
     release o=Debian,a=oldstable-updates,n=jessie-updates,l=Debian,c=
     origin ftp.debian.org
 500 http://ftp.debian.org/debian/ jessie-updates/main arm64 Packages
     release o=Debian,a=oldstable-updates,n=jessie-updates,l=Debian,c=
     origin ftp.debian.org
 500 http://ftp.debian.org/debian/ jessie/non-free Translation-en
 500 http://ftp.debian.org/debian/ jessie/main Translation-en
 500 http://ftp.debian.org/debian/ jessie/contrib Translation-en
 500 http://ftp.debian.org/debian/ jessie/non-free arm64 Packages
     release v=8.10,o=Debian,a=oldstable,n=jessie,l=Debian,c=non-free
     origin ftp.debian.org
 500 http://ftp.debian.org/debian/ jessie/contrib arm64 Packages
     release v=8.10,o=Debian,a=oldstable,n=jessie,l=Debian,c=contrib
     origin ftp.debian.org
 500 http://ftp.debian.org/debian/ jessie/main arm64 Packages
     release v=8.10,o=Debian,a=oldstable,n=jessie,l=Debian,c=main
     origin ftp.debian.org
Pinned packages:

```

**Pull request merged**
