### PR TITLE
Beta v6.22.1

### PR DESCRIPTION
**Pull request by MichaIng**
### Beta v6.22.1
_(16/03/19)_

#### Changes / Improvements / Optimisations (since v6.22)
- System | /etc/bashrc.d/ now allows ".bash" file ending as well. Merged all contained DietPi scripts into one: /etc/bashrc.d/dietpi.bash. https://github.com/MichaIng/DietPi/pull/2636
- General | CPU temps are now displayed in the login banners. If unsupported by current device, free space on RootFS is shown instead. Many thanks to esturniolo for the suggestion: https://twitter.com/esturniolo/status/1104912062298423297
- RPi | DietPi does not set or change "framebuffer_depth" in config.txt anymore which defaults to 16 which works in every known case. It will be re-added as fast as we find a case where another value is required.
- DietPi-Software | rTorrent: Runs now as user "rtorrent" and creates files as group "dietpi" with 775/664 permissions. Enabled Buster support and enhanced config file handling on reinstall: https://github.com/MichaIng/DietPi/pull/2633
- DietPi-Software | Plex Media Server: Now installs the latest version automatically (currently 1.15) which as well includes official ARM binaries. Many thanks to @WolfganP for informing us about this new release: https://github.com/MichaIng/DietPi/issues/2553
- DietPi-Software | Nextcloud: Resolved an admin panel warning about missing ocm/ocs-provider redirects. Many thanks to @minnux for reporting this issue: https://github.com/MichaIng/DietPi/issues/2638

#### Bug Fixes (since v6.22)
- DietPi-Software | rTorrent: Resolved an issue where the ruTorrent web UI could not connect to the rTorrent daemon. Many thanks to @Chester007 for reporting this issue: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5656

As always, many smaller code performance and stability improvements, visual and spelling fixes have been done, too much to list all of them here. Check out all code changes of this release on GitHub: https://github.com/MichaIng/DietPi/pulls?q=is%3Aclosed+base%3Amaster

#### Known/Outstanding Issues
- DietPi-Config | Enabling WiFi + Ethernet adapters, both on different subnets, breaks WiFi connection in some cases: https://github.com/MichaIng/DietPi/issues/2103
- DietPi-Config | RPi: Enabling OpenGL/VC4 causes sound card selection to be invalid: https://github.com/MichaIng/DietPi/issues/2173
- DietPi-Drive_Manager | encryptfs is currently not supported and will be removed from fstab when executing drive manager: https://github.com/MichaIng/DietPi/issues/2078
- RPi | LXAppearance (on LXDE desktop) hangs on dbus-launch: https://github.com/MichaIng/DietPi/issues/1791
- Odroid C2 | Some WiFi adapters do no work as hotspot: https://github.com/MichaIng/DietPi/issues/1955
- DietPi-Software | Node-RED: Pre-installed modules cannot be updated via web UI: https://github.com/MichaIng/DietPi/issues/2073
- DietPi-Software | Raspimjpeg: With Lighttpd, streaming mjpeg does not work: https://github.com/MichaIng/DietPi/issues/1747

For all additional issues that may appear after release, please see the following link for active tickets: https://github.com/MichaIng/DietPi/issues

### CODE REVIEW

**Comment by jvteleco** [comment]
Just confirming working perfectly a fresh install on a new microSD of the beta v6.22.1 on a raspberry pi 3 B+ with the following options activate on the dietpi.txt on first boot up:
AUTO_SETUP_AUTOMATED=1   
AUTO_SETUP_INSTALL_SOFTWARE_ID=78    #LESP nginx, sqlite, php
AUTO_SETUP_SSH_SERVER_INDEX=-2   #for OpenSSH 
AUTO_SETUP_WEB_SERVER_INDEX=-1  #for nginx
AUTO_SETUP_AUTOSTART_TARGET_INDEX=7 
AUTO_SETUP_HEADLESS=0 
DEV_GITBRANCH=beta

I have installed without issues and done basic test:
- Pihole
- Wireguard (on my Android mobile, connecting correctly and ad block working)
- Home assistant
- Influxdb
- Grafana
- Rpi monitor

if you want me to try anything specific (not super complicated), I can try this weekend.

**Comment by MichaIng** [comment]
@jvteleco 
Thanks very much for your testing! Last Beta update (nothing serious) is in the pipe, release and final v6.22 stable release until end of the week, besides we find some serious issues until then 😉: https://github.com/MichaIng/DietPi/pull/2643

**Comment by jvteleco** [comment]
OK. Is there a way to udpate to beta 6.22.2 ?

**Comment by MichaIng** [comment]
Not yet, besides switching to dev branch. But I will release later today or tomorrow to Beta branch.

**Pull request merged**
