### PR TITLE
DietPi-Software | Single File PHP Gallery: Resolved the failing installation

### LINKED ISSUE #5415: Unable to install single file php gallery
#### Details:
- Date           | Sat Apr  9 16:03:12 BST 2022
- DietPi version | v8.3.1 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | from scratch
- Hardware       | RPi 2 Model B (armv7l) (ID=2)
- Kernel version | `Linux server 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `curl -ILfvm 10 https://sye.dk/sfpg/Single_File_PHP_Gallery_4.8.1.zip`
- Exit code      | 22
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2a02:2350:5:10a:4a:9025:f784:46f3:443...
* Connected to sye.dk (2a02:2350:5:10a:4a:9025:f784:46f3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4278 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [520 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.sye.dk
*  start date: Apr  8 19:45:30 2022 GMT
*  expire date: Jul  7 19:45:29 2022 GMT
*  subjectAltName: host "sye.dk" matched cert's "sye.dk"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x241ed50)
} [5 bytes data]
> HEAD /sfpg/Single_File_PHP_Gallery_4.8.1.zip HTTP/2
> Host: sye.dk
> user-agent: curl/7.74.0
> accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
} [5 bytes data]
* The requested URL returned error: 404 
* stopped the pause stream!
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host sye.dk left intact
curl: (22) The requested URL returned error: 404 
```

### PR DESCRIPTION
**Pull request by MichaIng**
Seems like the reason we hosted the archive on our own server was that the old download is not available anymore once a new version has been released.

I asked Kenny (SFPG developer) whether we can provide a "latest" download URL, or an API from where the latest version can be obtained via curl. But otherwise I suggest we revert back to the previous solution, hosting the download at dietpi.com, so that it stays valid and we can update it with a simple download on our server.

### CODE REVIEW

**Review by Joulinar — DISMISSED** [review]

**Comment by Joulinar** [comment]
Let's see if Kenny is open to create "latest" version we could use on our scripting. If not we might need to go back to what we had before.

**Comment by Joulinar** [comment]
ok perfect

**Comment by MichaIng** [comment]
While testing, OOT: Cloudflare DNS is currently completely down, including 1.1.1.1, one.one.one.one, and also plain + filtered DoH. Waiting for user reports about failing Internet connection tests 😄. Luckily Quad9 works well.

**Comment by Joulinar** [comment]
using unbounb + DoT is still working with Cloutflare

```
15:34:43.051354 eth0  Out IP 192.168.0.11.33032 > 1.1.1.1.853: Flags [.], ack 10237, win 501, length 0
15:34:43.051381 eth0  In  IP 1.1.1.1.853 > 192.168.0.11.33032: Flags [P.], seq 10237:10729, ack 2975, win 68, length 492
15:34:43.051381 eth0  In  IP 1.1.1.1.853 > 192.168.0.11.33032: Flags [P.], seq 10729:11221, ack 2975, win 68, length 492
15:34:43.051381 eth0  In  IP 1.1.1.1.853 > 192.168.0.11.33032: Flags [P.], seq 11221:11713, ack 2975, win 68, length 492
15:34:43.051405 eth0  Out IP 192.168.0.11.33032 > 1.1.1.1.853: Flags [.], ack 10729, win 501, length 0
15:34:43.051424 eth0  Out IP 192.168.0.11.33032 > 1.1.1.1.853: Flags [.], ack 11221, win 501, length 0
15:34:43.051442 eth0  Out IP 192.168.0.11.33032 > 1.1.1.1.853: Flags [.], ack 11713, win 501, length 0
15:34:43.064413 eth0  In  IP 1.0.0.1.853 > 192.168.0.11.59968: Flags [P.], seq 11152:11644, ack 2823, win 75, length 492
15:34:43.064441 eth0  Out IP 192.168.0.11.59968 > 1.0.0.1.853: Flags [.], ack 11644, win 501, length 0
15:34:43.064635 eth0  Out IP 192.168.0.11.59968 > 1.0.0.1.853: Flags [P.], seq 2823:2975, ack 11644, win 501, length 152
15:34:43.070164 eth0  In  IP 1.1.1.1.853 > 192.168.0.11.33032: Flags [P.], seq 11713:12205, ack 3127, win 70, length 492
```

**Comment by MichaIng** [comment]
It just started working here again as well. The DoH issue on my notebook may have been indeed a result of the failing system DNS (ISP) connection, since DoH uses hostnames and need to be bootstrapped with an initial plain DNS query. But pinging 1.1.1.1 itself failed as well 🤔.

**Comment by Joulinar** [comment]
Who knows 😀

**Comment by MichaIng** [comment]
Added some messages about where we derive the latest download from and that image files are not removed on uninstall. Works well, install, reinstall, uninstall. Merging once CI is green.

**Pull request merged**
