### PR TITLE
DietPi-Software | Docker Compose: Fix install on ARMv8 + Stretch

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Software | Docker Compose: Add libffi-dev on ARMv8 + Stretch, required for cffi module compilation on ARMv8: https://dietpi.com/phpbb/viewtopic.php?p=34293#p34293

### CODE REVIEW

**Comment by Joulinar** [comment]
uhh I checked the original PR where I created the software title and `libffi-dev` together with `libssl-dev` was explicitly removed on arch64/arm64. But I guess we never checked Stretch on 64bit. 🙄

**Comment by MichaIng** [comment]
Seems so, the combination is rare anyway.

**Comment by Joulinar** [comment]
what do you use to check such combination?

**Comment by MichaIng** [comment]
A `systemd-nspawn` container running on a VM 😄. Horribly slow, but it works. Since we don't have Stretch images anymore, I used one of Meverics Stretch Odroid images: https://dietpi.com/meveric/images/Stretch/
Kernel and such does not matter (respectively cannot be tested) but on demand I switch between RPi, Armbian, Meveric kernel repo to check if a contained package, overriding a Debian one, would cause issues.

Another reason for bare DietPi container images: We can deploy it on a GitHub actions runner to do install tests for us, at least the ones which do not require user input 😄.

I ordered new SD cards, probably I can keep one with an ARMv8 Stretch image installed to run such tests on NanoPi R4S.

**Comment by Joulinar** [comment]
ok I see, I give these rar testing cases to you 😄

**Comment by MichaIng** [comment]
Jep that's fine. I have an extra VM with those containers prepared and ARMv7 containers on RPi, so can test all combinations we support.

**Review by Joulinar — APPROVED** [review]

**Pull request merged**
