### PR TITLE
Beta > Master

### PR DESCRIPTION
**Pull request by Fourdee**
**v6.19**
(04/12/18)

**Changes / Improvements / Optimisations:**
- General | ASUS TB: Image updated to mainline kernel, with midgard r13 GPU driver. Now supports hardware acceleration and Kodi. Please download the image and install Xserver (or desktop) through DietPi-Software to enable these features.
- General | RPi 3A+: Added hardware code enabling correct naming of device throughout DietPi: https://github.com/Fourdee/DietPi/issues/2301
- DietPi-Software | Renamed several software config files to have a consistent naming scheme: https://github.com/Fourdee/DietPi/pull/2312
- DietPi-Software | LXDE: Applied updated DietPi theme and wallpaper. For new installations only.
- DietPi-Software | Blynk Server: Now installed to DietPi userdata directory, and, runs under blynk user. Many thanks to @joaofl for this PR! https://github.com/Fourdee/DietPi/pull/2287
- DietPi-Software | Reboot prompt: Will now occur prior to the system rebooting. Giving you time to do more, before rebooting! :D
- DietPi-Software | Moved majority of conf/* files located on DietPi-RAMdisk, moved over to github for download during installations. Reducing the size of RAMdisk usage.
- DietPi-Software | Pydio: Added rewrite rules to all webserver configs to allow sync client connection out of the box. Thanks to @MonZon for reporting this issue: https://github.com/Fourdee/DietPi/issues/2308
- PREP | Serial console: Now enabled by default for all future DietPi images. Please note, only v6.19 images and above, will have this set by default. Existing images require edit of /boot/dietpi.txt and 'CONFIG_SERIAL_CONSOLE_ENABLE=1' before 1st run: https://github.com/Fourdee/DietPi/issues/2313

**Bug Fixes:**
- General | Asus TB (based on our recent 2.0.8 Tinker OS pre-image): Resolved issue with corrupt characters in desktops.
- DietPi-Update | Prevented backup prompt during each subversion patch from displaying.
- DietPi-Software | Chromium: Resolved incorrect scale of window under Kiosk mode: https://github.com/Fourdee/DietPi/issues/2298#issuecomment-442995196
- DietPi-Software | OMPD: Resolved a reinstall issue due to SQL table not being correctly dropped, before re-created: https://github.com/Fourdee/DietPi/issues/2305
- DietPi-Autostart | XU4: Resolved an issue with startx failing during boot: https://github.com/Fourdee/DietPi/issues/2130#issuecomment-443475525

**Allo GUI:**
- GMrender: Resolved service failing to be enabled: https://github.com/Fourdee/DietPi/issues/2305

As always, many smaller code performance and stability improvements, visual and spelling fixes have been done, too much to list all of them here. Check out all code changes of this release on GitHub: https://github.com/Fourdee/DietPi/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+base%3Amaster

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
Which is the reason to release this outside of usual schedule? Yeah broken chromium is nasty, but we had other issues delayed for longer 😉.

I like the desktop downloads/links finally on GitHub 👍. Actually they fit (mostly) into `/DietPi/dietpi/conf` as well, at least configuration files and desktop shortcuts?
The pngs do not belong there of course, as this would blow up the RAMdisk (compared to now).

Generally I would move `/DietPi/dietpi/conf` to `/var/lib/dietpi/dietpi-software/[$software_id/?]*`, as these files are veeery rarely or never in use. This can be done on a later version, but whether to have e.g. `pcmanfm.conf` in `.meta` (where it needs to be downloaded separately) or placed into users systems, should be decided now. Otherwise we need to keep them in `.meta` as well, just to not break a single versions download links 😉.
______________
Another thing I wanted to fine tune is the blynk install dir move. Currently we do not patch this, which leads to reinstalls use the prior data dir as install dir. Old data needs to be moved by user manually, old binary location will be left doubled.
I suggest we patch this, moving the old binary/data for existing installs in place and do a reinstall. Needs verification as well if a reinstall successfully migrates old data and binaries without overwriting any config and such.

**Comment by Fourdee** [comment]
@MichaIng 

> Which is the reason to release this outside of usual schedule?

No core code changes that need indepth testing. Simple and tested fixes for existing items that we do not need to delay release for.

> Generally I would move /DietPi/dietpi/conf to /var/lib/dietpi/dietpi-software/[$software_id/?]*, as these files are veeery rarely or never in use. This can be done on a later version, but whether to have e.g. pcmanfm.conf in .meta

I see a benefit in keeping most confs on github, less files on user system. Install only when needed etc. Some need to stay on ```conf``` (eg: ```network interfaces```) as used in Allo GUI etc.

Yep, we should change conf/desktop items to ```.data``` ```.downloads``` or something similar?

🈯️ ```.conf```

**Comment by MichaIng** [comment]
<s>Some conf dir references are still left in `dietpi-software`, will identify and fix.</s>
- At least for Nextcloud resolved already 👍

Also I would like to rename some of the files and simplify a bid, since this is the last chance we can do it. Only downside of this conf downloads: Once implemented, the URLs need to stay the same forever 😅.

**Comment by Fourdee** [comment]
@MichaIng 

> Also I would like to rename some of the files and simplify a bid, since this is the last chance we can do it. 

Yep, by all means, what you have in mind?

> Only downside of this conf downloads: Once implemented, the URLs need to stay the same forever 

We can always change ```dev``` links and rename the files as needed, won't affect beta/master branches until updated.

The upside:
- less junk (mostly unused for most users) in the RAMdisk 😃 
- Less code in ```dietpi-software``` once we replace more ```cat _EOF_``` with downloads.

Downside:
- flaky connection or github issue = failed install.

**Pull request merged**
