### PR TITLE
General | Handle missing kernel modules after upgrade

### LINKED ISSUE #4732: DietPi-Banner | Show warning on installed<>loaded kernel mismatch
#### Required Information
- DietPi version | `7.5.2`
- Distro version | `Bullseye`
- Kernel version | `Linux DietPi 5.10.52-v8+`
- SBC model | `RPi 4 Model B (aarch64)`
- Power supply used | CanaKit Power Supply
- SDcard used | Samsung 64GB

#### Additional Information (if applicable)
- Software title | DietPi-VPN
- Was the software title installed freshly or updated/migrated? | Fresh
- Can this issue be replicated on a fresh installation of DietPi? | Yes

- Bug report ID | `00629356-8cf8-4500-a9ab-486b31857f8f`

#### Steps to reproduce

1. Select DietPi-VPN
2. Select IPVanish
3. Input username and password
4. Select either UDP or TCP
5. Connect to server
6. Fails (Connection failed/timeout)

#### Expected behaviour

1. Follow steps 1-5
2. Connects to server

#### Actual behaviour
1. Follow steps 1-5
2. Not connecting to server

#### Extra details

- I have triple checked that all login info is correct. I have tried multiple servers, both UDP and TCP. I have reinstalled the image. Nothing seems to be working. I have skimmed the current and past bug reports but don't see anything on this issue. Upon typing `systemctl -l status dietpi-vpn` I get this error:

```
dietpi-vpn.service - VPN Client (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-vpn.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-09-13 01:53:31 EDT; 1min 4s ago
    Process: 28625 ExecStart=/usr/sbin/openvpn --suppress-timestamps --nobind --config /etc/openvpn/client.ovpn (code=exited, status=1/FAILURE)
   Main PID: 28625 (code=exited, status=1/FAILURE)
     Status: "Pre-connection initialization successful"
        CPU: 97ms

NCP: overriding user-set keysize with default
Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
DietPi openvpn[28625]: net_route_v4_best_gw query: dst 0.0.0.0
DietPi openvpn[28625]: net_route_v4_best_gw result: via 192.168.50.1 dev eth0
DietPi openvpn[28625]: ROUTE_GATEWAY 192.168.50.1/255.255.255.0 IFACE=eth0 HWADDR=XX:XX:XX:XX:XX:XX
DietPi openvpn[28625]: ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
DietPi openvpn[28625]: Exiting due to fatal error
DietPi systemd[1]: dietpi-vpn.service: Main process exited, code=exited, status=1/FAILURE
DietPi systemd[1]: dietpi-vpn.service: Failed with result 'exit-code'.

```

### LINKED ISSUE #4959: DietPi-Software | Gracefully handle kernel upgrades
If the kernel got upgraded but not reboot has been done yet, in most cases there is no `/lib/modules/$(uname -r)` anymore so that no additional kernel modules can be loaded. This leads to failures on some software installs:
- If Docker gets explicitly selected, we already to a check and in case unmark it and all it's dependants from being installed, leaving a prompt that a reboot is required first.
- If a Docker dependant got selected but not Docker itself, the above check is not done, hence the Docker install fails. Great would be a generic way to have the check done for all software titles which require additional kernel modules and also for all their dependants. I'm not yet sure how to add it elegantly, but before deferring it further, at least we can add it manually for the known Docker dependants for now.
- Aside of Docker, also Box86 and Box64 require to load additional kernel modules, `binfmt_misc` to  be precise, as we restart `systemd-binfmt` during the install to have i386/x86_64 binaries executed via Box86/Box64 automatically. However, in this case it makes more sense to check whether the module can be loaded, or is loaded already, and skip the service start if not, leaving an info that a reboot is required to have the binfmt functionality enabled. Even without a reboot, `box86 /path/to/executable` works already, so it is basically a convenience feature and assures that the wrapping is done as well when e.g. a script executes multiple binaries.

### PR DESCRIPTION
**Pull request by MichaIng**
- General | Make users more aware and abort dietpi-software installs if a reboot is required to finalise a recent kernel upgrade. Otherwise the installed kernel modules at /lib/modules do not match the loaded kernel and loading modules ondemand hence fails. Several software installs directly or indirectly load kernel modules, mounting filesystems requires the related kernel driver to be loaded, generally several system and maintenance tasks depend on it.
- DietPi-Software | WireGuard: Move install to be applied last, since it is the only one which forces a kernel upgrade, possibly breaking other installs if attempting to load kernel modules

### CODE REVIEW

**Comment by MichaIng** [comment]
I went a more intrusive way for now:
- `dietpi-update` does a reboot automatically during first run setup if a kernel upgrade was done, otherwise if shows a prompt, recommends and offers a reboot. I know the idea was to show a console message only, but somehow it doesn't feel fitting for DietPi scripts where we use whiptail prompts and want to allow users to finish everything without manual console inputs. Finally hitting return/enter once is not so disturbing, and the option to reboot directly without all services being started first seems reasonable.
- `dietpi-software` does the full APT upgrade during first run setup now at an earlier stage, before any interactive prompts happen, and then does a reboot automatically as well. It creates a flag so rule out reboot loops, when somehow the kernel does not come with modules (e.g. custom kernel builds with everything builtin). Related prompts also give the info that for such case the directory should be created manually to satisfy the check. However, none of our images does or will ever ship such a kernel.
    - On regular (not first run setup) `dietpi-software` calls, a prompt is shown to either perform a reboot or abort software installs. So we are strict here to avoid related install failures.
- `dietpi-drive_manager` recommends and offers a reboot in case. Here it is required if kernel drivers for filesystems need to be loaded, and the `autofs4` kernel module check depends on it.
- The DietPi banner shows an info as well, in case no DietPi or APT upgrades are available.

**Comment by Joulinar** [comment]
what would be best way to test this? Using `rpi-update`?

**Comment by MichaIng** [comment]
For example, or simply `mv /lib/modules/$(uname -r){,_bak}`.

**Comment by MichaIng** [comment]
Ran some tests with all affected scripts and first run setup and works all as expected here. Ready to be merged from my end.

**Comment by MichaIng** [comment]
I'll merge this so, so we may get a feeling about it during daily testing and can tune as required.

**Pull request merged**
