### PR TITLE
DietPi-Software | Pi-hole: Whitelist GEO IP API we use in banner and DietPi-VPN

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Patches | Pi-hole: Whitelist domain of GEO IP API we use in banner and DietPi-VPN as this is part of public blocklists
+ DietPi-Software | Pi-hole: Whitelist domain of GEO IP API we use in banner and DietPi-VPN as this is part of public blocklists

### CODE REVIEW

**Comment by Joulinar** [comment]
We will do this without user notification?

**Comment by ravenclaw900** [comment]
It would probably be good to at least put a comment for that entry, but I don’t think that you can do it from the command line.

**Comment by Joulinar** [comment]
technically it's working

```
root@DietPiProd:~# pihole -w freegeoip.app
  [i] Adding freegeoip.app to the whitelist...
  [✓] Reloading DNS lists
root@DietPiProd:~#
```

WAN IP is now being detected

` - WAN IP : 93.x.x.x Region Germany`

image

**Comment by MichaIng** [comment]
> We will do this without user notification?

The `pihole` command prints nicely what is done, but I added another notification about why we do it 👍.

> It would probably be good to at least put a comment for that entry, but I don’t think that you can do it from the command line.

I didn't know about those comments and they can be added via CLI as well, which I've added 👍.

**Comment by MichaIng** [comment]
```
# Pi-hole install
[ INFO ] DietPi-Software | Whitelisting "freegeoip.app", which is used by dietpi-banner and dietpi-vpn to obtain your public IP and location...
  [i] Adding freegeoip.app to the whitelist...
  [✓] Reloading DNS lists
...
# DietPi update
[ INFO ] DietPi-Patch | Whitelisting "freegeoip.app" in Pi-hole, which is used by dietpi-banner and dietpi-vpn to obtain your public IP and location...
  [i] freegeoip.app already exists in whitelist, no need to add!
```
Pi-hole whitelist

Very nice, I'm gonna merge it.

**Pull request merged**
