### PR TITLE
DietPi-RAMdisk | Replace with vmtouch to use native fs caching

### LINKED ISSUE #3288: DietPi-RAMdisk | Replace with vmtouch to use native fs caching
I am not 100% happy with DietPi-RAMdisk. Changes to those files should not rely on a clean shutdown, which is currently required to write RAMdisk back to disk. As well it causes confusion when files are present at two locations.

Actually since Linux has a very good disk caching system already, why not using that one. It caches often used files/scripts automatically. But if we really want DietPi scripts to be most responsive even when being called the first time, I found some tool which is able to lock files in cache: https://github.com/hoytech/vmtouch

Available from Debian repo since Buster: https://packages.debian.org/buster/vmtouch
But I would compile own binaries and implement with systemd unit, since the sysvinit service is broken anyway: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947603

Tested it and works as expected. Executing locked example scripts from /boot/dietpi results in exactly same read speed compared to tmpfs. The vmtouch binary itself is extremely lightweight, the overall used memory matches nearly exactly the locked files, hence not more then a few KiB overhead, most likely similar compared to an active tmpfs.

Requires some more testing but actually not much risk. Backwards compatibility can be simply achieved via symlink: `rmdir /DietPi; ln -s /boot /DietPi`

One single current issue: `/DietPi/dietpi/.network` needs to be global write-able currently to allow non-root users updating current active network adapter + IP (e.g. dietpi-banner) as well. But such flag files, which shall not survive boots, are better placed in /tmp or /run anyway.
______________
Argument summary:
- Our scripts cannot break if DietPi-RAMdisk fails to mount or move scripts from disk to tmpfs.
- Changes are not lost if DietPi-RAMdisk fails to move files back to disk on shutdown, e.g. in case of power loss.
- Users are not confused that changes to /boot/config.txt|boot.ini are not boot-persistent. Even that those files contain explaining comments, we have regular reports.
- Speeds up boot process since vmtouch is much faster then DietPi-RAMdisk service + script.
- vmtouch is then completely optional, speeding up our script executions and settings reads, allowing flexibel additional cache locks or releases. If it's removed or fails, disk caching falls back to Linux, which automatically caches often accessed files anyway.
- From disk writes perspective: Settings changes within our scripts then cause direct disk writes, merged according to async. However especially in combination with async those are minimal compared with other tasks, e.g. simple "apt update" causes magnitude of order larger writes. And more importantly with DietPi-RAMdisk, all DietPi scripts and settings are completely written to disk on every shutdown (and dietpi-update), which very likely is much more compared to edited settings files in a session.

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Review

**ToDo**:
- [x] Create runtime stat/flag files in /run/dietpi

**Commit list/description**:
+ DietPi-RAMdisk | Remove script due to replacement with vmtouch

### CODE REVIEW

**Comment by Joulinar** [comment]
@MichaIng 
let me know of you need testing

**Comment by MichaIng** [comment]
@Joulinar 
Many thanks for offer. Indeed the transition needs to be tested intensively. I'll let you know once its finished.

**Comment by MichaIng** [comment]
Okay, everything ready from my side:
- DietPi-RAMdisk is history
- Migration during update has been tested with several older images, should be failsafe
- Migration for Jessie systems is blocked, has been tested with one older and one newer Jessie image as well
- vmtouch is installed instead, locking DietPi scripts and dietpi.txt in RAM to preserve execution and parsing performance of RAMdisk. However it can be freely configured via `/etc/default/vmtouch` to lock anything or nothing or do another of its features instead. As well it is totally optional and can be disabled (systemctl disable vmtouch) or purged (apt purge vmtouch) without affecting DietPi functionality, only our scripts might be a bid slower when executed rarely and the first time during boot.

Do not write runtime files to disk, I moved those to a new runtime tmpfs dir `/run/dietpi` which do not need to be boot-persistent. This complies with Debian defaults, FHS etc as well:
- Runtime files, required during service or system runtime: `/run`
- Temporary files, e.g. per-script files, expected to be removed after usage: `/tmp`

**Comment by Joulinar** [comment]
@MichaIng 
Did a test on a Stretch as well as Buster VM. Both updates to v6.29 finished as follow:

```
[  OK  ] DietPi-Update | Incremental patching to v6.29.0 completed
[ SUB2 ] DietPi-Update > Completed
[ INFO ] DietPi-Update | Current version : v6.29.0
[ INFO ] DietPi-Update | Latest version  : v6.29.0
[  OK  ] DietPi-Survey | Sending survey data
[ SUB3 ] DietPi-Services > restart
[  OK  ] DietPi-Services | restart : airsonic
[  OK  ] DietPi-Services | restart : cron
Terminated
root@DietPiVM3:~# 
```

All fine, except the `Terminated` at the end 😄 

Not sure if this is something but I found this on `journalctl` on both systems.

```
Mar 06 22:24:16 DietPiVM3 systemd[1]: tmp.mount: Directory /tmp to mount over is not empty, mounting anyway.
Mar 06 22:24:16 DietPiVM3 systemd[1]: Mounting /tmp...
Mar 06 22:24:16 DietPiVM3 systemd[1]: Mounted /tmp.
```

**Comment by MichaIng** [comment]
@Joulinar 
Many thanks for testing. Yes the termination is expected. Due to the changes it is required to restart DietPi-Update (new code) from within the patch_file. When the child instance has finished, the parent instance must be terminated to not finish another time with old code. However I'll add some message that this is expected.
#### Done: https://github.com/MichaIng/DietPi/pull/3402/commits/9895c3d805ecedd6c7f5d2d24e5f3d672a55d0fa + https://github.com/MichaIng/DietPi/commit/edafa696850517e93df374379995fc9d2d76e427

> tmp.mount: Directory /tmp to mount over is not empty

We clear the /tmp dir when creating new images, however it can happen by times that something is written to the non-tmpfs /tmp dir when it mounts late at boot or unexpectedly unmounts or such. To solve:
```
mkdir /mnt/root
mount /dev/sda1 /mnt/root
rm -Rfv /mnt/root/tmp/{,.??,.[^.]}*
umount /mnt/root
rmdir /mnt/root
```

**Comment by Joulinar** [comment]
@MichaIng 
looks good now

```
[  OK  ] DietPi-Update | Incremental patching to v6.29.0 completed
[ SUB2 ] DietPi-Update > Completed
[ INFO ] DietPi-Update | Current version : v6.29.0
[ INFO ] DietPi-Update | Latest version  : v6.29.0
[  OK  ] DietPi-Survey | Sending survey data
[ SUB3 ] DietPi-Services > restart
[  OK  ] DietPi-Services | restart : redis-server
[  OK  ] DietPi-Services | restart : mariadb
[  OK  ] DietPi-Services | restart : php7.3-fpm
[  OK  ] DietPi-Services | restart : lighttpd
[  OK  ] DietPi-Services | restart : logitechmediaserver
[  OK  ] DietPi-Services | restart : cron
[  OK  ] DietPi-Services | ncc maintenance:mode --off
[  OK  ] DietPi-Patch | Everything done! Terminating the obsolete DietPi-Update parent instance...
Terminated
root@DietPiVM1:~#
```

Question: should there be an automated reboot initiated?

**Comment by MichaIng** [comment]
@Joulinar 
> Question: should there be an automated reboot initiated?

Nope, only on first boot, if this is the firstrun update and the image is pre-v6.20.

**Comment by Joulinar** [comment]
Roger that

**Pull request merged**
