### PR TITLE
DietPi-Ramlog | Toggle service on (un)install

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready for testing
- Or is there any reason why the service stays active, saving and recovering the /var/log file/folder structure on reboot?

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

> Or is there any reason why the service stays active, saving and recovering the /var/log file/folder structure on reboot?

Yep, its to ensure that the existing contents of ```/var/log``` is copied during boot:
```
		#Apply previous attributes and ownerships. Generates empty file if it doesnt exist.
		if [[ -d $FILEPATH_DIETPI_RAMLOG_SAVE ]]; then

			cp -R -p --attributes-only $FILEPATH_DIETPI_RAMLOG_SAVE/* /var/log/

		fi
```

Although, we could simply do the following during uninstall:
```
systemctl stop dietpi-ramlog #save
G_RUN_CMD umount /var/log
systemctl start dietpi-ramlog #restore contents to disk
systemctl stop dietpi-ramlog #done
systemctl disable dietpi-ramlog
```

**Comment by MichaIng** [comment]
@Fourdee 
Ah yes, makes sense to not leave `/var/log` empty on uninstall. I will add those steps.

**Comment by Fourdee** [comment]
@MichaIng 

I also think we might need to do something for the installation of RAMdisk aswell (if on disk currently), similar to above to ensure existing files are copied over. I'll check.

**Comment by Fourdee** [comment]
@MichaIng 

Yep, for install, we need to do, something like:
```

		INSTALLING_INDEX=103
		if (( ${aSOFTWARE_INSTALL_STATE[$INSTALLING_INDEX]} == 1 )); then

			Banner_Installing

			#Install (add tmpfs mount to fstab)
			local tmpfs_max_size=$(grep -m1 '^AUTO_SETUP_RAMLOG_MAXSIZE=' /DietPi/dietpi.txt | sed 's/^.*=//')
			sed -i "/\/var\/log/c\tmpfs                   \/var\/log                tmpfs   defaults,size=${tmpfs_max_size}m,noatime,nodev,nosuid,mode=1777  0 0" /etc/fstab
			
			local filepath_dietpi_ramlog_save='/var/lib/dietpi/dietpi-ramlog/storage'
			mkdir -p $filepath_dietpi_ramlog_save
			cp -R -p --attributes-only /var/log/* $filepath_dietpi_ramlog_save/
			
			rm -R /var/log/*
			
			G_RUN_CMD mount -t tmpfs -o size=${tmpfs_max_size}m tmpfs /var/log
			systemctl enable dietpi-ramlog
			G_RUN_CMD systemctl start dietpi-ramlog

		fi

```

**Comment by MichaIng** [comment]
@Fourdee 
Check last commit.

On install it now additionally just copies log skeletons to ramlog storage. Reboot will mount the ram drive and copy log files in place from storage. But we could also do it directly, as your post suggests?

**Comment by Fourdee** [comment]
@MichaIng 

Looking good 👍 

I'll merge and test.

**Comment by Fourdee** [comment]
RAMlog > full
```
Log file contents:
       │ umount: /var/log: target is busy
       │         (In some cases useful info about processes that
       │          use the device is found by lsof(8) or fuser(1).)
       │

--
root@DietPi:~# lsof | grep /var/log
rsyslogd  5213                 root    6w      REG       0,30    77249      22298 /var/log/syslog
rsyslogd  5213                 root    7w      REG       0,30    77107      22299 /var/log/kern.log
rsyslogd  5213                 root    8w      REG       0,30    13519      22300 /var/log/debug
rsyslogd  5213                 root    9w      REG       0,30    58119      22301 /var/log/messages
rsyslogd  5213                 root   10w      REG       0,30      434      22390 /var/log/auth.log
in:imuxso 5213 5215            root    6w      REG       0,30    77249      22298 /var/log/syslog
in:imuxso 5213 5215            root    7w      REG       0,30    77107      22299 /var/log/kern.log
in:imuxso 5213 5215            root    8w      REG       0,30    13519      22300 /var/log/debug
in:imuxso 5213 5215            root    9w      REG       0,30    58119      22301 /var/log/messages
in:imuxso 5213 5215            root   10w      REG       0,30      434      22390 /var/log/auth.log
in:imklog 5213 5216            root    6w      REG       0,30    77249      22298 /var/log/syslog
in:imklog 5213 5216            root    7w      REG       0,30    77107      22299 /var/log/kern.log
in:imklog 5213 5216            root    8w      REG       0,30    13519      22300 /var/log/debug
in:imklog 5213 5216            root    9w      REG       0,30    58119      22301 /var/log/messages
in:imklog 5213 5216            root   10w      REG       0,30      434      22390 /var/log/auth.log
rs:main   5213 5217            root    6w      REG       0,30    77249      22298 /var/log/syslog
rs:main   5213 5217            root    7w      REG       0,30    77107      22299 /var/log/kern.log
rs:main   5213 5217            root    8w      REG       0,30    13519      22300 /var/log/debug
rs:main   5213 5217            root    9w      REG       0,30    58119      22301 /var/log/messages
rs:main   5213 5217            root   10w      REG       0,30      434      22390 /var/log/auth.log

--
root@DietPi:~# lsof | grep /var/log^C
root@DietPi:~# systemctl stop rsyslog
Warning: Stopping rsyslog.service, but it can still be activated by:
  syslog.socket
root@DietPi:~# lsof | grep /var/log
rsyslogd  5577                 root    6w      REG       0,30    77549      22298 /var/log/syslog
rsyslogd  5577                 root    7w      REG       0,30    58419      22301 /var/log/messages
in:imuxso 5577 5579            root    6w      REG       0,30    77549      22298 /var/log/syslog
in:imuxso 5577 5579            root    7w      REG       0,30    58419      22301 /var/log/messages
in:imklog 5577 5580            root    6w      REG       0,30    77549      22298 /var/log/syslog
in:imklog 5577 5580            root    7w      REG       0,30    58419      22301 /var/log/messages
rs:main   5577 5581            root    6w      REG       0,30    77549      22298 /var/log/syslog
rs:main   5577 5581            root    7w      REG       0,30    58419      22301 /var/log/messages

```

**Comment by Fourdee** [comment]
Ok, lets try this a little different, leave it with me.


🈯️ 
```
root@DietPi:~# systemctl stop syslog.socket
root@DietPi:~# systemctl stop syslog
root@DietPi:~# lsof | grep /var/log
```

**Comment by Fourdee** [comment]
Retest:
- 🈯️ RAMlog 1 > full
- 🈯️ full > RAMlog 1

My only concern is if something else (that we can't* predict) is using ```/var/log``` during the uninstall, this will render it failed.

**Comment by MichaIng** [comment]
@Fourdee 
Hmm we could also add a single shot service that copies logs from storage to disk one single time on next boot, earliest possible boot stage, and disables itself (similar to fs resize service). Then do no tmpfs u/mount at all directly.

**Comment by Fourdee** [comment]
@MichaIng 

> Hmm we could also add a single shot service that copies logs from storage to disk one single time on next boot, earliest possible boot stage, and disables itself (similar to fs resize service). Then do no tmpfs u/mount at all directly.

Good idea 👍 

Yep, ideally this would be better, covers any issues with umount failing. I'll take a stab at this tomorrow if I can.

EDIT: Ticket: https://github.com/Fourdee/DietPi/issues/1924

**Pull request merged**
