### PR TITLE
enable wifi on orangepi zero

### PR DESCRIPTION
**Pull request by aliosa27**

### CODE REVIEW

**Comment by aliosa27** [comment]
you can omit build_h2 ..im not sure why it selected it. I am working on a full build/update script to go from armbian to dietpi in a more automated fashion, including chrooting to the target filesystem at the end and doing the dietpi prepwork there. what is your preferred method of resizing the card after its been finished?

**Comment by Fourdee** [comment]
@aliosa27 
I think this would be better suited in the set_hardware script, where we enable/disable the WiFi modules using a blacklist: https://github.com/Fourdee/DietPi/blob/master/dietpi/func/dietpi-set_hardware#L781

We would then add the module to ```/etc/modules``` on the image, allowing the blacklist to control enabled/disabled state.

All you need to do is create another ```aWIFI_MODULES``` with module for OPi Zero Wifi: https://github.com/Fourdee/DietPi/blob/master/dietpi/func/dietpi-set_hardware#L802

> pre-up iwconfig wlan0 power off

Is this to disable power saving, or, power off the WiFi device?

**Comment by Fourdee** [comment]
@aliosa27 
Now I see the need to  pre-up the module 👍 :
```
root@DietPi:~# cat /etc/modules
#w1-sunxi
#w1-gpio
#w1-therm
#sunxi-cir
xradio_wlan
g_serial

root@DietPi:~# lsmod
Module                  Size  Used by
bmp085                  3487  0
pcf8591                 3363  0
g_serial               27617  0
mac80211              358445  0

root@DietPi:~# dmesg | grep xradio
[   11.130697] xradio wlan power on
[   11.653919] [XRADIO_ERR] xradio_load_firmware: can't read config register, err=-110.
[   11.670691] [XRADIO_ERR] xradio_load_firmware failed(-110).
[   11.990282] xradio wlan power off

```

Shame we cant use ```modprobe.d``` to set power options, lacks module options:
```
echo -e "options xradio_wlan power off" > /etc/modprobe.d/xradio_wlan.conf

#Only MAC option is available
root@DietPi:~# modinfo xradio_wlan
parm:           macaddr:First MAC address (charp)
```

No effect:
```
cat << _EOF_ > /etc/network/interfaces.d/xradio_wlan.conf
pre-up modprobe xradio_wlan
pre-up iwconfig wlan0 power off
_EOF_
```

This module is so broken:
```
root@DietPi:~# modprobe xradio_wlan
modprobe: ERROR: could not insert 'xradio_wlan': Connection timed out
root@DietPi:~# modprobe xradio_wlan
```
wlan index of 6:
```
wlan6
```

**Comment by Fourdee** [comment]
@aliosa27 

> what is your preferred method of resizing the card after its been finished?

Script I use to resize after reading whole card to ```.img```:
```
#!/bin/bash
{

	#check packages are installed
	if (( ! $(dpkg -l | grep -ci -m1 'gparted') )); then
		apt-get install gparted zerofree -y
	fi

	#-------------------------------------------------------------------------------
	#MUST LEAVE 40MB+ space or automation autologin may fail due to 0 free space!!!
	#-------------------------------------------------------------------------------

	IMAGE_NAME="DietPi_v139_OrangePiPlus-armv7-(Jessie)"
	IMAGE_NAME+=".img"

	modprobe loop
	losetup -f
	losetup /dev/loop2 "$IMAGE_FP/$IMAGE_NAME"
	partprobe /dev/loop2

	e2fsck -f /dev/loop2p1
	e2fsck -f /dev/loop2p2

	#Mount loops so we can edit files if needed.
	mkdir -p /mnt/loop2p1
	mkdir -p /mnt/loop2p2
	mount /dev/loop2p1 /mnt/loop2p1
	mount /dev/loop2p2 /mnt/loop2p2
	# sync
	# fstrim /mnt/loop2p1 #Not supported in loop mode
	# fstrim /mnt/loop2p2 #Not supported in loop mode
	# sync
	read -p "loop is mounted to /mnt/loop2p1 and 2, press any key to umount and continue..."
	umount -f /mnt/loop2p1
	umount -f /mnt/loop2p2

	#Manual resize
	gparted /dev/loop2

	read -p "If failed press CTRL+C to exit and prevent further action, else, press any key to continue."

	zerofree -v /dev/loop2p1
	zerofree -v /dev/loop2p2

	losetup -d /dev/loop2

	END_PARTITION=$(( $(fdisk -l "$IMAGE_FP/$IMAGE_NAME" | grep ".img2" | awk '{print $3}') + 1 ))
	END_PARTITION=$(( $END_PARTITION * 512 ))

	truncate --size=$END_PARTITION "$IMAGE_FP/$IMAGE_NAME"

	read -p "Done, press any key to continue..."

	exit

}
```

**Comment by aliosa27** [comment]
That's strange. Adding those lines to interfaces and then running a scan works for me and I'm able to associate or put it into ap mode with hostapd with the same image. What did your dmesg output after you run ifup wlan0 ?

**Comment by Fourdee** [comment]
@aliosa27 
```
root@DietPi:~# dmesg | grep wlan
[   19.342071] xradio wlan power on
[   20.208101] xradio wlan power off
[   21.438633] xradio wlan power on
[   22.120730] systemd-udevd[192]: renamed network interface wlan0 to wlan10

root@DietPi:~# ifup wlan10
Internet Systems Consortium DHCP Client 4.3.1
Copyright 2004-2014 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/wlan10/e8:9b:de:bc:4a:e9
Sending on   LPF/wlan10/e8:9b:de:bc:4a:e9
Sending on   Socket/fallback
DHCPDISCOVER on wlan10 to 255.255.255.255 port 67 interval 5
DHCPDISCOVER on wlan10 to 255.255.255.255 port 67 interval 11
DHCPREQUEST on wlan10 to 255.255.255.255 port 67
DHCPOFFER from 192.168.0.1
DHCPACK from 192.168.0.1
bound to 192.168.0.23 -- renewal in 2859 seconds.

root@DietPi:~# dmesg | grep wlan
[  145.540410] ADDRCONF(NETDEV_UP): wlan10: link is not ready
[  147.181093] wlan10: authenticate with e8:de:27:4a:d0:66
[  147.220775] wlan10: send auth to e8:de:27:4a:d0:66 (try 1/3)
[  147.316163] wlan10: authenticated
[  147.320281] wlan10: associate with e8:de:27:4a:d0:66 (try 1/3)
[  147.325044] wlan10: RX AssocResp from e8:de:27:4a:d0:66 (capab=0x411 status=0 aid=3)
[  147.335448] ADDRCONF(NETDEV_CHANGE): wlan10: link becomes ready
[  147.336152] wlan10: associated
[  148.023944] wlan10: IPv6 duplicate address fe80::ea9b:deff:febc:4ae9 detected

root@DietPi:~# dmesg | grep xradio
[   19.342071] xradio wlan power on
[   19.872071] [XRADIO_ERR] xradio_load_firmware: can't read config register, err=-110.
[   19.885491] [XRADIO_ERR] xradio_load_firmware failed(-110).
[   20.208101] xradio wlan power off
[   21.394076] [XRADIO_ERR] xradio_host_dbg_init failed=2599
[   21.438633] xradio wlan power on
[  145.460379] [STA] !!!xradio_vif_setup: id=0, type=2, p2p=0

```

**Comment by Fourdee** [comment]
@aliosa27 
I did try a workaround during ```/DietPi/dietpi/boot``` phase, however, wlan index keeps increasing with each boot (and past the 0-9 current coded in ```/DietPi/dietpi/func/obtain_network_details```) lol:
```
		if (( $HW_MODEL == 32 )); then

			while true
			do

				modprobe xradio_wlan #as this fails "sometimes", loop until its completed.
				if (( $? == 0 )); then

					/DietPi/dietpi/func/obtain_network_details
					local wlan_index=$(sed -n 2p /DietPi/dietpi/.network)

					iwconfig wlan$wlan_index power off

					sed -i "s/wlan[0-9]/wlan$wlan_index/g" /etc/network/interfaces
					systemctl daemon-reload

					if (( $(cat /etc/network/interfaces | grep -ci -m1 '^iface wlan') )); then

						ifup wlan$wlan_index
					fi

					break

				else

					sleep 1

				fi

			done

		fi
```

Regardless of the above, wlan index increases every time ```modprobe xradio_wlan``` is used.

**Comment by aliosa27** [comment]
# Wifi
#allow-hotplug wlan0
iface wlan0 inet dhcp
pre-up modprobe xradio_wlan
pre-up iwconfig wlan0 power off
address 192.168.0.100
netmask 255.255.255.0
gateway 192.168.0.1
wireless-essid FuzonWifi
wireless-key abcde12345
wireless-mode Managed
wireless-power off
wpa-ssid FuzonWifi
wpa-psk abcde12345
#dns-nameservers 8.8.8.8 8.8.4.4


root@DietPi:~# ifup wlan0
Internet Systems Consortium DHCP Client 4.3.1
Copyright 2004-2014 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/wlan0/dc:44:6d:d3:a6:7f
Sending on   LPF/wlan0/dc:44:6d:d3:a6:7f
Sending on   Socket/fallback
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 4
DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 9
^C
[  215.232449] [XRADIO] Driver Label:L34M.01.08.0002  Dec  5 2016 19:38:41
[  215.232529] [XRADIO] Allocated hw_priv @ c2fa1240
[  215.233021] xradio wlan power on
[  215.233044] gpio wl_reg_on set val 1, act val 1
[  215.283176] gpio wl_reg_on set val 0, act val 0
[  215.285195] gpio wl_reg_on set val 1, act val 1
[  215.385228] [XRADIO] Detect SDIO card 1
[  215.386783] [mmc]: sdc1 power_supply is null
[  215.436644] mmc1: new high speed SDIO card at address 0001
[  215.437083] [SBUS] XRadio Device:sdio clk=50000000
[  215.437880] [XRADIO] XRADIO_HW_REV 1.0 detected.
[  215.577284] [XRADIO] Bootloader complete
[  215.659322] [XRADIO] Firmware completed.
[  215.664849] [WSM] Firmware Label:XR_C01.08.0043 Jun  6 2016 20:41:04
[  215.669863] [XRADIO] Firmware Startup Done.
[  215.670779] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[  216.730342] [STA] !!!xradio_vif_setup: id=0, type=2, p2p=0
[  216.810328] ADDRCONF(NETDEV_UP): wlan0: link is not ready
root@DietPi:~# iwlist wlan0 scanning
wlan0     Scan completed :
          Cell 01 - Address: 6C:AA:B3:09:09:88
                    Channel:4
                    Frequency:2.427 GHz (Channel 4)
                    Quality=46/70  Signal level=-64 dBm
                    Encryption key:off
                    ESSID:"BW TownandCountry"
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=0000000f5a415180
                    Extra: Last beacon: 680ms ago
                    IE: Unknown: 0011425720546F776E616E64436F756E747279
                    IE: Unknown: 010482848B96
                    IE: Unknown: 030104
                    IE: Unknown: 0706555320010B24
                    IE: Unknown: 2A0100
                    IE: Unknown: 32080C1218243048606C
                    IE: Unknown: DD180050F2020101880003A4000027A4000042435E0062322F00
                    IE: Unknown: 2D1AAD0103FFFF000000000000000000001000000000040646E70D00
                    IE: Unknown: 3D1604000000000000000000000000000000000000000000
                    IE: Unknown: 7F0400000000
                    IE: Unknown: DD080013920100018523
          Cell 02 - Address: AE:B6:D0:08:AE:C7
                    Channel:4
                    Frequency:2.427 GHz (Channel 4)
                    Quality=70/70  Signal level=-19 dBm
                    Encryption key:on
                    ESSID:"DIRECT-HVSPOOKY-STEALTHms6S"
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=000000098e70dea5
                    Extra: Last beacon: 680ms ago
                    IE: Unknown: 001B4449524543542D485653504F4F4B592D535445414C54486D733653
                    IE: Unknown: 01088C129824B048606C
                    IE: Unknown: 030104
                    IE: Unknown: 2A0100
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: 2D1AAD091BFFFF000000000000000000008000000000000000000000
                    IE: Unknown: 3D1604000100000000000000000000000000000000000000
                    IE: Unknown: 4A0E14000A00C800C800140005001900
                    IE: Unknown: 7F080500000000000040
                    IE: Unknown: DD180050F2020101810003A4000027A4000042435E0062322F00
                    IE: Unknown: DD0900037F01010000FF7F
                    IE: Unknown: DD9E0050F204104A0001101044000102103B000100104700107D5A0669BA2543D38A0BA610A485BDC8102100094D6963726F736F66741023000A57696E646F77732050431024000A31302E302E313433393310420001301054000800070050F20000001011000E53706F6F6B792D537465616C74681008000200081049000600372A00012010490017000137100600109E50E541B69241B0ADCBC6C6A84D0E53
                    IE: Unknown: DD0D506F9A0A00000600111C440006
          Cell 03 - Address: 6C:AA:B3:09:68:88
                    Channel:11
                    Frequency:2.462 GHz (Channel 11)
                    Quality=64/70  Signal level=-46 dBm
                    Encryption key:off
                    ESSID:"BW TownandCountry"
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=00000001cdb1d626
                    Extra: Last beacon: 430ms ago
                    IE: Unknown: 0011425720546F776E616E64436F756E747279
                    IE: Unknown: 010482848B96
                    IE: Unknown: 03010B
                    IE: Unknown: 0706555320010B24
                    IE: Unknown: 2A0100
                    IE: Unknown: 32080C1218243048606C
                    IE: Unknown: DD180050F20201018F0003A4000027A4000042435E0062322F00
                    IE: Unknown: 2D1AAD0103FFFF000000000000000000001000000000040646E70D00
                    IE: Unknown: 3D160B000000000000000000000000000000000000000000
                    IE: Unknown: 7F0400000000
                    IE: Unknown: DD080013920100018534
          Cell 04 - Address: 6C:AA:B3:49:09:88
                    Channel:4
                    Frequency:2.427 GHz (Channel 4)
                    Quality=46/70  Signal level=-64 dBm
                    Encryption key:on
                    ESSID:""
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=0000000f5a415548
                    Extra: Last beacon: 680ms ago
                    IE: Unknown: 0000
                    IE: Unknown: 010482848B96
                    IE: Unknown: 030104
                    IE: Unknown: 050400010000
                    IE: Unknown: 0706555320010B24
                    IE: Unknown: 2A0100
                    IE: Unknown: 32080C1218243048606C
                    IE: Unknown: DD180050F2020101880003A4000027A4000042435E0062322F00
                    IE: Unknown: 2D1AAD0103FFFF000000000000000000001000000000040646E70D00
                    IE: Unknown: 3D1604000000000000000000000000000000000000000000
                    IE: Unknown: 7F0400000000
                    IE: Unknown: DD080013920100018500
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
          Cell 05 - Address: 6C:AA:B3:49:68:88
                    Channel:11
                    Frequency:2.462 GHz (Channel 11)
                    Quality=64/70  Signal level=-46 dBm
                    Encryption key:on
                    ESSID:""
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=00000001cdb1c548
                    Extra: Last beacon: 440ms ago
                    IE: Unknown: 0000
                    IE: Unknown: 010482848B96
                    IE: Unknown: 03010B
                    IE: Unknown: 050400010000
                    IE: Unknown: 0706555320010B24
                    IE: Unknown: 2A0100
                    IE: Unknown: 32080C1218243048606C
                    IE: Unknown: DD180050F20201018F0003A4000027A4000042435E0062322F00
                    IE: Unknown: 2D1AAD0103FFFF000000000000000000001000000000040646E70D00
                    IE: Unknown: 3D160B000000000000000000000000000000000000000000
                    IE: Unknown: 7F0400000000
                    IE: Unknown: DD080013920100018500
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK

root@DietPi:~#

**Comment by aliosa27** [comment]
that was manually ifupping it, this was changing it to auto wlan0 in the conf file, and it comes up on boot




[   15.273895] EXT4-fs (mmcblk0p2): re-mounted. Opts: discard
[   17.278525] systemd-journald[163]: Received request to flush runtime journal from PID 1
[   17.351142] [XRADIO_ERR] xradio_host_dbg_init failed=2599
[   17.366484] [XRADIO] Driver Label:L34M.01.08.0002  Dec  5 2016 19:38:41
[   17.383336] [XRADIO] Allocated hw_priv @ c4e29240
[   17.398551] xradio wlan power on
[   17.411588] gpio wl_reg_on set val 1, act val 1
[   17.461656] gpio wl_reg_on set val 0, act val 0
[   17.463689] gpio wl_reg_on set val 1, act val 1
[   17.563795] [XRADIO] Detect SDIO card 1
[   17.565390] [mmc]: sdc1 power_supply is null
[   17.620527] mmc1: new high speed SDIO card at address 0001
[   17.637748] [SBUS] XRadio Device:sdio clk=50000000
[   17.654290] [XRADIO] XRADIO_HW_REV 1.0 detected.
[   17.815255] [XRADIO] Bootloader complete
[   17.966139] [XRADIO] Firmware completed.
[   17.982048] [WSM] Firmware Label:XR_C01.08.0043 Jun  6 2016 20:41:04
[   17.998417] [XRADIO] Firmware Startup Done.
[   18.015126] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[   18.610587] [STA] !!!xradio_vif_setup: id=0, type=2, p2p=0
[   18.720621] ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   19.605732] gmac0: probed
[   19.618189] gmac0 gmac0: eth0: eth0: PHY ID 00441400 at 0 IRQ poll (gmac0-0:00)
[   20.507064] Adding 102396k swap on /var/swap.  Priority:-1 extents:6 across:233472k SS


root@DietPi:~# cat /etc/network/interfaces
#/etc/network/interfaces
#Please use DietPi-Config to modify network settings.

# Local
auto lo
iface lo inet loopback

# Ethernet
allow-hotplug eth0
iface eth0 inet dhcp
address 192.168.0.100
netmask 255.255.255.0
gateway 192.168.0.1
#dns-nameservers 8.8.8.8 8.8.4.4

# Wifi
#allow-hotplug wlan0
auto wlan0
iface wlan0 inet static
pre-up modprobe xradio_wlan
pre-up iwconfig wlan0 power off
address 192.168.0.100
netmask 255.255.255.0
gateway 192.168.0.1
wireless-essid FuzonWifi
wireless-key abcde12345
wireless-mode Managed
wpa-ssid FuzonWifi
wpa-psk abcde12345
#dns-nameservers 8.8.8.8 8.8.4.4

root@DietPi:~#

**that wireless power off line needs to be set to on

then i can associate ...etc... Are you using the image i posted?



Right after rebooting, It associates for me

───────────────────────────────────────
 DietPi     | 21:50 | Mon 05/12/16
 ───────────────────────────────────────
 V138       | OrangePi Zero (armv7l)
 ───────────────────────────────────────
 IP Address | 192.168.0.100
 ───────────────────────────────────────

 Installation Aborted by User
 Installation must be completed prior to using DietPi
 Please run dietpi-software to restart the installation

root@DietPi:~# iwconfig
lo        no wireless extensions.

tunl0     no wireless extensions.

wlan0     IEEE 802.11bgn  ESSID:"BW TownandCountry"
          Mode:Managed  Frequency:2.427 GHz  Access Point: 6C:AA:B3:09:09:88
          Bit Rate=6.5 Mb/s   Tx-Power=20 dBm
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=43/70  Signal level=-67 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:1  Invalid misc:0   Missed beacon:0

eth0      no wireless extensions.

root@DietPi:~#

**Comment by Fourdee** [comment]
@aliosa27 

> Are you using the image i posted?

Yep. Module still fails to load during boot:

```
root@DietPi:~# dmesg | grep xradio
[   11.002998] xradio wlan power on
[   11.525359] [XRADIO_ERR] xradio_load_firmware: can't read config register, err=-110.
[   11.542118] [XRADIO_ERR] xradio_load_firmware failed(-110).
[   11.861711] xradio wlan power off
```

```/etc/network/interfaces``` (also tried with static ip, no luck):
```
allow-hotplug wlan0
iface wlan0 inet dhcp
pre-up modprobe xradio_wlan
pre-up iwconfig wlan0 power on
```

Manually load module:
```
modprobe xradio_wlan
```

WiFi adapter now available, but strangely, always sets to wlan0 (so far):
```
root@DietPi:~# ifconfig | grep wlan0
wlan0     Link encap:Ethernet  HWaddr dc:44:6d:d3:a6:7f
```

**Comment by Fourdee** [comment]
@aliosa27 
Ok, this works for me as a 'workaround' (also remove the pre-up from ```/etc/network/interfaces```). wlan0 connected with dhcp during boot:
```
cat << _EOF_ > /etc/systemd/system/xradio_wlan.service
[Unit]
Description=xradio_wlan
After=network.target network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes

ExecStartPre=/bin/bash -c 'modprobe xradio_wlan'
ExecStartPre=/bin/bash -c 'iwconfig wlan0 power on'
ExecStart=/bin/bash -c 'ifup wlan0'

[Install]
WantedBy=multi-user.target
_EOF_
systemctl enable xradio_wlan.service
systemctl daemon-reload
```

Maybe we should plan to release this under Beta status due to WiFi ?

**Comment by aliosa27** [comment]
sure. are you regenerating the image or should I?
 I can shortly

**Comment by Fourdee** [comment]
@aliosa27 
I'll make the changes to your image, resize, then upload to testing location.

Just to confirm, additions to /etc/network/interfaces are?:
```
pre-up modprobe xradio_wlan
pre-up iwconfig wlan0 power on
```

**Comment by aliosa27** [comment]
yes yes!

**Comment by Fourdee** [comment]
@aliosa27 
Done, your image available here: http://dietpi.com/downloads/testing/

If you can confirm working and stable, I'll run some tests tomorrow and implement soundcard, OPi sent me a Pi Zero interface card which has 2 usb ports, mic, IR and 3.5mm jack. Then I'll set image as released and give you full credit for it 👍 :
image

**Comment by Fourdee** [comment]
@aliosa27 
If you can update this commit with ```pre-up iwconfig wlan0 power on```, i'll get this merged.

Your image is now live, great work 👍 https://github.com/Fourdee/DietPi/issues/635

**Comment by aliosa27** [comment]
Done!

**Comment by Fourdee** [comment]
@aliosa27 
Nice one, thanks 👍

**Pull request merged**
