### PR TITLE
General | Improve/Fix IPv6 handling

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready
🈯️ Jessie VM, dietpi-update and dietpi-config all toggles
- [x] dietpi.txt entries
- [x] First run setup
- [x] Fix on patch
- [x] Changelog

**Reference**:
<s>- IPv6 support for Lighttpd + SSL: https://github.com/Fourdee/DietPi/issues/1840</s> **€: Separate PR**
- IPv6 disable method: https://github.com/Fourdee/DietPi/issues/2027

**Commit list/description**:
+ DietPi-Config | Move IPv6 handling to DietPi-Set_Hardware
+ DietPi-Config | Allow toggle IPv6 only, if not disabled on kernel level
+ DietPi-Config | Add toggle preferring IPv4, if IPv6 is enabled
+ DietPi-Config | Minor code and wording improvements
+ DietPi-Set_Hardware | Add improved/fixed IPv6 handling
+ DietPi-Set_Hardware | Add IPv4 preference toggle
+ dietpi.txt | (Re)add IPv4 preference and IPv6 toggle
+ DietPi-PreBoot | Add IPv6 + IPv4 first run setup
+ DietPi-PreBoot | Minor code improvements and rearrangement/simplification
+ DietPi-Patch | Allow user to decide, whether to keep IPv6 disabled on kernel level, or disable via sysctl instead
+ DietPi-Patch | Revert IPv4 preference removal
+ DietPi-Patch | Minor coding => line count reduction
+ Changelog entries
+ DietPi-Patch | Remove obsolete dietpi.txt entry on patch: "CONFIG_PREFER_IPVERSION"
+ DietPi-Patch | Syntax fix when G_WHIP_MENU is cancelled
+ DietPi-Set_Hardware | Whoopsie, want to write to dietpi.txt, not RPi's config.txt
+ DietPi-Config | Fix "iwgetid: command not found"
+ DietPi-Set_Hardware | Handle IPv6 specific /etc/hosts entries, when toggling IPv6
  - E.g. `/var/lib/dpkg/info/netbase.postinst` lists them as most common expected IPv6 entries
  - Ah great, DietPi-PREP already adds the same 👍.

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
Sorry, seems we worked on the same thing concurrently 🤣.

I also planned to re-enable IPv6 on kernel level for all devices. So this is already done.

But instead I added the other method, that does not imply the reported errors.

**Comment by Fourdee** [comment]
@MichaIng 

No worries lol 👍 

Basically, I wanted all IPv6 options removed, disabled the preferipversion function aswell, let the system automatically handle it.

But, feel free to change if needed.

**Comment by MichaIng** [comment]
@Fourdee 
I would still keep it, since there are these cases of unlimited connection attempts with IPv6 enabled (and IPv4 not preferred).

Also for e.g. privacy reasons and other things (reasonable or not), users might want to have IPv6 disabled.

Allow toggle IPv4 preference (performance + compatibility) as separate option now, both as first run setting in dietpi.txt and dietpi-config, to have it more consistent now.

**Comment by MichaIng** [comment]
@Fourdee 
G_WHIP issue

Anything changed on G_WHIP creation? The screen was way larger, so whiptail window could have been easily extended.

**Comment by Fourdee** [comment]
@MichaIng 

> Anything changed on G_WHIP creation? 

Not that I know of, unsure, probably some chars whiptail does like?

Copy and paste the command here with its text, i'll check.

**Comment by MichaIng** [comment]
@Fourdee 
See patch_file change. Quickcheck:
```
G_WHIP_MENU_ARRAY=(
0 'Re-enable IPv6 on kernel level, disable via sysctl instead (Recommended)'
1 'Keep IPv6 disabled on kernel level, I know what I am doing!'
)
G_WHIP_DEFAULT_ITEM=0
G_WHIP_MENU '[WARNING] IPv6 is disabled on kernel level\n
You disabled IPv6 via kernel module blacklist or boot cmd line. We also offered to do this via DietPi-Config.\n
Since more and more software requires and expects IPv6 kernel settings to be available, this might lead to APT install errors and worse.\n
For this we strongly advice to re-enable IPv6 on kernel level. However, instead IPv6 will be disabled for the interfaces on sysctl level.
You should not face any difference by following this advice, no IPv6 addresses will be assigned to your network devices.'
```
- Hmm strange, executing this directly on same machine after patch, works well 🤔. I retry the patch.
- ... retest: Above works well, `dietpi-update -1` looks ugly. Do we somehow overwrite something during patch?...
- ... even `wget https://raw.githubusercontent.com/Fourdee/DietPi/ipv6_handling/dietpi/patch_file`, and execute directly (`./patch_file 16`) also does NOT have the issue 🤔.
- **Found the issue: `./patch_file 16 > >(tee patch.log) 2>&1`** `tee` again, should have known it 😄.
- 🈯️ `./patch_file 16 | tee patch.log` works. Not sure about the redirection intentions.
- 🈴 `./patch_file 16 2>&1 | tee patch.log` ugly again
- 🈯️ `./patch_file 16 > >(tee patch.log)`
- 🈴 `./patch_file 16 &> >(tee patch.log)`

So whenever more/something else than `STOUT` is redirected to `tee` (subshell or not), G_WHIP has this issue. Not sure how to solve it best.

Direct test `G_WHIP_* $LONG_STRING 2>&1 | tee patch.log` works, also via tee subshell 🤔.
_______________
Debug code in `dietpi-globals`:
```
                WHIP_SIZE_X=$(( $(tput cols) - 6 ))
                echo "DEBUG: $WHIP_SIZE_X"
...
                WHIP_SIZE_Y=$(( $(tput lines) - 4 ))
                echo "DEBUG: $WHIP_SIZE_Y"
```
Result:
```
root@VM-Jessie:/tmp# ./patch_file 16 2>&1 | tee patch.log
DEBUG: 74
DEBUG: 20
...
root@VM-Jessie:/tmp# ./patch_file 16 | tee patch.log
DEBUG: 231
DEBUG: 67
```
- Error redirection shrinks terminal size to somehow a small default value.
```
root@VM-Jessie:/tmp# ./patch_file 16 2>&1
DEBUG: 231
DEBUG: 67
```
- Only in combination with `tee`.
_________________
Cleaner test:
```
root@VM-Jessie:/tmp# echo $(tput cols) $(tput lines) 2>&1 | tee
237 71
root@VM-Jessie:/tmp# ( echo $(tput cols) $(tput lines) ) 2>&1 | tee
80 24
root@VM-Jessie:/tmp# ( echo $(tput cols) $(tput lines) ) | tee
237 71
```
- Forwarding subshell/script output with merged STOUT to tee...

Strange, what else is redirected here...?
```
root@VM-Jessie:~# echo $(tput cols) $(tput lines) >(tee test.log) 2>&1
237 71 /dev/fd/63
root@VM-Jessie:~# (echo $(tput cols) $(tput lines)) >(tee test.log) 2>&1
-bash: syntax error near unexpected token `>(tee test.log)'
root@VM-Jessie:~# (echo $(tput cols) $(tput lines)) >(tee test.log)
-bash: syntax error near unexpected token `>(tee test.log)'
root@VM-Jessie:~# (echo $(tput cols) $(tput lines)) 2>&1
237 71
```
- `/dev/fd/63` seems to be a temporary subterminal that is somehow printed through tee as well:
```
root@VM-Jessie:~# l /dev/fd/
total 0
lrwx------ 1 root root 64 Oct  1 17:32 0 -> /dev/pts/0
lrwx------ 1 root root 64 Oct  1 17:32 1 -> /dev/pts/0
lrwx------ 1 root root 64 Oct  1 17:32 2 -> /dev/pts/0
lr-x------ 1 root root 64 Oct  1 17:32 3 -> /proc/6995/fd
```
- Redirection from subshell output to another subshell input does not seem to work. Piping works instead (see above), but terminal size info gets lost on the way.

**Comment by MichaIng** [comment]
Further reading: https://stackoverflow.com/questions/21763397/curious-tput-behavior-with-stderr-redirection
- Did not yet verify, but this leads to not `tee` doing something wrong, but `tput` not being able to read terminal sizes, if STOUT and STERR are both redirected. Piping itself is redirection of STOUT, which alone would still allow tput to read STERR, but with 2>&1 also STERR is redirected (in our case to tee), so `tput` cannot read terminal values from any stream.
- Seems that In case of `script 2>&1 ...`/`( subshell ) 2>&1 ...` redirection is done directly from/on each command within the script/subshell before the internal `tput` can even catch a stream. Understanding shell stream mechanic...
- So yeah we need to leave STERR stream, when calling a script (with internal tput/G_WHIP calls) and pipe output to somewhere else. Otherwise, if not possible/unwanted, we would need to e.g. export tput cols/lines values in the parent script to check and take by G_WHIP, instead of calling tput in subscript.
________
```
tput cols
128
tput cols > file
cat file
128
tput cols > file 2> /dev/null
cat file
80
```
- Jep, so `tput` need either STOUT or STERR. If both are redirected and/or piped, it seems it can even internally not catch it's output any more, which it needs to catch terminal size. Then defaults cols=80, lines=24 are used.
- Somehow funny, that it cannot internally read those values directly into a variable. The streams are redirected perhaps before it internally can redirect. But output is still empty (visually), so maybe just some invisible/overwriteable dummy "chars".
- My brain is broken now 🤣. Solutions/workarounds possible as mentioned above.

**Comment by MichaIng** [comment]
@Fourdee 
Added separate issue about the above G_WHIP problem: https://github.com/Fourdee/DietPi/issues/2105

It's unrelated to the PR, which is ready to merge from my side.

**Comment by Fourdee** [comment]
@MichaIng 

Many thanks 👍

**Pull request merged**
