### PR TITLE
DietPi-Software | Node.js uninstall cleanup; useradd nologin fix; consistency

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Software | Merge Uninstall_Software_Finalize() into Uninstall_Software()
+ DietPi-Software | npm call consistency
+ DietPi-Software | useradd consistancy: group is added automatically; /usr/sbin/nologin is only available nologin bin
+ DietPi-Software | Remove users home directory as well, when removing users
+ DietPi-Software | Node.js: On uninstall, remove the unbelievable amount of left files across system

Hijack:
+ DietPi-Software | Plax/Transmission: Allow access for download managers and media software, by running the services as "dietpi" group
  - And updated x86 Plex download to current version 1.13.8
+ DietPi-Patch | Run Transmission and Plex Media Server as "dietpi" group
+ Changelog entry
+ DietPi-Software | Whoopsie, add directories first, before placing files inside and remove them on uninstall

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
`useradd ... -s $(which nologin)` would be even more failsafe? On the other hand, /usr/sbin/nologin is really used for all other pre-installed system users...
__________
And could you verify that on ARM, Plex is as well installed with systemd service?

**Comment by Fourdee** [comment]
@MichaIng 

> which nologin

Yep, good call 👍 

> And could you verify that on ARM, Plex is as well installed with systemd service?

Yep:
```
root@DietPi:~# systemctl status plexmediaserver.service -l
● plexmediaserver.service - Plex Media Server for Linux
   Loaded: loaded (/lib/systemd/system/plexmediaserver.service; disabled; vendor
 preset: enabled)
   Active: active (running) since Sun 2018-10-07 05:17:08 BST; 46s ag
o
```

--- 

Interesting, current dev branch:
```
[ SUB2 ] DietPi-Process_tool > Apply
pgrep: only one pattern can be provided
Try `pgrep --help' for more information.
[FAILED] DietPi-Process_tool | Plex Media Server () : Affinity  0-5
[FAILED] DietPi-Process_tool | An issue has occurred
```

Sending commit to fix.

**Comment by Fourdee** [comment]
@MichaIng 

Great work, looks good 👍 

Lets merge for testing.

**Comment by Fourdee** [comment]
Install test ARMv7/8:
- 🈯️ Plex
- 🈯️ Transmission

Use test:
- 🈯️ Download something to play from transmission to ```downloads```
- 🈯️ Run in plex


@MichaIng 

Works a charm, great work 👍

**Pull request merged**
