### PR TITLE
Beta > Release

### PR DESCRIPTION
**Pull request by Fourdee**
**v6.18**
(26/11/18)

**Changes / Improvements / Optimisations:**
 - General | Concurrent execution detection: Now has a 5 second buffer to wait for exit (G_INIT_WAIT_CONCURRENT), before failing: https://github.com/Fourdee/DietPi/issues/2159#issuecomment-433619721
 - DietPi-Config | Added support for changing the brightness of the RPi touchscreen: https://github.com/Fourdee/DietPi/issues/2169
 - DietPi-Config | Added support for setting Xorg DPI scale.
 - DietPi-Services | MariaDB: DietPi now uses the pre-installed "mariadb" systemd service instead of obsoleve "mysql" init.d service: https://github.com/Fourdee/DietPi/pull/2196
 - DietPi-Software | Nextcloud Talk video calls with configured TURN server is now available for install: https://github.com/Fourdee/DietPi/pull/2197
 - DietPi-Software | NAA Daemon: Added installation support for ARMv8 and x86_64. Thanks Jussi!
 - DietPi-Software | Pi-hole: During (re)install you can now decide whether to show a blocking page to clients or not: https://github.com/Fourdee/DietPi/issues/2007
 - DietPi-Software | MotionEye: Now available to install for all devices. Removed support from Jessie: https://github.com/Fourdee/DietPi/issues/2229
 - DietPi-Software | G_BACKUP_FP: New feature rolled out to MPD and web server base DietPi-Software installations, in which config files are backed up before DietPi overwrites them: https://github.com/Fourdee/DietPi/issues/2187#issuecomment-433626639
 - DietPi-Software | SickRage: Is no longer available for installation. We will asses a replacement in v6.19. Sonarr is an excellent alternative with faster performance and stability.: https://github.com/Fourdee/DietPi/issues/2239
 - DietPi-Software | Docker: Now runs under 'simple' service type (previously 'notify'), to prevent service start delay which can occur on ARM based devices (eg: RPi), from delaying other applications starting on the system: https://github.com/Fourdee/DietPi/issues/2238#issuecomment-439474766
 - DietPi-Software | Mosquito: Service updated to systemd: https://github.com/Fourdee/DietPi/issues/2243
 - DietPi-Software | Radarr/Sonarr/Lidarr: logs (both .txt and .db*) have been moved to DietPi-RAMlog: https://github.com/Fourdee/DietPi/issues/2223
 - DietPi-Software | Pydio: WebUI warnings (security, performance) are now resolved for Nginx and Lighttpd webservers as well. Separate config files are created instead of touching the defaults, to enable required settings for Pydio only. Required PHP modules are installed and enabled, to be failsafe. Preserve existing install dirs on (re)install and inform user to update via WebUI updater: https://github.com/Fourdee/DietPi/issues/1913
 - DietPi-Software | Grafana: Existing database/plugin directory and admin password is now preserved on reinstall: https://github.com/Fourdee/DietPi/issues/2267
 - DietPi-Software | Syncthing: Updated installer to always pull the latest release and better handle existing installs. Thanks to @joaofl for bringing this to our attention.
 - DietPi-Software | Tautulli: Install enabled for ARMv8 devices.

**Bug Fixes:**
 - PREP: Resovled an issue where master.zip would always be downloaded, regardless of selected branch.
 - PREP: Resolved failed rootFS resize: https://github.com/Fourdee/DietPi/issues/2181#issuecomment-433715556
 - General | Resolved various gwtcwd errors during boot and software installations on VM: https://github.com/Fourdee/DietPi/issues/2237
 - General | NanoPi Fire3: Resolved an issue with blank HDMI output. Device is now switched to tty2 during boot, as a workaround/fix due to tty1 failing: https://github.com/Fourdee/DietPi/issues/2225
 - General | Resolved an issue, where entering passwords via our internal whiptail password box leads to "invalid match", when special characters are used, forcing a retry: https://github.com/Fourdee/DietPi/issues/2215#issuecomment-437683709
 - DietPi-Cleaner | Resolved an issue where test runs on -dev package removal, would remove the packages.
 - DietPi-Cleaner | Resolved a syntax error with function 'Run_Cleaners', disabling the ability to run cleaners. Many thanks to @optio50 for reporting this issue! https://github.com/Fourdee/DietPi/issues/2241
 - DietPi-Config | Resovled an visual error when selecting network options due to 'G_CHECK_VALIDINT'.
 - DietPi-Config | Locale: Resolved an issue where DietPi would always display en_GB as the current locale: https://github.com/Fourdee/DietPi/issues/2216#issuecomment-435599419
 - DietPi-Config | Resolved an issue where on Odroid C1/2 with current kernel 3.5" LCD shield does not work anymore. Thanks to @Kreeblah for reporting this issue and solution: https://github.com/Fourdee/DietPi/issues/2256
 - DietPi-Automation | CONFIG_NTP_MODE is now applied after APT cache, and, initial time sync is updated. Due to packages required for some modes: https://github.com/Fourdee/DietPi/issues/2181#issuecomment-433444882
 - DietPi-Software | Resolved an issue where rsyslog APT installation would report a failure, if service was already running previously but not installed via APT (mostly in backup/restore situations): https://github.com/Fourdee/DietPi/pull/2277/#issuecomment-441461982
 - DietPi-Software | Kodi: Resolved an issue where restart/shutdown options were not visable, due to lack of systemd-logind: https://github.com/Fourdee/DietPi/issues/2155
 - DietPi-Software | Mono applications (Radarr/Sonarr/Lidarr/Jackett): Rolled out "-O=-aot" (ahead of time optimzation) to all applications, which resolves a known external bug with recent Mono update. Many thanks to @Generator for testing and confirming this issue: https://github.com/Fourdee/DietPi/issues/2219#issuecomment-437594645
 - DietPi-Software | Roon Bridge: Resolved an issue where the remote update would fail due to underpriv permissions: https://community.roonlabs.com/t/dietpi-allo-units-not-getting-the-roonbridge-b167-update-from-b164/52503/6
 - DietPi-Software | Nextcloud: Resolved an issue with failed installation: https://github.com/Fourdee/DietPi/issues/2184
 - DietPi-Software | Nextcloud/Owncloud: Resolved an issue where userdata located on external drive would fail the installation: https://github.com/Fourdee/DietPi/issues/2221
 - DietPi-Software | OMPD/MyMPD: Resolved inability to update database. Currently we have rolled back the versions of these programs to a working state. We will investigate with the devs to find out the cause for future release: https://github.com/Fourdee/DietPi/issues/2156
 - DietPi-Software | Jackett: Resolved an issue where reinstall created an additional nested install dir. Thanks @msdos for reporting this issue: https://github.com/Fourdee/DietPi/issues/2212
 - DietPi-Software | RoonServer: Resolved an issue where reinstall created an additional nested install dir. Since RoonServer has an automated internal updater, download and install will be skipped, if install already exists.
 - DietPi-Software | PHP/databases: Resolved an issue where PHP database modules were not installed, when installing a new database and PHP was already installed before.
 - DietPi-Software | PHP: On Buster, moved to PHP7.3, since php-apcu and php-redis are not available for PHP7.2 any more. This resolves both PHP versions being installed concurrently.
 - DietPi-Software | OpenBazaar: Resolved an issue where remote OB clients could not connect to server with default configuration: https://github.com/Fourdee/DietPi/pull/2224
 - DietPi-Software | Resolved an issue where a global password with special characters lead to failing installs, due to missing escaping within our internal function G_CONFIG_INJECT. Thanks to @MistahDarcy for reporting this issue: https://github.com/Fourdee/DietPi/issues/2215
 - DietPi-Software | Docker: Resolved an issue where the Docker daemon failes to start due to invalid command argument. Thanks to @mspieth376 for reporting this issue: https://github.com/Fourdee/DietPi/issues/2238
 - DietPi-Software | Grafana: Resolved an issue, where WebUI password is not applied correctly, when containing ";" or "#". Thanks to @Warmbadger for reporting this issue and solution: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5248
 - DietPi-Software | Tautulli: Resolved an issue where Tautulli service failed to start up. As well improved reinstall, if install dir is already existent. Thanks to @Comfubar for reporting this issue: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5256
 - DietPi-Obtain_network_details | Resolved a tiny visual-only error message on non-root logins. Thanks to @AndrewZ for reporting: https://dietpi.com/phpbb/viewtopic.php?f=9&t=5194
 - DietPi-Update | Resolved a visual-only issue, where wrong RC versions could have been shown during incremental patching: https://github.com/Fourdee/DietPi/issues/2190

As always, many smaller code performance and stability improvements, visual and spelling fixes have been done, too much to list all of them here. Check out all code changes of this release on GitHub: https://github.com/Fourdee/DietPi/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+base%3Amaster

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
Please wait for Tautulli fix. Is nearly done, just changelog missing.

**Comment by Fourdee** [comment]
@MichaIng 

👍 

Putting release for tomorrow, want to run some final checks on (+ my changes):
https://github.com/Fourdee/DietPi/pull/2274

And general testing.

**Comment by Fourdee** [comment]
All testing passed, will release.

**Comment by MichaIng** [comment]
@Fourdee 
Jep, go from my side. Also did some rough tests, everything works fine 👍.

**Pull request merged**
