### PR TITLE
DietPi-Bugreport/Survey | Rework

### PR DESCRIPTION
**Pull request by MichaIng**
As this topic is kinda essential, I think we should have this done before v6.9 release.

- [x] Adjust upload method: SFTP
- [x] Adjust DietPi-Survey accordingly
- [x] Add 1st run and patch G_WHIP about DietPi-Survey opt-in/out

+ DietPi-Bugreport | Remove bug ID, to simply overwrite any old bug report on server, the content does not change based on the bug
+ DietPi-Bugreport | Write commands output to single file first, which will be added then to file list
+ DietPi-Bugreport | Add all files at once to archive, which should be faster and lead to smaller file
+ DietPi-Bugreport | Switch to 7z for smaller archive
+ DietPi-Bugreport | Add error handling/message to all checks being done around uploading

Testing:
🈯️ VM Jessie
🈯️ VM Stretch
🈯️ VM Buster

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

> DietPi-Bugreport | Switch to 7z for smaller archive

I tried this, results in 80% smaller filesize, however, could not work out a way to ensure 7z keeps absolute filepaths in the compression.

EG, ends up with:
- /dietpi-backup
- instead of /DietPi/dietpi/dietpi-backup

**Comment by MichaIng** [comment]
@Fourdee 
Jep, I also needed to play around until I found the right commands:
`- r` includes all files within folders recursively, but adds them without folder structure. In current case this broke execution, as we import e.g. `.bashrc` two times.
`7z a -spf` on the other hand works like `zip - r` does with zip command 😃.

**Review by Fourdee — APPROVED** [review]
👍

**Comment by Fourdee** [comment]
@MichaIng 

Looking good, impressive work 👍 

Feel free to merge when you are ready, i'll run some tests afterwards.

**Comment by MichaIng** [comment]
@Fourdee 
Okay, finished and merged for testing.

**Pull request merged**
