### PR TITLE
General | Switch from ntpd to systemd-timesyncd

### PR DESCRIPTION
**Pull request by MichaIng**
Issue: https://github.com/Fourdee/DietPi/issues/1580#issuecomment-370569005
Added branch to PR for easier discussion/overview 😃.

### CODE REVIEW

**Comment by MichaIng** [comment]
Note, when giving unreachable time server:
```
root@DietPi:~# systemctl status systemd-timesyncd
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
  Drop-In: /lib/systemd/system/systemd-timesyncd.service.d
           └─disable-with-time-daemon.conf
   Active: active (running) since Tue 2018-04-03 12:25:53 CEST; 6min ago
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 228 (systemd-timesyn)
   Status: "Idle."
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/systemd-timesyncd.service
           └─228 /lib/systemd/systemd-timesyncd

Apr 03 12:25:53 DietPi systemd[1]: Starting Network Time Synchronization...
Apr 03 12:25:53 DietPi systemd[1]: Started Network Time Synchronization.
Apr 03 12:25:54 DietPi systemd-timesyncd[228]: Network configuration changed, trying to establish connection.
root@DietPi:~# timedatectl status
      Local time: Tue 2018-04-03 12:32:28 CEST
  Universal time: Tue 2018-04-03 10:32:28 UTC
        RTC time: Tue 2018-04-03 10:32:35
       Time zone: Europe/Berlin (CEST, +0200)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no
```
`Active: active (running)` in place, no error message appears, `Status: "Idle."` and missing `synchronized` giving hint, but other errors (e.g. daemon not starting at all, broken systemd or any other) are not included. Scraping successful sync from `systemctl status` remains unsecure, `dbus` with short clear `timedatectl status` => ` synchronized: yes/no` remains best reliable check.
_________________________
Another note regarding sync speed:
```
Apr 03 12:45:29 DietPi systemd[1]: Stopping Network Time Synchronization...
Apr 03 12:45:29 DietPi systemd[1]: Stopped Network Time Synchronization.
Apr 03 12:45:29 DietPi systemd[1]: Starting Network Time Synchronization...
Apr 03 12:45:30 DietPi systemd[1]: Started Network Time Synchronization.
Apr 03 12:45:36 DietPi systemd-timesyncd[2760]: Synchronized to time server 192.168.178.1:123 (192.168.178.1).
Apr 03 12:45:36 DietPi systemd[1]: Time has been changed
Apr 03 12:45:40 DietPi dbus[257]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
Apr 03 12:45:40 DietPi systemd[1]: Starting Time & Date Service...
Apr 03 12:45:40 DietPi dbus[257]: [system] Successfully activated service 'org.freedesktop.timedate1'
Apr 03 12:45:40 DietPi systemd[1]: Started Time & Date Service.
Apr 03 12:46:25 DietPi dbus[257]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
Apr 03 12:46:25 DietPi systemd[1]: Starting Time & Date Service...
Apr 03 12:46:25 DietPi dbus[257]: [system] Successfully activated service 'org.freedesktop.timedate1'
Apr 03 12:46:25 DietPi systemd[1]: Started Time & Date Service.
```
- `systemd-timesyncd` finished synchronization a while before `dbus` react and `timedatectl` shows the updated status.

Second run, just doing `systemctl restart systemd-timesyncd`, showing 5s additional delay:
```
Apr 03 12:53:58 DietPi systemd[1]: Stopping Network Time Synchronization...
Apr 03 12:53:58 DietPi systemd[1]: Stopped Network Time Synchronization.
Apr 03 12:53:58 DietPi systemd[1]: Starting Network Time Synchronization...
Apr 03 12:53:58 DietPi systemd[1]: Started Network Time Synchronization.
Apr 03 12:53:58 DietPi systemd-timesyncd[2792]: Synchronized to time server 192.168.178.1:123 (192.168.178.1).
Apr 03 12:54:03 DietPi dbus[257]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
Apr 03 12:54:03 DietPi systemd[1]: Starting Time & Date Service...
Apr 03 12:54:03 DietPi dbus[257]: [system] Successfully activated service 'org.freedesktop.timedate1'
Apr 03 12:54:03 DietPi systemd[1]: Started Time & Date Service.
```
- This might be the reason for `run_ntpd status` to take that long. On SBC the delay of updating via dbus might be larger than on VM, leading to the unacceptable time found by @Fourdee : https://github.com/Fourdee/DietPi/issues/1580#issuecomment-370569005
- 'org.freedesktop.timedate1' looks again like this is mainly needed/used by desktop.

With this I am again on the side, using `systemctl status` with `Status: "Synchronized ` / `Status: "Using Time Server` (Jessie) and therefore heaving a careful look on if this changes: https://github.com/systemd/systemd/blob/master/src/timesync/timesyncd-manager.c#L678
- On searching a bid through systemd github, I found also `timedatectl` (still) under heavy rework: https://github.com/systemd/systemd/pull/8615
- Seems to be a quite "heavy" cycle: timesyncd -> dbus -> timedated, also check for other NTP services, so more a general frontend.

**Comment by Fourdee** [comment]
@MichaIng 

Great work 👍 , apologies this seems to been missed.

Ok, lets get this merged and i'll run some tests to compare it against NTPD

**Comment by Fourdee** [comment]
Sync times, by rebooting then logging in and running ```dietpi-software```
NB: with NTPD previously, I would get 7-15 seconds.

 ``` debian.pool.ntp.org```:
- Asus TB = 45 seconds
- VM = 30 seconds

Europe:
- Asus TB = 30 seconds
- VM = 60 seconds

pool.ntp.org:
- VM = 100 seconds

---

I'll try to debug and find out why its taking so long.

**Comment by Fourdee** [comment]
@MichaIng 

Appears time sync is done quickly, but ```timedatectl status``` takes a while to update. 

Hmm, ~does this effect it actually being applied to system~, or, an issue with ```timedatectl status``` itself?

```
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendo
r preset: enabled)
  Drop-In: /lib/systemd/system/systemd-timesyncd.service.d
           └─disable-with-time-daemon.conf
   Active: active (running) since Mon 2018-05-21 15:31:57 BST; 24s ag
o
     Docs: man:systemd-timesyncd.service(8)
 Main PID: 898 (systemd-timesyn)
   Status: "Synchronized to time server 129.70.132.34:123 (1.europe.pool.ntp.org
)."
   CGroup: /system.slice/systemd-timesyncd.service
           └─898 /lib/systemd/systemd-timesyncd

May 21 15:31:58 DietPi systemd-timesyncd[898]: No network connectivity, watching
 for changes.
May 21 15:32:00 DietPi systemd-timesyncd[898]: Network configuration changed, tr
ying to establish connection.
May 21 15:32:19 DietPi systemd-timesyncd[898]: Synchronized to time server 129.7
0.132.34:123 (1.europe.pool.ntp.org).
root@DietPi:~# timedatectl status
      Local time: Mon 2018-05-21 15:32:23 BST
  Universal time: Mon 2018-05-21 14:32:23 UTC
        RTC time: Mon 2018-05-21 14:32:24
       Time zone: Europe/London (BST, +0100)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no
root@DietPi:~# timedatectl status
      Local time: Mon 2018-05-21 15:32:36 BST
  Universal time: Mon 2018-05-21 14:32:36 UTC
        RTC time: Mon 2018-05-21 14:32:36
       Time zone: Europe/London (BST, +0100)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no
root@DietPi:~# timedatectl status
      Local time: Mon 2018-05-21 15:32:56 BST
  Universal time: Mon 2018-05-21 14:32:56 UTC
        RTC time: Mon 2018-05-21 14:32:57
       Time zone: Europe/London (BST, +0100)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

---

The issue is ```timedatectl ```, system time has been applied, however, this takes at least another 20+ seconds to correctly verify time synced.
I set the time to 1:00:00 before rebooting system ```date +%T -s "1:0:0"```
```
root@DietPi:~# cat date
Boot date Mon 21 May 01:00:32 BST 2018


root@DietPi:~# timedatectl status
      Local time: Mon 2018-05-21 15:39:00 BST
  Universal time: Mon 2018-05-21 14:39:00 UTC
        RTC time: Mon 2018-05-21 14:39:00
       Time zone: Europe/London (BST, +0100)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no
```

**Comment by MichaIng** [comment]
@Fourdee 
> Great work 👍

Ehm, this branch was created by you once, I just made a PR out of it for better discussion/testing as stated above 😆.
However I fixed conflicts regularly to avoid having to do too much one time to go on with it 😉.

Hope, code is still valid, but looks good, just patch_file addition needs to move to current version 😛.

> Appears time sync is done quickly, but timedatectl status takes a while to update.

Yes I watched this as well. `dbus` + `timedated` seems to be an additional layer on top of `timesyncd`. On my tests it was just some additional seconds, not as much as on your tests, but that an additional service (timedated) is actually started on top (can be watched on htop) which does not more than getting and setting `timesyncd` is for me already an argument to ignore or drop it and just go with/check `timesyncd` status, even if scraping `systemctl status systemd-timesyncd` does not look as safe as `timedatectl`. Also the latter changed it's output on Buster, so that it needed to be adjusted. No 100% safety possible anyway.

For my impression we should install dbus (to enable timedatectl) only, if this was chosen to be in daemon mode. In that case users might expect timedatectl command.
For mode <`4` I would skip it and `systemctl status systemd-timesyncd | grep -q '^[[:blank:]]*Status: "Synchronized to time server'`

**Comment by Fourdee** [comment]
@MichaIng 

> buster

Does buster report the pool server, only when synced? If so, we could run a scrape for current pool server as detection of sync using ```systemctl status systemd-timesyncd```
```
May 21 15:41:46 DietPi systemd-timesyncd[878]: Synchronized to time server 185.4
1.243.30:123 (1.europe.pool.ntp.org).
```

**Comment by MichaIng** [comment]
@Fourdee 
See edit above: `systemctl status systemd-timesyncd | grep -q '^[[:blank:]]*Status: "Synchronized to time server'`
- Is safer, as the log tail might contain older successful sync, while currently error occurred.

**Comment by Fourdee** [comment]
@MichaIng 

Maybe we could simply run the binary and control it manually? :D
```
root@DietPi:~# /lib/systemd/systemd-timesyncd
Timed out waiting for reply from 80.254.4.222:123 (0.europe.pool.ntp.org).
Timed out waiting for reply from 213.5.39.34:123 (0.europe.pool.ntp.org).
Synchronized to time server 178.136.117.33:123 (0.europe.pool.ntp.org).
```

Runs in blocking mode, but we can run it as a BG thread then check scrape for completion, then terminate process

Lets try with the service scrape 1st.

Ok so changes:
- dbus only for mode 4
- ```grep -q '^[[:blank:]]*Status: "Synchronized to time server' systemctl status systemd-timesyncd``` for sync completion check.

**Comment by MichaIng** [comment]
@Fourdee 
Actually I like the direct binary call. Didn't have a look into the service file so far, but going with bare native mode totally makes sense to me 👍.

**Comment by Fourdee** [comment]
@MichaIng 

> Actually I like the direct binary call. Didn't have a look into the service file so far, but going with bare native mode totally makes sense to me

Agree, but, seems a little overkill/last resort. Lets try the service 1st, let SystemD do its job.

**Comment by Fourdee** [comment]
@MichaIng 

Commits sent. Much better results. 4 seconds for VM 👍

**Comment by MichaIng** [comment]
Jessie fix: https://github.com/Fourdee/DietPi/commit/32a8cd00edac6c98736a9ef98c0398682bfa5bd6

**Pull request merged**
