### PR TITLE
DietPi-Software | Moonlight Qt : GUI game streaming client for Sunshine and NVIDIA GameStream

### PR DESCRIPTION
**Pull request by mtekman**
This is based on PR https://github.com/MichaIng/DietPi/pull/6303 as discussed here https://github.com/MichaIng/DietPi/pull/6303#issuecomment-1520465353

### CODE REVIEW

**Comment by MichaIng** [comment]
So this can run with full KMS, but only from console, or with fake KMS from desktop. I guess it could even run from desktop as well, but would need to be forced to run in DRM/KMS mode. I'll run some tests.

**Comment by mtekman** [comment]
> I guess it could even run from desktop as well, but would need to be forced to run in DRM/KMS mode. 

Are you referring to the `H264_DECODER_HINT=h264_v4l2m2m DRM_FORCE_DIRECT=1 moonlight-qt` command from [here](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4)

>  I'll run some tests.

Appreciated!

**Comment by MichaIng** [comment]
> Are you referring to the `H264_DECODER_HINT=h264_v4l2m2m DRM_FORCE_DIRECT=1 moonlight-qt` command from [here](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4)?

Yes, or something like the `-platform` CLI options of Moonlight embedded.

**Comment by MichaIng** [comment]
I tried starting it from console on RPi 2 with fKMS and KMS, with and without `H264_DECODER_HINT=h264_v4l2m2m DRM_FORCE_DIRECT=1`. In all cases, it starts up, but it has a large black border at the top with overlays parts of the GUI. However, it auto-detects the Sunshine server. I can pair it and connect, then select the Desktop app there, but it starts and stops immediately... Ah lol, now when I tried the exact same from SSH, it suddenly worked. Again, here I finish the text from keyboard and monitor attached to the RPi.

This was with full KMS and without any environment variable. It tells me on the SSH console that I should switch to fKMS and/or apply the `rpivid-v4l2` overlay. But it does steam now.
```
00:00:03 - FFmpeg: [hevc_v4l2m2m @ 0x2940c20] v4l2 output format not supported
00:00:03 - FFmpeg: [hevc_v4l2m2m @ 0x2940c20] Could not find a valid device
00:00:03 - FFmpeg: [hevc_v4l2m2m @ 0x2940c20] can't configure decoder
00:00:03 - FFmpeg: [hevc_v4l2m2m @ 0x2940c20] V4L2 Codec end
00:00:03 - FFmpeg: V4L2 Context destroyed
00:00:03 - SDL Error (0): Unable to open decoder for format: 100
00:00:03 - SDL Error (0): Unable to load FFmpeg decoder
00:00:03 - SDL Info (0): V-sync disabled
00:00:03 - SDL Error (0): Full KMS Mode is enabled! Hardware accelerated H.264 decoding will be unavailable!
00:00:03 - SDL Error (0): Change 'dtoverlay=vc4-kms-v3d' to 'dtoverlay=vc4-fkms-v3d' in /boot/config.txt to fix this!
00:00:03 - SDL Warn (0): Raspberry Pi HEVC decoder is not enabled! Add 'dtoverlay=rpivid-v4l2' to your /boot/config.txt to fix this!
00:00:03 - SDL Info (0): Using SDL renderer
```

**Comment by MichaIng** [comment]
FFmpeg is used for hardware accelerated video decoding, actually. Shall we install it OOTB?
```sh
aSOFTWARE_DEPS[$software_id]=7
```

**Review by MichaIng — DISMISSED** [review]

**Comment by MichaIng** [comment]
@mtekman 
The README actually shows the name "Moonlight PC": https://github.com/moonlight-stream/moonlight-qt
Shall we use that as well? It might be a little confusing since we currently offer the APT packages for RPi only, where "PC" is just a misleading term 🤔. On the other hand, "Moonlight" is shown on their GitHub repo and website as "Moonlight Embedded": https://moonlight-stream.org/

I'm wondering whether we should use own names to make the difference pretty clear, like "Moonlight (CLI)" and "Moonlight (GUI)" or so, to make sure that one is a pure CLI variant and the other is a pure GUI variant? Or follow the official naming from their repos? Or just ask THEM for a preference? 🙂

**Comment by MichaIng** [comment]
Okay, let's do it that way. Usually I'm for following the developers/manufacturers official naming but in this case it is confusing indeed, especially as long as we offer the RPi compatible packages only.

**Pull request merged**
