### PR TITLE
DietPi-Config | Correctly disable IPv6 on x64 devices

### PR DESCRIPTION
**Pull request by MichaIng**
https://github.com/Fourdee/DietPi/issues/1343#issuecomment-359652751
Tested: Ready to merge

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

If i remember correctly, any changes to default grub, won't take effect until grub is updated on system?: https://github.com/Fourdee/DietPi/blob/41c8724234b8a88be1085e9c9b9c0c7858da6b59/dietpi/dietpi-config#L3132

eg:
```
#Make changes to default grub file

#Update

root@DietPi:~# update-grub
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.9.0-5-amd64
Found initrd image: /boot/initrd.img-4.9.0-5-amd64
Adding boot menu entry for EFI firmware configuration
done
```

**Comment by Fourdee** [comment]
Need to prevent dupes and set default during ```set-core_env```, i'll edit PR:
```
root@DietPi:~# cat /etc/default/grub | grep LINUX
GRUB_CMDLINE_LINUX_DEFAULT="quiet"
GRUB_CMDLINE_LINUX="net.ifnames=0"
#GRUB_DISABLE_LINUX_UUID=true
root@DietPi:~# sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"/GRUB_CMDLINE_LINUX_DEFAULT=\"ipv6.disable=1 /' /etc/default/grub
root@DietPi:~# cat /etc/default/grub | grep LINUX  
GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1 quiet"
GRUB_CMDLINE_LINUX="net.ifnames=0"
#GRUB_DISABLE_LINUX_UUID=true
root@DietPi:~# sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"/GRUB_CMDLINE_LINUX_DEFAULT=\"ipv6.disable=1 /' /etc/default/grub
root@DietPi:~# cat /etc/default/grub | grep LINUX  
GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1 ipv6.disable=1 quiet"
GRUB_CMDLINE_LINUX="net.ifnames=0"
#GRUB_DISABLE_LINUX_UUID=true
root@DietPi:~# sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"ipv6.disable=1 /GRUB_CMDLINE_LINUX_DEFAULT=\"/' /etc/default/grub
root@DietPi:~# cat /etc/default/grub | grep LINUX  
GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1 quiet"
GRUB_CMDLINE_LINUX="net.ifnames=0"
#GRUB_DISABLE_LINUX_UUID=true
root@DietPi:~# sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"ipv6.disable=1 /GRUB_CMDLINE_LINUX_DEFAULT=\"/' /etc/default/grub
```

**Review by Fourdee — APPROVED** [review]
👍

**Comment by Fourdee** [comment]
Additional changes done:
https://github.com/Fourdee/DietPi/commit/9ea78771b9f1cf59cabcedfe2a34880777a2e02a

**Comment by Fourdee** [comment]
+ core env update/reset:
https://github.com/Fourdee/DietPi/commit/f1af9294f07aab297a6a9de71d5af5332ebf0e01

**Comment by MichaIng** [comment]
@Fourdee 
Of course, totally forgot the grub-update 😄, thx.

I would still not disable IPv6 by default. There might be networks without IPv4 usage at all, so that SSH/internet is just possible, if IPv6 is enabled.
So as default case, it is okay to have something in between. Enabled IPv6 functionality (kernel/module), just in case it is needed to enable network at all for the SBC/machine, but prefer/force IPv4 usage for wget/apt, for the cases (like mine VMs), where IPv6 access tries, completely break/time out.
This should be the best 1st run compatibility possible. Just php readfile can break in these rare cases like mine, but this is not used on 1st run usually 😉.

If we really want to disable IPv6 by default, than we actually don't need to handle this apt/wget stuff at all, as it chooses IPv4 by default, if IPv6 is really off.

You accidentally switched grub adjustment on enable/disable, or do I mix something up? On disable IPv6, put `ipv6.disable=1` inside, on enable, remove it. Fixed by https://github.com/Fourdee/DietPi/pull/1421

**Comment by Fourdee** [comment]
@MichaIng 

> This should be the best 1st run compatibility possible.
If we really want to disable IPv6 by default, than we actually don't need to handle this apt/wget stuff at all, as it chooses IPv4 by default, if IPv6 is really off.

Yep agree, it should only be default if we have a automation entry in ```dietpi.txt``` to toggle enable ```ipv6```, then we can remove all the apt/wget stuff.
However, all v6.0 images would need to be redone with the updated boot code (runs prior to ```dietpi-update```), so for now, lets revert ipv6 disable on x86_64 and consider this for future + updated images.

**Pull request merged**
