### PR TITLE
DietPi-Software | Resolve port conflicts

### PR DESCRIPTION
**Pull request by Joulinar**
**Status**: Review
- [x] rTorrent: Test RPC socket connection with all webservers. Check if additional HTTP authentication is required on Lighttpd and Nginx, like done on Apache2. And check if it's possible to use the same `.rutorrent-htaccess` creation and authentication method on all webservers, using the securely hashed global software password. Currently we have a crazy mix of different methods on each webserver.
- [x] ~Koel: Test if it's possible to avoid interactive email and credentials input: https://github.com/koel/koel/issues/1302~
- [x] Koel: Implement .env-based port setting and socket-based database connection, if possible: https://github.com/koel/koel/issues/1303

**Reference**: https://dietpi.com/phpbb/viewtopic.php?t=8737

**Commit list/description**:
+ DietPi-Software | Mute new composer warning when being executed as root user
+ DietPi-Software | IceCast: Allow install on VM, there is zero reason to deny it
+ DietPi-Software | IceCast: Use global software password for web admin panel as well, but do not overwrite passwords that were already changed, to align with other software installs. The config file by default is only readable to root and icecast user, hence the (plain text) passwords should be considered safe enough.
+ DietPi-Software | IceCast: Fix DarkIce config so that it works with the default IceCast hostname "localhost". Remove the obsolete service config as well. Harden permissions of the config file so that only the root user can read the contained plain text global software password.
+ DietPi-Software | WebIOPi: On fresh installs, change port to 8002 to avoid conflict with IceCast
+ DietPi-Software | WebIOPi: Remove obsolete service enable step, which is controlled (i.e. disabled) by dietpi-services
+ DietPi-Software | WebIOPi: Align and enhance uninstall, especially remove forgotten webiopi-passwd binary as well
+ DietPi-Software | rTorrent: Switch to local RPC socket for ruTorrent => rTorrent connection
+ DietPi-Software | rTorrent: Do not override existing HTTP authentication files
+ DietPi-Software | rTorrent: Adjust ruTorrent config so that it connects via RPC socket to rTorrent and additionally protect the RPC URL via HTTP authentication on Lighttpd. Additionally the global software password is used instead of hardcoded "dietpi".
+ DietPi-Software | rTorrent: Instead of backing up the existing config file on reinstalls, and use the new ones, backup the new ones (with ".example" ending) and keep the existing ones effective.
+ DietPi-Software | rTorrent: On Apache, allow ruTorrent login with any user that has been added to the authentication file, so users can change it or add a second user.
+ DietPi-Software | rTorrent: On Nginx, use the global software password instead of hardcoded "dietpi" as default ruTorrent login password
+ DietPi-Software | rTorrent: On Nginx, use HTTP authentication for the RPC endpoint as well and use the safer "arp1" encryption of password with Nginx. It supports SHA256 (and SHA512) from Debian Buster on, which should then be used.
+ DietPi-Software | Firefox Sync Server: On fresh installs, change port to 5002 to avoid conflict with Shairport Sync
+ DietPi-Software | Firefox Sync Server: Update Git commit, use log identifier which is otherwise "gunicorn" and further harden systemd unit by using private /tmp and /var/tmp mounts.
+ DietPi-Software | Koel: Fix install due to wrong directory name. Also the downloaded archive now contains the assets, which hence do not need to be downloaded separately anymore.
+ DietPi-Software | Koel: Switch to port 8003 to avoid conflict with IceCast
+ DietPi-Software | Koel: Fix install which now requires the PHP SQLite module, even when MariaDB is used as database
+ DietPi-Software | Koel: Switch to MariaDB socket connection, via host=localhost (and port=0)
+ DietPi-Software | Koel: Generating the key is now included in koel:init, hence does not need to be done manually. However, we can scan the interactively chosen media directory.
+ DietPi-Software | Koel: Do artisan calls as Koel service users, which is a permissions check as well. Also change the service log identifier, so that it shows "Koel" instead of "phpX.Y" in journalctl
+ DietPi-Software | Koel: Simplify install now that frontend assets do not need to be compiled anymore
+ DietPi-Software | Koel: Use random password for database access instead of global software password. Users never need to deal with this password, it's for internal Koel > MariaDB access only.
+ DietPi-Software | OctoPrint: On fresh installs, change port to 5001 to avoid conflict with Shairport Sync
+ DietPi-Software | Quote all globs passed to G_AGP which must be expended function-internally and not on function call and additionally avoid asterisks where we know the exact file/directory path
+ DietPi-Software | Use G_EXEC in a few more cases

### CODE REVIEW

**Comment by MichaIng** [comment]
Many thanks. Firefox Sync Server and rTorrent listen on port 5000 as well btw 😅.

Shall we resolve all those overlaps? I'm for a conservative method, leaving the most used software at port 5000 and then based on usage 5001 ... 5003: https://dietpi.com/survey/#software

1. Shairport Sync (669): **5000**
2. OctoPrint (204): **5001**
3. ~rTorrent (105): **5002**~ **EDIT: => RPC socket**
4. Firefox Sync Server (89): **5002**

But we should not overwrite existing configs on reinstall but only apply this on new installs.

**Comment by Joulinar** [comment]
good idea to solve it. Probably we need to create an overview of ports and what applications connected to it. Just to don't lose the overview.

**Comment by MichaIng** [comment]
There are conflicts on port 8000 as well: WebIOPi, IceCast and Koel
- WebIOPi is not maintained anymore since 2015 and Python 2 only, so I'd simply remove it. There is a fork with Python 3 support, but it is not maintained since 2018 and lacks e.g. full RPi 4 support, same as the original then as well: https://github.com/thortex/rpi3-webiopi
Ah here is another fork with RPi 4 and Python 3 support: https://github.com/Freenove/WebIOPi

- IceCast (58): 8000
- Bitwarden_RS is already using 8001!
- WebIOPi (48): 8002
- Koel (25): 8003

At least we should add used network ports one as regular (searchable) text to the docs: https://github.com/MichaIng/DietPi-Docs/issues/388

**Comment by Joulinar** [comment]
ok it was intend as a small fix and turns into a larger restructuring 🤣 

At least good to start with the possibility to search for the ports. I was going the same way yesterday but I failed as it was not possible atm. For internal purposes, it might be good to maintain a global overview of all ports used. In case of new application, we could easily spot a free port number. Uhh it's getting bigger and bigger the more we are thinking on it 😜

**Comment by MichaIng** [comment]
We can add the ports to the software list in the wiki as well: https://github.com/MichaIng/DietPi/wiki/DietPi-Software-list

**Comment by Joulinar** [comment]
that might be a good and easy to manage idea

**Comment by Joulinar** [comment]
Uhh you are doing quite some rework on these software titles 👍

**Comment by MichaIng** [comment]
Mostly fixes, found while doing install tests 😄.

**Comment by nonnorm** [comment]
Should I change the IPFS API port away from 5001?

**Comment by MichaIng** [comment]
Yes, it should be **5003** then.

**Pull request merged**
