### PR TITLE
Beta v6.33.0

### PR DESCRIPTION
**Pull request by MichaIng**
### Beta v6.33.0
_(03/10/20)_

#### APT Changes
- DietPi-Globals | The G_FP_DIETPI_USERDATA variable has been removed. Variables cannot be used in every context, e.g. not in config files stored on GitHub or dietpi.com for download, its value "/mnt/dietpi_userdata" does not change and using the path literally allows slightly simplified and hardened coding.

#### Changes / Improvements / Optimisations
- DietPi-Login | Logins do not wait for DietPi-PostBoot to finish anymore, as this is not strictly required. On local console, DietPi-PostBoot processing output practically blocks login until finished or timed out and logins on any other console like SSH or serial do not require it. DietPi-PostBoot only checks for DietPi updates, starts background services and prints the pre-login banner to local console, nothing that is required for console usage.
- DietPi-Autostart | Autostart programs with a foreground process are now started as replacement for the DietPi-Login process via "exec" which saves 3-4 MiB RAM usage.
- DietPi-Software | When using an invalid input argument, dietpi-software now prints usage info to the terminal.
- DietPi-Software | The "dietpi" UNIX group has been made the primary group for all* services which ran with "Group=dietpi" before: Transmission, Mopidy, MiniDLNA, Airsonic, Plex Media Server, Emby Server, Medusa, Tonido, Blynk Server, SABnzbd, Koel, NZBGet. If the user (+group) is created by an external package or installer, the original primary group is kept as supplementary group to not possibly break access permissions to pre-created directories and files. *Only example from these changes is Deluge for now, since we don't want to run the separate web UI service with dietpi group permissions. In case of Tautulli, the dietpi group permissions are remove, since Tautulli does not require it.
- DietPi-Software | Bazarr: Companion application to Sonarr and Radarr, which manages and downloads subtitles based on your requirements, now available for install. Many thanks to @DiogoAbu for doing this suggestion: https://github.com/MichaIng/DietPi/issues/2045
- DietPi-Software | phpBB: New installs will be v3.3.1 now, existing instances won't be touched as updates need to be done manually through the internal update mechanism, which includes the mandatory database migration. Additionally new installs will now be places at /var/www/phpbb, the old location /var/www/phpBB3 is still handled gracefully, if existing.
- DietPi-Software | OctoPrint: The service runs now as user "octoprint", the Git branch directory has been moved to /opt/octoprint and /mnt/dietpi_userdata/octoprint is the run users home and hence config and data directory now. To apply these changes, OctoPrint is reinstalled with DietPi v6.33, which includes the Python 3 migration (see v6.32 changelog) on Buster and Bullseye systems. This implies that the CLI ("octoprint" command) needs to be executed as user "octoprint" to invoke the correct configuration. A bash shell alias solves this automatically for all users with sudo permissions, but if you use a custom shell, the CLI needs to be called like: "sudo -u octoprint octoprint <command>". Many thanks to @ModischFabrications for reporting an issue that is related to the fact that the service ran as root user before: https://github.com/MichaIng/DietPi/issues/3315
- DietPi-Software | Tautulli: Finally, directories, user and service are renamed from "plexpy" to "tautulli". Additionally it runs with Python 3 now instead of Python 2. These changes are applied as well during DietPi update.
- DietPi-Software | Baikal: Update (re)install procedure to cover the new config directory and use the pre-packed release archives instead of raw source and composer. Additionally webserver configs have been added to harden access permissions.
- DietPi-Software | Docker: On fresh installs or reinstalls, logs are now done with limited verbosity to systemd-journald (RAM), accessible via "journalctl -u docker -u containerd" to reduce disk writes. Docker can be reinstalled via "dietpi-software reinstall 162". Many thanks to @SaturnusDJ for doing this suggestion: https://github.com/MichaIng/DietPi/issues/2388
- DietPi-Software | Mosquitto: The official APT repository is now used where possible, which currently excludes ARMv8/arm64 and Raspbian/Debian Bullseye. This change is applied via reinstall during DietPi update. Many thanks to @marcobrianza for doing this suggestion: https://github.com/MichaIng/DietPi/issues/3042
- DietPi-Software | Cuberite: A wrong directory name based on a typo has been fixed. A reinstall updates Cuberite and moves its install directory to /mnt/dietpi_userdata/cuberite as intended. This is applied via DietPi update but a backup is created to cover issues due to potential structural changes, especially for older instances installed at /etc/cubrite.

#### Bug Fixes
- General | Resolved an issue where using AUTO_UNMASK_LOGIND=1 or enabling Amiberry fastboot did not allow to start systemd-logind as intended if the required dbus package was not installed before. Many thanks to @razerbann for reporting this issue: https://github.com/MichaIng/DietPi/issues/3770
- RPi | Resolved an issue where Allo USBridge Sig (ASIX AX88179) Ethernet fails due to non-matching driver. Many thanks to @dsnyder0pc for reporting this issue any many thanks to Allo for providing stable branch driver builds and a method to compare kernel module layouts: https://github.com/MichaIng/DietPi/issues/3725
- DietPi-Backup | Resolved an issue where F2FS was not supported as target location. Since it has full UNIX permissions and symlinks support and can be used as rootfs file system, it can be used for OS backups as well. Many thanks to @Cjkeenan for reporting this issue: https://github.com/MichaIng/DietPi/issues/606#issuecomment-695944450
- DietPi-Set_swapfile | Resolved an issue where swapon failed on ext4 due to an external bug in Linux 5.7 and 5.8. The script now tries quick and less write-intense fallocate pre-allocation first, regardless of kernel version and file system type, and falls back to dd in case of failure. Many thanks to @auanasgheps for reporting this issue: https://github.com/MichaIng/DietPi/issues/3756
- DietPi-Config | Resolved an issue where on devices with old Linux kernel versions (e.g. Sparky SBC with Linux 3.10.38) the Performance Options failed to open with a syntax error. Many thanks to @dsnyder0pc for reporting this issue: https://github.com/MichaIng/DietPi/issues/3799
- DietPi-Software | OpenTyrian: The autostart option and run script have been fixed and slightly enhanced to lower RAM usage a bid.
- DietPi-Software | Firefox Sync Server: Resolved an issue where the build failed due to missing MySQL/MariaDB headers, newly required. Many thanks to @kinoushe for reporting this issue: https://github.com/MichaIng/DietPi/issues/3774
- DietPi-Software | LXDE: Resolved several issues due to conflicts between the RPi desktop LXDE packages with native LXDE.
- DietPi-Software | Webmin: Worked around an issue where install failed. Webmin depends on apt-show-versions which does not support compressed APT list files, which be implemented as default with DietPi v6.32.
- DietPi-Software | WebIOPi: Resolved an issue where the download failed.
- DietPi-Software | Home Assistant: Resolved an issue where install failed on ARM due to missing new build dependency. Many thanks to @pbutterworth for reporting and @novitibo for providing the solution: https://dietpi.com/phpbb/viewtopic.php?f=11&t=8095
- DietPi-Software | Kodi: Resolved an issue on Odroid XU4 where install failed due to missing librockchip-mpp1 package which instead was aimed to be installed on Odroid N1 only.
- DietPi-Software | TigerVNC+LXDE: Resolved an issue where lxappearance start ("Customize Look and Feel") hangs within TigerVNC sessions.

### CODE REVIEW

**Comment by Joulinar** [comment]
@MichaIng 
you are reading my mind. I was already thinking if it would make sense to go for next release as there are already quite some changes 👍 

Should I already do some testing or wait until you have merged it into beta branch?

**Comment by MichaIng** [comment]
> Should I already do some testing or wait until you have merged it into beta branch?

As you like. I've finished everything I wanted for now. As always I'm going through all file changes again, but will finish that tomorrow. Too tired eyes to hope for finding syntax error, typos and such 😄.

**Comment by Joulinar** [comment]
first look on an empty RPi3B+
<details>
  <summary>Logfile attached. Click to expand!</summary>

```
root@DietPi3:~# G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=dev' /boot/dietpi.txt
[  OK  ] G_CONFIG_INJECT | Setting in /boot/dietpi.txt adjusted: DEV_GITBRANCH=dev
root@DietPi3:~# dietpi-update

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Checking for available DietPi update

[ INFO ] DietPi-Update | Checking mirror: https://raw.githubusercontent.com/MichaIng/DietPi/dev/dietpi/server_version-6
[  OK  ] DietPi-Update | Using update server: https://raw.githubusercontent.com/MichaIng/DietPi/dev/dietpi/server_version-6
[  OK  ] DietPi-Update | Update available:
[ INFO ] DietPi-Update | Current version : v6.32.2 (branch: MichaIng/master)
[ INFO ] DietPi-Update | Latest version  : v6.33.-1 (branch: MichaIng/dev)

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Checking for update pre-requirements

[  OK  ] DietPi-Update | DietPi-Userdata validation: /mnt/dietpi_userdata
[  OK  ] DietPi-Update | Free space check: path=/ | available=12289 MiB | required=100 MiB
[ SUB1 ] DietPi-Services > stop
[  OK  ] DietPi-Services | stop : cron

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Applying pre-patches

[  OK  ] DietPi-Update | Downloading pre-patch file
[  OK  ] DietPi-Update | Applying execute permission
[  OK  ] DietPi-Update | Successfully applied pre-patches

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Upgrading APT packages

[ INFO ] DietPi-Update | APT update, please wait...
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:2 https://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
Get:4 https://archive.raspberrypi.org/debian buster/main armhf Packages [331 kB]
Get:5 http://raspbian.raspberrypi.org/raspbian buster/contrib armhf Packages [58.7 kB]
Fetched 13.4 MB in 11s (1240 kB/s)
Reading package lists...
[  OK  ] DietPi-Update | APT update
[ INFO ] DietPi-Update | APT upgrade, please wait...
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 21064 files and directories currently installed.)
Preparing to unpack .../base-files_10.3+rpi1+deb10u6_armhf.deb ...
Unpacking base-files (10.3+rpi1+deb10u6) over (10.3+rpi1+deb10u4) ...
Setting up base-files (10.3+rpi1+deb10u6) ...
Installing new version of config file /etc/debian_version ...
Processing triggers for install-info (6.5.0.dfsg.1-4+b1) ...
[  OK  ] DietPi-Update | APT upgrade

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Installing new DietPi code

[  OK  ] DietPi-Update | Downloading update archive
[  OK  ] DietPi-Update | Unpacking update archive
[  OK  ] DietPi-Update | Installing new DietPi scripts
[  OK  ] DietPi-Update | Installing new DietPi system files
[  OK  ] DietPi-Update | Setting execute permissions for DietPi scripts
[ SUB1 ] DietPi-Set_software > verify_dietpi.txt ()
[  OK  ] DietPi-Set_software | Checking URL: https://raw.githubusercontent.com/MichaIng/DietPi/dev/dietpi.txt
[  OK  ] DietPi-Set_software | Downloading current dietpi.txt
[  OK  ] DietPi-Set_software | dietpi.txt verification completed
[  OK  ] verify_dietpi.txt  | Completed

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Applying incremental patches

[ INFO ] DietPi-Update | Current version : v6.32.2 (branch: MichaIng/master)
[ INFO ] DietPi-Update | Latest version  : v6.33.-1 (branch: MichaIng/dev)
[ INFO ] DietPi-Patch | Patching 6.32 to 6.33
[  OK  ] DietPi-Patch | Commenting "arm_freq_min" in config.txt until related system instabilities have been solved
[ INFO ] Updating ASIX AX88179 driver for kernel 5.4.51-v7+, as provided by allo.com:
[ INFO ] - https://github.com/allocom/USBridgeSig/tree/master/ethernet
[ INFO ] Estimating required module layout...
[ INFO ] Downloading driver...
################################################################################################################################################# 100.0%
[ INFO ] Installing driver...
removed '/lib/modules/5.4.51-v7+/kernel/drivers/net/usb/ax88179_178a.ko'
'/tmp/ax88179_178a.ko' -> '/lib/modules/5.4.51-v7+/kernel/drivers/net/usb/ax88179_178a.ko'
[ INFO ] Running depmod...
[ INFO ] Cleaning up...
removed '/tmp/ax88179_178a.ko'
[ INFO ] Updating ASIX AX88179 driver for kernel 5.4.51-v8+, as provided by allo.com:
[ INFO ] - https://github.com/allocom/USBridgeSig/tree/master/ethernet
[ INFO ] Estimating required module layout...
[ INFO ] Downloading driver...
#=#=- #    #
curl: (22) The requested URL returned error: 404 Not Found
[ INFO ] No matching stable branch driver found, trying master branch driver...
################################################################################################################################################# 100.0%
[ INFO ] Installing driver...
removed '/lib/modules/5.4.51-v8+/kernel/drivers/net/usb/ax88179_178a.ko'
'/tmp/ax88179_178a.ko' -> '/lib/modules/5.4.51-v8+/kernel/drivers/net/usb/ax88179_178a.ko'
[ INFO ] Running depmod...
[ INFO ] Cleaning up...
removed '/tmp/ax88179_178a.ko'
[  OK  ] DietPi-Software | Initialised database
[  OK  ] DietPi-Software | Reading database
[ SUB2 ] DietPi-Software > Automated reinstall
[ INFO ] DietPi-Software | 123: Mosquitto is not currently installed
[ INFO ] DietPi-Software | Use "dietpi-software install 123" to install Mosquitto.
[  OK  ] DietPi-Software | No changes applied for: Mosquitto
[ INFO ] DietPi-Patch | APT autopurge, please wait...
[  OK  ] DietPi-Patch | APT autopurge
[  OK  ] DietPi-Update | Incremental patching to v6.33.-1 completed

 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Completed

[ INFO ] DietPi-Update | Current version : v6.33.-1
[ INFO ] DietPi-Update | Latest version  : v6.33.-1
[  OK  ] DietPi-Survey | Purging survey data
[ SUB1 ] DietPi-Services > restart
[  OK  ] DietPi-Services | restart : cron
root@DietPi3:~#
```
</details>

Some errors on Allo driver update

**Comment by MichaIng** [comment]
> I guess it should be `1` instead of `-1`

I was thinking to go with this versioning concept:
- After master release: Raise subversion, set RC version to `-1`, i.e. after DietPi v6.33 release, dev branch version string will become `6.34.-1`. This assures that `dietpi-update -1` will not re-apply the v6.33 patches and pre-patches and when someone switches from master or beta to dev branch, an update is offered immediately.
- The first beta will always be RC version `0`, so before this is merged, it needs to be set to `0`.
- So basically the RC version of the master release shows the amount of beta cycles done for this release.

Open for other ideas, I just wanted to go with a consistent versioning throughout development/release cycles.
____________
> Some errors on Allo driver update

Yes that is expected. Probably we find a way to mute the error or add an info that it is expected, so leaving the informational part but avoid making users feel like something is not in order? It's this issue: https://github.com/MichaIng/DietPi/issues/3725
- Allo provides an updated ASIX AXsomething driver, an Ethernet chip that is used by [Allo USBridge Sig](https://allo.com/sparky/usbridge-signature-pcb.html), which solves bad experience with this Ethernet chip on ARM devices in general.
- The driver comes from ASIX themselves but something prevents it from being merged into Linux upstream and since it contains large changes, difficult to compare with the old (x86-optimised) one, RPi devs refuse to merge it when not coming through Linux upstream.
- So to make `USBridge Sig` running well, Allo provides own kernel module driver builds for this chip. This needs to be redone with every kernel release and Allo does this moreless regularly based on the current RPi firmware master branch for ARMv7 and ARMv8: http://3.230.113.73:9011/Allocom/USBridgeSig/
- But sometimes RPi devs do multiple firmware commits with the same Linux version and in cases these require a different kernel module layout, means Allo needs to rebuild their modules but the kernel version string stays the same. So either they break the previous master firmware version or have a module which is incompatible with the final stable release (which is shipped via APT package), which is what happened, hence the GitHub issue.
- I'm not sure whether Allo got my point there that instead of building their module on unstable/dev master branch, they should prioritise on building them based on stable release branch, which is used by all RPi OS users by default as well. However they now started to build those separately: http://3.230.113.73:9011/Allocom/USBridgeSig/stable_rel/
- One issue apparent is that those do not contain ARMv8 builds (yet). And still, we cannot know reliable whether a user runs a stable kernel/firmware release, or has updated via `rpi-update`, e.g. to test or solve a certain issue.
- So what we are doing now is trying to download a matching driver (matching by kernel string) for stable kernel first, check if the module layout machtes, if any of both fails, try with the one for dev/master kernel. Since at least for ARMv8 kernel and rpi-updated kernels there is no stable module build, this will always fail with 404 intentionally. Since the script is meant to run on all APT packaged kernel upgrades, or when external updaters call `/etc/kernel/postinst.d/`, we cannot call DietPi-Globals there to mask the actual command output with nice messages. So to not loose the ability to be informed and debug unexpected errors, from what I can think of we need to leave the expected error messages. So best I can think of currently is to add another message that curl 404 errors are expected and no reason to worry, since in worst case the default ASIX driver will stay in place, and most of the users won't even use that chip at all 😉.

**Comment by MichaIng** [comment]
Okay version is now `6.33.0`, I fine tuned the ASIX update output a bid, but didn't want to add too much output, as this runs at least two times on every kernel upgrade.

Fine for a first beta round from my side, @Joulinar any issues from your side?

**Comment by Joulinar** [comment]
> After master release: Raise subversion, set RC version to -1, i.e. after DietPi v6.33 release, dev branch version string will become 6.34.-1. This assures that dietpi-update -1 will not re-apply the v6.33 patches and pre-patches and when someone switches from master or beta to dev branch, an update is offered immediately.

sounds logic, I was just wondering 😃 

> Fine for a first beta round from my side

yes fine for public beta

**Pull request merged**
