### PR TITLE
DietPi-Software | Home Assistant: Redo dependencies depending on architecture

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**ToDo**:
- [x] Check in which cases `libxcb1` is required: https://github.com/MichaIng/DietPi/pull/4809#issuecomment-937983327

**Commit list/description**:
+ DietPi-Software | Home Assistant: Redo dependencies depending on architecture

### CODE REVIEW

**Comment by MichaIng** [comment]
`x86_64` and I guess `aarch64` do not require any of these runtime libraries. I guess Pillow from PyPI has those libraries statically linked, which also explains the significantly larger wheel size (compared to piwheels builds):
- https://pypi.org/project/Pillow/#files
- https://piwheels.org/project/pillow/

piwheels also lists those as dependencies, even more (likely not strictly linked but required for additional image type support).

So far I however could not find a case where `libxcb1` was required 🤔.

**Comment by Joulinar** [comment]
side node. I guess pre-patch for the Debian SSL issue is obsolet?

```
 DietPi-Update
─────────────────────────────────────────────────────
 Phase: Applying pre-patches

[  OK  ] DietPi-Update | Downloading pre-patches
[  OK  ] DietPi-Update | Applying execute permission
[ INFO ] DietPi-Pre-patches | Connecting to deb.debian.org via plain HTTP once until latest OpenSSL has been installed: https://github.com/MichaIng/DietPi/issues/4795
[  OK  ] DietPi-Pre-patches | sed -i s|https://deb.debian.org|http://deb.debian.org| /etc/apt/sources.list
[  OK  ] DietPi-Update | Successfully applied pre-patches

```

**Comment by MichaIng** [comment]
> side node. I guess pre-patch for the Debian SSL issue is obsolet?

Yes, I'll replace it with Mosquitto and/or Webmin repo(s), if they do not solve it until Saturday.

**Comment by Joulinar** [comment]
hmm replicated again in my RPi3B+ ARMv7 Bullseye

```
Oct 08 00:37:05 DietPi3 systemd[1]: Started Home Assistant (DietPi).
Oct 08 00:37:22 DietPi3 homeassistant[16330]: 2021-10-08 00:37:22 ERROR (MainThread) [homeassistant.setup] Setup failed for image: Unable to import component: libxcb.so.1: cannot open shared object file: No such file or directory
```

**Comment by MichaIng** [comment]
Okay, required on all ARMv6 and ARMv7, I seemed to have checked it wrong on first test iteration.

**Pull request merged**
