### PR TITLE
META | Add script for distro upgrade to Bookworm

### PR DESCRIPTION
**Pull request by MichaIng**
#### However, we are happy for everyone testing it, so we can add more fixes and migration required for software configs, package changes etc, to make this script safer to use for future users.
_Currently, for a successful PHP migration, you need to move to DietPi `dev` branch as well._
```sh
G_DEV_BRANCH dev
bash -c "$(curl -sSf 'https://raw.githubusercontent.com/MichaIng/DietPi/dev/.meta/dietpi-bookworm-upgrade')"
```

Bookworm support and testing status: https://github.com/MichaIng/DietPi/wiki/Debian-Bookworm-testing

Best if you just want to test Bookworm, is to flash a Bookworm image freshly: https://dietpi.com/downloads/images/

### CODE REVIEW

**Comment by Joulinar** [comment]
ok did some testing:

- "empty" systems
✅ RPi 3B+ 32bit ARMv7
✅ RPi 4B 64bit ARMv8
✅ NanoPi R5S
✅ NanoPi R6S (already on Bookworm, was correctly detected 😉 )

One point we need to consider, the `failed to connect to bus` message on reboot. Something to be fixed or hide. 

- typical software installed
✅ RPi 4B 64bit ARMv8 (all *arr services)
✅ NanoPi R5S (Home Assistant)
❌ RPi 3B+ 32bit ARMv7 (NextCloud)
reinstall on PHP 8.1 packages is failing. We would need to adjust our install script to PHP 8.2 in generall 😉 
```
[FAILED] DietPi-Software | APT install for: php8.1-fpm php8.1-apcu php8.1-curl php8.1-gd php8.1-mbstring php8.1-xml php8.1-zip php8.1-mysql php8.1-redis
```
And NC 25 don't like PHP 8.2. There is a warning about incompatibility at the end of the reinstall process.

As a last step, we force a software reinstall of selected software title. There you will be asked to run a backup (again), next to the one executed before Bookworm upgrade. In most cases this will overwrite the initial Bullseye backup with Bookworm. If things go wrong on reinstall, you will not be able to restore to a point before the upgrade. Just as an idea: would it make sense to skip the second backup?

**Comment by Joulinar** [comment]
Some more test. My R5S was booting to fast leading to a conflict during login. Because on first login after upgrade, we force the `autopurge` which might run into a started `apt` package check. We might need to disable the `apt` package check on this initial first login after Bookworm upgrade. 🤔 

```
[ INFO ] Autoremoving leftover packages from Bookworm upgrade...
[ INFO ] APT autopurge, please wait...
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1211 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
[FAILED] APT autopurge
 - Command: apt-get -y autopurge
```

**Comment by MichaIng** [comment]
> reinstall on PHP 8.1 packages is failing. We would need to adjust our install script to PHP 8.2 in generall 😉

Already done on `dev` 😉.

> And NC 25 don't like PHP 8.2. There is a warning about incompatibility at the end of the reinstall process.

I added a patch in `dev` to make it compatible with PHP 8.2. There are some deprecation warnings, but otherwise it works fine (running my home server like this).

**Comment by MichaIng** [comment]
> OK might be a user issue. I had 2 sessions open reconnecting automatically same time, leading to two concurrent executions of the autopurge step. 🙄

Two things to enhance:
1. Skip step if non-root user is logging in
2. Remove script before running autopurge, so it cannot be called concurrently

**Comment by Joulinar** [comment]
actually it's failing right at the beginning

```
[ INFO ] DietPi-Update | APT update -f, please wait...
E: Command line option 'f' [from -f] is not understood in combination with the other options.
[FAILED] DietPi-Update | APT update -f
 - Command: apt-get -y -eany update -f
```

**Comment by MichaIng** [comment]
Transition freeze for Bookworm btw. has happened at schedule: https://lists.debian.org/debian-devel-announce/2023/01/msg00004.html

What I missed is that this (reasonably) does not stop in-progress transitions, which was true for PHP (8.1 => 8.2) and Python (3.10 => 3.11). Both transitions have now been completed, so both can now be tested reasonably:
- Test all PHP applications with PHP 8.2 on Bookworm
- Test all Python applications with Python 3.11 on Bookworm

In case of Python, ARMv6/7 need a special eye on, since piwheels does not ship wheels for Bookworm/Python 3.11 yet. Since the version is now however fixed, I'll check back with the piwheels maintainers whether support can be added already now, to allow early testing and smooth upgrades. Of course this adds significant additional load to their build servers, for probably a small audience.

**Comment by Joulinar** [comment]
ahh and I cancelled the install on the issue above. However the process continued

```
[FAILED] DietPi-Update | Unable to continue, DietPi-Update will now terminate.
[ INFO ] dietpi-bookworm-upgrade | Updating package lists
[  OK  ] dietpi-bookworm-upgrade | sed -i s/bullseye/bookworm/g /etc/apt/sources.list
[ INFO ] dietpi-bookworm-upgrade | Reverting some package lists which have no Bookworm suite
[  OK  ] dietpi-bookworm-upgrade | sed -i s/bookworm/bullseye/ /etc/apt/sources.list.d/raspi.list
```

**Comment by MichaIng** [comment]
Ah I see the issue.

**Comment by Joulinar** [comment]
some more issues along the way

```
[  OK  ] dietpi-bookworm-upgrade | APT dist-upgrade
/boot/dietpi/func/dietpi-globals: line 25: unset: G_PROGRAM_NAME: cannot unset: readonly variable
[  OK  ] dietpi-bookworm-upgrade | Congratulations, you are now on Bookworm:
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[ INFO ] dietpi-bookworm-upgrade | Running post upgrade migrations
```

and one more for a NC/Apache2 system

```
[ INFO ] dietpi-bookworm-upgrade | Running post upgrade migrations
[ SUB1 ] DietPi-Services > stop
[  OK  ] DietPi-Services | stop : cron
[  OK  ] DietPi-Services | stop : apache2
[  OK  ] DietPi-Services | stop : mariadb
[  OK  ] DietPi-Services | stop : redis-server
[  OK  ] dietpi-bookworm-upgrade | Setting in /root/.ssh/known_hosts adjusted: [ssh.dietpi.com]:29248 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJdEPlagpQ+RVHNOX3jkG1Bya7Oza1dAke8h8NszVW84
[FAILED] dietpi-bookworm-upgrade | a2dismod php7.4
 ERROR: Module php7.4 does not exist!
```

**Comment by Joulinar** [comment]
After the NC is not working/ running due to PHP8.2

```
This version of Nextcloud is not compatible with PHP>=8.2.
You are currently running 8.2.1.
```

**Comment by MichaIng** [comment]
Both issues fixed. One test I need to do:
- We use PHP-FPM since a while for Apache as well, so `mod_php` is not installed, which is why the command fails.
- We did however not enforce the transition. It was applied on reinstall only.
- So I need to test whether the module gets disabled automatically when the `libapache2-mod-php7.4` package is purged. It actually should be. This would render the step as well obsolete on Buster => Bullseye upgrade.

**Comment by StephanStS** [comment]
Did some tests with Proxmox-VMs:

- Basic console VM: ✅
- VM with node-red, NGINX, PHP, NFS client: ✅
- VM with X11 (Xfce): ✅
- VM with Plex Media Server: ✅
- VM with Nextcloud: ❌
  image
  (I keep it at this state for further investigations)

- VM with MQTT Server: ✅
- VM with X11 (Xfce) and many office applications (XSane, OpenOffice,...): ✅
- VM with X11 (Xfce) and many development applications (VSCodium, GitHub Desktop, KeePassXC, Atom, Firefox,...): ✅

- LXC container: ✅

I had only minor issues that sometimes apt update etc. hangs, a "retry" option of the scripts always helped.

**Comment by MichaIng** [comment]
@StephanStS 
Awesome, thanks for the many tests. On the failing Nextcloud reinstall, can you check the Redis service logs:
```sh
journalctl -u redis-server
```

**Comment by Joulinar** [comment]
tested NC/ Apache2 again on RPi 64bit again. Except one issue, it's working fine.

```
[  OK  ] dietpi-bookworm-upgrade | APT dist-upgrade
/boot/dietpi/func/dietpi-globals: line 25: unset: G_PROGRAM_NAME: cannot unset: readonly variable
[  OK  ] dietpi-bookworm-upgrade | Congratulations, you are now on Bookworm:
```

**Comment by MichaIng** [comment]
> /boot/dietpi/func/dietpi-globals: line 25: unset: G_PROGRAM_NAME: cannot unset: readonly variable

Good catch. It's actually unnecessary to load `dietpi-globals` again. It's sufficient to reload only the hardware model info file.

**Comment by Joulinar** [comment]
btw, do we really need to print `/etc/os-release`?

```
[  OK  ] dietpi-bookworm-upgrade | Congratulations, you are now on Bookworm:
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[ INFO ] dietpi-bookworm-upgrade | Running post upgrade migrations
```

Personally, the Congratulations message would be fine for me.

**Comment by MichaIng** [comment]
I thought it would be a nice verification. It was in the Bullseye upgrade guide, so I added it. But if you think it is unnecessary, we can remove it.

**Comment by Joulinar** [comment]
We can check with @StephanStS and Holger. At the end it is visual only, somewhere within the package update and reinstall phase.

**Comment by MichaIng** [comment]
You are right, the script moves on, so not much time to see this anyway. I thought about adding some halts to give time reviewing what has been done so far. E.g. after the upgrade itself:
```sh
read -rp 'Next, some migrations are done for all software to run nicely on Bookworm. This can include dietpi-software reinstalls. Press any key to continue ...'
```

**Comment by StephanStS** [comment]
Did some tests with Proxmox-VMs:

- Basic console VM: ✅
- VM with node-red, NGINX, PHP, NFS client: ✅
- VM with X11 (Xfce): ✅
- VM with Plex Media Server: ✅
- VM with Nextcloud: ❌
  image
  (I keep it at this state for further investigations)

- VM with MQTT Server: ✅
- VM with X11 (Xfce) and many office applications (XSane, OpenOffice,...): ✅
- VM with X11 (Xfce) and many development applications (VSCodium, GitHub Desktop, KeePassXC, Atom, Firefox,...): ✅

- LXC container: ✅

I had only minor issues that sometimes apt update etc. hangs, a "retry" option of the scripts always helped.


> @StephanStS Awesome, thanks for the many tests. On the failing Nextcloud reinstall, can you check the Redis service logs:
> 
> ```shell
> journalctl -u redis-server
> ```

grafik

**Comment by Joulinar** [comment]
probably the TCP port is still in use by another process and therefore Redis could not connect. Can you share following.

```
ss -tulpn | grep LISTEN
```

BTW: can you use SSH to connect and to copy information directly from SSH terminal?

**Comment by StephanStS** [comment]
> probably the TCP port is still in use by another process and therefore Redis could not connect. Can you share following.
> 
> ```
> ss -tulpn | grep LISTEN
> ```
 
```
root@nc-test1:/tmp/DietPi-Software# ss -tulpn | grep LISTEN
tcp   LISTEN 0      80         127.0.0.1:3306      0.0.0.0:*    users:(("mariadbd",pid=46185,fd=18))
tcp   LISTEN 0      4096         0.0.0.0:111       0.0.0.0:*    users:(("rpcbind",pid=21819,fd=4),("systemd",pid=1,fd=70))
tcp   LISTEN 0      128          0.0.0.0:22        0.0.0.0:*    users:(("sshd",pid=23160,fd=3))
tcp   LISTEN 0      4096            [::]:111          [::]:*    users:(("rpcbind",pid=21819,fd=6),("systemd",pid=1,fd=72))
tcp   LISTEN 0      128             [::]:22           [::]:*    users:(("sshd",pid=23160,fd=4))
```

> BTW: can you use SSH to connect and to copy information directly from SSH terminal?

I know, the last screenshot was taken via (you are allowed to laugh :-))  
Windows PC (local) -> VirtualBox DietPi VM -> RustDesk -> Win10 PC (at home) -> MobaXterm -> Nextcloud test VM  
(I did a screenshot of the Nextcloud test VM and entered it at the Windows PC first in the row. I will explain it later.)

**Comment by MichaIng** [comment]
Hmm, port is not used, but Redis still fails to bind. Was there probably a mandatory config change?
```sh
diff /etc/redis/redis.conf* | grep -vE '^[<>] #|^[0-9-]'
```

**Comment by StephanStS** [comment]
> 

```
root@nc-test1:/tmp/DietPi-Software# diff /etc/redis/redis.conf* | grep -vE '^[<>] #|^[0-9-]'
< bind 127.0.0.1 ::1
> bind 127.0.0.1 -::1
>
>
< unixsocket /run/redis/redis-server.sock
< unixsocketperm 770
>
>
< supervised no
< pidfile /var/run/redis/redis-server.pid
> pidfile /run/redis/redis-server.pid
< loglevel warning
> loglevel notice
< logfile ""
> logfile /var/log/redis/redis-server.log
< syslog-enabled yes
>
>
> set-proc-title yes
>
> proc-title-template "{title} {listen-addr} {server-mode}"
>
>
<
< save 900 1
< save 300 10
< save 60 10000
>
< repl-diskless-sync no
> repl-diskless-sync yes
> repl-diskless-sync-max-replicas 0
>
>
>
>
>
>
>
> lazyfree-lazy-user-flush no
>
>
>
>
> disable-thp yes
>
>
> appenddirname "appendonlydir"
>
<
< lua-time-limit 5000
> aof-timestamp-enabled no
>
>
>
>
>
>
>
>
>
>
>
>
>
>
<
<
< hash-max-ziplist-entries 512
< hash-max-ziplist-value 64
> hash-max-listpack-entries 512
> hash-max-listpack-value 64
< list-max-ziplist-size -2
> list-max-listpack-size -2
< zset-max-ziplist-entries 128
< zset-max-ziplist-value 64
> zset-max-listpack-entries 128
> zset-max-listpack-value 64
>
root@nc-test1:/tmp/DietPi-Software#
```

**Comment by MichaIng** [comment]
Do you have IPv6 disabled on this VM?

**Comment by StephanStS** [comment]
> Do you have IPv6 disabled on this VM?

Nope.
I always disable IPv6 in the DietPi Proxmox VMs, otherwise there are some kernel error logs on the console.

**Comment by MichaIng** [comment]
> I always disable IPv6 in the DietPi Proxmox VMs, otherwise there are some kernel error logs on the console.

Would be interesting to investigate those. When WiFi is used on the host for Internet access, it is known to cause issues, but otherwise not. But lets do that in a dedicated issues if wanted.

Back to the issue, which I think is due to this diff:
```diff
< bind 127.0.0.1 ::1
> bind 127.0.0.1 -::1
```
The leading dash for sure allows Redis to fail binding to an IP on Bookworm's version, so it is allowed to fail on IPv6. But Bullseye's version does not contain the dash. I guess older Redis was always allowed to fail on IPv6, or had some clever detection for whether IPv6 is enabled, and did not try to bind to it if not. Recent Redis is not allowed to fail on IPv6 if not explicitly defined with this dash, or it has the detection removed, in any case forcing admins to be more explicit.

Try to fix with:
```sh
G_CONFIG_INJECT 'bind ' 'bind 127.0.0.1 -::1' /etc/redis/redis.conf
systemctl restart redis
```
_________
Checking the docs, respectively default upstream config:
- v6.0 (Bullseye) https://raw.githubusercontent.com/redis/redis/6.0/redis.conf: no dash explained above `bind`
- v6.2 https://raw.githubusercontent.com/redis/redis/6.2/redis.conf: the dash is even explained now
    Interesting is following statement, which obviously does not apply to IPv6 as unsupported protocol, if disabled for all interfaces. Probably the kernel module would need to be disabled for this to apply:
    > unsupported protocols will always BE silently skipped.

**Comment by Joulinar** [comment]
is that on issue dedicated to x86? Because on my RPi4, I could manage to upgrade a NC system.

**Comment by MichaIng** [comment]
> is that on issue dedicated to x86? Because on my RPi4, I could manage to upgrade a NC system.

I guess you have IPv6 enabled on your RPi 4? Disable it and try to restart the server. It should then throw the same error.

**Comment by MichaIng** [comment]
Seeing all the other changed defaults, we should suggest upstream and in case to Debian maintainers to use the `include` setting by default to include `/etc/redis/redis.conf.d` or so by default. That way we wouldn't need to edit the base config but could create an override instead, so that package upgrades can update the base config as well.

**Comment by Joulinar** [comment]
@MichaIng you are absolutely right. It's IPv6. Having it disabled leads Redis to fail. Getting it back enabled and Redis will start again.

```
[  OK  ] DietPi-Software | systemctl restart mariadb
[FAILED] DietPi-Software | systemctl restart redis-server
[ SUB3 ] DietPi-Set_hardware > enableipv6 (enable)
[  OK  ] DietPi-Set_hardware | Comment in /etc/hosts converted to setting: ::1 localhost ip6-localhost ip6-loopback
[  OK  ] DietPi-Set_hardware | Comment in /etc/hosts converted to setting: ff02::1 ip6-allnodes
[  OK  ] DietPi-Set_hardware | Comment in /etc/hosts converted to setting: ff02::2 ip6-allrouters
[  OK  ] DietPi-Set_hardware | Setting in /boot/dietpi.txt adjusted: CONFIG_ENABLE_IPV6=1
[  OK  ] enableipv6 enable | Completed
[..    ] DietPi-Software | systemctl restart redis-server
[  OK  ] DietPi-Software | systemctl restart redis-server
```

**Comment by StephanStS** [comment]
> Try to fix with:
> 
> ```shell
> G_CONFIG_INJECT 'bind ' 'bind 127.0.0.1 -::1' /etc/redis/redis.conf
> systemctl restart redis
> ```

That worked, but redis was not restarted:
```
root@nc-test1:/tmp/DietPi-Software# G_CONFIG_INJECT 'bind ' 'bind 127.0.0.1 -::1' /etc/redis/redis.conf
systemctl restart redis
[  OK  ] G_CONFIG_INJECT | Setting in /etc/redis/redis.conf adjusted: bind 127.0.0.1 -::1
Failed to restart redis.service: Unit redis.service not found.
```

Ignoring this message worked fine for the script.

Issue 1: The reboot gave a failure:

```
root@nc-test1:~# reboot
Failed to connect to bus: Datei oder Verzeichnis nicht gefunden
```

Issue 2: The Nextcloud instance did not run. The browser showed:

```
This version of Nextcloud is not compatible with PHP>=8.2.
You are currently running 8.2.1.
```

I am using Nextcloud Hub 25.0.3.

**Comment by MichaIng** [comment]
I think we should do this as migration step:
```sh
sed -i '/^bind 127.0.0.1 ::1$/c\bind 127.0.0.1 -::1' /etc/redis/redis.conf
```
So if that line is untouched/the default on Bullseye, we add the dash to align it with the default on Bookworm.

**Comment by StephanStS** [comment]
If you updated the script, I can re-test the update again.

**Comment by MichaIng** [comment]
> That worked, but redis was not restarted:

Ah sorry, the alias is not created unless the service is enabled:
```sh
systemctl start redis-server
```
We really need to change service startup/control behaviour to have services enabled by default on DietPi. This also creates aliases, so shortcuts or alternative names to control the same service.

**Comment by MichaIng** [comment]
> Issue 2: The Nextcloud instance did not run. The browser showed:

Ah right, the patch was applied on fresh installs only, with latest commit also on reinstalls.

> Failed to connect to bus: Datei oder Verzeichnis nicht gefunden

Yes, known on Bookworm if `dbus` is not installed. However, it does poweroff/restart just fine. Not sure what to do about it of what even can be done. Probably we can manipulate PAM configs, but if `dbus` is installed and systemd-logind used, I guess this would break the intended functionality.

**Comment by StephanStS** [comment]
Ran the script again, now without errors.
Only the Nextcloud instance is not running like described above.

**Comment by Joulinar** [comment]
ok another test using NC finished without issues. 👍

**Comment by MichaIng** [comment]
I'll merge this now. But lets keep testing/discussing here. My plan:
- [ ] Create a general Bookworm testing issue here on GitHub.
- [ ] Create an additional general Bookworm testing topic on the forum, for users which do not use GitHub? What do you think?
- [ ] Update the related [wiki page](https://github.com/MichaIng/DietPi/wiki/Debian-Bookworm-testing) according to test results.
- [ ] Create a blog post about Bookworm and how to apply the script. Reference GitHub issue and in case forum topic for feedback, and the wiki page to check test results of required software.

**Comment by lukaszsobala** [comment]
My upgrade on rpi zero 2w went well. Now testing on raspberry pi 4 with more things installed.

One question - after the upgrade is successful, can we change the branch back to stable releases? Or is dev needed for PHP to work at all?

**Comment by Joulinar** [comment]
you can change back to master without issue

**Comment by lukaszsobala** [comment]
Thanks. The script worked fine for Raspberry Pi 4 too.

There's one thing that might have not been as you wished: I executed the script inside `screen`, detached it and logged out. In the meantime it completed. When I connected via ssh again, the autopurge was automatic and it happened before the reboot. I then did `screen - r` and rebooted (no problems ensued).

**Comment by Joulinar** [comment]
yes the package will get cleaned on next root login. Maybe @MichaIng has an idea if we need to verify if a reboot already happened or not. 🤔

**Comment by MichaIng** [comment]
Because on `x86_64` systems (respectively if the Debian kernel package is used) the autoremoval would purge the currently loaded kernel as well, which isn't optimal if you do not reboot soon, since it is then impossible to load kernel modules. There may be other cases of packages which are currently used and would be purged. So it is generally saver to do autoremoval after a reboot.

That another login does autoremoval already is indeed unintended, but I have no suitable idea for assuring that it is done only after a reboot, without making it too complex. We just use a login script.

What do you think about doing the autoremoval immediately but enforcing the reboot instead? If someone does a distribution upgrade, it is unlikely that a reboot is a problem or unwanted, and in case anything important needs to be saved or so, another SSH session can be used before hitting Ok.

**Comment by MichaIng** [comment]
Ah I didn't mean to do the reboot automatically, but to not give the choice to hit "Cancel". I'd change it into a `read -rp ...text...` so that one can easily scroll up and review the recent output and then reboot on return/enter.

A completely automated upgrade is anyway not possible due to the `read -rp` that is done already after the package upgrades and before config/software migrations.

**Comment by MichaIng** [comment]
I think all three of us are running GNU Screen in SSH session by default 😉. But there is a difference between watching the screen the whole time or going for a coffee in between and check back by times it it has finished or input is needed. I think it is good to have those two required inputs to give time for/encourage users reviewing the output, especially before doing the reboot.

**Comment by lukaszsobala** [comment]
I also think that the `archive.raspberrypi.org` repository did not get update, is this by design? They have a `bookworm` release now.

```
Hit:1 https://download.docker.com/linux/debian bookworm InRelease
Hit:2 https://deb.debian.org/debian bookworm InRelease
Hit:3 https://archive.raspberrypi.org/debian bullseye InRelease
Hit:4 https://deb.debian.org/debian bookworm-updates InRelease
Hit:5 https://deb.debian.org/debian-security bookworm-security InRelease
Hit:6 https://deb.debian.org/debian bookworm-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: https://archive.raspberrypi.org/debian/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details
```

**Comment by MichaIng** [comment]
> They have a `bookworm` release now.

But it is empty 😉:
- https://archive.raspberrypi.org/debian/dists/bookworm/main/binary-arm64/Packages
- https://archive.raspberrypi.org/debian/dists/bookworm/main/binary-armhf/Packages

**Comment by churchofnoise** [comment]
As mentioned on the DietPi forum, ran the script after migrating to dev branch (from beta) on a x86-64 system running Home Assistant.

All is running very well (and even snappier than before), yet sudo reboot results in this:
`Failed to set wall message, ignoring: Unit dbus-org.freedesktop.login1.service failed to load properly, please adjust/correct and reload service manager: File exists
Call to Reboot failed: Unit dbus-org.freedesktop.login1.service failed to load properly, please adjust/correct and reload service manager: File exists`
(same message appeared at the end of running the script after I'd been asked if I wanted to reboot, which I confirmed). Any ideas?

**Comment by Joulinar** [comment]
`dbus `messages a little bit as expected on Bookworm as we don't install `dbus `package by default. Something we still thinking of how to avoid that message. But your system is performing the reboot?

**Comment by MichaIng** [comment]
Yes it want's to de-register the session with `systemd-logind` which is not used by default on DietPi. Maybe we find a way that it tries this only if the service is actually active.

**Comment by churchofnoise** [comment]
Thanks for the info!
It does indeed reboot properly, so functionally all is well.

**Comment by kelvmod** [comment]
Apt after the upgrade:

`# apt update
Hit:1 https://download.docker.com/linux/debian bookworm InRelease
Hit:2 https://deb.debian.org/debian bookworm InRelease
Hit:3 https://deb.debian.org/debian bookworm-updates InRelease
Hit:4 https://deb.debian.org/debian-security bookworm-security InRelease
Hit:5 https://deb.debian.org/debian bookworm-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
N: Repository 'Debian bookworm' changed its 'non-free component' value from 'non-free' to 'non-free non-free-firmware'
N: More information about this can be found online in the Release notes at: https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.html#non-free-split`

Required change:

`# sed -i 's/non-free/non-free non-free-firmware/' /etc/apt/sources.list`

**Comment by MichaIng** [comment]
Good point! We do this already for fresh Bookworm images, when the APT mirror is changed on a Bookworm system or when a Bookworm system is upgraded from an older DietPi version: https://github.com/MichaIng/DietPi/blob/0423238/dietpi/func/dietpi-set_software#L135-L136

But indeed in this script it is missing. Will add it.

**Comment by Trimble-tech** [comment]
After testing it virtually, I ran this script on my Bullseye system and it worked well; I am now using Bookworm and my apps are up and running. The only thing I noticed is the Nginx config file ( `/etc/nginx/sites-available/default` ) changed which disabled my self-signed certs. I pulled my old file from the backup and moved it in place, renaming the new file. Aside from this everything went off without a hitch. Thanks as always to the developers.

_System Info:_
- Device: Raspberry Pi 4B 8GB
- Dietpi Version: 8.21.-1 (manually changed from 8.21 before update)
- Disks Used: 4TB Sata NAS HD (data), 1TB Sata SSD (boot) {both connected via USB3}
- Logging: Full

_Software Installed:_
- `OpenSSH Client (0)`
- `IPTraf (11)`
- `Git (17)`
- `Fail2Ban (73)`
- `Nginx (85)`
- `MariaDB (88)`
- `PHP (89)`
- `Redis (91)`
- `Pi-Hole (93)`
- `Logrotate (101)`
- `Rsyslog (102)`
- `OpenSSH Server (105)`
- `Nextcloud (114)`
- `Webmin (115)`
- `PiVPN (117)`
- `Python 3 (130)`
- `Unbound (182)`
- `Java JRE (196)`
- `Homer (205)`

Considering how many variables/software packages are on this system, I am impressed the update only needed one text file changed afterwards.

**Comment by MichaIng** [comment]
Thanks for testing. Right, the Nginx installation is a little intrusive, overwriting `/etc/nginx/nginx.conf` and `/etc/nginx/sites-available/default` on every (re)install. We need to switch to using drop-in configs where possible and otherwise add or edit individual lines/blocks only.

However, generally I'd always advice to create an own file for each server block, like `/etc/nginx/sites-available/ssl` and then:
```sh
ln -s ../sites-available/ssl /etc/nginx/sites-enabled/ssl
```

**Comment by Smyl3** [comment]
After ran update script, system refused my SSH key with Putty. It turned out I had to update the Putty client that solved the issue.

**Comment by MichaIng** [comment]
The kernel is generally distro-version-agnostic. Implementing full support for the new set of kernel/firmware packages is in the works, but much to do. You can however migrate already: https://github.com/MichaIng/DietPi/issues/6676

**Comment by Smyl3** [comment]
> The kernel is generally distro-version-agnostic. Implementing full support for the new set of kernel/firmware packages is in the works, but much to do. You can however migrate already: #6676

Thanks. I see. It surprised me because I saw that for raspberry OS the new kernel is already available by apt upgrade if I right.
Since then I compiled a custom 6.6 kernel for Zero2W and bookworm with default enabled zswap, but I saw very heavy unresponsiveness regularly with wlan packet losses and dietpi-wifi-monitor.sh generated wlan reconnects which I see weird because I use 10s test timeout and 10 try attempts settings in dietpi-config. I tried to set swapiness to higher value than 1 and keep testing it.

**Comment by MichaIng** [comment]
The whole way where kernel and boot configs are stored, where the FAT partition is mounted, which graphics/camera drivers are supported etc have changed quite radically. You cannot just install the new APT packages over the old one, which is why we creates the migration script and give it some time for intense testing, as the process intrusive. Also a bunch of software options need to change or in cases be removed and the display and camera settings provided by our scripts reworked. This ia much work and we are a small team. This is by far the largest change RPi Ltd. has ever done to their kernel/firmware packages, so it is not just the kernel upgrade from 6.1 to 6.6 which would be trivial (and can be done with a custom build or `rpi-update` indeed, but leaving everything else at legacy setup).

Ia your RPi a mobile device moving from one AP to another? If it has just a little flaky WiFi connection but is otherwise stationary connected to the same AP, the WiFi monitor is not suitable. The connection would then usually be re-established much faster when just leaving it untouched. Also I cannot imagine this has anything to do with the kernel version.

**Comment by Smyl3** [comment]
> Ia your RPi a mobile device moving from one AP to another? If it has just a little flaky WiFi connection but is otherwise stationary connected to the same AP, the WiFi monitor is not suitable. The connection would then usually be re-established much faster when just leaving it untouched. Also I cannot imagine this has anything to do with the kernel version.

Rpi is still at same location and on same 2.4GHz wifi network which is only one network, no repeater, nothing. Already tried to play with different wifi channels, reboot router, disable WMM etc.
It seems that the wifi connection will be a packet loss so DietPi-WiFi_Monitor service dropping the whole connection instantly without any tolerance in ping tests and init a reconnection. It can occur multiple times in few minutes even the ping times are low. I see that in logs with  the stock 6.1.21-v8+ kernel and under bullseye either. So the connection test options in dietpi-config seems doesn't affect DietPi-WiFi_Monitor service itself.
I continue to test my router wifi stability either.

**Pull request merged**
