### PR TITLE
DietPi-Software | frp

### PR DESCRIPTION
**Pull request by Joulinar**
- switch from `ini` to `toml` configuration file because `ini` format is deprecated and the support will be removed in the future

### CODE REVIEW

**Comment by MichaIng** [comment]
Shall we do some kind of migration from ini to toml?

**Comment by Joulinar** [comment]
thougt about it, but we would need to check whole ini file for custom changes. Isn't it?

**Comment by MichaIng** [comment]
Yeah, and the number of config keys is much too large to do all of this:
- https://github.com/fatedier/frp/blob/dev/conf/frps_full_example.toml
- https://github.com/fatedier/frp/blob/dev/conf/frpc_full_example.toml

Sadly there is no internal conversion feature. So it looks like this is something we need to ask users to do manually. Best we can probably do is, checking whether the ini files exist, and if so, prompt an information, and rename them to *.bak (to not repeat the prompt).

Btw there is a way to generate bash completion files:
```sh
frpc completion bash
frps completion bash
```
Probably something to document in our docs?

**Review by MichaIng — APPROVED** [review]
Works well now. An unrelated issue is that the frp server can sometimes take longer to start than the frp client, and hence the client then fails to connect. It restarts up to 3 times, but during GitHub Actions test, for ARMv7 emulation, even that sometimes was not sufficient, but it failed ultimately. But I have no idea how to fix this properly. The daemon would need to return some systemd notify call to lock the start sequence until a defined state, like when the TCP listener is up. But as they removed their systemd examples a while ago, I don't think this has any priority.

**Comment by Joulinar** [comment]
Yes have noticed this as well. At least until know we don't have a report this being an issue. Should be fine i guess

**Comment by MichaIng** [comment]
Yeah, and if needed, we can raise `RestartSec`, to wait longer until a restart is schedulsd (currently 5 seconds), to give the server more time to start. This seems to be cleanest, without impacting common operation, like a `ExecStartPre=/bin/sleep X` would do.

**Pull request merged**
