### PR TITLE
DietPi-Software | Bazarr

### LINKED ISSUE #4615: [Bazarr] Installation broken
#### Required Information
- DietPi version | `G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=4
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='applied'`

- Distro version | `buster 10.10`
- Kernel version | `Linux Pi-1 5.10.52-v8+ #1440 SMP PREEMPT Tue Jul 27 09:56:40 BST 2021 aarch64 GNU/Linux`
- SBC model | `RPi 4 Model B (aarch64)`
- Power supply used | 5V 3A (Official)
- SDcard used | SanDisk ultra 400

#### Additional Information (if applicable)
- Software title | `Bazarr`
- Was the software title installed freshly or updated/migrated? `Freshly`
- Can this issue be replicated on a fresh installation of DietPi? `Unknown`

- Bug report ID | 

#### Steps to reproduce

1. Use dietpi-software and install Bazarr
2. Check <ip>: 6767 for the page load error

#### Expected behaviour

- Once Bazarr is installed, it should be accessible via the IP webpage and port 6767.

#### Actual behaviour

- Getting page load error. It appears that Bazarr is running (ps -aux) and port 6767 is accessible (a service is running), but no page comes up. It is possibly a webserver issue, except that the systemctl logs indicate its a Bazarr signal error to Radarr - which should not be set/specified in the Bazarr *install*. 
 
> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

#### Extra details

- Already had the following installed (which "may" affect the Bazarr install):
 `Radarr `(current version) - I noticed Bazarr may have auto-config for it? however I won't be using Bazarr with Radarr (even if they're on the same machine).
  `Nginx` Webserver
- systemctl shows the following:

```
root:/# systemctl status bazarr
● bazarr.service - Bazarr Daemon (DietPi)
   Loaded: loaded (/etc/systemd/system/bazarr.service; disabled; vendor preset: enabled)
   Active: active (running) since *** ; 56min ago
 Main PID: 1085 (python3)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/bazarr.service
           ├─1085 /usr/bin/python3 /opt/bazarr/bazarr.py -c /mnt/dietpi_userdata/bazarr
           └─1274 /usr/bin/python3 -u /opt/bazarr/bazarr/main.py -c /mnt/dietpi_userdata/bazarr

Bazarr[1085]: *** - app   (7fa790f6d8) :  ERROR (app:1891) - Exception on / [GET]
Bazarr[1085]: *** - app   (7fa790f6d8) :  ERROR (app:1891) - Exception on /favicon.ico [GET]
Bazarr[1085]: *** - root  (7fa79f1e80) :  ERROR (signalr_client:143) - BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...
Bazarr[1085]: *** - root  (7fa790f908) :  INFO (signalr_client:124) - BAZARR SignalR client for Radarr is connected and waiting for events.
Bazarr[1085]: *** - root  (7fa790f4a8) :  INFO (signalr_client:124) - BAZARR SignalR client for Radarr is connected and waiting for events.
Bazarr[1085]: *** - root  (7fa790fc50) :  ERROR (get_movies:545) - BAZARR Error trying to get movies from Radarr. Timeout Error.
Bazarr[1085]: *** - root  (7fa790f5c0) :  ERROR (get_movies:545) - BAZARR Error trying to get movies from Radarr. Timeout Error.
Bazarr[1085]: *** - root  (7fa790f390) :  ERROR (get_movies:545) - BAZARR Error trying to get movies from Radarr. Timeout Error.
Bazarr[1085]: *** - app   (7fa79f1e80) :  ERROR (app:1891) - Exception on / [GET]
Bazarr[1085]: *** - app   (7fa79f1e80) :  ERROR (app:1891) - Exception on /favicon.ico [GET]
```
- app seems to have launched:

```
root:/# ps -aux | grep bazarr
bazarr   25672  0.0  0.1  17844  9952 ?        Ss   16:05   0:00 /usr/bin/python3 /opt/bazarr/bazarr.py -c /mnt/dietpi_userdata/bazarr
bazarr   25673  1.9  1.5 246276 118252 ?       Sl   16:05   0:15 /usr/bin/python3 -u /opt/bazarr/bazarr/main.py -c /mnt/dietpi_userdata/bazarr
```

- No apparent errors in the install log found:
[DietPi-4615-dietpi-software-Bazarr-Install.log](https://github.com/MichaIng/DietPi/files/6929252/DietPi-4615-dietpi-software-Bazarr-Install.log)

- the only thing that doesn't seem right from the install log is this (which is presumptuous) - but disabling this in the bazarr config makes no difference to the issue:
- 
```
[  OK  ] DietPi-Software | Setting in /mnt/dietpi_userdata/bazarr/config/config.ini adjusted: use_radarr = **True**
[  OK  ] DietPi-Software | systemctl daemon-reload
```

- Reboot/Restarting the service did not resolve the issue.

- Screenshot (http)
image

### PR DESCRIPTION
**Pull request by Joulinar**
**Status**:  Ready
- [x] adjust installation procedure for Bazarr

**Reference**: https://github.com/MichaIng/DietPi/issues/4615

**Commit list/description**:
- DietPi-Software | Bazarr - adjust installation procedure as it has been changed on latest Bazarr version v0.9.6

### CODE REVIEW

**Comment by MichaIng** [comment]
Nice find with the "latest" download URL, I didn't know this exists. We always scrape api.github.com for the latest download URL, but that one seems to be a shortcut, at least in cases where the file name itself does not contain the version string.

**Comment by Joulinar** [comment]
Not sure if this is working as live patch as we change from `git clone` to a tarball. This is a different way of installation. Does this could be changed with a one-liner?

**Comment by MichaIng** [comment]
Yes, I edited the idea back and forth, in this case it is too complicated/risky to patch.

**Comment by MichaIng** [comment]
It seems Git is now not required anymore at all. The updater works fine without.

**Comment by Joulinar** [comment]
Ah I totally forgot about to check and correct dependencies

**Review by MichaIng — DISMISSED** [review]

**Comment by MichaIng** [comment]
Ready from my end.

**Comment by Joulinar** [comment]
Yap looks good

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
