### PR TITLE
DietPi-Software | Ampache - Change ownership on web server root directory

### PR DESCRIPTION
**Pull request by Joulinar**
**Status**: Ready
- [x] check install procedure

**Reference**: https://dietpi.com/phpbb/viewtopic.php?f=11&t=8367&p=29376&hilit=ampache#p29376

For Ampache it is needed to have write access to web server directoty as Ampache needs to be able to write config files down to disk

**Commit list/description**:
- DietPi-Software | Ampache - Change ownership to user and group www-data

### CODE REVIEW

**Comment by MichaIng** [comment]
Good find. Let's limit it to the config directory.

**Comment by MichaIng** [comment]
Actually, only write access to the actual config file itself is required to update it, e.g. after reinstall. I'm also currently implementing that we use and update the shipped example config file instead of downloading a very outdated one.

**Comment by MichaIng** [comment]
It's fixed during the update now as well 😀.
Okay retested everything. Little bonus: This also fixed the waveform image when playing the song and in song info. There was a temporary directory setting missing previously for this to work.

waveform

@Joulinar 
Ready from your side?

**Review by MichaIng — APPROVED** [review]

**Comment by Joulinar** [comment]
yes, have seen it. Well done @MichaIng 

Yes ready. my test was successful

**Pull request merged**
