### PR TITLE
DietPi-Drive_Manager | Move user data and rootfs enhancements

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Drive_Manager | Enforce filesystem limit for moving the rootfs by only showing supported filesystem types in the format menu. The dedicated Btrfs warning/abortion is obsolete as the target partition is reformatted.
+ DietPi-Drive_Manager | Allow moving the rootfs on Odroid C4, which works like on all other Odroids.
+ DietPi-Drive_Manager | Do not force the user to unmount the rootfs target manually, as this is done automatically when the partition is formatted.
+ DietPi-Drive_Manager | Check whether the filesystem is supported when moving DietPi user data. Enforce a filesystem type with native UNIX permissions and symlink support. NTFS with emulated features via ntfs-3g driver has been shown to not be reliable in this regards and a network drive is currently ruled out as the option isn't shown in the menu then. We may think about allowing user data on an NFS mount with verified that UNIX permissions and symlinks are both supported. Do the same fileystem type validation in dietpi-set_userdata, just in case it is called manually.

### CODE REVIEW

**Comment by amibumping** [comment]
Can be this to be possible on Odroid HC4? Or is not possible?

**Comment by MichaIng** [comment]
Here is how to manually achieve it: https://dietpi.com/forum/t/tutorial-odroid-c4-rootfs-on-usb-drive/15662

**Comment by amibumping** [comment]
> Here is how to manually achieve it: https://dietpi.com/forum/t/tutorial-odroid-c4-rootfs-on-usb-drive/15662

Yeah I know, but I was asking about the old option.

Thank you anyway.

**Comment by MichaIng** [comment]
That is indeed what #5295 is about.

But actually, since the HC4 has an SPI flash, it can boot completely from USB and SATA. There is just a little change need to be done in our boot configs: https://dietpi.com/forum/t/odroid-hc4-booting-from-ssd/6322/45

I'll generate fresh images with this change applied today.

**Pull request merged**
