### PR TITLE
DietPi-Drive_Manager | Enhance network share input prompts

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Review

**Commit list/description**:
- DietPi-Drive_Manager | Align network drive input prompts, allow to enter a path as SMB/CIFS server shared folder, remove leading slash when given

### CODE REVIEW

**Comment by Joulinar** [comment]
we should add a network share detection for NFS. At the moment we just simply mount root export directory. But in most cases the NFS export has some sub folder. This available shares could be displayed using `showmount`. But it would require `nfs-common` to be installed first.

```
root@DietPi4:/tmp# showmount -e 192.168.0.10
Export list for 192.168.0.10:
/volume1/NFS 192.168.0.0/24
root@DietPi4:/tmp#
```

**Comment by MichaIng** [comment]
Jep, lets do that in a different PR.

**Comment by Joulinar** [comment]
should I open a `feature request`?

**Comment by MichaIng** [comment]
@StephanStS 
Does this cover the docs extension you proposed here? https://github.com/MichaIng/DietPi-Docs/pull/675
Generally we should try to keep those dialogues self-explaining and complete, instead of adding notes to our docs, which are not read by everyone.

**Pull request merged**
