### PR TITLE
Update dietpi-imager

### PR DESCRIPTION
**Pull request by sal666**
Improve detection of drives

### CODE REVIEW

**Comment by MichaIng** [comment]
@sal666 
I would allow all file systems. Especially BTRFS can be well used as rootfs, and there are others. However excluding current root drive of course makes sense. What about
```
local current_root=$(findmnt -no MAJ:MIN /)
current_root=${current_root%:*}
G_WHIP_MENU_ARRAY=($(lsblk -dnpo NAME,SIZE -e 1,$current_root))
```
?

**Comment by sal666** [comment]
@MichaIng 

> I would allow all file systems. Especially BTRFS can be well used as rootfs, and there are others.

Now ext4 is used because this is the FS used by DietPi (as instructed in this [howto](https://github.com/MichaIng/DietPi/wiki/How-to-create-a-DietPi-image-for-x86_64-PCs-(UEFI))), and this script is meant to be used (only?) to image DietPi systems. Allowing more FS types is pretty straightforward by changing the _grep_ command:
`grep -E ' ext4$| btrfs$'`
or
`grep ' ext4$\| btrfs$'`

Filtering by the FS known to be used by DietPi helps reducing the list of devices offered to the user when he is asked to select the device. Also, `lsblk` is able to output the name of the parent device (PKNAME) of every partition, making it easier to manage situations like this:
```
$ lsblk
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda             8:0    0    2G  0 disk 
├─sda1          8:1    0   94M  0 part
└─sda2          8:2    0  1.9G  0 part
mmcblk1       179:0    0 57.6G  0 disk 
├─mmcblk1p1   179:1    0   64M  0 part
└─mmcblk1p2   179:2    0 57.6G  0 part
mmcblk1boot0  179:8    0    4M  1 disk
mmcblk1boot1  179:16   0    4M  1 disk
```
Here the expected list is of devices is:
```
/dev/sda 2G
/dev/mmcblk1 57.6G
```

> local current_root=$(findmnt -no MAJ:MIN /)
> current_root=${current_root%:*}
> G_WHIP_MENU_ARRAY=($(lsblk -dnpo NAME,SIZE -e 1,$current_root))

That would exclude all block devices with the same [major device number](https://www.kernel.org/doc/Documentation/admin-guide/devices.txt) as the one hosting the root FS, probably always resulting in an empty list.

**Comment by MichaIng** [comment]
@sal666
You're right, my suggestion is buggy and all the resize2fs + zerofree calls anyway rely on ext4 file system. No need to allow anything else currently.

I'm currently trying to resolve the conflicts and found the following:
On VM:
```
root@VM-Buster:/# lsblk -npo PKNAME $(findmnt -no SOURCE /)
/dev/sda
```
On RPi:
```
2019-10-25 00:29:07 root@micha:/# lsblk -npo PKNAME $(findmnt -no SOURCE /)

2019-10-25 00:29:09 root@micha:/# lsblk -npo NAME,PKNAME $(findmnt -no SOURCE /)
/dev/mmcblk0p2
2019-10-25 00:29:11 root@micha:/# lsblk -npo NAME,PKNAME
/dev/sda
/dev/sdb
/dev/mmcblk0
├─/dev/mmcblk0p1 /dev/mmcblk0
└─/dev/mmcblk0p2 /dev/mmcblk0
```
Not sure why, but somehow on RPi, PKNAME is not shown when calling lsblk for a single partition, while this works well on VM. On non-specific lsblk however, PKNAME is shown correctly.
But as you can see, PKNAME does not exist, if the drive has no partition table, which leads to:
```
2019-10-25 00:34:35 root@micha:/# lsblk -rnpo PKNAME,SIZE,FSTYPE
 2.7T ext4
 1.8T ext4
 59.8G
/dev/mmcblk0 43.1M vfat
/dev/mmcblk0 59.8G ext4
```
This breaks your array. Indeed a partition table is required to boot an OS from, so it makes sense to exclude block devices with none. The following assures it exist by explicitly checking the second word against "ext4":
```
lsblk -rnpo PKNAME,FSTYPE,MOUNTPOINT | mawk '{if ( $2=="ext4" && $3!="/" ) print $1,$2}'
```
There is a tiny chance it fails, if a drive without partition table is attached and mounted to "ext4", which AFAIK is impossible since mount points must contain a leading slash.

And since we now only show drives with partition table, I re-added your previous suggestion to skip trying to unmount the parent drive.

`umount -R` btw attempts to recursively unmount contained mountpoints first. Otherwise e.g. `/dev/sda1` mounted to `/mnt/rpi` and `/dev/sda2` mounted to `/dev/rpi/boot`, leading to unmount in alphabetical order (first /dev/sda1) will fail.

I hope this includes all you were aiming for initially?

(lsblk `-e 1` btw is default, thus I skipped it)

**Comment by sal666** [comment]
@MichaIng 

> I hope this includes all you were aiming for initially?

Yes, LGTM. Just add a 'sort -u' at the end because there could be more than one ext4 FS per drive. It's not that common on DietPi systems, but it makes no harm to be extra cautious.
```
lsblk -rnpo PKNAME,FSTYPE,MOUNTPOINT | mawk '{if ( $2=="ext4" && $3!="/" ) print $1,$2}' | sort -u
```

**Comment by sal666** [comment]
@MichaIng 
Sorry, no. It will not work correctly when more than one ext4 partitions are present in the drive with the root FS:
```
$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0  89.1M  1 loop /snap/core/7917
loop1    7:1    0    89M  1 loop /snap/core/7713
loop2    7:2    0   792K  1 loop /snap/fwup/24
sda      8:0    0 931.5G  0 disk 
├─sda1   8:1    0   300M  0 part /boot/efi
├─sda2   8:2    0    12G  0 part /
├─sda3   8:3    0 903.2G  0 part /home
└─sda4   8:4    0    16G  0 part [SWAP]
sr0     11:0    1  1024M  0 rom  
$ lsblk -rnpo PKNAME,FSTYPE,MOUNTPOINT | mawk '{if ( $2=="ext4" && $3!="/" ) print $1,$2}' | sort -u
/dev/sda ext4
```
We need to store the device of the root FS in a temp var so we can check against all ext4 partitions:

```
$ ROOTFS_DEVICE=$(lsblk -npo PKNAME $(findmnt -no SOURCE /))
$ lsblk -rnpo PKNAME,FSTYPE | awk -v RFSD=$ROOTFS_DEVICE '{if ( $1!=RFSD && $2=="ext4" ) print $1,$2}' | sort -u
```

**Comment by MichaIng** [comment]
@sal666 
Jep, the `sort -u` is inside of course.

Ah damn you're right. Why can one only exclude drives by major number instead of any other matching field (e.g. mount point) as well 😄.

`lsblk -npo PKNAME $(findmnt -no SOURCE /)` as mentioned above does not work on RPi somehow. What can be done:
```
ROOTFS_DEVICE=$(lsblk -npo PKNAME,MOUNTPOINT | mawk '$2=="/" {print $1}')
```

**Comment by sal666** [comment]
@MichaIng 
> `lsblk -npo PKNAME $(findmnt -no SOURCE /)` as mentioned above does not work on RPi somehow. What can be done:
> 
> ```
> ROOTFS_DEVICE=$(lsblk -npo PKNAME,MOUNTPOINT | mawk '$2=="/" {print $1}')
> ```

You're right. In fact that's almost my original proposal:
`ROOTFS_DEVICE=$(lsblk -rnpo PKNAME,MOUNTPOINT | grep ' /$' | mawk '{print $1}')`
But your version is more efficient :+1:

In my case `lsblk -npo PKNAME $(findmnt -no SOURCE /)` won't work because I'm using Berryboot as a boot manager thus / is mounted on a aufs.

**Comment by MichaIng** [comment]
@sal666 
Okay should be fine with last commit. If you agree, I will merge.

**Comment by sal666** [comment]
LGTM, go ahead!

**Pull request merged**
