### PR TITLE
Update dietpi.txt

### PR DESCRIPTION
**Pull request by cocoflan**
**Status**: WIP | Testing | Ready | ?
- [ ] Example task 1

**Reference**: https://github.com/MichaIng/DietPi/issues/XXXX

**Commit list/description**:

- ...

### CODE REVIEW

**Comment by MichaIng** [comment]
@cocoflan 
This does not contain any change? And please do changes always against the `dev` branch. It will be merged into `beta` once the beta phase starts.

**Comment by Joulinar** [comment]
@MichaIng 
anyway, I guess it would need to be updated. At least the first lines

```
# - Modifications to /boot/dietpi.txt will not be preserved on reboot.
# - Please ensure you edit from the DietPi-RAMdisk location: /DietPi/dietpi.txt
```

With v6.29 file will be relocated to `/boot/` isn't it?

**Comment by MichaIng** [comment]
@Joulinar 
> At least the first lines

This has already been done in `dev` branch 😉.

**Comment by Joulinar** [comment]
Ah ok I didn't checked that. Sorry

**Pull request closed without merging**
