### PR TITLE
DietPi-Software | OpenSSH: Host key regeneration quirks

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready
- [x] Decide if skipping regeneration on reinstall is even better
- [x] Changelog
- [x] Make `dietpi-software install 104/105` as well stop SSH services and mark the other SSH server for uninstall.

**Testing**:
- 🈯️ Jessie: Install Dropbear => OpenSSH, OpenSSH => Dropbear, boot order
- 🈯️ Stretch: Install Dropbear => OpenSSH, OpenSSH => Dropbear, boot order

**Retest**:
- [x] Stretch: Choice system via menu
- [x] Stretch: Choice system via `dietpi-software install/uninstall`
- [x] Jessie: Choice system via menu
- [x] Jessie: Choice system via `dietpi-software install/uninstall`

**Reference**: https://github.com/Fourdee/DietPi/issues/2375

**Commit list/description**:
+ DietPi-PreBoot | SSH servers: Regenerate distro/version default host keys via "dpkg-reconfigure"
+ DietPi-PreBoot | Start systemd unit before SSH servers, to have fresh SSH host keys for first session; It makes sense anyway to not start SSH servers before even "network-pre.target" has reached. Initramfs integration is another thing outside of systemd.
+ DietPi-Software | Dropbear: On Stretch, only install "dropbear-run", to match PREP as well
+ DietPi-Software | Dropbear: Generate ECDSA host key on Jessie, if not yet done before, since it is not done by default; Remove "/etc/dropbear" on uninstall, since with manually created host key, it is not removed by APT
+ DietPi-Software | OpenSSH: Do not recreate host keys on install, preserve existing ones
+ DietPi-Software | SSH servers: Enable services, just to be failsafe in case it got disabled at some point
+ DietPi-Software | SSH servers: Update SSH choice index, set uninstall marks and stop active SSH services during install step, to assure this is done as well when using: "dietpi-software install 104/105"
+ DietPi-Software | SSH servers: Always check for installed SSH servers via "dpkg", to assure uninstall is done as well for installs outside of dietpi-software
+ CHANGELOG | SSH servers: Host key generation and install rework
+ DietPi-Software | Init "local software_id=-1" to prevent potential issues since "0" is reserved for OpenSSH client

### CODE REVIEW

**Review by Fourdee — APPROVED** [review]
@MichaIng 

Very nice 👍 

Please merge when ready.

**Comment by MichaIng** [comment]
@Fourdee 
Okay I updated the choice system to be correctly applied as well when using `dietpi-software install/uninstall` and failsafe check for existing installs via `dpkg`.

Will do some final tests on new year. Happy new year to you and your family! 😃 🎆 🍾

**Comment by Fourdee** [comment]
@MichaIng 

>  Happy new year to you and your family! 

Thanks Micha, same to you, hope you had a good one? 😄 🥂

**Comment by MichaIng** [comment]
@Fourdee 
Jep, great celebration with friends 😃.

Okay PR passed local testing.

There is another minor improvement we could do:
- Allow install of Dropbear server + OpenSSH client.
- This basically means on OpenSSH server uninstall we leave OpenSSH client in place. Since Dropbear brings it's client as well (`dbclient`), there is little use for this, but in rare circumstances users might need the features of OpenSSH for client, but not server.
- OpenSSH SFTP server would be again the next step, since this can be even used with Dropbear server (which has no SFTP functionality otherwise).

But I don't want to implement this now. Adding SFTP to the file server offer can be combined with this with a later release.

**Pull request merged**
