### PR TITLE
Release v6.19.7 => v6.20.5

### PR DESCRIPTION
**Pull request by Fourdee**
#### Image line-up
- We removed Jessie images from our download server (besides for Odroid C1), since we see no advantage to use them anymore. Existing Jessie systems are still supported, but we encourage all users to consider switching to a fresh Stretch image by times: https://github.com/Fourdee/DietPi/issues/2332

#### Changes / Improvements / Optimisations
- DietPi-PREP | Removed the option to install a Jessie system. Removed the option to install DietPi on top of a Wheezy image, since an upgrade over two distro version would be required, which is not reliable. It is still possible to install DietPi on top of a Jessie image, where a distro upgrade to Stretch would be applied: https://github.com/Fourdee/DietPi/issues/2332
- General | RPi-Update: In our effort to improve system stability, and, offer software installations which build custom modules (eg: WireGuard), we can not longer support systems with non-stock APT kernel installed. If "rpi-update" is installed during update, DietPi will prompt and return you back to stock APT kernel.
- General | Moved the remaining conf/* files located on DietPi-RAMdisk to /var/lib/dietpi or into DietPi-PREP, and removed /DietPi/dietpi/conf completely. These files were only used once or never, thus have no business inside the RAMdisk.
- DietPi-Config | RPi: Improved available options for HDMI boost setting: https://github.com/Fourdee/DietPi/issues/2350
- DietPi-Config | RPi: Headless display mode is now applied via undocumented config.txt setting. Removed/Replaced some other obsolete config.txt entries: https://github.com/Fourdee/DietPi/pull/2402
- DietPi-Config | RPi: Added info to "hifiberry-dacplus" sound device overlay that it supports the AMP2 DAC. Thanks to @Lat Dior for reporting the issue and testing the solution: https://dietpi.com/phpbb/viewtopic.php?t=5396
- DietPi-Config | WiFi Hotspot: You can now toggle support for 802.11 N. Please note this is device and compatibility dependent, mileage may vary.
- DietPi-Drive_Manager | Now allows to check & repair the boot file system and trigger it for root file system on next reboot: https://github.com/Fourdee/DietPi/issues/1740#issuecomment-388325204
- DietPi-Software | AmiBerry: Updated to v2.24, thanks @midwan! Brings several bug fixes, new features and improvements over the previous version (2.19). Please check the version history for full details on the changes made: https://github.com/midwan/amiberry/wiki/Version-history
- DietPi-Software | DietPi-NordVPN: Now available for installation. Includes a GUI which allows for easy connection to a list of NordVPN servers 'dietpi-nordvpn'. If you need a NordVPN subscription, please use this link: https://go.nordvpn.net/aff_c?offer_id=15&aff_id=5305&url_id=902
- DietPi-Software | WireGuard VPN is now available for installation. Is can be easily configured as client or as server, passing either all client traffic through the tunnel, local network access only, or server access only, e.g. as well in combination with Pi-hole, to have remote ad blocking.
- DietPi-Software | SickRage has been replaced by Medusa, which is now available for install: https://github.com/Fourdee/DietPi/issues/2239
- DietPi-Software | Blynk: Reinstalls now preserve existing config files; New directory structure and blynk user (v6.19) is patched now as well to existing installs: https://github.com/Fourdee/DietPi/pull/2324
- DietPi-Software | Plex Media Server: Updated to v1.14.0 on x86 images, switch to HTTPS ARM repo and automated locale switch to en_US.UTF-8: https://github.com/Fourdee/DietPi/issues/2294
- DietPi-Software | Nextcloud Talk: Disabled the very verbose coturn logging by default to reduce disk I/O. This can be overridden via /etc/turnserver.conf: https://github.com/Fourdee/DietPi/issues/2321
- DietPi-Software | Deluge: UMask 002 applied to all downloads: https://github.com/Fourdee/DietPi/issues/2339
- DietPi-Software | Netdata: Updated to v1.11.1 and now runs as user "netdata": https://github.com/Fourdee/DietPi/pull/2337
- DietPi-Software | ownCloud/Nextcloud: Updated webserver configs to match current recommendations and security hardenings. Only applied on new installs. To apply manually, run "dietpi-software reinstall 47" (owncloud) or "dietpi-software reinstall 114" (Nextcloud). You will be informed about the new configs, which then need to be manually moved to overwrite the old ones, since we don't want to mess with manual changes: https://github.com/Fourdee/DietPi/pull/2361
- DietPi-Software | OpenSSH: Host keys won't be recreated anymore on reinstall, only on first boot of a fresh image, using now "dpkg-reconfigure openssh-server" to generate default key types based on distro.
- DietPi-Software | Dropbear: Now installs only the "dropbear-run" package on Stretch (and above), which matches the default DietPi setup on our images and PREP script.
- DietPi-Software | NAA Daemon: Updated to 3.5.5-39. Thanks to @volpone for the heads up: https://github.com/Fourdee/DietPi/issues/2387#issue-395321320
- DietPi-Software | MPD: Updated to 0.20.23-1. Includes support for NFS and Samba: https://github.com/Fourdee/DietPi/issues/2377
- DietPi-Software | MPD: Now runs as "mpd" user again, updated systemd unit to match official one and better handle existing cache and log files on reinstall: https://github.com/Fourdee/DietPi/issues/2378
- DietPi-Software | Samba: Moved disk cache to RAM to reduce disk I/O. Thanks to @WolfganP for suggesting this enhancement: https://github.com/Fourdee/DietPi/issues/2396
- DietPi-Software | Kodi RPi: Default GPU memory split is now 320MB for 1GB devices. This should improve overall performance and stability: https://github.com/Fourdee/DietPi/issues/2365
- DietPi-Software | Airsonic: Now installs the latest upstream version automatically: https://github.com/Fourdee/DietPi/pull/2410
- DietPi-Software | You will now receive a whiptail prompt, if config files are overwritten during software installations: https://github.com/Fourdee/DietPi/issues/2325
- DietPi-Software | NoMachine: Enabled ARMv8 support and will now install current version 6.4.6: https://github.com/Fourdee/DietPi/pull/2408
- DietPi-Software | Shairport Sync: Updated to 3.2.2 (previously 3.1.7): https://github.com/Fourdee/DietPi/issues/2439
- DietPi-Software | Gitea: New installations now install 1.7 (previously 1.4). Many thanks to @yumiris for this update! https://github.com/Fourdee/DietPi/pull/2448
- DietPi-Software | Grafana: Now the new official APT repo is used for all architectures (excluding ARMv6), which allows updates to the current upstream version (currently v5.4.3) as well. This change will be applied to existing installs on dietpi-update to v6.20. Thanks to @jvteleco for informing us: https://github.com/Fourdee/DietPi/issues/2449
- DietPi-Update | Added optional ability to automatically update DietPi, when updates are available. Please note, this is disabled by default.
- DietPi-Sync | Removed the compression option, which has no effect on local sync, since files are not stored compressed, but only transferred compressed through remote sync protocols, which are currently not offered by DietPi-Sync.
- DietPi-RAMlog/Logclear | The internally rotated LetsEncrypt (CertBot) log files are now removed, hourly with DietPi-RAMlog enabled, or when executing DietPi-Logclear manually.

#### Bug Fixes
- DietPi-Software | LXDE: Installation will no longer enable the weather application. This is due to Yahoo API hard coded into LXpanel, being taken offline: https://github.com/Fourdee/DietPi/issues/2416#issuecomment-456805925
- DietPi-Software | Nextcloud: Resolved an issue, where the Nextcloud Apache config was not downloaded correctly. Thanks to @Stefan3v for reporting this issue: https://github.com/Fourdee/DietPi/issues/2383
- DietPi-Software | ownCloud/Nextcloud (Talk): Resolved an issue, where occ/ncc commands could fail, if Redis server is not running: https://github.com/Fourdee/DietPi/issues/2321
- DietPi-Software | ownCloud/Nextcloud: Resolved an issue, where during fresh installs on v6.19, Apache configs were not enabled correctly.
- DietPi-Software | MPD: Resolved an issue on Stretch, where the mpd binary could not find the configuration file without giving it explicitely as argument. Thanks to @mfeif for reporting this issue: https://github.com/Fourdee/DietPi/issues/2378
- DietPi-Software | Mopidy: Resolved an issue, where playlist files could not be created due to missing permissions. Further improved handling of existing configs, data and cache directories on (re)install. Thanks to @cyberlussi for reporting this issue: https://github.com/Fourdee/DietPi/issues/2384
- DietPi-Software | Deluge: Resolved a visual-only error in systemd unit, since same-line comments are not allowed anymore. Thanks to @Gabba for reporting this issue: https://dietpi.com/phpbb/viewtopic.php?t=5378
- DietPi-Software | No-IP: Fixed an issue, where on "Generic device" (ID 22), the wrong binary could have been installed. As well added failsafe "/usr/local/[bin|etc]" directory pre-creation, in case not present on the system or manually removed by user. Thanks to @walker93 for reporting this issue: https://github.com/Fourdee/DietPi/issues/2426
- DietPi-Software | PHP: Resolved an issue where install fails on Stretch due to package name changes in the Debian repo. Thanks to @rox-wolf for reporting this issue: https://github.com/Fourdee/DietPi/issues/2438
- DietPi-Sync | Resolved an issue, where dry-run and compression options were not applied correctly. Thanks to @WilburWalsh for reporting the issue and identifying the faulty code: https://dietpi.com/phpbb/viewtopic.php?f=11&t=5347
- DietPi-Sync | Resolved an issue, where daily sync was not applied due to changed settings file scheme.
- DietPi-Config | RPi: gpu_mem_256/512 are now capped when being applied (to prevent value exceeding limits of each board type): https://github.com/Fourdee/DietPi/issues/2417
- DietPi-Config | Resolved a visual-only issue, where WiFi interface starts throw an error message about unsupported power management: https://github.com/Fourdee/DietPi/issues/2198
- DietPi-WiFi-Monitor | Resolved an issue, where DietPi-WiFi-Monitor stuck in a reconnection loop, if no valid WiFi interface was detected or the WiFi adapter is unplugged.
- DietPi-Cloudshell | Resolved an issue where CPU scene failed on VM and other devices that do not support CPU governors: https://github.com/Fourdee/DietPi/issues/2428
- DietPi-LetsEncrypt | Resolved an issue where Nginx and Apache modules are missing, if one installs CertBot first and the webserver afterwards on a separate dietpi-software run: https://github.com/Fourdee/DietPi/issues/2295
- General | Pinebook: Resolved issue with failed apt-get upgrades due to missing armbian-release data file. Also switched to stable kernel packages and kernel updates over APT are now enabled.
- General | Enhanced and fixed some issue with dependencies and boot order of DietPi systemd units: https://github.com/Fourdee/DietPi/pull/2357
- General | AudioPhonics I-Sabre-K2M: Once the driver is compiled, it will no longer be recompiled. This prevents ALSA installs from re-compiling the driver each time.
- General | Resolved an issue, where login with non-bash session caused an error message. Thanks to @Elijahg for reporting this issue: https://github.com/Fourdee/DietPi/issues/2347
- General | Resolved an issue where G_CHECK_URL would not terminate applications on failure. Also added option to retry + change networking options.

As always, many smaller code performance and stability improvements, visual and spelling fixes have been done, too much to list all of them here. Check out all code changes of this release on GitHub: https://github.com/Fourdee/DietPi/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+base%3Amaster

#### Known/Outstanding Issues
- DietPi-Config | Enabling WiFi + Ethernet adapters, both on different subnets, breaks WiFi connection in some cases: https://github.com/Fourdee/DietPi/issues/2103
- DietPi-Config | RPi | OpenGL/VC4 causes sound card selection to be invalid: https://github.com/Fourdee/DietPi/issues/2173
- RPi | LXAppearance (on LXDE desktop) hangs on dbus-launch: https://github.com/Fourdee/DietPi/issues/1791
- Pine A64 | No sound over 3.5mm jack: https://github.com/Fourdee/DietPi/issues/2153
- Odroid C2 | Some WiFi adapters do no work as hotspot: https://github.com/Fourdee/DietPi/issues/1955
- DietPi-Software | Node-RED: Pre-installed modules cannot be updated via webUI: https://github.com/Fourdee/DietPi/issues/2073
- DietPi-Software | Raspimjpeg: With Lighttpd, streaming mjpeg does not work: https://github.com/Fourdee/DietPi/issues/1747
- DietPi-Drive_Manager | encryptfs is currently not supported and will be removed from fstab, when executing drive manager: https://github.com/Fourdee/DietPi/issues/2078

For all additional issues that may appear after release, please see the following link and select the 'Next Version Milestone' to see active tickets: https://github.com/Fourdee/DietPi/milestones

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
I will take care the conflicts now, just to prevent we do this in parallel 😉.

**EDIT: Okay conflicts resolved back and fort.**

Do you know a way to force adding older master-only commits into dev? I tried with "`Sqash and merge`" as well as "`Create a merge commit`" Beta > Dev and in both cases all commits that were applied to beta, but not master, are listed, but they are not really added to `dev`. When comparing branches, the commits and related changes are shown again.
It "`Rebase and merge`" required or a PR directly from `master` to `dev` to resolve (e.g. directly after v6.20 release)?

I mean not critical, but when doing hotfix changes to beta or master directly, it would be good to do a backwards merge at some point to assure all branches are on the same stage. This is only 100% safe, if it does not show `XX commits behind <branch>`.

**Comment by Fourdee** [comment]
@MichaIng 

> Do you know a way to force adding older master-only commits into dev? 

I have no idea 🤣 

Usually I manually resolve conflicts. If that is near impossible, another option as last resort is to delete the branch and replace/refresh with ```dev``` at same time as release. Although, been a few years since I did that.

**Comment by MichaIng** [comment]
@Fourdee
I think I will try to merge master into beta and beta into dev directly after release, in case with rebase commits.

When doing hotfix to master, I think we should do them to beta first, merge into master and backwards into dev. Then when fixing in dev via usual patch_file, related pre-patch_file changes can be removed in dev. This assures when merging for next beta/release, that no conflicts or inconsistencies occur.

**Comment by Fourdee** [comment]
@MichaIng 

I'am happy to release this tonight, or, would you prefer we wait for tomorrow?

**Comment by MichaIng** [comment]
@Fourdee 
Let's go for it tonight 😃.

**Comment by Fourdee** [comment]
@MichaIng 

Great work on this release, really appreciate it 👍 💯 

https://twitter.com/DietPi_/status/1090006763393482752

**Comment by MichaIng** [comment]
@Fourdee 
Btw: The backwards commit merges have resolved themselves. Perhaps it just took a little while until all commits got attached correctly. Now when attempting to merge `master > beta`, `beta > dev` or `master > dev`, only the latest release commits are listed and no file differences, as it should be 👍.

**Pull request merged**
