### PR TITLE
v6.8

### PR DESCRIPTION
**Pull request by Fourdee**
**v6.8**
(13/05/18)

**Changes / Improvements / Optimizations:**

General | All future DietPi images (v6.8 and onwards), now has serial console enabled by default for the 1st run setup. It will be disabled automatically after first run setup to save on resources, unless 'CONFIG_SERIAL_CONSOLE_ENABLE=1' is set in dietpi.txt: https://github.com/Fourdee/DietPi/issues/1759

General | DietPi.com website: Server has been upgraded to Debian Stretch, featuring HTTPS redirect.

General | FBset is no longer a pre-req package for DietPi systems. This will be removed on fresh installations (not existing, to avoid any package conflicts): https://github.com/Fourdee/DietPi/issues/1716

General | DietPi login script and globals init moved to /etc/profile.d/99-dietpi-login.sh. Ensuring any user on system with sudo permissions can load them. Global commands are also now supported across multiple users, eg: either 'sudo -i G_AGI pacakge' or 'G_SUDO G_AGI package': https://github.com/Fourdee/DietPi/issues/1477

General | G_WHIP*: Improved scaling detection based on character count and line count. We now also calculate character count per line, to determine if additional lines are required against X. In other words, it should be a more 'snug' fit :) https://github.com/Fourdee/DietPi/issues/1740

DietPi-Automation | 'AUTO_SETUP_RAMLOG_MAXSIZE' added to dietpi.txt. Sets max /var/log tmpfs size during 1st run. Requires v6.8 or higher image.

DietPi-Config | Native PC > Soundcard: 'firmware-intel-sound' is now installed automatically for Intel based CPUs.

DietPi-Drive_Manager | Added ability to adjust reserved blocks percentage on ext4 file system: https://github.com/Fourdee/DietPi/issues/1662

DietPi-Drive_Manager | Added ability to check and optionally repair a filesystem. Many thanks to MonZon for the feature request! rootFS and /boot checks will be added in v6.9, currently additional drives are supported by this feature https://github.com/Fourdee/DietPi/issues/1740

DietPi-Drive_Manager | Enabled access for virtual machines: https://github.com/Fourdee/DietPi/issues/1765

DietPi-LetsEncrypt | Lighttpd: SSL configuration upgrade according to Mozillas SSL generator: https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=lighttpd-1.4.35&openssl=1.0.1t&hsts=yes&profile=intermediate

DietPi-LetsEncrypt | Minor code and error handling improvements, as well increasing transparency of what the script is currently doing: https://github.com/Fourdee/DietPi/pull/1738

DietPi-Process_tool | Rewrite of save file, to allow for stringed entries. The save file will be cleared during the update, to support this feature: https://github.com/Fourdee/DietPi/issues/1750

DietPi-Process_tool | Added Plex Media Server to process tool, however, transcoding will not be affected by this: https://github.com/Fourdee/DietPi/issues/1750#issuecomment-386826317

DietPi-Set_Hardware | Allo Piano firmware is now installed on demand and will be removed on update, if not chosen as soundcard: https://github.com/Fourdee/DietPi/issues/1656

DietPi-Software | AmiBerry (Amiga Emulator): Updated to v2.19, contains bug fixes and improvements: https://github.com/Fourdee/DietPi/issues/1707#issue-314377609

DietPi-Software | Chromium: No longer requires a desktop and can be installed as a lightweight single use program, using dietpi-autostart to run under kiosk mode. Many thanks to @AYapejian! 720p is the default window size, please see '/var/lib/dietpi/dietpi-software/installed/chromium-autostart.sh' for full options when running under 'dietpi-autostart' mode: https://github.com/Fourdee/DietPi/issues/1737

DietPi-Software | Readymedia (MiniDLNA): Removed ALSA pre-req as it is not required. Many thanks to @bokiroki: https://github.com/Fourdee/DietPi/issues/1712

DietPi-Software | Pi-hole: Enabled support for FTLDNS: https://github.com/Fourdee/DietPi/issues/1696

DietPi-Software | Gitea: Updated to latest version (1.4), for new installations only. Many thanks to @yumiris: https://github.com/Fourdee/DietPi/pull/1723

DietPi-Software | PHPBB3: Latest version update (3.2.2), for new installations only.

DietPi-Software | Docker: Enabled for ARMv8 devices: https://github.com/Fourdee/DietPi/issues/1736

PREP | G_HW_MODEL: Added for 'OrangePi PC Plus'. Many thanks to @SuBLiNeR: https://github.com/Fourdee/DietPi/pull/1704

PREP | Optimized rootfs re-partition and resize. This will reduced the required initial system reboot count by one. Will take affect from official v6.8 DietPi images and onwards.

**Bug Fixes:**

General | Remote SCP/Rsync fix when running under 'dietpi' user: https://github.com/Fourdee/DietPi/issues/1703

General | ASUS TB: Resolved issues with onboard WiFi not being detected. Our latest image is required for this fix due to kernel: https://github.com/Fourdee/DietPi/issues/1760

General | Sparky SBC: Unmute USB-DAC audio fix applied during boot. Many thanks to @sudeep.

DietPi-Config | RPi onboard sound: Resolved an issue where changing from 3.5mm output back to auto, would not have any effect.

DietPi-Config | Resolved an error when selecting 'Sample Rate' CPU option.

DietPi-Drive_Manager | Resolved issues with incorrect detection of drives and mounts on Debian Stretch: https://github.com/Fourdee/DietPi/issues/1748

DietPi-Drive_Manager | Resolved issues RootFS transfer being stuck in a endless rsync loop: https://github.com/Fourdee/DietPi/issues/1748

DietPi-Drive_Manager | Resolved an issue where setting read only/write modes had no effect on fstab entries. This affected recent images only: https://github.com/Fourdee/DietPi/issues/1758

DietPi-Justboom | ALSA must now be installed, and /etc/asound.conf must exist, before this application can be run.

DietPi-LetsEncrypt | Now skips any webserver configuration edit, if CertBot execution returns with error: https://dietpi.com/phpbb/viewtopic.php?f=11&t=1909

DietPi-Software | Pi-SPC: PATH fix for sds.sh.

DietPi-Software | WiringPi: Now installed to '$HOME/WiringPi', previously this would be wiringPi-HEAD-8d188fa.

DietPi-Software | XRDP: Resolved an issue with blue screen running under Xorg. VNC4 is now installed by default, and the new connection method is 'Xvnc': https://github.com/Fourdee/DietPi/issues/1727#issuecomment-383858979

DietPi-Software | AmiBerry: Fix for standard boot SDL2 keyboard leaking to background. Please note fast boot is still affected by the SDL2 keyboard leak: https://github.com/Fourdee/DietPi/issues/1707

**Allo GUI v7:**
- Resolved errors with swapfile display/change.
- Resolved issues with CPU gov not being correctly applied.

### CODE REVIEW

**Comment by slim0287** [comment]
I updated to 6.8, and when I ssh into my Raspberry Pi 2, I get the following error:

`-sh: 146: /DietPi/dietpi/func/dietpi-globals: Syntax error: Bad function name`

If I understood linux better I'd figure out specifically what 146 refers to (i.e., is it line of the file?  executable line of the script?) and put it into this message.  However, any guidance would be appreciated.

Thanks.

**Comment by Fourdee** [comment]
@slim0287 

Thanks for the report 👍 

Number indicates line, the code is ```G_DIETPI-NOTIFY```, maybe it doesn't like the ```-```?

Although, fine with Putty/Kitty.

Which SSH client are you using?

**Comment by slim0287** [comment]
I'm using SSH from macOS.  I'll also try from a Linux box later today.

**Comment by slim0287** [comment]
I get the same error when ssh'ing in from a Linux Mint 18.3 desktop as well.  How should I address the error?

Thanks.

**Comment by Fourdee** [comment]
@slim0287 

Thanks for info 👍 . We'll open a new ticket and start investigations.

**Comment by Fourdee** [comment]
REF: https://github.com/Fourdee/DietPi/issues/1776#issue-323167048

**Comment by slim0287** [comment]
I have one other issue with v6.8.  Prior to this version, when I went to the super user with `sudo su` I would get a "welcome page" to super user from DietPi listing DietPi configuration and software commands, etc.  I no longer get that welcome page.   Not a major issue, but it is a different behavior.

**Comment by MichaIng** [comment]
@slim0287 @Fourdee 
Puhh, seems the move from `~/.bashrc` to `/etc/profile.d/99-dietpi-login` causes more issues than it solves.
- I don't like `~/.bashrc` being called by non-interactive shells as well and being user specific, but `/etc/profile.d/*` get's called on non-login shells, only, which is really only shells where you need to login with unix user, no sub shells like `sudo su`, screen or desktop terminals.
- The only shell configuration for only interactive and non-login shells seems `/etc/bash.bashrc` because of `[ -z "$PS1" ] && return`. Sadly there is no split config folder available... Diskussion without result for several years: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=675008
- Further ref: https://yeupou.wordpress.com/tag/etcbash-bashrc/

On other distros (RedHead) `/etc/bashrc.d/` seems to be implemented as above. Some packages even seem to link or add their shell config files to that folder, if it exists. We could create this by ourself and allow not only our aliases and G_ commands to be available on XTerm, Mate terminal, screen etc. but also `bash-completion` e.g. which has the same problem. Would love to not need to adjust maintainer shipped files directly, but in this case I see no other good solution, besides turning as much as possible into login shells, as mentioned here: https://github.com/Fourdee/DietPi/issues/1777#issuecomment-389987640

**Comment by Fourdee** [comment]
@MichaIng 

> Puhh, seems the move from ~/.bashrc to /etc/profile.d/99-dietpi-login causes more issues than it solves.

Yep, seems we found that out the hard way by trying to do it right way 😃

**Pull request merged**
