### PR TITLE
DietPi-Software | Minor code improvements

### PR DESCRIPTION
**Pull request by MichaIng**
+ DietPi-Software | ownCloud/Nextcloud: Minor install code improvements, use of G_CONFIG_INJECT
+ DietPi-Software | Minor code improvements
+ DietPi-Software | Mark NTP as installed on images by default
+ DietPi-Software | Assure all pre-req software being reinstalled

**WIP: Testing needed**

@Fourdee 
When checking for pre-req software, we do in most cases not check, if the dependency software title is already installed and set status =1 in every case. If I am not wrong, this leads to a reinstall of the related dependency. E.g. SQLite will be reinstalled every time, another title is installed that requires SQLite: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L2909-L2925

Could be desired, if configuration depends on the other installed titles, on the other hand in many cases we should be able to skip it, in some cases it might be even dangerous, if user made manual adjustments e.g.?

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

> this leads to a reinstall of the related dependency.

Correct, we always re-run pre-reqs during installs, few reasons for this:
- Ensures that even if DietPi considers it installed, if the user manually removed it from APT/system, it always gets installed
- Running ```G_AGI``` won't reinstall if its already installed.

Its basically a "cover all" to ensure we do not see tickets, with cause due to missing pre-reqs and unexpected manual system changes outside our scripts.

I did consider changing our installed state to a detection system, but:
- Would slow down the script vastly
- Due to the various APT, ZIP installs across multiple devices, would be a nightmare to maintain and error prone.

**Comment by MichaIng** [comment]
@Fourdee 
Ah okay, for MariaDB reinstall was not the case, I guess as this check previously included MySQL and we checked which one was installed. I will remove the checks from the script, especially since MariaDB installation now carefully handles existing databases.

€: Removed some other existing checks as well, uncritical as these are low level pre-reqs.

**Comment by Fourdee** [comment]
@MichaIng 

Looking good, great work 👍 

Will merge for testing. I'll run some owncloud/nextcloud installs + reinstalls.

**Comment by Fourdee** [comment]
Installs:
- NextCloud + UI test
-- external web issues:
```
Log file contents:
Spider mode enabled. Check if remote file exists.
--2018-04-26 13:51:59--  https://download.nextcloud.com/server/releases/latest.zip
Resolving download.nextcloud.com (download.nextcloud.com)... 88.198.160.133
Connecting to download.nextcloud.com (download.nextcloud.com)|88.198.160.133|:443... connected.
Unable to establish SSL connection.
```
- 🈯️ Owncloud + UI test

Reinstalls:
- NextCloud + UI test
- 🈯️ OwnCloud + UI test

**Pull request merged**
