### PR TITLE
DietPi-Start_Kodi | On RPi 64-bit systems, do not try to start Kodi without X server

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Reference**: https://dietpi.com/phpbb/viewtopic.php?t=9030

**Commit list/description**:
+ DietPi-Start_Kodi | On RPi 64-bit systems, do not try to start Kodi without X server

### CODE REVIEW

**Comment by MichaIng** [comment]
I wonder why this hasn't been recognised before. I guess since starting it from desktop still succeeds, where a wrapping X server session is present.

**Comment by Joulinar** [comment]
I could review it on the evening only as I'm out atm. Hope it's still fine for the release.

**Comment by Joulinar** [comment]
Kodi is starting without issues using auto-start as user `root`. These are the running processes 

```
root@DietPi4:~# ps -ef|grep kodi
root       562   554  0 21:59 tty1     00:00:00 xinit /usr/bin/kodi --standalone
root      1021   562  0 21:59 tty1     00:00:00 /bin/sh /usr/bin/kodi --standalone
root      1023  1021 13 21:59 tty1     00:00:04 /usr/lib/aarch64-linux-gnu/kodi/kodi.bin --standalone
```

**Review by Joulinar — APPROVED** [review]

**Comment by MichaIng** [comment]
Perfect, I also ran a few dry runs on RPi 2 and it all behaves as expected. xinit is invoked on 64-bit RPi systems, what we wanted.

**Pull request merged**
