### PR TITLE
Make spelling consistent in file

### PR DESCRIPTION
**Pull request by stevejenkins**
Changed "finalise" to "finalize" in two places.

**Status**: Ready

**Reference**: N/A (just a simple wording fix)

**Commit list/description**:
- Changed some post-installation wording.

### CODE REVIEW

**Comment by MichaIng** [comment]
@stevejenkins 
Thanks for your PR.

Just checked, `finalise` seems to be BE, while `finalize` is AE. Since DietPi/Fourdee is from GB, the first fit's better? I remember also preferring BE spelling in other text, but this might be not yet the case in several strings (e.g. I am no native English speaker 😉) and it makes sense to align everything either to BE or AE
__________
Searching code:
- NB: `dietpi-software` is never included, I guess since it is too large 🙄.
- https://github.com/Fourdee/DietPi/search?q=finalise&type=Code
- https://github.com/Fourdee/DietPi/search?q=finalize&type=Code

**Comment by Fourdee** [comment]
@stevejenkins 

Many thanks for your PR 👍 

Yep, as @MichaIng has mentioned, DietPi is British English (most of the time 🤣), however, we should replace all references of ```finalize``` to ```finalise```.

**Comment by MichaIng** [comment]
@stevejenkins 
I added finalize => finalise commit. Will merge and go though the other scripts, as above.
Thanks again for the wording hint 😃!

**€: Ah PR was opened against `master` branch, please always open again `dev`.
Needed to rebase with some conflict commits, but those would have been necessary anyway when merging into master on release.**

**Comment by MichaIng** [comment]
Adjusted further occurrences: https://github.com/Fourdee/DietPi/commit/414aac7bf1c38e771f29b2cc04aa45c0232a3da8 + https://github.com/Fourdee/DietPi/commit/56dd1a787f9b39fb4a8923014d9e9b78bd9d9ef1

**Comment by Fourdee** [comment]
@stevejenkins 

Please email me your address, I'll send over some DietPi stickers for this first PR:
daniel.knight@dietpi.com

**Pull request merged**
