### PR TITLE
Image | Add support for NanoPi R6S

### LINKED ISSUE #5981: Image for NanoPi R6S contains dev branch in dietpi.txt
#### Required Information
- NanoPi R6S

#### Additional Information (if applicable)
Contents of /boot/dietpi.txt contains `DEV_GITBRANCH=dev` (should be `DEV_GITBRANCH=master`).

Need to be fixed with Release of DietPi v8.12

### PR DESCRIPTION
**Pull request by MichaIng**
- NanoPi R6S | Support for FriendlyELEC's new flagship router SBC has been added to DietPi with hardware ID 79. Many thanks to FriendlyELEC for sending us free developer samples.

### CODE REVIEW

**Comment by MichaIng** [comment]
```console
root@DietPi:/tmp# cat /var/lib/dietpi/dietpi-benchmark/results
BENCH_HW_MODEL=79
BENCH_CPU='1.86'
BENCH_ROOTFS_WRITE='45'
BENCH_ROOTFS_READ='58'
BENCH_RAM_WRITE='1251'
BENCH_RAM_READ='2565'
BENCH_CPU_TEMP_START='32'
BENCH_CPU_TEMP_END='41'
...
root@DietPi:/tmp# cat /var/lib/dietpi/dietpi-benchmark/results
BENCH_HW_MODEL=79
BENCH_CPU='1.86'
BENCH_ROOTFS_WRITE='45'
BENCH_ROOTFS_READ='59'
BENCH_RAM_WRITE='1241'
BENCH_RAM_READ='2629'
BENCH_CPU_TEMP_START='32'
BENCH_CPU_TEMP_END='41'
```
RAM reads are slower, but RAM writes are a little faster compared to Radxa ROCK 5B: https://github.com/MichaIng/DietPi/discussions/5247#discussioncomment-4237315

Otherwise very comparable performance. This was with Bullseye on SD card, now testing on eMMC (with Bookworm image).

**Comment by MichaIng** [comment]
```console
root@NanoPiR6S:~# cat /var/lib/dietpi/dietpi-benchmark/results
BENCH_HW_MODEL=79
BENCH_CPU='2.04'
BENCH_ROOTFS_WRITE='125'
BENCH_ROOTFS_READ='212'
BENCH_RAM_WRITE='1239'
BENCH_RAM_READ='2637'
BENCH_CPU_TEMP_START='32'
BENCH_CPU_TEMP_END='40'
```
Repeated 3 times, always 2.04 seconds for CPU test, while on Bullseye it was 3 times 1.86 seconds. I cannot imagine that it makes a difference whether the systems runs from eMMC or SD card, hence I think Bullseye vs Bookworm makes the difference, i.e. Bookworm performs worse 🤔.

**Comment by Joulinar** [comment]
my RootFS write seems to be extremely slow

```
root@DietPiR6S:~# cat /var/lib/dietpi/dietpi-benchmark/results
BENCH_VERSION=2
BENCH_HW_MODEL=79
BENCH_CPU='2.09'
BENCH_ROOTFS_WRITE='13'
BENCH_ROOTFS_READ='58'
BENCH_RAM_WRITE='1236'
BENCH_RAM_READ='2624'
BENCH_CUSTOMFS_WRITE='Not tested'
BENCH_CUSTOMFS_READ='Not tested'
BENCH_CPU_TEMP_START='27'
BENCH_CPU_TEMP_END='36'
BENCH_NET_LAN_SPEED='Not tested'
root@DietPiR6S:~#
```

**Comment by Joulinar** [comment]
ok found the issue. System was running of SD card still. Switching to eMMC fixed it 🤣 

```console
root@DietPiR6S:~# cat /var/lib/dietpi/dietpi-benchmark/results
BENCH_VERSION=2
BENCH_HW_MODEL=79
BENCH_CPU='2.09'
BENCH_ROOTFS_WRITE='125'
BENCH_ROOTFS_READ='207'
BENCH_RAM_WRITE='1259'
BENCH_RAM_READ='2598'
BENCH_CUSTOMFS_WRITE='Not tested'
BENCH_CUSTOMFS_READ='Not tested'
BENCH_CPU_TEMP_START='27'
BENCH_CPU_TEMP_END='35'
BENCH_NET_LAN_SPEED='Not tested'
root@DietPiR6S:~#
```

**Comment by Joulinar** [comment]
Not sure why but I'm only getting 100Mbps on all Ethernet interface

```
Dec 17 12:49:06 DietPiR6S kernel: rk_gmac-dwmac fe1c0000.ethernet eth0: Link is Up - 100Mbps/Full - flow control off
```

**Comment by MichaIng** [comment]
Thanks for your tests and benchmarks. Quite consistent.

> Failed to connect to bus: No such file or directory

You used the Bookworm image, right? On Bookworm this is normal since a while. I didn't check yet whether this dbus connection attempt can be omitted or not, and what it is actually done for (given that no systemd-logind is used). Probably we need to have it installed/running OOTB on DietPi with Bookworm.

**Comment by Joulinar** [comment]
Yap was the bookworm image.

**Pull request merged**
