### PR TITLE
DietPi-Software | MotionEye: Enable Python 3 support

### LINKED ISSUE #4753: DietPi-Software | motionEye: Enable Python 3 support
DietPi-Software | MotionEye: Enable Python 3 support #4671 

Maybe use docker version of motioneye for the moment till it is fixed.

https://github.com/ccrisan/motioneye/wiki/Install-in-Docker

Tested and works on bullseye with docker on an x86 running bullseye 7.6.2, maybe a temporary solution.

install sudo apt-get install v4l-utils on your system and add     --device=/dev/video0\ in docker run command

docker run --name="motioneye" \
    -p 8765:8765 \
    --hostname="motioneye" \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/motioneye:/etc/motioneye \
    -v /var/lib/motioneye:/var/lib/motioneye \
    --restart="always" \
    --detach=true \
   --device=/dev/video0\
    ccrisan/motioneye:master-amd64

Greetings

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Testing

**Reference**: https://dietpi.com/phpbb/viewtopic.php?t=9308

**Commit list/description**:
+ DietPi-Software | MotionEye: Enable Python 3 support via experimental python3 branch

### CODE REVIEW

**Comment by MichaIng** [comment]
Okay, so while it installs and starts and the web UI is accessible, it lacks essential functionality, e.g. V4L2 (common USB) cameras are not listed, admin passwords cannot be set etc. There are PRs open to fix many of these issues, so it basically requires some activity of the maintainer to test and merge them:
- https://github.com/ccrisan/motioneye/pull/2013
- https://github.com/ccrisan/motioneye/pull/2177
- https://github.com/ccrisan/motioneye/pull/1978
- https://github.com/ccrisan/motioneye/pull/1805

We're not going to re-implement EOL Python 2 support and ship deprecated insecure software where every tool fires warnings about for a long time already (most notably pip), that's for sure. Anyone who is interested in MotionEye on Bullseye, which includes me as it is actually awesome software, you may use this PR for testing. If you're able to, send small PRs to fix individual issues related to Python 3, so we hopefully can get things going forward.

**Comment by Joulinar** [comment]
@MichaIng 
Are you planning to keep this branch update or will it stay on 7.5 until a solution has been found?

**Comment by MichaIng** [comment]
I'll update it on each stable release at least. To make testing for interested users as save as possible, I think its good to not merge dev branch stages into it. And I don't expect MotionEye Python 3 support to be sufficiently stable soon, to be true, given the amount of open PRs while the python3 branch got its last merge soon a year ago.

**Comment by Joulinar** [comment]
I agree not to merge dev or beta brach.

**Comment by TheRaven500** [comment]
What files need to be replaced? My problem is that i don't know how to apply all patches for phy3. ATM i have only replaced "v4l2ctl.py" (i hope with the right one). And this way my v4l2 cameras are not working.

**Comment by MichaIng** [comment]
Just that we have a common bases: You migrated your DietPi system to this branch and then installed or reinstalled MotionEye? I.e.
```sh
G_DEV_BRANCH motioneye
dietpi-software install 136
```

On top of that, replacing this once file should be sufficient indeed to get the camera list, especially as the underlying used tool `v4l2-ctl --list-devices` in your case list those successfully. If this does still not work, can you check for service errors, please:
```sh
journalctl -u motioneye
```

**Comment by TheRaven500** [comment]
I updated my Dietpi from Buster to Bullseye.
Then i ran "G_DEV_BRANCH motioneye" and "dietpi-software install 136".
After that i tried to add camera via webif without success (no cameras where listed).
So i rebooted the Pi. But still does not work.
The log looks like that:
root@VideoServer1:~# journalctl -u motioneye
Journal file /var/log/journal/cff038c9da334118b7471615c7412902/system.journal is truncated, ignoring file.
-- Journal begins at Tue 2021-07-13 19:29:24 CEST, ends at Sat 2021-08-28 22:29:10 CEST. --
Aug 28 22:27:06 VideoServer1 systemd[1]: Started motionEye Server.
Aug 28 22:27:08 VideoServer1 meyectl[493]:     INFO: hello! this is motionEye server 0.42
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: main config file /etc/motioneye/motion.conf does not exist, using default values
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: cleanup started
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: wsswitch started
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: tasks started
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: mjpg client garbage collector started
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: server started
Aug 28 22:28:57 VideoServer1 meyectl[1004]: /bin/sh: 1: lsb_release: not found
Aug 28 22:29:10 VideoServer1 meyectl[493]: /usr/lib/python3.9/subprocess.py:941: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
Aug 28 22:29:10 VideoServer1 meyectl[493]:   self.stdout = io.open(c2pread, 'rb', bufsize)
And when i try again to add camera and switch to MMAL, it looks like this:
root@VideoServer1:~# journalctl -u motioneye
Journal file /var/log/journal/cff038c9da334118b7471615c7412902/system.journal is truncated, ignoring file.
-- Journal begins at Tue 2021-07-13 19:29:24 CEST, ends at Sat 2021-08-28 22:29:51 CEST. --
Aug 28 22:27:06 VideoServer1 systemd[1]: Started motionEye Server.
Aug 28 22:27:08 VideoServer1 meyectl[493]:     INFO: hello! this is motionEye server 0.42
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: main config file /etc/motioneye/motion.conf does not exist, using default values
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: cleanup started
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: wsswitch started
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: tasks started
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: mjpg client garbage collector started
Aug 28 22:27:10 VideoServer1 meyectl[493]:     INFO: server started
Aug 28 22:28:57 VideoServer1 meyectl[1004]: /bin/sh: 1: lsb_release: not found
Aug 28 22:29:10 VideoServer1 meyectl[493]: /usr/lib/python3.9/subprocess.py:941: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
Aug 28 22:29:10 VideoServer1 meyectl[493]:   self.stdout = io.open(c2pread, 'rb', bufsize)
Aug 28 22:29:46 VideoServer1 meyectl[493]: /usr/lib/python3.9/subprocess.py:941: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
Aug 28 22:29:46 VideoServer1 meyectl[493]:   self.stdout = io.open(c2pread, 'rb', bufsize)
Aug 28 22:29:48 VideoServer1 meyectl[493]:    ERROR: a bytes-like object is required, not 'str'
Aug 28 22:29:48 VideoServer1 meyectl[493]: Traceback (most recent call last):
Aug 28 22:29:48 VideoServer1 meyectl[493]:   File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1548, in _stack_context_handle_exception
Aug 28 22:29:48 VideoServer1 meyectl[493]:     raise_exc_info((type, value, traceback))
Aug 28 22:29:48 VideoServer1 meyectl[493]:   File "<string>", line 4, in raise_exc_info
Aug 28 22:29:48 VideoServer1 meyectl[493]:   File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1756, in wrapper
Aug 28 22:29:48 VideoServer1 meyectl[493]:     result = method(self, *args, **kwargs)
Aug 28 22:29:48 VideoServer1 meyectl[493]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/handlers.py", line 275, in get
Aug 28 22:29:48 VideoServer1 meyectl[493]:     self.list()
Aug 28 22:29:48 VideoServer1 meyectl[493]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/handlers.py", line 206, in wrapper
Aug 28 22:29:48 VideoServer1 meyectl[493]:     return func(self, *args, **kwargs)
Aug 28 22:29:48 VideoServer1 meyectl[493]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/handlers.py", line 608, in list
Aug 28 22:29:48 VideoServer1 meyectl[493]:     cameras = [{'id': d[0], 'name': d[1]} for d in mmalctl.list_devices()
Aug 28 22:29:48 VideoServer1 meyectl[493]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/mmalctl.py", line 42, in list_devices
Aug 28 22:29:48 VideoServer1 meyectl[493]:     d = dict(p.split('=', 1) for p in support.split())
Aug 28 22:29:48 VideoServer1 meyectl[493]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/mmalctl.py", line 42, in <genexpr>
Aug 28 22:29:48 VideoServer1 meyectl[493]:     d = dict(p.split('=', 1) for p in support.split())
Aug 28 22:29:48 VideoServer1 meyectl[493]: TypeError: a bytes-like object is required, not 'str'
Aug 28 22:29:48 VideoServer1 meyectl[493]:    ERROR: 500 GET /config/list/?_=1630182588476&username=admin&password=PASSWORD&proto=mmal&_username=admin&_signature=SIGNATURE (IPADRESS) 73.18ms
Aug 28 22:29:51 VideoServer1 meyectl[493]: /usr/lib/python3.9/subprocess.py:941: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
Aug 28 22:29:51 VideoServer1 meyectl[493]:   self.stdout = io.open(c2pread, 'rb', bufsize)

**Comment by MichaIng** [comment]
Okay, the first looks like you didn't apply the V4L2 patch yet, please try:
```sh
systemctl stop motioneye
rm -R /usr/local/lib/python3.9/motioneye/__cache__
curl -sSfL 'https://raw.githubusercontent.com/ccrisan/motioneye/bb89334/motioneye/v4l2ctl.py' -o /usr/local/lib/python3.9/dist-packages/motioneye/v4l2ctl.py
systemctl start motioneye
```

**Comment by TheRaven500** [comment]
rm -R /usr/local/lib/python3.9/motioneye/__cache__
**Dies not exist. Do you mean:** /usr/local/lib/python3.9/dist-packages/motioneye/__pycache__ **instead?**

**Comment by MichaIng** [comment]
Ah yes sorry, `__pycache__` should have been it. Okay great that this part works now.

The first error on our log looks pretty much like the same as with V4L2 before the fix. So we can try to apply the exact same fix for this, if the code matches or I'm able to understand it good enough to abstract it. The second looks like a type error which should be easy to fix. I'll try to fix it locally and send a PR then, so you can test it as well.

**Comment by TheRaven500** [comment]
Unfortunately i have no clue about phyton. So i hope you can find a solution. :-)

**Comment by TheRaven500** [comment]
Small update:
I updated my server to bullseye. The server is for recording and managing the cameras (mjpeg only).
As expected motioneye does not run after the update because py3 is missing.
So i updated motioneye with the py3 version and it is working so far!
It looks like mjpeg streams are ok.

**Comment by TheRaven500** [comment]
Hmm, why does ccrisan not commit this patches? Busy?
Better a "buggy" than a "non working" version of motioneye in phyton3 if you ask me.

**Comment by cocoflan** [comment]
Maybe use docker version of motioneye for the moment till it is fixed.

https://github.com/ccrisan/motioneye/wiki/Install-in-Docker

Greetings

**Comment by TheRaven500** [comment]
I need to downgrade. Last week a thief was on my way and I was lucky that this camera was still running with buster and python2. Luckily he was filmed. If there is any progress i will upgrade again to test.

**Comment by Joulinar** [comment]
I doubt we could fix it as log as MotionEye developer is not working on it.

**Comment by TheRaven500** [comment]
i wrote him an email. But yes, unfortunately I fear that too.

**Comment by MichaIng** [comment]
An alternative would be a fork.

**Comment by Joulinar** [comment]
But is this something we can manage from resourcing point of view?

**Comment by TheRaven500** [comment]
Bad news, he answered and told me that he don't have time and in the near future there will be no official python3 support :-1: 
Not what i like to hear, because motioneye is a really nice tool.
So it looks like the only way is a fork of it. But uh, i am not a coder. After bash my skills end soon.

**Comment by cocoflan** [comment]
maybe an alternative https://moeiscool.github.io/Shinobi/

**Comment by Joulinar** [comment]
But the install script is not taking Debian into account. Looks like it's checking for Ubuntu.

**Comment by cocoflan** [comment]
Just an alternative, not debian compatible i see, only docker.

**Comment by cocoflan** [comment]
> I don't think shinobi is an alternative for me. I like mjpeg streams and I don't like cloud stuff. That's why I stay with motioneye. The only problem from motioneye is the python language. If someone will port it to python3, at the latest when python4 arrives it will be outdated again. Because of that i really hate python, java, dotnet and all similar coding languages. But the only way to keep motioneye is to port it to python3 ATM.


Yes

**Comment by Joulinar** [comment]
not sure if this is an alternative, but at least it seems to be working https://dietpi.com/phpbb/viewtopic.php?p=41061#p41061

**Comment by MichaIng** [comment]
Awesome, it is a fork off the python3 branch, just like I planned it. Probably still worth to compare with latest comments to MotionEye base branch and the open Python 3 requests. But just in case some other fixes/enhancements have been done at the original project, looks like it makes more sense to contribute/merge them into this fork instead of maintaining an own one.

**Comment by TheRaven500** [comment]
Looks promising! I will try it for sure.

**Comment by Mictronics** [comment]
I have another python3 branch WIP: https://github.com/Mictronics/motioneye/tree/python3
Test environment see README.

**Comment by ovz93br43v7** [comment]
Probably a similar project which you could consider: https://github.com/electreeks/spyagent

**Comment by Joulinar** [comment]
@MichaIng 
Projekt has been closed https://github.com/ccrisan/motioneye/issues/2290

> Due to personal reasons I can no longer be actively involved with this project. If anyone is interested in taking it over, please contact me and we'll work out together a hand-off plan.

**Comment by MichaIng** [comment]
It is already disabled on all Bullseye and Bookworm systems. Not sure how the user was able to (attempt to) install it 🤔. We need to look through the forks.

**Comment by TheRaven500** [comment]
I had a thief visit again. For me it is therefore very important that there is a solution. ;-) I am not a coder (only bash) but if i can help in any way let me know (i have usb, mmal and network cameras).

**Comment by MichaIng** [comment]
@Mictronics 
Did you try to merge the upstream master/dev branch into your python3 branch, to get all recent changes? Also you could open all Python 3 related PRs from upstream at your repository. Make the related contributors aware/ask them within the PR, but generally should be fine (given the license 😉).

I wonder whether we should create a "motionEye" organisation to invite some more possible maintainers/developers and get somehow a more official looking fork/continuation. We can also ask @ccrisan whether he would hand over the original repository to this organisation, so visitors of the original repo get redirected automatically, it is not shown as fork but as original repo (which includes the sometimes helpful feature to search the source code via GitHub 😉). In this case your commits/fork would need to be merged again. What do you think?

**Comment by Mictronics** [comment]
@MichaIng I took the python3 branch at 25ee819 (29 Dec 2020) and start my fork development from there. I haven't merged anything into python3 branch from master/dev. However some changes from other python3 forks are include into mine. Things I found useful or that made sense for me.

**Comment by MichaIng** [comment]
Some further Python 3 related bugs are solved with PRs waiting/open at the upstream repo. Once is very large, but some are very targeted to fix specific syntax errors, hence should be trivial to merge.

The python3 branch is 47 commits behind dev, but I haven't reviewed the changes yet: https://github.com/ccrisan/motioneye/compare/python3...dev#files_bucket

**Comment by ccrisan** [comment]
> @Mictronics Did you try to merge the upstream master/dev branch into your python3 branch, to get all recent changes? Also you could re-open all Python 3 related PRs from upstream at your repository. Make the related contributors aware/ask them within the PR, but generally should be fine (given the license wink).
> 
> I wonder whether we should create a "motionEye" GitHub organisation to invite some more possible maintainers/developers and get somehow a more official looking fork/continuation. We can also ask @ccrisan whether he would hand over the original repository to this organisation, or even join himself, so visitors of the original repo get redirected automatically, it is not shown as fork but as original repo (which includes the sometimes helpful feature to search the source code via GitHub wink). In this case your commits/fork would need to be merged again. What do you think?

I'd be happy to hand over the project to whomever wants to take care of it. If anyone wants to create a GitHub organization around it, i'll be happy to support this move, whatever that implies. We can start considering that the "official" home for motionEye. However I don't have time to do any further development (nor PR reviews) for this project.

**Comment by MichaIng** [comment]
That is great.

@Mictronics 
Since you did a notable amount of work on your fork already, would it be feasible for you when we create an organisation, have the original repository handed over to it (GitHub then creates automatic redirects and it is not seen as fork but as original repo), merge your commits into it and then start working together on it? E.g. also trying to merge recent commits to `master` into `python3` branch or the other way round to have an up-to-date and Python 3 compatible branch for further testing among the many users who are urgently requesting MotionEye.

This should also make it easier for doing a new release to PyPI, once we feel it is ready.

**Comment by ccrisan** [comment]
Let me know when you need access to PyPI and I'll make sure you (or the CI) can publish it.

**Comment by MichaIng** [comment]
That would be great. I have zero knowledge about how to publish to PyPI. I guess we'd go with GitHub actions for build and publishing when a release is done, and secrets can then be stored in GitHub for the CI. But I think it will take a while when the goal is to get everything merged and Python 3 ready first, given that we want to have this tested thoroughly before doing a release.

**Comment by MichaIng** [comment]
The organization "Motioneye" exists already: https://github.com/Motioneye
No public repos, members of projects, also no indication of when this was created. Not sure if this is related to our "motionEye" at all? Probably we could name it "motionEyeOrg" then, or does anyone have other suggestions?

**Comment by TheRaven500** [comment]
> or does anyone have other suggestions?
motionEye-NG? But in the end it's just a name, what matters is the content. ;-)

**Comment by MichaIng** [comment]
What does the `-NG` suffix stand for? I saw `-ng` here and there but cannot find the abbreviation meaning 😅.

**Comment by Joulinar** [comment]
NG: Next Generation 😄

**Comment by ovz93br43v7** [comment]
Next generation?

Am 21. Februar 2022 14:12:56 MEZ schrieb MichaIng ***@***.***>:

**Comment by TheRaven500** [comment]
> What does the `-NG` suffix stand for? I saw `-ng` here and there but cannot find the abbreviation meaning sweat_smile.

Not really sure, but i thought it stand for "New Generation". Saw this in a lot of tools (iptraf-ng for example). Persönlich verbinde ich es auch mit einem fork, bin aber nicht sicher ob das so ist. ;-)

**Comment by MichaIng** [comment]
Ah okay, yeah would fit given that its a new/next generation of maintainers and next Python major version, at least as only target now. But note that its about the name for the organisation, not for the project/repo.

However, before I create the org, I need someone in the board who did already work on it and uses motionEye actively. I can help but cannot maintain it alone (given that DietPi is my main project), hence feedback from @Mictronics would be great 🙂.

**Comment by TheRaven500** [comment]
Just an idea: What about asking some contributors from the official motioneye git?

**Comment by MichaIng** [comment]
That's the plan once the repo is up, especially those which have open PRs.

**Comment by Mictronics** [comment]
@MichaIng The only reason why I touched motioneye at all was that I don't want python2 on your Dietpi bullseye installation. I don't use motioneye frequently at the moment, just have a test system with a Pi camera and USB webcam. Last but not least, I am not a python programmer, my preference is C and also TS instead of JS. That said, I will not contribute that much in the future. However, I have some plans to get rid of the outdated and obsolete jQuery and maybe rebuild the web interface with bootstrap. But that's long term ideas, not sure when and if that will happen.

**Comment by MichaIng** [comment]
Understood. However, as you use it by times and have some plans already (I'd agree to get rid of jQuery, it doesn't serve sufficient benefit anymore, I'm planning the same for our website), that would be sufficient from my end to start the organisation. And if course we should invite other contributors or owners of forks to join as well to bundle efforts. So you are fine with creating and joining the orga? Any preferences about the name, motionEyeOrg, motionEye-(ng|NG), motionEyeTeam is another idea I have, which IMO sounds more inviting and fitting to what it would be, compared to the term "organisation".

**Comment by MichaIng** [comment]
@jmichault
Also pinging you here, as you are the maintainer of an actively developed fork with Python 3 support and internationalization, which is a nice thing. I'm not sure how deep the changes are compared to upstream, but I see you kept merging upstream changes into your fork. To keep up motionEye development on a more sustainable basis (no single maintainer, but a team), would you be willing to join a GitHub organisation which takes over the upstream repo, merging your great work on internationalization there?

**Comment by jmichault** [comment]
Hello, I am ready to join such an organization, and to contribute to it.
A note on the internationalization I've done: I've chosen to use Esperanto rather than English as my base language.
Esperanto has the disadvantage of being less widespread than English or Chinese, but it can be learned easily by anyone: it only takes 10 hours to learn to read it, thanks to its simple grammar ( 16 grammar rules only, and no exceptions).
I hope you don't have a problem with this choice.

**Comment by MichaIng** [comment]
That is great.

As of Esperanto: I was already wondering which language it is, never heard of it: https://wikipedia.org/wiki/Esperanto
For existing commits IMO it's fine, if merging those back to upstream, a commit history must anyway not be manipulated. For future commits/development I think we should stick to English as the de-facto standard for international communication and possible future contributes feel more invited. Even that the idea behind Esperanto is great, aiming to exactly support international communication with an as-easy-as-possible language, on a first sight people feel like the repository is for a local speaking area they do not belong to 😅. And it shouldn't be necessary to invest 10 hours of learning a language first, to do a little contribution or understand a commit, though I'll definitely have a closer look at it 🙂.

Do you have any preference as of the organisation name? I feel like I should simply do the choice and create it instead of keep asking this, but on the other hand as this shall be a teamwork, I do not want to do the very first decision all by myself 😉.

**Comment by jmichault** [comment]
motionEyeOrg, motionEyeTeam/motionEye-team, all seem appropriate.
Make the choice you like the most, or roll the dice...

**Comment by ccrisan** [comment]
I took the liberty to create https://github.com/motioneye-project so we can move forward. If you don't like it, we can eventually rename it. In the hope that you do like it, please let me know whom I should invite to the organization by reacting to the post, commenting or by any other means.

**Comment by MichaIng** [comment]
Many thanks, I was busy with our release the last days. Another good idea for the name, let's stick with it. As of discussion above, please invite me, @Mictronics and @jmichault.

**Comment by ccrisan** [comment]
> Many thanks, I was busy with our release the last days. Another good idea for the name, let's stick with it. As of discussion above, please invite me, @Mictronics and @jmichault.

Done!

**Comment by TheRaven500** [comment]
A very good name. Cool! Thanks!

**Comment by jmichault** [comment]
I have transferred my own fork to the project.

We need to decide what repository will be your base.

Personally, i suggest that ccrisan  transfer the motioneye repository to the project, if he is OK with that : 
his repository is the most known.

Then i can do a pull request from my repository to transfer my work on python 3 and internationalization.

**Comment by MichaIng** [comment]
I second that the original project by @ccrisan should be the base. It is the most used and widest spread one, so that way we catch most motionEye users to be redirected automatically to the new project.

**Comment by ccrisan** [comment]
> I second that the original project by @ccrisan should be the base. It is the most used and widest spread one, so that way we catch most motionEye users to be redirected automatically to the new project.

It's done!

**Comment by MichaIng** [comment]
Okay great, let's move discussion over.

**Comment by MichaIng** [comment]
Merging this now with install aligned the way intended upstream. I marked it with "beta", until we have a stable motionEye release and upload to PyPI.

**Comment by TheRaven500** [comment]
Updated all my clients to "beta" and no problems so far. Seems to work fine!!! :-) Maybe a stupid question but: How to update/install on a plain debian? Maybe a "how to install" the new version would be fine?

**Comment by Joulinar** [comment]
there you go https://github.com/motioneye-project/motioneye/wiki/Installation

**Comment by Joulinar** [comment]
true, probably you could ask on the Motioneye-Project Github if this could be updated.

In meantime you could have a look to our install script and try to follow 
https://github.com/MichaIng/DietPi/blob/5a7be6292a708d263167aee510595be2eb4b4439/dietpi/dietpi-software#L9487

We install Python3 + FFmpeg as dependency

**Comment by TheRaven500** [comment]
Removing the old version and install the new versions with:
`pip3 install --no-cache-dir -U 'https://github.com/motioneye-project/motioneye/archive/dev.tar.gz'`
has worked (i think...) :-)

**Comment by TheRaven500** [comment]
Tested now on different Pi's (3A+, 3B+, Zero 2W) and different methods (USB, MMAL and MJPG-Stream) and works so far. No bugs detected until now. :+1:
Only 1 small thing: I think it took a little bit longer until the camera picture (preview) is showing (before it shows a crossed out camera symbol). But not really a problem for me. I am very happy that it now works with phyton3! :-)

**Comment by MichaIng** [comment]
Thanks for testing. We'll do an official open beta release with motionEye soon, a stable release hopefully shortly after, when no difficult bugs are reported 🙂.

**Comment by TheRaven500** [comment]
I think i found a bug with the brightness control. If the control is "off", it locks the brightness and does not adjust if it gets darker or brighter (so if brightness change you have a dark or very bright picture). If it is "on" then as soon the brightness should change it toggles very strange. I think it is something with the new motioneye version, because before with the old one and with motion stand alone it has worked. Any idea how to debug this?

**Comment by Joulinar** [comment]
Please report such issues on the motioneye project GitHub.

**Pull request merged**
