### PR TITLE
DietPi-Login/Autostart | Add autostart option for a custom script to be ran after automatic login.

### LINKED ISSUE #4633: Add ability for custom script alongside automatic login
#### Is your feature request related to a problem? Please describe:
I want to be able to autostart with cli-visualizer instead of C.A.V.A.

#### Describe the solution you'd like:
I would like an option for a custom script autostart to be executed in shell after automatic login.

#### Describe alternatives you've considered:
An alternative would be to just select automatic login and then add conditionals similar to [those in dietpi-login](https://github.com/MichaIng/DietPi/blob/master/dietpi/dietpi-login#L241-L247) to my .bashrc before running the script. However, I thought it would be better implemented as a native option.

#### Additional context
It wasn't immediately clear that some options would go alongside the automatic login option, so I was a bit confused when my custom script wasn't starting cli-visualizer the same way the cava autostart option was starting cava. It took a lot of digging to find out that some of the autostart options would automatically login before executing, while others wouldn't - and that the custom script was included in those that wouldn't.

I think that there are a lot of use cases for wanting a custom script to be executed after automatic login.

#### MR Created here (if this feature request is accepted):
https://github.com/MichaIng/DietPi/pull/4634

### PR DESCRIPTION
**Pull request by scorgn**
**Status**: Ready

**Reference**: https://github.com/MichaIng/DietPi/issues/4633

**Commit list/description**:
DietPi-Login/Autostart | Add autostart option for a custom script to be ran after automatic login.

### CODE REVIEW

**Comment by scorgn** [comment]
Unsure if the name of the option is too long but I wasn't sure what else to call it.

**Comment by scorgn** [comment]
The more I think about it the more it makes sense to only have one custom script autostart option. 

Having a script autostart in the background is not mutually exclusive with any of the other startup options. It could be something that is always available (you just have to put code in a file), or it could be something you have to enable manually.

In this scenario I think using a @reboot crontab would make more sense. As a sidenote (related to crontab) I would like to put some time into making a crontab/command scheduler made with whiptail for dietpi, if you have any thoughts on that as well I'd love to hear them.

**Comment by MichaIng** [comment]
Since option `14` now behaves differently, we may inform users on DietPi update about this change. On the other hand, nothing changes (service and script anyway remains untouched) unless `dietpi-autostart` is executed, where the new options and descriptions are visible. What do you think?

**Comment by MichaIng** [comment]
I'll merge it now and play a bit more with it to see whether a notification on update makes sense or not.

**Comment by MichaIng** [comment]
Changelog: https://github.com/MichaIng/DietPi/commit/89fcdf978e67a592668321021cb0b8890446f0f6

**Comment by MichaIng** [comment]
No notification on update required. We never apply an autostart option non-interactively besides during first run setup. And when actively changing the option, users will see the change + the changelog explains it in quite some detail.

**Pull request merged**
