### PR TITLE
Generel | Remove "net-tools" commands in favour of "ip" and "/proc/" + "/sys/" scraping

### PR DESCRIPTION
**Pull request by MichaIng**
Ref: https://github.com/Fourdee/DietPi/issues/1666
+ DietPi-Cloudshell | Replace "net-tools" commands with "ip" and "/proc/sys/net" or "/sys/class/net/" where applicable.
+ DietPi-Cloudshell | General code rework
NB: #/sys/class/net/ values are being reset by system/kernel when they reach X size. Some sort of "cap".
	- Retest? Even on long time running dietpi.com server, values match with output of currently used "netstat -i"
	- Alternative "cat /proc/sys/net"?
	- Otherwise workaround/fail_safe by sum new value to old value, if (( $NETWORK_USAGE_TOTAL_CURRENT_RECIEVED < $total_previous_recieved ))?
_______________________
+ DietPi-Boot | Switch from "net-tools" commands (route) to "ip" commands (ip r)
+ DietPi-Bugreport | Replace "net-tools" commands (ifconfig) with "ip" commands (ip a + ip r + ip l to not miss something)
+ DietPi-Config | Replace "ifconfig" with "ip a", add CIDR to mask function to generate e.g. 255.255.255.0 out of 192.168.0.100/**24**
+ DietPi-Config | General code improvements
+ DietPi-PREP | Remove "net-tools" from DietPi core packages
+ Changelog entry

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
- Ready to test.
- Shall we also patch `apt-mark auto net-tools`, in case inform user to get used to `ip` or reinstall?

**Comment by Fourdee** [comment]
@MichaIng 

Great work, very nice 👍 

> Shall we also patch apt-mark auto net-tools

Yep, and a little whip message (🈯️ https://github.com/Fourdee/DietPi/commit/ec76369630d8775f4be51cc90a88529bf71895b7) 👍 

I'll merge this now.

**Comment by Fourdee** [comment]
@MichaIng 

WiFi hotspot + allo GUI, either needs net-tools pre-req or we change code below.
```
dietpi-software (3 hits)
	Line 10265: 			ifconfig wlan$wifi_index 192.168.42.1
	Line 12240: if (( \$(ifconfig -a | grep -ci -m1 'eth1') )); then
	Line 12248: elif (( ! \$(ifconfig -a | grep -ci -m1 'eth0') )); then
```

🈯️ https://github.com/Fourdee/DietPi/commit/ec76369630d8775f4be51cc90a88529bf71895b7

**Comment by MichaIng** [comment]
@Fourdee 
Great, thanks for dietpi-software fix. Indeed it didn't show up on searching "ifconfig" and the other commands via github repo search. I think the file is just skipped for searches, remember recognizing this already one time, maybe due to file size. Have to remember for future code searches to always separately search within opened dietpi-software.

**Pull request merged**
