### PR TITLE
DietPi-Software | phpSysInfo

### PR DESCRIPTION
**Pull request by Joulinar**
At the moment installation of phpSysInfo is giving an error while downloading archive file as it's redirected to a URL not existing 

`curl: (22) The requested URL returned error: 404`

Original URL `https://github.com/phpsysinfo/phpsysinfo/archive/master.tar.gz`
Redirected to `https://codeload.github.com/phpsysinfo/phpsysinfo/tar.gz/master`

**Status**: Ready
- [x] adjust installation procedure for phpSysInfo 

**Reference**: https://dietpi.com/phpbb/viewtopic.php?t=9278

**Commit list/description**:
- DietPi-Software | phpSysInfo - adjust installation procedure to clone the Git instead of downloading an archive file

### CODE REVIEW

**Comment by MichaIng** [comment]
Only the default branch has been renamed from `master` to `main`, so we can do a minimal change and skip the switch to git clone.

**Comment by Joulinar** [comment]
Ok great

**Comment by MichaIng** [comment]
Good for a live patch:
```
grep -E 'phpsysinfo(-|/archive/)master' /boot/dietpi/dietpi-software
                        Download_Install 'https://github.com/phpsysinfo/phpsysinfo/archive/master.tar.gz'
                                G_EXEC mv /var/www/phpsysinfo/phpsysinfo.ini phpsysinfo-master/phpsysinfo.ini
                        G_EXEC mv phpsysinfo-master /var/www/phpsysinfo
```
=>
```sh
sed -Ei 's#phpsysinfo(-|/archive/)master#phpsysinfo\1main#' /boot/dietpi/dietpi-software
```
=>
```
2021-08-04 18:14:23 root@Zero:/tmp# grep -E 'phpsysinfo(-|/archive/)main' /boot/dietpi/dietpi-software
                        Download_Install 'https://github.com/phpsysinfo/phpsysinfo/archive/main.tar.gz'
                                G_EXEC mv /var/www/phpsysinfo/phpsysinfo.ini phpsysinfo-main/phpsysinfo.ini
                        G_EXEC mv phpsysinfo-main /var/www/phpsysinfo
```

**Review by MichaIng — DISMISSED** [review]

**Comment by MichaIng** [comment]
PR for live patch up: #4621

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
