### PR TITLE
DietPi-Installer | Fix ARMv7 image creations on ARMv8 hosts

### PR DESCRIPTION
**Pull request by MichaIng**
@dirkhh
In the hope that you were not concurrently working on a new PR. Would be great if you could test whether this solves your issue. With `-b installer` you can tell `dietpi-build` to use this branch.

Btw, I could not find the original issue/discussion we had about this. Could you link it? Nice to have the original report in changelog.

### CODE REVIEW

**Comment by dirkhh** [comment]
This wasn't an issue (because I assumed it was user error), but instead a discussion: https://github.com/MichaIng/DietPi/discussions/6541
And I closed it once I had a fix.

I just backed out my fix, switched to the installer branch, and ran with it using `sudo bash ../DietPi/.build/images/dietpi-build -m 52 -b installer`

Here's the interesting part (I hope) of the output:
```
[ INFO ] Selected Git branch: MichaIng/installer
[ INFO ] DietPi-Installer | Detected distribution version: Bookworm (ID: 7)
[ INFO ] DietPi-Installer | Detected target CPU architecture: aarch64 (ID: 3)

 DietPi-Installer
─────────────────────────────────────────────────────
 Step: [0] Detecting existing DietPi system

[ INFO ] DietPi-Installer | No DietPi system found, skipping old instance uninstall...

 DietPi-Installer
─────────────────────────────────────────────────────
 Step: [1] Target system inputs

[ INFO ] DietPi-Installer | Entered image creator: 0
[ INFO ] DietPi-Installer | Entered pre-image info: 0
[  OK  ] DietPi-Installer | Exit selected. Aborting...
```
It started the interactive dialog since m 52 was not in the available list.

**Comment by dirkhh** [comment]
hmm. now I'm confused.
I updated after the last push into this branch:
```
~/src/DietPi$ git reflog -1
d4a14cb7 (HEAD -> installer, origin/installer) HEAD@{0}: pull origin installer: Fast-forward
```
Consequently, `~/src/DietPi$ git grep "Detected target CPU architecture"` results in no output.

Yet when I go back to my build directory and run `~/src/dp-builds$ sudo bash ../DietPi/.build/images/dietpi-build -m 52 -b installer` I see this in the output (before it fails):
```
[ INFO ] Selected Git branch: MichaIng/installer
[ INFO ] DietPi-Installer | Detected distribution version: Bookworm (ID: 7)
[ INFO ] DietPi-Installer | Detected target CPU architecture: aarch64 (ID: 3)
```

So this still doesn't work - but the output makes me think that I'm not really testing what I should be testing...

**Comment by MichaIng** [comment]
Ah my mistake, `-b installer` tells it to use this branch for the DietPi system on the image, but not that it shall use this branch for downloading the installer itself. This should work:
```sh
export G_GITBRANCH='installer'
./dietpi-build -m 52
```

**Comment by dirkhh** [comment]
ding-ding-ding-ding-ding-ding

We have a winner...

```
Reading package lists... Done
[ INFO ] Selected Git branch: MichaIng/master
[ INFO ] DietPi-Installer | Detected distribution version: Bookworm (ID: 7)
[ INFO ] DietPi-Installer | Detected host CPU architecture: aarch64 (ID: 3)

 DietPi-Installer
─────────────────────────────────────────────────────
 Step: [0] Detecting existing DietPi system

[ INFO ] DietPi-Installer | No DietPi system found, skipping old instance uninstall...

 DietPi-Installer
─────────────────────────────────────────────────────
 Step: [1] Target system inputs

[ INFO ] DietPi-Installer | Entered image creator: 0
[ INFO ] DietPi-Installer | Entered pre-image info: 0
[ INFO ] DietPi-Installer | Detected target userland/OS architecture: armhf
[ INFO ] DietPi-Installer | Selected hardware model ID: 52
[ INFO ] DietPi-Installer | Marking WiFi as required
[ INFO ] DietPi-Installer | Selected Debian version: bookworm (ID: 7)
```

and I already have a completed build :)

**Comment by MichaIng** [comment]
Great. Probably we should make `dietpi-build` recognise when it is executed from a local Git repo with the `dietpi-installer` just beside it, so it can execute the local one instead of downloading it.

**Comment by dirkhh** [comment]
> Great. Probably we should make `dietpi-build` recognise when it is executed from a local Git repo with the `dietpi-installer` just beside it, so it can execute the local one instead of downloading it.

that seems like a good optimization (and will create less confusion when people are testing code for you)

**Pull request merged**
