### PR TITLE
v6.12

### PR DESCRIPTION
**Pull request by Fourdee**
**v6.12**
(19/07/18)

**Changes / Improvements / Optimizations:**

DietPi-Drive_Manager | Samba/CIFS mounting: Now automatically uses the highest available CIFS version supported on client and server: https://github.com/Fourdee/DietPi/issues/1893#issuecomment-403034799

DietPi-Software | Jackett: Now runs as its own user, and, from the /opt/jackett directory, for new installations only. Many thanks to @userdeveloper98 for contributing this improvement: https://github.com/Fourdee/DietPi/pull/1895

DietPi-Software | MiniDLNA: Now uses a SystemD service, also updates its library during service start.

DietPi-Software | JRiver: Removed and no longer available for installation: https://github.com/Fourdee/DietPi/issues/1080#issuecomment-403489246

DietPi-Software | Various titles: Now run under their own system user account, with limited permissions (previously root): https://github.com/Fourdee/DietPi/issues/1877#issuecomment-403298679

DietPi-Software | SABnzbd: Language packs are now installed by default: https://github.com/Fourdee/DietPi/issues/1917#issue-340631943

DietPi-RAMlog | Increased the max size of /var/log to 50MB by default (previously 20MB). This should prevent 0 free space errors for excessive log file usage. Pi-Hole max logfile size is now 50MB/3 (16MB~) for high usage with daily stats support: https://github.com/pi-hole/pi-hole/issues/2270#issuecomment-405109135 | https://github.com/Fourdee/DietPi/issues/1923

DietPi-RAMlog | Service is now disabled when RAMlog mode is not selected: https://github.com/Fourdee/DietPi/issues/1924

**Bug Fixes:**

General | Resolved an issue where cron jobs, containing DietPi scripts, failed: https://github.com/Fourdee/DietPi/issues/1923

General | Resolved an issue on ARM64 + Jessie with APT, due to debian-security removing suppport and packages for those devices. If you experience this issue, and are unable to update DietPi, please see : https://github.com/Fourdee/DietPi/issues/1915

General | Resolved an issue where NFSv3 network drives could not be mounted: https://github.com/Fourdee/DietPi/issues/1898

DietPi-Config | ASUS TB: Resolved loss of WiFi device after a reboot: https://github.com/Fourdee/DietPi/issues/1760

DietPi-Drive_Manager | Resolved an issue where the program could remove a non-empty directory in rare situations.

DietPi-Software | Resolved a potential Mono instability issue with Radarr, Sonarr and Jackett, due to using '--optimize=all --server'. This has now been removed for new installations. Many thanks to @hellfirehd for debugging/testing and @Taloth for dev insights: https://github.com/Fourdee/DietPi/issues/1896

DietPi-Software | Mono: Temp mono files are now cleared from memory once installed, preventing out of memory errors for additional software installs afterwards: https://github.com/Fourdee/DietPi/issues/1877#issuecomment-403856446

DietPi-Software | Xserver: Resolved rarely occuring uninstall issus by not purging dependencies, but leaving them for autoremove: https://github.com/Fourdee/DietPi/issues/1921

DietPi-Software | MineOS: Resolved failed installation due to incompatibilities with nodejs v10. v8 is now installed: https://github.com/Fourdee/DietPi/issues/1880

DietPi-Update | Resolved an issue where incorrect version would be displayed, once update was completed. This is due to '| tee' on a function, making var changes local: https://github.com/Fourdee/DietPi/issues/1877#issuecomment-403866204

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

Great work on this version, really impressive and I appreciate it 👍 

I'am going to nudge this forward for release tomorrow. Just want to run some final tests my end, make sure we covered everything before public release.

REF: https://twitter.com/DietPi_/status/1019689739908255750

**Comment by Fourdee** [comment]
Notes: 

🈯️ I need to check for 0 free space on RAMlog during EMR patch. Then run logclear. Just in case we have a few more users with the cron issue and long uptime.

**Comment by MichaIng** [comment]
@Fourdee 
Add `nofail` option to network drives as well? Check: https://github.com/Fourdee/DietPi/issues/1898#issuecomment-406392906

**Comment by Fourdee** [comment]
@MichaIng 

Great work on the fix 👍 Legend 🥇 

> Add nofail option to network drives as well? Check: #1898 (comment)

~Is already the default for all non-rootfs drives:~ We mount differently for networked drives, let me re-check.
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-drive_manager#L291-L300

Samba already done, i'll apply NFS.

**Comment by MichaIng** [comment]
@Fourdee 
> Is already the default for all non-rootfs drives

Hmm, seems to be not for network drives, my fstab entry is just: `192.168.178.28:/ /mnt/VM-Jessie nfs auto,_netdev 0  0`

**Comment by Fourdee** [comment]
@MichaIng 

Yep apologies (https://github.com/Fourdee/DietPi/pull/1938#issuecomment-406424359) | https://github.com/Fourdee/DietPi/pull/1938/commits/c035976111897a80b38313e93f2810b66e22a99b

🈯️ Samba + NFS: Mount + reboot (fstab) re-mount test

**Comment by MichaIng** [comment]
@Fourdee 
Ahh, missed something. `netbase` is installed when installing NFS client via dietpi-software, but this is skipped when using drive_manager to mount NFS drive 😉. Hmm I think we should either always use dietpi-software to install it or just use `G_AG_CHECK_INSTALL_PREREQ` and remove it from dietpi-software?

Okay done.

And to be true. Actually, as NFSv3 requires the path to be added to fstab entry.
Ah I think it's `fsid=0` is just valid for NFSv3

**Comment by Fourdee** [comment]
@MichaIng 

> G_AG_CHECK_INSTALL_PREREQ and remove it from dietpi-software

```G_AG_CHECK_INSTALL_PREREQ ``` is fine for now.

Yep, ideally, we need to review these items in dietpi-software, and, offer/point the user towards ```dietpi-drive_manager``` when attempting to install them.

For now, lets leave it as is, covers both types of users who want easy install + manual configure afterwards, without using ```dietpi-drive_manager```

---

EDIT: i'll add a message in during install of nfs/samba

The main reason for not using ```dietpi-software``` to install the pre-reqs, takes too long. For short install's of small packages, ```G_AG_CHECK_INSTALL_PREREQ ``` is preferred. But yes, having dupe install code is not good for maintenance.

🈯️ https://github.com/Fourdee/DietPi/pull/1938/commits/27f93b6862edcf3049f04b1d9734c47d7707cc71

image

**Comment by MichaIng** [comment]
@Fourdee 
Jep, I think it's fine for now. Connecting to NFSv3 still needs manual adjustment, but this was the same before (v6.9).

Ideally we need to identify if NFS server is v3 or v4 and in case ask user to add path as well, but let's move that to v6.13, as this needs some good idea and/or good sleep 😄. Currently my only idea is to test mounting the drive and if it fails, ask the user to verify the server is v3 and add path then... Not very handy, but currently I have no better idea 😅.

**Comment by Fourdee** [comment]
@MichaIng 

> Currently my only idea is to test mounting the drive and if it fails, ask the user to verify the server is v3 and add path then... Not very handy, but currently I have no better idea 😅.

But an idea non-the-less 👍. Yep, NFS is somewhat a pain when its comes to actual/current documentation and usage. Seems to be left behind Samba.

**Comment by Fourdee** [comment]
Ok, I'll do some final testing, then we can release. < 1 hour.

**Comment by Fourdee** [comment]
@MichaIng 

v6.12 is released: https://twitter.com/DietPi_/status/1020084158549413888

Great work on this 👍 🥇, I know i've been somewhat unavailable this release (RL), apologies for that.

**Comment by Hax4us** [comment]
@fourdee where is it ? I can't find new image here https://dietpi.com/downloads/images/

**Comment by MichaIng** [comment]
@Hax4us 
The images are not necessarily updated on new DietPi release. It also is not needed, as DietPi updates itself automatically on first boot to current version.

But yeah, it's a bid cleaner to have them up-to-date directly. At least for VirtualBox and VMWare I will update them now.

**Comment by Hax4us** [comment]
@MichaIng my problem is that I have only hotspot (my Android) so as you know Asus TB onboard WiFi is not working in previous version of DietPi and dietpi will  update itself only if I have internet connection so ...😩

**Comment by MichaIng** [comment]
@Hax4us 
Ah okay, I understand. I hope @Fourdee finds the time to create an updated image soon.

**Comment by Hax4us** [comment]
Can I create from source ? Any hint ?  @MichaIng

**Comment by MichaIng** [comment]
@Hax4us 
Theoretically yes, using the preparation script. But I am not sure, which pre-image we use for Asus TB and if some manual adjustments are needed, I suggest you wait for Fourdee, to be sure to have an image that works as expected.

**Pull request merged**
