### PR TITLE
DietPi-Software | HAProxy

### PR DESCRIPTION
**Pull request by Joulinar**
update version to 2.6

https://dietpi.com/forum/t/update-haproxy-to-latest-release-2-6-0/13347

### CODE REVIEW

**Comment by mariusrugan** [comment]
i've tested a local modified dietpi-software script, with version bump to 2.6.0, and works perfectly, 
also ```USE_PROMEX=1``` which i was after (enable prometheus metrics). 
It's a fairly cheap upgrade, imho, and useful. No other packages or libs needed.  

```
haproxy -vv

HAProxy version 2.6.0-a1efc04 2022/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.0.html
Running on: Linux 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64
...
Built with the Prometheus exporter as a service
```

would you care to include it ?
thanks in advance!

**Review by MichaIng — DISMISSED** [review]

**Comment by MichaIng** [comment]
Yes it's difficult to get the latest stable sources automatically. I guess we could parse the HTML files on the download page, but I couldn't find a clean method in the past either.

**Comment by MichaIng** [comment]
Prometheus metrics sound interesting for a load balancer. If that doesn't add significant binary size/RAM usage, we could add it, otherwise have an option in `dietpi.txt` to switch it on, or one for custom build flags, to make it more flexible?

**Comment by mariusrugan** [comment]
I already am using it, exactly for that purpose, load balancing k3s api from 3 masters, but also offloading TLS for self-hosted stuff.  
i don't see for the last 12hrs+ since enabled, any issue with it.

pmap screenshot attached,
Screenshot 2022-06-07 at 12 06 57

i can provide any other investigation related to performance, on demand.

**Comment by MichaIng** [comment]
Build flag added and made further updates/enhancements.

**Review by MichaIng — DISMISSED** [review]

**Comment by mariusrugan** [comment]
thanks a lot for your work!

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Docs update required: https://github.com/MichaIng/DietPi-Docs/issues/739

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
