### PR TITLE
v6.1

### PR DESCRIPTION
**Pull request by Fourdee**
**v6.1** | Hotfix
(29/01/18)

**Bug Fixes:**

DietPi-Software | Kodi: Resolved failed installation due to libcec package naming. Patched re-install during dietpi-update: https://github.com/Fourdee/DietPi/issues/1428#issuecomment-361092857

DietPi-Software | Tonido: Resolved issue with service failing to start. Patched re-install during dietpi-update: https://github.com/Fourdee/DietPi/issues/1432

DietPi-Software | Fail2Ban: Resolved issue with service failing to start. Patched re-install during dietpi-update: https://github.com/Fourdee/DietPi/issues/1431

### CODE REVIEW

**Comment by k-plan** [comment]
@Fourdee 

Update dialog on "old" v159 is okay for me.



But I can't live with this:

```
───────────────────────────────────────
 DietPi     | Image available
 ───────────────────────────────────────
 V159       | NanoPi Neo (armv7l)
 ───────────────────────────────────────
 IP Address | 192.168.100.126
 ───────────────────────────────────────

 Created by : Daniel Knight
 Web        : http://DietPi.com
 Twitter    : http://twitter.com/dietpi_
 Donate     : http://goo.gl/pzISt9

 Device image possible thanks to: ARMbian
 DietPi's web hosting is powered by: MyVirtualServer.com

 dietpi-launcher  = All the DietPi programs in one place.
 dietpi-config    = Feature rich configuration tool for your device.
 dietpi-software  = Select optimized software for installation.

 An updated DietPi image is available, please goto:
 http://dietpi.com/phpbb/viewtopic.php?f=8&t=9#p9

 htop             = Resource monitor.
 cpu              = Shows CPU information and stats.

root@NanoPi-Neo:~#
```


I  personally want to stay on Jessie with some of my devices, without annoying login banners! Sorry.

It's not my fault, what user can't read or understand what is going on or why they can't simple update to v6.1, or why they can't edit` dietpi.txt` any more or Odroid has still Jessie and not Stretch.

Sorry,  I am already nerved of so much ignorance.  :speak_no_evil:   :hear_no_evil:   :see_no_evil: 

No harm meant!

**Comment by Fourdee** [comment]
@k-plan 

> I personally want to stay on Jessie with some of my devices, without annoying login banners! Sorry.

To lock version and remove the update info, simply set core and sub version to something high:
```
cat << _EOF_ > /DietPi/dietpi/.version
1337
1337
_EOF_
dietpi-update
```

```
[  OK  ] No updates required, your DietPi installation is up to date.

[ INFO ] Current Version : 1337
```

Unless we reach DietPi v6.1338, you'll be fine 😃

**Comment by k-plan** [comment]
Hi Dan,

not a problem personal for me:



See xmas tree .... :smile:  ... but I hate support for things like this. Sorry.

I mostly can help me out by such things. It's simple.

But what will user do, how don't understand anything, can not google or read posting?

Yea, simple post in formun or make a github issue......

**Comment by Fourdee** [comment]
@k-plan 

> See xmas tree .... 😄 ... but I hate support for things like this. Sorry.
I mostly can help me out by such things. It's simple.
But what will user do, how don't understand anything, can not google or read posting?
Yea, simple post in formun or make a github issue......

I think we've covered the information for V6.0 as much as we can (forums/git/twitter), failing that, we are relying on the user to read that information, before posting an issue.
Failing that, if we can assist them in the right direction, thats all we can do :)

**Pull request merged**
