### PR TITLE
DietPi-Software | WiringPi: Enable support for selected NanoPi models

### LINKED ISSUE #3514: DietPi-Software | WiringPi: Add support for NanoPi
#### Required Information
- DietPi version | CORE=6, SUB=29, RC=2, GITBRANCH=master, GITOWNER=MichaIng
- Distro version | buster
- Kernel version | Linux DietPi 5.4.14-sunxi #rc1 SMP Sat Jan 25 15:19:01 CET 2020 armv7l GNU/Linux
- SBC model | NanoPi Neo
- Power supply used | 5V 2A
- SDcard used | SanDisk Micro SDHC I 16GB

#### Additional Information (if applicable)
- Can this issue be replicated on a fresh installation of DietPi? --> Yes
- On the stretch image with the exact same hardware the error is not present.
- Propably belongs to: #2979

#### Steps to reproduce
1. Download DietPi_NanoPiNEO-ARMv7-Buster.img
2. Write the image to SD-Card
3. Opt Out of DietPi-survey
4. Adjust both the software password and user passwords to the same password
5. Disable serial console
6. Don't select any software
7. Select install
8. Have a UART-device connected to ttyS1
9. cat /dev/ttyS1

#### Expected behaviour
- cat should be able to connect to the UART-device

#### Actual behaviour
```
cat /dev/ttyS1
cat: /dev/ttyS1: Input/output error
```
In fact this error shows on all serial interfaces except ttyS0. On the stretch image ttyS0 - ttyS3 are available.

#### Extra details
- Worked like a charm on stretch image with same hardware.

### LINKED ISSUE #4149: DietPi-Software | WiringPi: Migrate to new branch
I'm sorry to read such a frustrating deprecation message of the founder of WiringPi: http://wiringpi.com/wiringpi-deprecated/
But there is a new repository which further maintains the code: https://github.com/WiringPi/WiringPi

For RPi, we ship a fixed commit that seems to be the second last official release before Gordon stopped developing it: https://github.com/WiringPi/WiringPi/commit/093e0a17a40e064260c1f3233b1ccdf7e4c66690
A final release v2.50 has been made and now the further maintained repository. Which we should use.

I'll have a closer look into this with next development cycle.
_______
This is the RPi version, not supporting other SBCs, while other manufacturers have their own repos:
- Odroid: https://github.com/hardkernel/wiringPi
- NanoPi: https://github.com/friendlyarm/WiringNP
- ~BananaPi: https://github.com/LeMaker/WiringBP~ **EDIT: too long unmaintained and we don't ship BananaPi images currently**

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Testing

**Commit list/description**:
+ DietPi-Software | WiringPi: Enable support for selected NanoPi models: https://github.com/friendlyarm/WiringNP

### CODE REVIEW

**Comment by MichaIng** [comment]
@StephanStS 
Linking you here, as I know you have some NanoPi's around. Nothing urgent, but if you find time to do a quick test on them, it would be awesome.
```
dietpi-software install 70
gpio readall
```

The `gpio` utility uses the underlying library, so if this produces the expected output (a table of GPIO channels/states), then it seems to work. Ah also the readme suggests this test: https://github.com/friendlyarm/WiringNP#verify-wiringnp

**Comment by MichaIng** [comment]
Merging now. Testing can be done via `dev` branch.

**Comment by StephanStS** [comment]
@MichaIng: Tested it on 

- NanoPi NEO2, NanoPi NEO4, NanoPi M3 (aarch64)
- NanoPi M1+ (armv71)

Always got an error message at `dietpi-software install 70`:   
`[FAILED] DietPi-Software | Software title (WiringPi) is not supported for NanoPi M1 Plus (armv7l).`

The software ID 70 is also not found in `dietpi-software` when searching for "wiring".

I could try it also on a NanoPi R2s, NEO3, NEO Plus2, ZeroPi if these would be 'different' hardware variants.

(On an ODROID C4 all worked fine, so the procedure given above is working).

**Comment by MichaIng** [comment]
Many thanks for testing. Only the following models are supported: NanoPi NEO, NEO Air, NEO2, NEO Plus2, M1, K1 Plus

Indeed M1 Plus should also be supported, it's on the repo list as well. I'll add it now.

But NEO2 you got the message as well?

When a software title is disabled for a hardware model, architecture or distro version, it also does not show up in search results indeed.

**Comment by MichaIng** [comment]
There was a copy&paste issue why it was not enabled for any NanoPi. Fixed with: https://github.com/MichaIng/DietPi/commit/f4a6c77c1e970dd663651c9970851eaf958a806d
+ Added M1 Plus

**Comment by StephanStS** [comment]
Test failed on NanoPi M1+ and NEO2:
Output of `dietpi-software install 70`:

image

**Comment by MichaIng** [comment]
Ah, the directory has non-capital "w". If the prompt is still open, can you change the command to `mv wiringNP-master WiringPi-master`?

**Comment by Joulinar** [comment]
Better to use `mv wiringNP-master WiringPi-master` according screen print

**Comment by MichaIng** [comment]
Yes, just the capital letter was wrong: https://github.com/MichaIng/DietPi/commit/724b9338820e84b33b9b992cc03618cf7d0de065

**Comment by StephanStS** [comment]
Are you sure? :-)

Tested on NEO2 and M1.

image

The tar command generates a directory `wiringPi-master`.  
Changing to `mv wiringPi-master WiringPi-master` works better.

There is an error during the compiling: 
image

There are only these /dev/gp* devices:
image


And after the compiling has ended:
image

**Comment by StephanStS** [comment]
On an ODROID (C4) there is:
image

On this ODROID the `gpio readall` works fine.

**Comment by MichaIng** [comment]
Lol, sorry, that commit was full of errors, I should have done a dummy install test first 😅. The capital "W" was correct but the URL wrong. Now double-checked content of the archive. Whether the compiling works well or not is the important question, as the Armbian kernel might be not compatible with this library, made for the FriendlyARM FriendlyCore kernel: https://github.com/MichaIng/DietPi/commit/37565ba1f85345063d226c08c4aaf8743d7be085

**Comment by StephanStS** [comment]
No problem, next try. :-)

On the NEO2 it works now, on the M1+ not.

**Pull request merged**
