### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by cocoflan**
**Status**: WIP | Testing | Ready | ?
- [x] Example task 1

**Reference**: https://github.com/MichaIng/DietPi/issues/XXXX

**Commit list/description**:

- ...

### CODE REVIEW

**Comment by Joulinar** [comment]
changed to `dev` branch

**Comment by MichaIng** [comment]
Many thanks, let me see how SECURITY.md is usually used. We should make clear that it's not about security issues/vulnerabilities within the software/packages we ship but within the implementation, e.g. default settings, startup service/user, UNIX permissions, and, or course within our own scripts, boot schedule, service handling and such.

Also generally I think we should provide a mail address to report since its not nice to report a security issue on a public place first and potentially endanger users with this without giving us the chance to close the hole first. The usual procedure is to have a fixing release first before making the security issue public/transparent and by this encourage users to update or follow the fix manually, if affected. Of course it depends, but in case of doubt the security of users goes before immediate transparency.

**Comment by MichaIng** [comment]
@cocoflan 
I added some slight text format, made clear what we are responsible for and in which case the issue should be better reported to repository maintainers or upstream devs, and that security issues should be at best reported via email, if there is any chance that our users systems can be compromised with the contained information.

What do you think?

**Comment by cocoflan** [comment]
Ok very good !! 


Van: "MichaIng" <notifications@github.com> 
Aan: "MichaIng/DietPi" <DietPi@noreply.github.com> 
Cc: "cocoflan" <christophe.kinet@telenet.be>, "Mention" <mention@noreply.github.com> 
Verzonden: Dinsdag 25 augustus 2020 13:03:33 
Onderwerp: Re: [MichaIng/DietPi] Create SECURITY.md (#3721) 





[ https://github.com/cocoflan | @cocoflan ] 
I added some slight text format, made clear what we are responsible for and in which case the issue should be better reported to repository maintainers or upstream devs, and that security issues should be at best reported via email, if there is any chance that our users systems can be compromised with the contained information. 

What do you think?

**Comment by cocoflan** [comment]
> @cocoflan
> I added some slight text format, made clear what we are responsible for and in which case the issue should be better reported to repository maintainers or upstream devs, and that security issues should be at best reported via email, if there is any chance that our users systems can be compromised with the contained information.
> 
> What do you think?

Ok great !!

**Pull request merged**
