### PR TITLE
DietPi-Software | SABnzbd: Fix startup on Buster and install on RISC-V

### PR DESCRIPTION
**Pull request by Joulinar**
lock version on Buster systems as SABnzbd 4 require Python version above 3.8.

Related to https://github.com/sabnzbd/sabnzbd/issues/2545

### CODE REVIEW

**Comment by Joulinar** [comment]
@MichaIng can you have a look pls. I guess there is a better way to distinguish between Buster and Bullseye 😉

**Comment by MichaIng** [comment]
That one is fine. I just removed some code duplication 🙂.

**Comment by MichaIng** [comment]
Test: https://github.com/MichaIng/DietPi/actions/runs/4855405100

**Comment by MichaIng** [comment]
On ARM, install currently fails as on piwheels the module build is currently running: https://www.piwheels.org/project/sabctools/

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
