### PR TITLE
DietPi-Software | Sonarr: Migrate to v3

### LINKED ISSUE #4241: DietPi-Software | Sonarr: Migrate from v2 to v3
#### Required Information
- DietPi version
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=0
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'

- Distro version
buster 10.9

- Kernel version
Linux DietPi 5.10.17-v71+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv71 GNU/Linux

- SBC model
RPi 4 Model B (armv71)

- Power supply used
Official RPi 4 Power Supply

- SDcard used
256GB SanDisk Ultra

#### Additional Information (if applicable)
- Software title
Sonarr

- Was the software title installed freshly or updated/migrated?
Fresh Install

- Can this issue be replicated on a fresh installation of DietPi?
Yes

#### Steps to reproduce
1. Either a fresh install of DietPi headless with Sonarr as an application to install or;
2. Fresh install of DietPi through the interactive prompt and install Sonarr

#### Expected behaviour
- Sonarr should install

#### Actual behaviour
Error is thrown
```
Err:3 https://apt.sonarr.tv master InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBFF6B99D9B78493
Reading package lists...
W: GPG error: https://apt.sonarr.tv master InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EBFF6B99D9B78493
E: The repositiory 'https://apt.sonarr.tv master InRelease' is not signed.
```

#### Extra details
It seems no matter how you try and get DietPi to install Sonarr on a fresh installation it throws this signature error :(

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Software | Sonarr: Migrate to v3
+ DietPi-Software | Mono: Remove obsolete "-O=-aot" from Mono calls, which was a workaround that has been fixed in the meantime: https://github.com/MichaIng/DietPi/issues/2219
+ DietPi-Software | Complement and align Arr service hardenings

### CODE REVIEW

**Comment by Tooloco** [comment]
Hello, I dont know how to use github very well. I just wanted to point out that there seems to be an issue in this script /dietpi/misc/dietpi-arr_to_RAM at line 79.  When parsing arguments the if statements checks for sonarr instead of radarr. I also wanted to point out that in the last update (7.1.2) the scripts created by the dietpi-arr_to_ram 2 command (when migrating sonarr or radarr) have a typo that wont let the command run. I believe I've explained myself if not get back to me.

**Comment by Joulinar** [comment]
Yes we know and already fixed it.

https://github.com/MichaIng/DietPi/pull/4315

**Comment by Tooloco** [comment]
Ok, is the patch up right now?

edit: thanks for the fast answer !

**Comment by Joulinar** [comment]
If you already created the script, it would need to be changed manually

**Edit**
At least the typo we correct

**Comment by Tooloco** [comment]
Ok, I'll do those manually then. What about the other problem on the argument check. Is that something that is known ? here: https://github.com/MichaIng/DietPi/blob/master/dietpi/misc/dietpi-arr_to_RAM  
line 79

**Comment by Joulinar** [comment]
Not yet 😃 

https://github.com/MichaIng/DietPi/blob/86c5e377c607c2e1d8e97138c7cb9d377120a55d/dietpi/misc/dietpi-arr_to_RAM#L79

**Comment by MichaIng** [comment]
True, another typo.

**Comment by Joulinar** [comment]
@MichaIng 
Are you going to do the change?

**Comment by MichaIng** [comment]
Done: https://github.com/MichaIng/DietPi/commit/4b171a13bcb341cbc56960443a2ca323631863dd

**Comment by Tooloco** [comment]
Wow, you sure work fast guys! I cannot be happier with dietpi!

**Comment by MichaIng** [comment]
Thanks for reporting the issue 👍, I added a MOTD patch to have it fixed for all users.

**Comment by gorby-pranata** [comment]
I'm sorry but I'm a newbie with this kinda coding stuff. Can you tell me how can i apply the MOTD patch? Cz i already created the dietpi to ram script and having difficulty fix them manually. Thank you

**Comment by MichaIng** [comment]
```
sed -i 's/_RAN/_RAM/' /mnt/dietpi_userdata/*arr/dietpi-arr_to_RAM.sh
```

**Comment by gorby-pranata** [comment]
> ```
> sed -i 's/_RAN/_RAM/' /mnt/dietpi_userdata/*arr/dietpi-arr_to_RAM.sh
> ```

It says "Script exited with code: 1" while testing custom script in sonarr. Really really appreciate the assistance 😊

**Comment by MichaIng** [comment]
After you ran the command above?

Can you please paste:
```
cat /mnt/dietpi_userdata/sonarr/dietpi-arr_to_RAM.sh
```

**Comment by gorby-pranata** [comment]
> #!/bin/dash
/boot/dietpi/misc/dietpi-arr_to_RAM 2 sonarr

This is the terminal results, unfortunately sonarr custom script still says "script exited with error code:1". I will attach a screenshot of the error
Screenshot_20210502-003019208

**Comment by MichaIng** [comment]
What happens when you call it manually?
```
sudo -u sonarr /mnt/dietpi_userdata/sonarr/dietpi-arr_to_RAM.sh
```

**Comment by gorby-pranata** [comment]
> 2021-05-02 08:43:53 | DietPi-Arr_to_RAM: Radarr detected
2021-05-02 08:43:53 | DietPi-Arr_to_RAM: Updating Radarr database backup...
Error: attempt to write a readonly database
2021-05-02 08:43:53 | DietPi-Arr_to_RAM: [ERROR] Updating Radarr database backup failed.
2021-05-02 08:43:53 | DietPi-Arr_to_RAM: Sonarr detected
2021-05-02 08:43:53 | DietPi-Arr_to_RAM: Updating Sonarr database backup...
2021-05-02 08:43:53 | DietPi-Arr_to_RAM: Updated Sonarr database backup.
2021-05-02 08:43:53 | DietPi-Arr_to_RAM: [ERROR] An issue has occurred. Please check the above output for details.

This are the results.

**Comment by Joulinar** [comment]
Just to be sure, you don't have Radarr installed? Correct?

**Comment by gorby-pranata** [comment]
> Just to be sure, you don't have Radarr installed? Correct?

i have both sonarr and radarr installed, sorry if i didn't address this earlier. I thought the fix would apply to both radarr and sonarr

**Comment by Joulinar** [comment]
There is one more issue for detecting Radarr correctly. It would require correction on line 79

https://github.com/MichaIng/DietPi/blob/86c5e377c607c2e1d8e97138c7cb9d377120a55d/dietpi/misc/dietpi-arr_to_RAM#L79

**Comment by gorby-pranata** [comment]
> There is one more issue for detecting Radarr correctly. It would require correction on line 79
> 
> https://github.com/MichaIng/DietPi/blob/86c5e377c607c2e1d8e97138c7cb9d377120a55d/dietpi/misc/dietpi-arr_to_RAM#L79

i'm a newbie with coding and this stuff, so i'm not sure i can figure a way how to correct that line.  Would there be a patch that i can just run in the command line that would fixed both radarr and sonarr with dietpi to ram script?

**Comment by MichaIng** [comment]
Do you have MOTD in the DietPi banner enabled? If so, can you paste the output of:
```
cat /run/dietpi/.dietpi_motd
```

**Comment by Tooloco** [comment]
Just adding to this that until I manually ran dietpi-banner the fix did not happen. So it might help running it.

**Comment by MichaIng** [comment]
> until I manually ran dietpi-banner

But it runs on any login, doesn't it?

**Comment by gorby-pranata** [comment]
> Do you have MOTD in the DietPi banner enabled? If so, can you paste the output of:
> 
> ```
> cat /run/dietpi/.dietpi_motd
> ```

This is the output
Screenshot_20210502-172845644

**Comment by MichaIng** [comment]
That's a very old MOTD which should have been replaced long ago 🤔. Can you please paste the following:
```
journalctl --no-pager -u cron | grep daily
```

**Comment by gorby-pranata** [comment]
> That's a very old MOTD which should have been replaced long ago 🤔. Can you please paste the following:
> 
> ```
> journalctl --no-pager -u cron | grep daily
> ```

Okay... I don't know how it got wrong.. this is the output for the journalctl command

> root@DietPi:~# journalctl --no-pager -u cron | grep daily
> Apr 29 01:25:01 DietPi CRON[13999]: (root) CMD (test -x /usr/sbin/anacron || { cd / && run-parts --report /etc/cron.daily; })
> Apr 30 01:25:02 DietPi CRON[19250]: (root) CMD (test -x /usr/sbin/anacron || { cd / && run-parts --report /etc/cron.daily; })
> May 01 01:25:01 DietPi CRON[22570]: (root) CMD (test -x /usr/sbin/anacron || { cd / && run-parts --report /etc/cron.daily; })
> May 02 01:25:01 DietPi CRON[12018]: (root) CMD (test -x /usr/sbin/anacron || { cd / && run-parts --report /etc/cron.daily; })

**Comment by MichaIng** [comment]
I think I found the issue. The following file does not exist, does it?
```
ls -l /boot/dietpi/.dietpi-banner
```

The MOTD is only updated daily, if MOTD is actually enabled in the banner: https://github.com/MichaIng/DietPi/blob/master/rootfs/etc/cron.daily/dietpi#L38-L43
To check this, we however check for the config file (the one above), which is only created if one manually changes the banner settings. Since the MOTD is enabled by default (when no config file exists), it needs to be updated as well in that case.

And I was wondering why still so many users suffer from issues that should be fixed already 😄.
**Fixed: https://github.com/MichaIng/DietPi/commit/a5136698de58abbb5bcd9a769207f233bc8daaf4
Changelog: https://github.com/MichaIng/DietPi/commit/0d209764f0e3050dd0ac76d3aa07b9192b6dc332**

In you case:
```
rm /run/dietpi/.dietpi_motd
curl -sSfL https://dietpi.com/motd -o /run/dietpi/.dietpi_motd
dietpi-banner 1
```

**Comment by gorby-pranata** [comment]
> I think I found the issue. The following file does not exist, does it?
> 
> ```
> ls -l /boot/dietpi/.dietpi-banner
> ```
> 
> The MOTD is only updated daily, if MOTD is actually enabled in the banner: https://github.com/MichaIng/DietPi/blob/master/rootfs/etc/cron.daily/dietpi#L38-L43
> To check this, we however check for the config file (the one above), which is only created if one manually changes the banner settings. Since the MOTD is enabled by default (when no config file exists), it needs to be updated as well in that case.
> 
> And I was wondering why still so many users suffer from issues that should be fixed already 😄.

okay so should i just wait till tomorrow and use the fix the MOTD offer or am i missing something? again really appreciate your time and effort in answering my questions😁

**Comment by MichaIng** [comment]
Run the commands I edited into my post 🙂.

**Comment by gorby-pranata** [comment]
> Run the commands I edited into my post 🙂.

Awesome! the fix works wonderfully! thank you so much for the time and effort! You're amazing 😁

**Comment by MichaIng** [comment]
Thanks for your kind feedback and responsiveness here as well. Great that we finally found the reason for users seeing outdated banner messages (and not receiving fixes we hack inside).

I hope I find time for next release to add a dedicated transparent live-patch feature that allows to interactively apply such fixes, like "A patch is available for issue X, run dietpi-live-patches to apply it to your system" or so. So we can do fixes for issues that can be safely resolved with a single `sed` between releases, but transparently instead of the current sneaky way 😅.

**Comment by gorby-pranata** [comment]
> Thanks for your kind feedback and responsiveness here as well

Very happy to help 😊!

**Comment by Tooloco** [comment]
> > until I manually ran dietpi-banner
> 
> But it runs on any login, doesn't it?

The banner does show whenever I ssh into it but I manually had to nano in to the arr to ram script to fix it.

**Comment by Joulinar** [comment]
@Tooloco 
do you have MOTD activated?

**Comment by MichaIng** [comment]
Same reason, I guess: https://github.com/MichaIng/DietPi/pull/4292#issuecomment-830788123
The MOTD was not updated as expected, so the fix was not applied as expected 😉.

**Comment by Tooloco** [comment]
> @Tooloco
> do you have MOTD activated?

Yes, and I had manually configured the banner, adding all options but vpn status.

**Comment by MichaIng** [comment]
Ah, you mean the when you reported the issue here? https://github.com/MichaIng/DietPi/pull/4292#issuecomment-829471064
The fix has been applied after (and thanks to!) your report 🙂.

**Comment by Tooloco** [comment]
> Same reason, I guess: [#4292 (comment)](https://github.com/MichaIng/DietPi/pull/4292#issuecomment-830788123)
> The MOTD was not updated as expected, so the fix was not applied as expected 😉.

```
dietpi@DietPi3:~$ cat /run/dietpi/.dietpi_motd
# Live-patches
if [[ $G_DIETPI_VERSION_SUB == 1 ]]
then
        if [[ -w '/boot/dietpi/misc/dietpi-arr_to_RAM' ]]
        then
                grep -q 'dietpi-arr_to_RAN' /boot/dietpi/misc/dietpi-arr_to_RAM && sed -i 's/dietpi-arr_to_R
AN/dietpi-arr_to_RAM/' /boot/dietpi/misc/dietpi-arr_to_RAM
                [[ $(sed -n 79p /boot/dietpi/misc/dietpi-arr_to_RAM) == *sonarr* ]] && sed -i "79c\\\tif \[\
[ \${INPUT_PROG:-radarr} == 'radarr' \]\]" /boot/dietpi/misc/dietpi-arr_to_RAM
        fi
fi
# MOTD
motd='Did you know that you can run "dietpi-banner" to change its content?'
```

**Comment by Tooloco** [comment]
> Ah, you mean the when you reported the issue here? [#4292 (comment)](https://github.com/MichaIng/DietPi/pull/4292#issuecomment-829471064)
> The fix has been applied after (and thanks to!) your report 🙂.

OK just making sure everything is OK its running smoothly now, I've added the script to sonarr and radarr and it's working flawlessly.

**Comment by MichaIng** [comment]
Perfect, many thanks for validating.

**Pull request merged**
