### PR TITLE
Add support opi5

### PR DESCRIPTION
**Pull request by danielpinto8zz6**

### CODE REVIEW

**Comment by danielpinto8zz6** [comment]
Had to rename the branch, the 'feature/' was giving error during tar generation

**Comment by MichaIng** [comment]
> Had to rename the branch, the 'feature/' was giving error during tar generation

Where exactly did this happen? I can imagine when at some point a file name is derived from an URL and slash is interpreted as another directory separator?

**Comment by MichaIng** [comment]
Resolved conflicts against `dev`.

**Comment by MichaIng** [comment]
Wait, something is wrong there.

**Comment by danielpinto8zz6** [comment]
> > Had to rename the branch, the 'feature/' was giving error during tar generation
> 
> Where exactly did this happen? I can imagine when at some point a file name is derived from an URL and slash is interpreted as another directory separator?
Exactly

**Comment by danielpinto8zz6** [comment]
Good news, got it working :D
I had to revert the overlay prefix 'opi5' it was not booting with it, I guess it uses some overlays from other device maybe?
image

**Comment by danielpinto8zz6** [comment]
Just in case anyone wants to test 
https://drive.google.com/file/d/1WBD7S2DBf6HheRzLoeckR28cdgExje9f/view?usp=sharing

**Comment by MichaIng** [comment]
> I had to revert the overlay prefix 'opi5' it was not booting with it, I guess it uses some overlays from other device maybe?

This is only used when you do actually apply a device tree overlay via `overlays=` line in `/boot/dietpiEnv.txt`, which is not the case by default. And the recent kernel version definitely contains those overlays. And even if the prefix was complete garbage, it would fail loading the overlays from non-existing path into memory and in this case just continues. So the boot issue cannot have something to do with the prefix 😉.

**Comment by danielpinto8zz6** [comment]
> > I had to revert the overlay prefix 'opi5' it was not booting with it, I guess it uses some overlays from other device maybe?
> 
> This is only used when you do actually apply a device tree overlay via `overlays=` line in `/boot/dietpiEnv.txt`, which is not the case by default. And the recent kernel version definitely contains those overlays. And even if the prefix was complete garbage, it would fail loading the overlays from non-existing path into memory and in this case just continues. So the boot issue cannot have something to do with the prefix wink.

Humm, I'll test again

**Comment by MichaIng** [comment]
But great that it works 🥳. Could you add a changelog entry?

Also needs addition to our [docs](https://github.com/MichaIng/DietPi-Docs/blob/master/docs/hardware.md) and [download page](https://github.com/MichaIng/DietPi-Website/blob/master/index.html), but no hurry on that. More important to have an image for testing, thanks for providing already! I'll merge and run it through our CI as well to have it on our server.

**Comment by danielpinto8zz6** [comment]
@MichaIng updated changelog, I can update the docs and download page later :+1:

**Comment by danielpinto8zz6** [comment]
@MichaIng oh and btw, I've tested again with the opi5 overlay and it's working, reverting back

**Comment by MichaIng** [comment]
> altough I'm not able to apply other overlays for example "opi5-sata" which enables sata support

You then just need to add "sata" to the overlays line. It doesn't make anything other than looking for a file named `/boot/dtb/$overlay_path/overlay/$overlay_prefix-$input.dtbo`, so compared to Armbian, if they use `rockchip-rk3588` as prefix, just skip the "opi5-" in all names.

**Review by MichaIng — APPROVED** [review]

**Comment by danielpinto8zz6** [comment]
> > altough I'm not able to apply other overlays for example "opi5-sata" which enables sata support
> 
> You then just need to add "sata" to the overlays line. It doesn't make anything other than looking for a file named `/boot/dtb/$overlay_path/overlay/$overlay_prefix-$input.dtbo`, so compared to Armbian, if they use `rockchip-rk3588` as prefix, just skip the "opi5-" in all inputs/names.

Yeah, you're right, just confirmed, thank you

**Pull request merged**
