### PR TITLE
DietPi-Update | Apply new update system that allows automatic branch migration

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Review

**Commit list/description**:
+ DietPi-Update | Add new remote version file for updates and automatic branch migration from next version on

### CODE REVIEW

**Comment by nonnorm** [comment]
Wow, v7.  Will this come after or replace 6.35?

**Comment by MichaIng** [comment]
To allow a smoother drop of support for old Debian versions (Stretch somewhere this year) and as well old DietPi versions, without having to radically break the update ability, I added this method to natively migrate users to separate branches in case automatically, where we can theoretically provide some kind of LTS support, e.g. applying important/security patches for a while, or in case of Debian Stretch implement prompts/hints about how to dist-upgrade to a supported Debian version and then migrate back to the master/stable branch.

This way we don't need to handle complicated and error-prone migration and update-restart cycles and steps in the main branches. This has become quite complicated already and requires a lot of update-path testing to assure that none is broken.
Currently Jessie systems are migrated to the `jessie-support` branch, but for older DietPi versions this is done after the (theoretically Jessie-incompatible) code has been installed already, so it's not failsafe. Then dropping `/DietPi` RAMdisk came while Jessie systems are migrated to branch with RAMdisk, which made the patch file code much more complicated and error-prone.

Another major aim is to not completely break updates from older versions when incrementing the major/core version. Instead we can now start to drop support for a tail of very old subversions to simplify the patch file step by step until it (the old one) can be removed completely in two years or so. Then, the `dietpi/` directly finally will contain the actual system scripts only while all update-related scripts and files, that are not aimed to remain on systems, are in the dedicated `.update/` directory.

It was not required, but since it became possible now, I did increment the major version to **v7.0**, so that **v6.35** is a transition version only, required as intermediate step before an update restart migrates to the new system. But aside of that, it's not a large update, so no deeper meaning. A little like Linux 5.0 being to larger update than 4.19 or 5.1 😄.

What do you think?

**Comment by Joulinar** [comment]
does it means, DietPi version updates are populated to people running latest Debian Buster atm? And for Stretch we just provide bug-fixing? Just for my understanding 🤣

**Comment by MichaIng** [comment]
> DietPi version updates are populated to people running latest Debian Buster atm?

For now nothing changes about version support, only Jessie systems would be migrated. But those will never execute that code, as they are migrated via `patch_file` as before, so it's currently just to show how it can be used. First I had the plan to drop Stretch support when Debian Bullseye becomes stable, but reviewing the current [Stretch system share](https://dietpi.com/survey/#distro), it's probably better to keep it longer, e.g. end of the year. There are quite some nice things we an do when relying on Buster+, but not that important that we need to make ~9% of our users unhappy 😄.

But yes, once we decide to drop support for Stretch from the main repository code, we can then keep a minimal support on that dedicated branch, backporting only important fixes, depending also on reports/demand or user contributions.

**Comment by Joulinar** [comment]
probably as well we could prompt a banner info about Stretch being eol somewhere mid of the year too 🤔

**Comment by MichaIng** [comment]
> probably as well we could prompt a banner info about Stretch being eol somewhere mid of the year to 🤔

Good idea. We did similar for Jessie users two years ago, via MOTD, so there is some buffer to find a spare-time weekend for a dist-upgrade or fresh flash instead of a surprise all of a sudden.

**Comment by Joulinar** [comment]
Officially we did not support `dist-upgrade` 😉 . However this question will pop up sooner or later once Bullseye is out. Maybe we should add a `dist-upgrade` section to the docs, containing the usual warning. But probably something users would be appreciate on 🤔

**Comment by MichaIng** [comment]
Yes, I'd still always recommend a fresh flash instead of a dist-upgrade, but many users ignore(d) that anyway and then it's better to have some documented best practice instructions or even start supporting it officially, which forces us to review/learn more about possible unwanted left-overs. Some software options might require a reinstall and such to remain functional.

And indeed it became much less risky than it was a few Debian versions ago. I saw quite some more changelog entries were dist-upgrades were particularly taking into account.

**Pull request merged**
