### PR TITLE
DietPi-Software | ownCloud: Installation fixed for all distros

### PR DESCRIPTION
**Pull request by MichaIng**
+ DietPi-Software | ownCloud: Installation fixed for all distros

### CODE REVIEW

**Comment by MichaIng** [comment]
Mistakenly created for master branch, but luckily mergeable without conflicts into testing 😅.

**Comment by Fourdee** [comment]
@MichaIng 

Thanks for the fix 👍 

Are you able to add these fixes to the changelog aswell? 
https://github.com/Fourdee/DietPi/blob/testing/CHANGELOG.txt

Same for PR https://github.com/Fourdee/DietPi/pull/1242 if possible? 😃

**Comment by MichaIng** [comment]
Updated Changelog here: https://github.com/Fourdee/DietPi/pull/1242
to prevent conflicts, as this was accidentally added to master branch.

**Comment by Fourdee** [comment]
@MichaIng 
Legend, many thanks 👍

**Pull request merged**
