### PR TITLE
v6.9

### PR DESCRIPTION
**Pull request by Fourdee**
**v6.9**
(07/06/18)

**Changes / Improvements / Optimizations:**

General | During first run of DietPi (and during this patch), you will now be given the option to change the global password for 'root' + 'dietpi' accounts, and all future software to be installed that requires a password: https://github.com/Fourdee/DietPi/issues/1782

General | Increased verbosity and logging of DietPi boot scripts to assist with debugging: https://github.com/Fourdee/DietPi/issues/1772

General | G_ERROR_HANDLER: Retry mechanic added, allows you to re-run and retry the last command when an error occurs. Also included option to send DietPi a bug report when an issue occurs.

General | NTP removed from DietPi-Config time sync options and DietPi core packages. All time sync modes are now offered via systemd-timesyncd, which is part of every Debian based core system: https://github.com/Fourdee/DietPi/pull/1628

General | DietPi-Set_Core_Environment was removed. DietPi service and system config files are now updates automatically via new update system, other environment setup steps are moved into DietPi-PREP: https://github.com/Fourdee/DietPi/issues/1749

DietPi-BugReport | Has been revised and improved to remove end user security concerns.

DietPi-Drive_Manager | Swapfile: Added ability to move the swapfile and set size. This replaces the previous option in DietPi-Config.

DietPi-Process_Tool | NoMachine + Webmin: Processes can now be controlled.

DietPi-Services | Webmin: Added and now controlled.

DietPi-Software | Fail2Ban: Install now uses the systemD backend. No longer requires Rsyslog pre-req. For new installations only.

DietPi-Software | Search: Feature now available. Find the software you require for install, faster! https://twitter.com/DietPi_/status/1000858660682305536

DietPi-Software | InfluxDB and Grafana now available for installation. Many thanks to @marcobrianza for the install code and documentation guides: https://github.com/Fourdee/DietPi/issues/1784

DietPi-Software | LXDE: Resolved missing icons with 'pcmanfm' under RPi devices: https://github.com/Fourdee/DietPi/issues/1558#issuecomment-390328173

DietPi-Software | Webmin: Resolved failed installation due to missing package pre-reqs. Upgraded to use a systemD service: https://github.com/Fourdee/DietPi/issues/1741

DietPi-Software | Removed npm root access error during installs: https://github.com/Fourdee/DietPi/issues/1340#issuecomment-389899081

DietPi-Software | OpenJDK/JRE now installs Java version 8 across all DietPi system. This is for stability across all programs that require it: https://github.com/Fourdee/DietPi/issues/1340#issuecomment-389889264

DietPi-Software | Updated several non-APT software titles for fresh installs and reinstalls: https://github.com/Fourdee/DietPi/pull/1774

DietPi-Software | Transmission: General clean up of install config file. G_CONFIG_INJECT is now used to replace/add our optimized entries. Also cleaned up the service, now runs as forking: https://github.com/Fourdee/DietPi/issues/1754

DietPi-Software | sabnzbd: Updated to latest version 2.3.4 (for new installations only): https://github.com/Fourdee/DietPi/issues/1340

DietPi-Software | CAVA: Updated to latest version 0.6.1. Enabled for x86_64: https://github.com/Fourdee/DietPi/issues/1340

DietPi-Software | OctoPrint: libjpeg-dev now installed by default, this is required for additional plugin installations (eg: Astroprintcloud Plugin): https://github.com/Fourdee/DietPi/issues/1800

DietPi-Software | Xserver: DPMS and all known screen blanking/saving is now disabled by default. To re-enable this feature, remove the following file '/etc/X11/xorg.conf.d/99-dietpi-dpms_off.conf': https://github.com/Fourdee/DietPi/issues/1823

DietPi-Survey | Has been revised and improved to remove end user security concerns.

DietPi-Update | Implemented an automated update system for DietPi files, placed outside of /DietPi, e.g. system configurations and service files. This allows significant reduction of script code and assures consistency across all systems: https://github.com/Fourdee/DietPi/pull/1802

**Bug Fixes:**

General | Login and globals moved to /etc/bashrc.d/*, due to issues with remote shell and desktop terms under /etc/profile.d/99-dietpi-login.sh: https://github.com/Fourdee/DietPi/issues/1777#issuecomment-390248960

General | Completely removed root permission requirements from login scirpts and banner. Also users without sudo permissions will see the login banner and will be able to use dietpi-* and G_* functions: https://github.com/Fourdee/DietPi/pull/1790

General | Sparky SBC + USB-DAC unmute fix (v2), now sets volume to max: https://github.com/Fourdee/DietPi/pull/1779

General | UID bit reapplied for Sudo. Reported not applied on current XU4 image: https://github.com/Fourdee/DietPi/issues/794#issuecomment-392335392

DietPi-Config | WiFi HotSpot: Resolved inability to toggle state (enable/disable) and change channel: https://github.com/Fourdee/DietPi/issues/1810#issuecomment-394126835

DietPi-Drive_Manager | Format: Resolved an issue where formatting any drive, would reset the swapfile back to auto size and default location: https://dietpi.com/phpbb/viewtopic.php?f=11&t=3851&p=12864#p12864

DietPi-set_dphys-swapfile | Resolved issues with fallocate on vfat partitions which caused a failure.

DietPi-Software | SickRage: SystemD service updated to prevent timeouts, allowing the process to fully init. Experienced by some users installs: https://github.com/Fourdee/DietPi/issues/1762

DietPi-Software | AirSonic: Resolved issues with incorrect memory limit being set during installation: https://github.com/Fourdee/DietPi/issues/1764

DietPi-Software | AirSonic/SubSonic: Resolved 503 error when accessing web interface: https://github.com/Fourdee/DietPi/issues/1764

DietPi-Software | CloudPrint: Resolved an issue where the CUPS web interface would fail to connect: https://github.com/Fourdee/DietPi/issues/1797

DietPi-Software | VNC + LXDE: Resolved error message 'no session for PID x'.:

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

Great work on the SFTP changes, brilliant 👍 👍 

v6.9 is ready I believe, done all the testing I can. Agree?

**Comment by MichaIng** [comment]
@Fourdee 
Jep, I think so. Patch and all the bug report and survey thinks were tested.

Ah wait, just reviewed the changelog and found: `General | DietPi-Survey: Disabled G_USER_INPUTS, ensuring that a failed connection test will not generate a background whiptail prompt.`
I removed G_USER_INPUTS=0 again, to allow interactive error handling when started as well interactively. Does the automated detection of globals not work in every case? Of course when doing automated first run installations e.g. this shall never occur. Should not, as OPTED_IN=0 is default now, but we need to be secure here. Makes sense otherwise e.g. to force G_USER_INPUTS=0 directly before starting automated first run setup?

**Comment by blogabe** [comment]
Congratulations on 6.9  I'm wondering if https://github.com/Fourdee/DietPi/issues/1782 resolves https://github.com/Fourdee/DietPi/issues/1211 or if that still inherently mean we can't use Allo WebUI if we change the password.

**Comment by Fourdee** [comment]
@MichaIng 

> General | DietPi-Survey: Disabled G_USER_INPUTS, ensuring that a failed connection test will not generate a background whiptail prompt.

This was before the revised ```dietpi-survey```. Its not required now and i'll remove it from log.

> Should not, as OPTED_IN=0 is default now, but we need to be secure here. Makes sense otherwise e.g. to force G_USER_INPUTS=0 directly before starting automated first run setup?

```OPTED_IN=2``` is the new default (enabled), before user changes, once the new save file is generated during patch.

When automated installation is running, ```G_USER_INPUTS=0``` as auto detected by ```dietpi-globals```. There is now harm in setting ```G_USER_INPUTS=0```, but it shouldn't be required, allow auto detect to take control.

@blogabe 

> Congratulations on 6.9 I'm wondering if #1782 resolves #1211 or if that still inherently mean we can't use Allo WebUI if we change the password.

Unfortunately not in v6.9
Currently Allo GUI requires a hard coded password in the PHP code. That password ```dietpi``` must match the root password on system.
If I can apply a quick fix in v6.10 I will, however, I believe this will require a rewrite of the SSH code used and a different SSH library to resolve correctly. In which case i'll refer this to Allo and see if its something they want to review.

**Comment by blogabe** [comment]
No problem, Dan.  Appreciate you and the team's effort with DietPi.

**Comment by Fourdee** [comment]
@blogabe 

> Appreciate you and the team's effort with DietPi.

Thank you. We appreciate you using DietPi 👍

**Comment by Fourdee** [comment]
Twitter post v6.9: https://twitter.com/DietPi_/status/1004874682401779712

**Pull request merged**
