### PR TITLE
Added new devices to selection list in PREP-Script 

### PR DESCRIPTION
**Pull request by ghost**
Added LeMaker Guitar and BananaPi (1st Gen) - both are stable after migration from Armbian.

### CODE REVIEW

**Comment by Fourdee** [comment]
@SuBLiNeR 

Many thanks 👍 

I'll merge both PR's, however, I will change the index's for both items as we want to keep the total count as low as possible (basically means less arrays in ```dietpi-software```, less performance impact).

EDIT: done: https://github.com/Fourdee/DietPi/commit/2c739d7382583d6d292a9fd1c30981d0fb0ab5e5

**Comment by ghost** [comment]
@Fourdee: Seems there‘s somehow an error on these file. I tried using it freshly installed from the testing branch. It generates an error on ‚)) ?!? and sets the hw_model to generic device/ unknown device.
It even is enough to run dietpi-obtain_hw_model to get an error message that stats that the added lines somehow are not correct...

**Comment by Fourdee** [comment]
@SuBLiNeR 

Thanks 👍 I'll check.

**Comment by Fourdee** [comment]
@SuBLiNeR 

Ah yes, appears ```G_HW_Model``` was used (lower case), ```G_HW_MODEL``` should be.

**Comment by Fourdee** [comment]
@SuBLiNeR 

Fixed: https://github.com/Fourdee/DietPi/commit/06e8ff673bb304d56da853226d59404ebb64c39e

**Pull request merged**
