### PR TITLE
DietPi-Software | ownCloud: Bring ownCloud installation onto the stage of Nextclouds

### PR DESCRIPTION
**Pull request by MichaIng**
ready to test!

### CODE REVIEW

**Comment by MichaIng** [comment]
`dietpi-software` adjusted so far, have to add webserver config files and test all procedure on Jessie and Stretch...

**Comment by MichaIng** [comment]
Successfully tested installation and uninstallation on Stretch and Jessie.

Somehow php5-fpm/php7.0-fpm service needed another restart, before adjusted php values (by webserver configs as well as by php module configs) are applied.
I am wondering because all services got disabled and started again after complete installation. But phpinfo.php clearly showed, that opcache and apcu settings were not applied (I recognized because of warning on Nextcloud admin panel).
Another restart of php service fixed it. If the same is the case for other testers, I would mark a necessary reboot for ownCloud+Nextcloud.

**Comment by Fourdee** [comment]
@MichaIng 

Legend, great work 👍 

I'll merge and run tests aswell:
- 🈯️ OC+ Jessie + Lighttpd ```dietpi-software install 80 47```
- 🈯️ OC+ Jessie + Apache2 ```dietpi-software install 74 47```
- 🈯️ OC+ Jessie+ Nginx ```dietpi-software install 77 47```
- 🈯️ OC+ Stretch + Lighttpd
- 🈯️ OC+ Stretch + Apache2
- 🈯️ OC+ Stretch + Nginx
- 🈯️ NC + Jessie + Lighttpd ```dietpi-software install 80 114```
- 🈯️ NC+ Jessie + Apache2 ```dietpi-software install 74 114```
- 🈯️ NC+ Jessie+ Nginx ```dietpi-software install 77 114```
- 🈯️ NC+ Stretch + Lighttpd
- 🈯️ NC+ Stretch + Apache2
- 🈯️ NC+ Stretch + Nginx

**Comment by Fourdee** [comment]
@MichaIng 
Perfect, impressive 👍

**Pull request merged**
