### PR TITLE
DietPi-Software | Jellyfin

### LINKED ISSUE #5564: Error installing Jellyfin on ASUS Tinker Board
#### Required Information
- DietPi version | `cat /boot/dietpi/.version`
```
G_DIETPI_VERSION_CORE=8
G_DIETPI_VERSION_SUB=5
G_DIETPI_VERSION_RC=1
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
```
- Distro version | `echo $G_DISTRO_NAME $G_RASPBIAN`
`bullseye`
- Kernel version | `uname -a`
`Linux DietPi 5.15.35-rockchip #22.05.1 SMP PREEMPT Sat May 28 08:18:16 UTC 2022 armv7l GNU/Linux`
- SBC model | `echo $G_HW_MODEL_NAME` or (EG: RPi3)
`ASUS Tinker Board (armv7l)`
- Power supply used | (EG: 5V 1A RAVpower)
5V 1A
- SD card used | (EG: SanDisk ultra)
Samsung

#### Additional Information (if applicable)
- Software title | (EG: Nextcloud)
Jellyfin
- Was the software title installed freshly or updated/migrated?
Freshly
- Can this issue be replicated on a fresh installation of DietPi?
Yes

- Bug report ID | `echo $G_HW_UUID`

#### Steps to reproduce

1. Freshly install Dietpi
2. At dietpi-software step choose Jellyfin

#### Expected behaviour

- Jellyfin should end installation fine and launch its web GUI

#### Actual behaviour

- I get this two errors in sequence and jellyfin service is not started:
jellyfin
jellyfin2

#### Extra details

- ...

### LINKED ISSUE #5583: Jellyfin "Error while starting server"
Issue potentially similar to #4806 

The Jellyfin server fails to start. This is a freshly installed DietPi installation, with jellyfin installed using dietpi-software, but I also experienced this problem after a recent upgrade of an older installation of DietPi. The following messages are displayed using `journalctl -u jellyfin.service`

jellyfin.service: Changing to the requested directory failed: No such file or directory
jellyfin.service: Failed at step CHDIR spawning /usr/bin/jellyfin: No such file or directory
jellyfin.service: Main process exited, code=exited, status=200/CHDIR
jellyfin.service: Failed with result 'exit-code'

`cat /etc/default/jellyfin`
\# Jellyfin default configuration options
\# This is a POSIX shell fragment

\# Use this file to override the default configurations; add additional
\# options with JELLYFIN_ADD_OPTS.

\# Under systemd, use
\#  /etc/systemd/system/jellyfin.service.d/jellyfin.service.conf
\# to override the user or this config file's location.

\#
\# General options
\#

\# Program directories
JELLYFIN_DATA_DIR=/mnt/dietpi_userdata/jellyfin
JELLYFIN_CONFIG_DIR="/etc/jellyfin"
JELLYFIN_LOG_DIR="/var/log/jellyfin"
JELLYFIN_CACHE_DIR=/mnt/dietpi_userdata/jellyfin/cache

\# web client path, installed by the jellyfin-web package
JELLYFIN_WEB_OPT="--webdir=/usr/share/jellyfin/web"

\# Restart script for in-app server control
JELLYFIN_RESTART_OPT="--restartpath=/usr/lib/jellyfin/restart.sh"

\# ffmpeg binary paths, overriding the system values
JELLYFIN_FFMPEG_OPT="--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"

\# [OPTIONAL] run Jellyfin as a headless service
\#JELLYFIN_SERVICE_OPT="--service"

\# [OPTIONAL] run Jellyfin without the web app
\#JELLYFIN_NOWEBAPP_OPT="--nowebclient"

\# Space to add additional command line options to jellyfin (for help see ~$ jellyfin --help)
JELLYFIN_ADDITIONAL_OPTS=""

\# [OPTIONAL] run Jellyfin with ASP.NET Server Garbage Collection (uses more RAM and less CPU than Workstation GC)
\# 0 = Workstation
\# 1 = Server
\#COMPlus_gcServer=1

\#
\# SysV init/Upstart options
\#
\# Note: These options are ignored by systemd; use /etc/systemd/system/jellyfin.d overrides instead.
\#

\# Application username
JELLYFIN_USER="jellyfin"
\# Full application command
JELLYFIN_ARGS="\$JELLYFIN\_WEB\_OPT \$JELLYFIN\_RESTART\_OPT \$JELLYFIN\_FFMPEG\_OPT \$JELLYFIN\_SERVICE\_OPT \$JELLYFIN\_NOWEBAPP\_OPT \$JELLFIN\_ADDITIONAL\_OPTS"

`systemctl cat jellyfin.service`
\# /lib/systemd/system/jellyfin.service
[Unit]
Description = Jellyfin Media Server
After = network-online.target

[Service]
Type = simple
EnvironmentFile = /etc/default/jellyfin
User = jellyfin
Group = jellyfin
WorkingDirectory = /var/lib/jellyfin
`ExecStart = /usr/bin/jellyfin ${JELLYFIN_WEB_OPT} ${JELLYFIN_RESTART_OPT} ${JELLYFIN_FFMPEG_OPT} ${JELLYFIN_SERVICE_OPT} ${JELLYFIN_NOWEBAPP_OPT} ${JELLYFIN_ADDITIONAL_OPTS}`
Restart = on-failure
TimeoutSec = 15
SuccessExitStatus=0 143

[Install]
WantedBy = multi-user.target

\# /etc/systemd/system/jellyfin.service.d/jellyfin.service.conf
\# Jellyfin systemd configuration options

\# Use this file to override the user or environment file location.

[Service]
\# Alter the user that Jellyfin runs as
\#User = jellyfin

\# Alter where environment variables are sourced from
\#EnvironmentFile = /etc/default/jellyfin

\# Service hardening options
\# These were added in PR #6953 to solve issue #6952, but some combination of
\# them causes "restart.sh" functionality to break with the following error:
\#   sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the
\#   'nosuid' option set or an NFS file system without root privileges?
\# See issue #7503 for details on the troubleshooting that went into this.
\# Since these were added for NixOS specifically and are above and beyond
\# what 99% of systemd units do, they have been moved here as optional
\# additional flags to set for maximum system security and can be enabled at
\# the administrator's or package maintainer's discretion.
\# Uncomment these only if you know what you're doing, and doing so may cause
\# bugs with in-server Restart and potentially other functionality as well.
\#NoNewPrivileges=true
\#SystemCallArchitectures=native
\#RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
\#RestrictNamespaces=false
\#RestrictRealtime=true
\#RestrictSUIDSGID=true
\#ProtectControlGroups=false
\#ProtectHostname=true
\#ProtectKernelLogs=false
\#ProtectKernelModules=false
\#ProtectKernelTunables=false
\#LockPersonality=true
\#PrivateTmp=false
\#PrivateDevices=false
\#PrivateUsers=true
\#RemoveIPC=true
\#SystemCallFilter=\~@clock
\#SystemCallFilter=\~@aio
\#SystemCallFilter=\~@chown
\#SystemCallFilter=\~@cpu-emulation
\#SystemCallFilter=\~@debug
\#SystemCallFilter=\~@keyring
\#SystemCallFilter=\~@memlock
\#SystemCallFilter=\~@module
\#SystemCallFilter=\~@mount
\#SystemCallFilter=\~@obsolete
\#SystemCallFilter=\~@privileged
\#SystemCallFilter=\~@raw-io
\#SystemCallFilter=\~@reboot
\#SystemCallFilter=\~@setuid
\#SystemCallFilter=\~@swap
\#SystemCallErrorNumber=EPERM

System information

DietPi version : 8.5.1
Distro version : bullseye 0
Kernel version : Linux DietPi 5.15.32-v7+
SBC model : RPI2
Software title : jellyfin

### PR DESCRIPTION
**Pull request by Joulinar**
Jellyfin service needs some time now to finish first time startup. Otherwise config files are not created next time we start the service. https://dietpi.com/forum/t/jellyfin-installation-error/13402

I'm not quite happy with the delay of 30 sec, maybe you have a better idea @MichaIng 

Furthermore we need to changed `WorkingDirectory` within service config to point to `/mnt/dietpi_userdata/jellyfin` as well.

### CODE REVIEW

**Review by MichaIng — CHANGES_REQUESTED** [review]
Check out the `Create_Config` function, which does basically the same: Loop and wait for config file with timeout 🙂.

**Comment by Joulinar** [comment]
> Check out the Create_Config function

That's as it is right now. 

And there is the problem atm. Because the service needs to finish his startup once, to be able to create configuration files on next service start. Currently we stop the service right after package has been installed. And that's to early. There the service did not complete and will not create files next service start, which ist triggered by `create_config`. Means no configuration files are created and `create_config` is failing. Therefore I tried to delay the shutdown of the service right after it has been installed.

I hope I could explain it a bit. Honestly I'm not sure if this is an intended behaviour.

**Comment by Joulinar** [comment]
Honestly I don't know. The service needs to pass the first a couple of initial steps. But not sure if he is doing something on file system level.

**Comment by MichaIng** [comment]
There must be some change in filesystem level, as there is nothing else that can be different on service restart. But a specific database entry is difficult to check for. I'll have a look.

**Comment by MichaIng** [comment]
Actually if the config files do not exist yet, why do we stop the service just for starting it again. In this case we can just let it run to safe time and extra restart loop when waiting for the config file to be created.

**Comment by Joulinar** [comment]
Doesn't matter how we do it, we need to keep the service first time running for 20-30 seconds before we are going to restart.

**Comment by Rmy1992** [comment]
(Therefore I tried to delay the shutdown of the service right after it has been installed)

can u teach how to do this, so just before the arrival of dietpi v8.6?

**Comment by Joulinar** [comment]
Most probably we will release a beta version of DietPi v8.6 on upcoming weekend. I recommend to wait 2 more days.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Can you share the full installation log? At best copy & paste the raw text from SSH console, if possible.

Only explanation I have is that one of the loops waiting for the config file after service start times out. If that is the case the output of the following command would be helpful as well:
```bash
journalctl -u jellyfin
```

**Pull request merged**
