### PR TITLE
Modified fstab to enable NTFS to work with Owncloud

### PR DESCRIPTION
**Pull request by CedArctic**
Changed the mounting options of the NTFS drive. Added the permissions flag so "sudo chown -R www-data:www-data /var/lib/owncloud/data" can be issued to enable owncloud to work with NTFS drives.

### CODE REVIEW

**Comment by Fourdee** [comment]
@CedArctic 
Good find and fix :+1: 

As all development is done on the testing branch, before its merged into master (live), could you please send this pull request to the testing branch (https://github.com/Fourdee/DietPi/tree/testing)? 

I will then accept the request.

**Comment by CedArctic** [comment]
OK sure, eventhough I think that solving this issue is kind of more complicated than just changing the mount flags, but this is definitely the first step. Sending the pull request to testing.

**Comment by Fourdee** [comment]
@CedArctic 
Thanks

> OK sure, eventhough I think that solving this issue is kind of more complicated than just changing the mount flags, but this is definitely the first step. Sending the pull request to testing.

Its as simple as that. I checked the code just to be sure.

The only script that modifies those entries is:
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-external_drive_setup

It changes the `/etc/fstab` `/mnt/usb_1` entry using a pattern match and replacement:
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-external_drive_setup#L64-L66
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-external_drive_setup#L133-L138

As for existing users running USB NTFS, I cant risk patching their system as enabling the permissions flag, without the previous permissions applied during install, could break any installed software and/or files in `/mnt/usb_1`.

**Comment by Fourdee** [comment]
Applied to testing branch: https://github.com/Fourdee/DietPi/pull/227

**Pull request closed without merging**
