### PR TITLE
Image | NanoPi R4S and NanoPi R1

### LINKED ISSUE #3458: Image | NanoPi R1S-H3
#### Formal device information
- Device name | NanoPi R1S-H3
- Official product URL | https://www.friendlyarm.com/index.php?route=product/product&product_id=274
- GitHub resource URL (if available) | http://wiki.friendlyarm.com/wiki/index.php/NanoPi_R1
- Image download URL | https://drive.google.com/drive/folders/19Eu--we0rmXUAtA4T0qGzz3GwyizRdct

#### Is the SBC officially supported by the Debian installer?
- Not sure

#### If not, is a reliable 3rd party Debian image available for this SBC?
- EDIT: REMOVED OBSOLETE LINK

#### If not, are there install instructions for Debian available?
http://wiki.friendlyarm.com/wiki/index.php/Building_U-boot_and_Linux_for_H5/H3/H2%2B

The M1plus DietPi image boots, wifi and serial console work, so it shouldn't be a big lift to

### LINKED ISSUE #3923: Image | NanoPi R4S
#### Formal device information
- Device name | NanoPi R4S (RK3399 with dual GiB Ethernet on 66 x 66 mm PCB)
- Official product URL | https://wiki.friendlyarm.com/wiki/index.php/NanoPi_R4S

#### Is the SBC officially supported by the Debian installer?
- That is to be tested: https://packages.debian.org/buster-backports/linux-image-arm64
- U-Boot? https://github.com/friendlyarm/uboot-rockchip

#### If not, is a reliable 3rd party Debian image available for this SBC?
- Armbian to come for sure, but no download available yet

### LINKED ISSUE #4017: Image | NanoPi R1
#### Formal device information
- Device name | **FriendlyARM NanoPi R1**
- Official product URL | **https://www.friendlyarm.com/index.php?route=product/product&product_id=248**
- GitHub resource URL (if available) | **https://github.com/friendlyarm**
- Image download URL | **http://download.friendlyarm.com/nanopir1**
- Wiki URL | **https://wiki.friendlyarm.com/wiki/index.php/NanoPi_R1**

#### Is the SBC officially supported by the Debian installer?
- only UNSTABLE | **https://wiki.debian.org/InstallingDebianOn/Allwinner**
- on sunny **H5** | !FriendlyARM NanoPi NEO 2 | **sun50i-h5-nanopi-neo2.dtb**
- on sunny **H3** | Nano Pi Neo | **sun8i-h3-nanopi-neo.dtb**

#### If not, is a reliable 3rd party Debian image available for this SBC?
- ARMBIAN | **https://redirect.armbian.com/nanopi-r1/Buster_current**

#### If not, are there install instructions for Debian available?
**https://github.com/drtyhlpr/rpi23-gen-image/
https://github.com/Debian/raspi3-image-spec**
- ...

#### SBC Spec
Hardware Spec
    CPU: Allwinner H3, Quad-core Cortex-A7 Up to 1.2GHz
    DDR3 RAM: 512MB/1GB
    Storage: NC/**8GB eMMC**
    Network:
        10/100/1000M Ethernet x 1，
        10/100M Ethernet x 1
    WiFi: **802.11b/g/n, with SMA antenna** interface
    Bluetooth：4.0 dual mode
    USB Host: Type-A x2
    MicroSD Slot x 1
    MicroUSB: for OTG and power input
    Debug Serial Port: 3Pin 2.54mm pitch pin-header
    UART: 4Pin 2.54mm pitch pin-header
    LED: LED x 3
    KEY: KEY x 1
    PC Size: 50.5 x 60mm
    Power Supply: DC 5V/2A
    Temperature measuring range: -20℃ to 70℃
    **OS/Software: U-boot，Ubuntu-Core，OpenWRT**

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Obtain_HW_model | Add NanoPi R4S and R1 support

### CODE REVIEW

**Comment by Joulinar** [comment]
sorry I don't have such a SBC. 🙃

**Comment by StephanStS** [comment]
> sorry I don't have such a SBC. upside_down_face

Me neither (only R2s).

**Comment by ckuethe** [comment]
> sorry I don't have such a SBC.

I do (#3458). I'll try give this a run later in the weekend.

**Comment by Joulinar** [comment]
It's already merged into dev branch, pls use this one 😉

**Comment by MichaIng** [comment]
Nice. I'll be able to create images this weekend.

**Pull request merged**
