### PR TITLE
WiFi Hotspot | Add 802.11ax/WiFi 6 support (Bookworm only)

### PR DESCRIPTION
**Pull request by MichaIng**

### CODE REVIEW

**Comment by MichaIng** [comment]
Merging this now. The toggle generally works as expected and on Bookworm only. What I am not sure about is 6 GHz in this regards. The example config says:
```sh
# Operation mode (a = IEEE 802.11a (5 GHz), b = IEEE 802.11b (2.4 GHz),
# g = IEEE 802.11g (2.4 GHz), ad = IEEE 802.11ad (60 GHz); a/g options are used
# with IEEE 802.11n (HT), too, to specify band). For IEEE 802.11ac (VHT), this
# needs to be set to hw_mode=a. For IEEE 802.11ax (HE) on 6 GHz this needs
# to be set to hw_mode=a. When using ACS (see channel parameter), a
# special value "any" can be used to indicate that any support band can be used.
# This special case is currently supported only with drivers with which
# offloaded ACS is used.
# Default: IEEE 802.11b
hw_mode=g
```
So `hw_mode=a` means 5 GHz in general, but for 802.11ax/WiFi 6 it means 6 GHz? How to toggle between WiFi 6 with 5 GHz and 6 GHz then, as it supports both frequencies, or more precisely, 6 GHz is actually "Wi-Fi 6E", and I do not see a way to switch between WiFi 6 with 5 GHz and WiFi 6E with 6 GHz.

I cannot test it as I have no WiFi 6 capable adapter, so how hostapd behaves exactly with WiFi 6 and 5 GHz enabled in `dietpi-config`, probably depending on the capabilities of the adapter, still needs to be found out.

**Comment by lukaszsobala** [comment]
Hello, I am trying to test this but the isc-dhcp-server fails to start. It doesn't seem to be related to the WiFi version... I have sent a report, please take a look

**Comment by MichaIng** [comment]
Can you please open a new issue and add your bug report UUID?

**Comment by lukaszsobala** [comment]
> Can you please open a new issue and add your bug report UUID?

Sorry I am away now and cannot do this, but I will as soon as I can.

**Pull request merged**
