### PR TITLE
DietPi-Software | CertBot: Fix renewal issues

### PR DESCRIPTION
**Pull request by MichaIng**
+ Mainly deals with https://github.com/Fourdee/DietPi/issues/734#issuecomment-361774084
+ Fixes initial https://github.com/Fourdee/DietPi/issues/734 issue as well.
+ Also adds Minio cert renewal to Stretch+ renewal system service.
+ As on Stretch+ cert renewal is added to systemd service on APT installation, the option with dietpi-letsencrypt does not make too much sense. Switched it with (new?) HSTS option. 
+ Is https://github.com/Fourdee/DietPi/issues/1159 still present? I can't find the noip warning any more.

Accidentally committed first part on master, but merging into testing seems to work.

____________________

As of the current apache/nginx module authentication issues https://github.com/Fourdee/DietPi/issues/734#issuecomment-361774084, I am not sure, if switching Jessie to affected backports packages makes sense. The certbot master branch already fixed this issue for our Jessie installations and we would awake it again. I would leave it as it is for now and just work around the issue on Stretch+. If some fix will find it's way to Stretch repo, we can revert renewal back to `--apache/--nginx`.

____________________

🈯️ RPi Buster with Apache
🈯️ VM Jessie with Nginx + Minio S3
🈯️ VM Stretch with Lighttpd
🈯️ VM Buster with Minio S3

### CODE REVIEW

**Comment by MichaIng** [comment]
🈯️ VM Jessie with Minio S3:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
```
I was confused, since the newest master branch version is in use, but then I realized we force TLS-SNI method currently for Minio. Removing this, allowed certbot to continue:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for teerwlkj.fsfse.org
Waiting for verification...
Cleaning up challenges
```

**Comment by MichaIng** [comment]
@Fourdee 
From my side it is ready to merge, tested all parts on different distros with different webservers.

**Comment by Fourdee** [comment]
@MichaIng 

Legend 👍  I'll merge for testing.

**Review by Fourdee — APPROVED** [review]
👍

**Pull request merged**
