### PR TITLE
DietPi-Build | Generate ROCK 5B images with a single ext4 partition

### LINKED ISSUE #6206: Rock5B - bookworm - no space left when updating (boot partition)
trying to update linux-image-legacy-rockchip-rk3588 Result in a no space left:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  linux-image-legacy-rockchip-rk3588
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
20 not fully installed or removed.
Need to get 25.7 MB of archives.
After this operation, 36.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://imola.armbian.com/apt bullseye/main arm64 linux-image-legacy-rockchip-rk3588 arm64 23.02.2 [25.7 MB]
Fetched 25.7 MB in 27s (967 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 18390 files and directories currently installed.)
Preparing to unpack .../linux-image-legacy-rockchip-rk3588_23.02.2_arm64.deb ...
Unpacking linux-image-legacy-rockchip-rk3588 (23.02.2) over (22.11.4) ...
dpkg: error processing archive /tmp/apt/archives/linux-image-legacy-rockchip-rk3588_23.02.2_arm64.deb (--unpack):
 cannot copy extracted data for './boot/vmlinuz-5.10.110-rockchip-rk3588' to '/boot/vmlinuz-5.10.110-rockchip-rk3588.dpkg-new': failed to write (No space left on device)
Removing obsolete initramfs images
Removing obsolete initramfs images
Errors were encountered while processing:
 /tmp/apt/archives/linux-image-legacy-rockchip-rk3588_23.02.2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### PR DESCRIPTION
**Pull request by MichaIng**

### CODE REVIEW

**Comment by isarrider** [comment]
out of curiosity -> why exactly 752 as size?

**Comment by MichaIng** [comment]
I use multiples of 64 MiB for the overall initial image size (is minimised later) and based on experience with other images with a single ext4 partition, that is the minimum sufficient one.

**Comment by isarrider** [comment]
overall means? (as 752 / 64 = 11,75)
As is starts from 16, do you add this? (to get to 768)?

**Comment by MichaIng** [comment]
> As is starts from 16, do you add this? (to get to 768)?

Exactly, "overall" image size.

**Comment by isarrider** [comment]
Got it...
Thx!

**Review by isarrider — APPROVED** [review]
LGTM - Ill test...

**Comment by isarrider** [comment]
I would also like to test Bookworm with a single partition with Btrfs and zstd compression enabled
(prob level 3 is a good tradeoff), as in my cases the SD-Card is always the slowest link in the chain...
Is there an easy way for you to generate this?

**Comment by isarrider** [comment]
awesome - gracias...

**Comment by MichaIng** [comment]
Thanks for the info.

I think so and created images to test this yesterday, coincidentally: https://github.com/MichaIng/DietPi/discussions/5168#discussioncomment-5387235
Still want to assure it works with the particular kernel and U-Boot build we use from Armbian. And the images also use an MBR partition table, which might not work (it does not with our Orange Pi 5 and ROCK 5B images), so this might need to be reverted to use GPT.

**Pull request merged**
