### PR TITLE
Beta v6.25.1

### PR DESCRIPTION
**Pull request by MichaIng**
### Beta v6.25.1
_(29/06/19)_

#### Changes / Improvements / Optimisations (since v6.25.0)
- System | By default the "haveged" entropy daemon is now installed on all DietPi systems and patched with v6.25. It assures the pool of random bits /dev/random stays filled by using additional sources of randomness. This solves a bunch of issues, including hanging or very long boot times, very long service (re)starts or timeout failures and on Buster hanging network access. Especially affected is PHP7.3-FPM but as well VPN servers and WiFi hotspots and potentially many other network or cryptography related tasks. More information on this topic: https://github.com/MichaIng/DietPi/issues/2806
- System | Initial RPi4 support has been added to the code and some other rare RPi models are now detected correctly by their revision codes. Note that a new Buster-based image is required to support RPi4 and further work on DietPi-Config to support new RPi4 features. Full support is expected with DietPi v6.26, testing images can be found here: https://github.com/MichaIng/DietPi/issues/2935#issuecomment-506389899

#### Bug Fixes (since v6.25.0)
- DietPi-Drive_Manager | Resolved an issue where on x86_64 systems a specific Seagate drive, attached via USB, does not spin down on idle. Many thanks to @tomillr for reporting this issue: https://github.com/MichaIng/DietPi/issues/2905
- DietPi-Config | (RPi) Resolved an issue where selecting sound cards with vc4 enabled would result with incorrect alsa card index: https://github.com/MichaIng/DietPi/issues/2173
- DietPi-Software | Resolved an issue on Buster systems that were dist-upgraded manually from Stretch, where DietPi-Software failed to obtain the global software password. Many thanks to @MattL0 for reporting this issue: https://github.com/MichaIng/DietPi/issues/2937

### CODE REVIEW

**Comment by CollinChaffin** [comment]
For the first time, updating from 6.25.0 to 6.25.1 via `dietpi-update` brings up the blue update screen with menu, can perform backup and read release notes off that menu, but no matter what I do selecting "Apply 6.25.1 update" even manually tabbing to the OK button and hitting it does nothing at all.  I've restarted cleanly and tried again with same result and no other apparent issues on the build.  Is there a different way this update needs to be performed?

**Comment by user349** [comment]
Try dietpi-update 1
Faced the same issue ,above command updated no problem

**Comment by CollinChaffin** [comment]
A bit nervous to do that which is why I commented here first this is unlike past updates before I try to jackhammer it in just wanted to verify if this is a known issue or not but otherwise I guess I'll just force it.

**Comment by MichaIng** [comment]
@CollinChaffin @user349 
Many thanks for reporting. Yes `dietpi-update 1` is the way to go.

Found the issue:
```
root@DietPi:~# whiptail --msgbox 'test' 10 60
root@DietPi:~# whiptail --msgbox '--test' 10 60
--test: unknown option
```
- The first works well.
- The second interprets the message that should show in the box as option (due to leading dashes) which is invalid, thus it fails.

The update whiptail has leading dashes in its text, thus fails. Strange however is that we have this already since... let me see.. ah nope, I removed a leading blank line...
```
root@DietPi:~# whiptail --msgbox '
> --test' 10 60
```
- Works well again.
- However the leading blank line looked a bid ugly to me 😄.

Resolved with: https://github.com/MichaIng/DietPi/blob/dev/dietpi/dietpi-update
- + some max menu width, so that these dash lines do not end in the middle of the dialog.

Okay this means all current beta users must update with `dietpi-update 1` until v6.25.2.
______________
@CollinChaffin
There is btw absolutely no difference between `dietpi-update 1` and using the menu, besides that the menu allows you to do backup first, see the changelog and toggle auto-updates. And yeah this confirmation prompt that caused the issue.

**Comment by CollinChaffin** [comment]
Wow that was fast!  Thanks @MichaIng just ran it non-interactively via `dietpi-update 1` and all is well.  Thanks again!

**Pull request merged**
