### PR TITLE
Support of RISC-V (StarFive VisionFive 2) - step 1

### PR DESCRIPTION
**Pull request by StephanStS**
First step of the support of the [RISC-V board VisionFive 2](https://www.starfivetech.com/en/site/boards) with the JH7110 processor

### CODE REVIEW

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Okay I added some fix for the Debian repo (hardcoding Debian ports Sid an unreleased) and installing/preserving the ports repo key in DietPi-Installer. Also it adds contrib and non-free components, which should fix the firmware installs.

I removed the dedicated CPU ID, which isn't needed as long as its for a single SBC only and from the same vendor than the SBC as well.

**Comment by MichaIng** [comment]
For adding support to DietPi-Build, we'd need to package the kernel that is installed on your device, since it is not present in the APT repositories (is it?). But that can be done after DietPi v8.14 release 🙂.

**Comment by StephanStS** [comment]
I will test this changes in the dietpi-imager.

**Comment by StephanStS** [comment]
> For adding support to DietPi-Build, we'd need to package the kernel that is installed on your device, since it is not present in the APT repositories (is it?). But that can be done after DietPi v8.14 release slightly_smiling_face.

Actually, kernel is 
`Linux DietPi 5.15.0-starfive #1 SMP Mon Dec 19 07:56:37 EST 2022 riscv64 GNU/Linux`

The repo has

```
root@DietPi:~# apt-cache search linux-image
linux-headers-6.1.0-4-riscv64 - Header files for Linux 6.1.0-4-riscv64
linux-image-6.1.0-4-riscv64-dbg - Debug symbols for linux-image-6.1.0-4-riscv64
linux-image-6.1.0-4-riscv64 - Linux 6.1 for 64-bit RISC-V platforms
linux-image-riscv64-dbg - Debugging symbols for Linux riscv64 configuration (meta-package)
linux-image-riscv64 - Linux for 64-bit RISC-V platforms (meta-package)
linux-image-5.15.0-starfive - Linux kernel, version 5.15.0-starfive
```

So I can try to update to 6.1.0-4.

**Comment by MichaIng** [comment]
> So I can try to update to 6.1.0-4.

That does not work. The kernel is there already but it does not have a device tree for the VisionFive 2. We need to generate a `.deb` file from the `linux-image-5.15.0-starfive` package installed on your system. There is a package which can do that, I'll check it out after merging the DietPi release.

**Pull request merged**
