### PR TITLE
DietPi-NordVPN | Safe settings file in a shell source-able way, tiny fix and minor coding

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-NordVPN | Tiny fix: `G_WHIP_YES_NO` => `G_WHIP_YESNO`
+ DietPi-NordVPN | Safe settings file in a shell source-able way
+ DietPi-NordVPN | Minor coding

@Fourdee 
What do you think? Only concern is that the plain text password and `NORDVPN_PASSWORD` string are associated in a single file, though, only readable by root user.
We could do something similar than with global password: Encrypting the password in a separate hidden file.

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

Thanks Micha 👍 💯 

> We could do something similar than with global password: Encrypting the password in a separate hidden file.

Yep, will try and add this in today.

**Comment by Fourdee** [comment]
@MichaIng 

Sourceable settings file does not work, as OpenVPN config expects 2 lines:
```
username
password
```

Edit, only reads 1st two lines, so we can still source after that.

**Comment by MichaIng** [comment]
@Fourdee 
Ahh this is used by OpenVPN directly? Should have read the `dietpi-software` code.

**Comment by Fourdee** [comment]
@MichaIng 

Yep, read by OpenVPN. Might need to split into two files as this is a little messy on source:
```
/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/settings.conf: line 1: XXXXXX@gmail.com: command not found
```

**Comment by MichaIng** [comment]
@Fourdee 
Then better revert to non source-able, too complicated otherwise, and I am not keen to have to password saved two times in plain text.
And yeah, this also makes encryption save impossible, if not OpenVPN natively allows to decrypt an encrypted password line?

Hmm am I blind? Where do we tell OpenVPN to use this config file?

**Comment by Fourdee** [comment]
@MichaIng 

 ```G_CONFIG_INJECT 'auth-user-pass[[:blank:]]' "auth-user-pass $FP_SETTINGS_OVPN" /etc/openvpn/ovpn_$PROTOCOL/$NORDVPN_SERVER```

**Comment by MichaIng** [comment]
@Fourdee 
Ah jep, so I am blind 😄. Yeah I think revert to previous stage with single config file? Doesn't have any advantage to make this complicated with two of them?

Also the single quote escaping is not required then, respectively would most likely lead to wrong results. I am pretty sure that OpenVPN reads the line as is without any expansion, similar to what `sed -n Xp` leads.

**Comment by Fourdee** [comment]
@MichaIng 

> Yeah I think revert to previous stage with single config file? Doesn't have any advantage to make this complicated with two of them?

Its fine as it is with 2 files, allows us to expand features on our source-able file in the future, if needed.

**Pull request merged**
