### PR TITLE
DietPi-Software | Single File PHP Gallery

### PR DESCRIPTION
**Pull request by Joulinar**
There is a new version of `Single File PHP Gallery` available. I adjusted the link to point to maintainer web side instead of `dietpi.com`

**Status**: Ready
- [x] adjust download link

**Reference**: https://dietpi.com/phpbb/viewtopic.php?t=9601

**Commit list/description**:
- DietPi-Software | Single File PHP Gallery - update download link

### CODE REVIEW

**Comment by MichaIng** [comment]
I think we host it intentionally on our server so that we can update it on the fly without the need to touch the code. Sadly there is no official "latest" download link. This has also downsides, e.g. when a new version has new dependencies or drops old PHP version support or so, so that we want to keep the version fixed for a DietPi version. But SFPG was very conservative in the past, although from the v4.8.0 changelog:
> If you are upgrading from an older version to this version you need to delete the contents of DATA_ROOT.

This means that we either need to migrate existing installs or remove `/var/www/gallery/_sfpg_data` generally on reinstalls.

I'll check what is inside. Cache and thumbnails are not an issue but when settings are stored there in a way, we must inform users, of course.

**Comment by MichaIng** [comment]
Okay, `/var/www/gallery/_sfpg_data` contains only thumbnails and metadata, all recreated automatically when missing. It is hence safe to simply remove it on every reinstall, when present. More problematic is actually that we overwrite user settings in `index.php` itself on reinstalls, but due to the nature of this PHP script to not have settings stored in a dedicated files, I see no way around this. However, since I see no reason why we'd ever need to force a reinstall, this shouldn't be an issue. If we do need to do a reinstall in the future, we should simply create a backup of the config section, the lines between `CONFIGURATION START` and `CONFIGURATION END`.

So with a cache removal on reinstalls, updating the archive on our server on the fly isn't an issue. It still has up and downsides. Any opinion on this?

**Comment by MichaIng** [comment]
A proper security phrase is now set. The previous method changed another case in the script where it would have automatically create one when missing. This doesn't cause any issues since it was set, but better to be more explicit and change only the one intended occurrence at the start of the script, using a 30 alphanumeric character string, like the script itself would attempt it.

**Review by MichaIng — APPROVED** [review]

**Comment by Joulinar** [comment]
Question is how often the version is changing? I guess not that often right?

**Pull request merged**
