### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by rhkean**
Initial PineA64 support

### CODE REVIEW

**Comment by Fourdee** [comment]
Hi Rob,

Excellent work on this, i'll take a look today.

Your updated image is uploaded: http://dietpi.com/downloads/images/

**Comment by Fourdee** [comment]
@rhkean 
Code is spot on, great work :+1:

**Comment by rhkean** [comment]
Any objections to me making reference to this on the Pine A64 forums?

**Comment by Fourdee** [comment]
@rhkean 
By all means, if you want to have users test it, spread the word.

I can put it on the dietpi.com main page and forums, aswell if you think its ready for full release?

**Comment by rhkean** [comment]
Sure... the more testers the better... :smile: 

definitely list it as alpha, though

**Comment by rhkean** [comment]
do you have a standardized post/announcement that you use?

**Comment by Fourdee** [comment]
@rhkean 
:+1:  I'll add your image to the main website and forum documentation.

> do you have a standardized post/announcement that you use?

Something like this, but improve on it if you can, I tend to rush the posts just to get them out lol:
C2 http://forum.odroid.com/viewtopic.php?f=138&t=19948
C1 (nice and clean) http://forum.odroid.com/viewtopic.php?f=114&t=11962&p=83691#p83691

Heres the phpbb post code for c1:

```
[attachment=0]dietpi-logo_150.png[/attachment]
[size=150][b]DietPi for Odroid-C1[/b]: Lightweight Justice for your Odroid.
[url]http://DietPi.com[/url]
[/size]
DietPi for Odroid C1 was featured in the July issue of the Odroid Magazine [url]http://magazine.odroid.com/assets/201507/pdf/ODROID-Magazine-201507.pdf[/url].

DietPi for Odroid C1 is currently based on Meveric's excellent Debian Jessie images: [url]http://forum.odroid.com/viewtopic.php?f=96&t=17542#p114709[/url].

[b]Download DietPI / Getting started: [/b][url]http://dietpi.com[/url]
[b]DietPi-Software list:[/b] [url]http://dietpi.com/software[/url]

[b]DietPi web hosting is powered by [url]http://MyVirtualServer.com[/url][/b]
```

Either way, go wild :)

You can grab the DietPi logo (150 is a good size) from: http://dietpi.com/images

**Comment by Fourdee** [comment]
@rhkean 
Main site (you may need to ctrl+f5 refresh it): http://dietpi.com/#five

Once you've completed the Pine 64 post, link it here and I'll add it to releases on the forums: http://dietpi.com/phpbb/viewforum.php?f=8

**Comment by rhkean** [comment]
http://forum.pine64.org/showthread.php?tid=1068

**Comment by Fourdee** [comment]
@rhkean 
Excellent post, looks good :+1: 

I've added forum references for Pine A64: 
- http://dietpi.com/phpbb/viewtopic.php?f=8&t=420#p1828 | Links straight to your Pine post
- http://dietpi.com/phpbb/viewtopic.php?f=8&t=9#p9

**Pull request merged**
