### PR TITLE
DietPi-Software | Plex Media Server: Update installer

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Testing
- [x] Changelog

**Testing:**
- [x] Jessie
- [x] Stretch
- [x] Buster
- [x] ARM, Jessie + locale change

**Reference**: https://github.com/Fourdee/DietPi/issues/2294

**Commit list/description**:
+ DietPi-Software | Plex Media Server: Update x86 download link to v1.14.0
+ DietPi-Software | Plex Media Server: Switch ARM repo to HTTPS
+ DietPi-Software | Plex Media Server: Switch locale automated, as well on non-interactive executions. Prompt whiptail window for user information only.

### CODE REVIEW

**Comment by MichaIng** [comment]
@Fourdee 
When you find time: Could you test on ARM Jessie to verify https repo does not cause issues there?

**Comment by MichaIng** [comment]
- [x] Revert G_AGUP to be applied after armhf is applied to ARM devices? Or isn't `deb [arch=armhf]` in sources + `libstdc++6:armhf plexmediaserver-installer:armhf` actually sufficient to allow PMS armhf package to be installed on ARMv8? Ah perhaps `libstdc++6:armhf` does not install then?

€: Generally I don't like `dpkg --add-architecture xxx` very much, since it leads to additional package sources/cache being downloaded and saved to disk of ~30M and much more apt update output.
- If this is only required for a single package, `libstdc++6:armhf` might do?
- If required for a whole repo `deb [arch=armhf]` should do.
- When downloading deb packages manually, they can be edited to be handled as arch that you want, so no need to add the foreign arch to dpkg by default as well.

Same for x86 and i386 deb arch. Currently don't remember for which software title it was, but only for a single one, AFAIK. I remove this always as first step from my VMs, never ran into an issue with this, so never hit the related package during testing so far 😉. Hence we should adjust this either via above methods or only being applied on the affected software installs.

Btw: On my RPi I managed to move the APT cache to RAM:
```
2018-12-13 01:40:03 root@micha:/tmp# cat /etc/apt/apt.conf.d/99-micha-apt_cache
#Dir "/";
Dir::Cache "tmp/apt";
#Dir::Cache::archives "archives/";
#Dir::Cache::srcpkgcache "";
#Dir::Cache::pkgcache "pkgcache.bin";
2018-12-13 19:24:42 root@micha:/tmp# l /tmp/apt/
total 58952
drwxr-xr-x 3 root root       80 Dec 13 01:38 archives
-rw-r--r-- 1 root root 30180387 Dec 13 01:38 pkgcache.bin
-rw-r--r-- 1 root root 30180275 Dec 13 01:38 srcpkgcache.bin
2018-12-13 19:28:36 root@micha:/tmp# G_TREESIZE /tmp/apt
57.6 MB /tmp/apt
0.0 KB /tmp/apt/archives
```
- Source package cache can be disabled completely by using empty string: `Dir::Cache::srcpkgcache "";` But not sure if this is still re-downloaded on every APT update then.
- Cache needs to be recreated after reboot of course, but this is done way less often than APT update, usually, and I prefer this over up to 60M being rewritten to disk every time.
- 60M is as above without archives and with only `main` (no `contrib`/`non-free`/`ui`) repo and only raspbian+rasperrypi, so no additional repos, and disabled translations: `Acquire::Languages "none";`

Since it works quite safe, and non-existent cache is never an issue for APT, we might want to add it as default to DietPi, optionally allow to move it back to disk via `dietpi-config`?
- Perhaps also leave on disk for low RAM devices, e.g. <512M.

**Comment by Fourdee** [comment]
@MichaIng 

> When you find time: Could you test on ARM Jessie to verify https repo does not cause issues there?

Yep, will try and setup one today/tomorrow.

**Comment by Fourdee** [comment]
@MichaIng 

> Btw: On my RPi I managed to move the APT cache to RAM:

Nice 👍 

Could work as optional, but, we'd need to ensure our swapfile auto set has not been cleared by user. Also, might need to increase swapfile to 4GB - RAM, to prevent any out of memory errors in large/multiple APT installations.

**Comment by Fourdee** [comment]
Jessie install test Odroid C2:
- 🈯️ 

@MichaIng 

Works a charm 👍

**Comment by MichaIng** [comment]
@Fourdee 
> Also, might need to increase swapfile to 4GB - RAM, to prevent any out of memory errors in large/multiple APT installations.

If a larger swap is required (so used), then this step somehow loses it's intention to reduce disk I/O, besides one can move the swap away from SDcard. I agree it should be optional and perhaps only available for devices with at least 512M (or better 1G?) RAM. And it makes sense to measure current free RAM and measure current APT cache size to give recommendation about this to user.
We can further allow to move the cache to custom dir (e.g. external drive), if RAM is already used much, to at least reduce SD I/O. Optionally allow to disable package translation downloads as well to reduce the cache size. Can be separate sub menu within Advanced options. Since it's easy to implement, I can do this for v6.20 I hope 🙂.

**Pull request merged**
