### PR TITLE
DietPi-Set_Hardware | Install allo Piano firmware on demand

### PR DESCRIPTION
**Pull request by MichaIng**
https://github.com/Fourdee/DietPi/issues/1656

@Fourdee 
Was creating PR a bid too fast. Actually the allo web ui is not needed for using their DAC modules, right? So firmware on demand installation needs to be done (just) via `dietpi-set_hardware` and not `dietpi-software`?
Also then firmware should be removed only (within patchfile), when `dtoverlay=*allo-piano-dac*` can be found within `config.txt` (btw. this is used by Sparky as well? https://github.com/Fourdee/DietPi/blob/allo_firmware_ondemand/dietpi/func/dietpi-set_hardware#L1931) or `/etc/modules` and not on dietpi-software uninstall.

- [x] Clarification allo web ui vs DACs / firmware => Remove firmware install/uninstall from dietpi-software?

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

> So firmware on demand installation needs to be done (just) via dietpi-set_hardware

Yep, this is fine. 

In regards to the allo GUI, when selecting a soundcard it also runs ```dietpi-set_hardware```. So we are covered there aswell.

Also need to remove the firmware install from PREP, if i remember correctly?

**Comment by MichaIng** [comment]
@Fourdee 
Okay should be fine now. Firmware installation just via `DietPi-Set_Hardware`, when choosing allo Piano DAC as soundcard. We will leave firmware in place then, as if user has the DAC, he might want to use it again, perhaps switching soundcard for testing and we do not want to reinstall the firmware every time.

- `/DietPi/config.php` does not exist on Sparky, thus it's good to add the dtoverlay (Sparky uses kernel module) line just in case of RPi, right?
- `/lib/firmware/allo` does not exist by default on Sparky, right? Otherwise the current solution would never install the sparky-test repo version and ondemand would not make sense for that device 😉.

**Comment by Fourdee** [comment]
@MichaIng 

> /DietPi/config.php does not exist on Sparky, thus it's good to add the dtoverlay (Sparky uses kernel module) line just in case of RPi, right?

Yep, no harm. ```config.txt``` is used by RPi only, but added to all our images so we dont need to check for it. 

> /lib/firmware/allo does not exist by default on Sparky, right? Otherwise the current solution would never install the sparky-test repo version and ondemand would not make sense for that device 😉

``` /lib/firmware/allo``` does exist. We may need to remove the folder check for both devices, always download and install the latest firmware.

EDIT:
Actually, should be fine to leave check in. Allo contact me when there are any updates and we can simply apply it in patch file.

**Review by Fourdee — APPROVED** [review]
👍

**Comment by Fourdee** [comment]
@MichaIng 

Great work, many thanks. Will merge 👍

**Comment by MichaIng** [comment]
@Fourdee 
Ah you already adjusted the patch_file, just recognized the forgotten `!` 😅.

Hmm okay if Sparky comes with preinstalled firmware anyway, then for my impression we can directly ship the newer (?) firmware version with our image and forget about ondemand for this device. On the other hand, if it does not hurt, we could remove the firmware on DietPi-PREP first (as we do on patch now), providing slightly smaller image/disc usage, and leave ondemand in place. This as well guarantees newest firmware version, when user plugs the DAC.

My main aim with this was to prevent deployment of **additional** firmware that might be just used by few users. Especially when I saw the download of this on `dietpi-update` to my RPi few versions ago and thought that it never did and will never (most properly) produce any sound output 😉.

**Pull request merged**
