### PR TITLE
DietPi-Software | Ampache: Fix install of v5 (Bullseye)

### PR DESCRIPTION
**Pull request by Joulinar**
Since version 5, Ampache web path has been changed to `/ampache/public`

https://github.com/ampache/ampache/wiki/Ampache-Next-Changes#you-will-need-to-update-the-web-server-document-root

**Status**: Ready
- [x] adjust install

**Reference**: https://dietpi.com/phpbb/viewtopic.php?t=9947

**Commit list/description**:
- DietPi-Software | Ampache - web server path has been changed on Ampache 5

### CODE REVIEW

**Comment by MichaIng** [comment]
Since Ampache v5 requires PHP7.4 or higher, on Buster we install Ampache v4, so this needs to be conditional.

It is ugly with an additional path, but no idea how to resolve since the public scripts require the other files to be in the parent directory. At least worth a test is to install Ampache to `/mnt/dietpi_userdata/ampache` and link `/var/www/ampache => /mnt/dietpi_userdata/ampache/public`. Not sure whether PHP then finds the parent directory instead of failing to find the files in `/var/www`.

**Comment by Joulinar** [comment]
Ok let me have a look

**Comment by Joulinar** [comment]
Surprise @MichaIng 
having it installed into `/mnt/dietpi_userdata/ampache` and do a symlink `var/www/ampache` => `/mnt/dietpi_userdata/ampache/public`, is working. Not sure if this is as expected, but yeaahhh. I tested using Nginx. 

But somehow I'm not confident with it, as we move web server data into a completely different directory outside the web server.

**Comment by MichaIng** [comment]
Adjusted accordingly. Read to test.

**Comment by MichaIng** [comment]
Works fine now, also on Bookworm. I'll merge.

**Pull request merged**
