### PR TITLE
Includes option for minutely cronjobs

### PR DESCRIPTION
**Pull request by d5c0d3**
i needed to run a cronjob on a 2 minute basis for reading a sensor. since the prefered way of editing the crontab is dietpi-cron I edited this file.
There needs to be added a folder /etc/cron.minutely for the jobs.
I tested the script extensively. Everything seems to work as supposed.

### CODE REVIEW

**Comment by MichaIng** [comment]
@d5c0d3 
Thanks for the PR. I am not too sure, if adding a new non-default `/etc/cron...` folder is necessary here. The others (hourly, daily, weekly, monthly) are present by default on all Debian based distros, we just allow to change the times. They are used again by other software for their background jobs, so you can control via dietpi-cron when they shall occur.

For individual user cron jobs, I think `crontab -u <unix_username> -e` is the usual safe solution. As you need your job every 2 minutes instead of every minute, you would just need to add the line
`*/2 * * * * <command>`

But enabling `/etc/cron.minutely` indeed also does not hurt. Let's see what @Fourdee thinks about it 🙂.

Ref: https://manpages.debian.org/stretch/cron/crontab.5.en.html

**Comment by d5c0d3** [comment]
I agree, using `crontab -u <unix_username> -e` would be the way I usualky would go and likely simpler. However, to stay with the prefered way I decided to adapt `dietpi-cron` and added `/etc/cron.minutely`. Up to @Fourdee (and you?) to decide wether it would enhance DietPi.

Thanks for the great work, by the way!

**Comment by MichaIng** [comment]
Btw, we could also add a GUI for adding/removing jobs to crontab. Method: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L8318-L8319

But would just be nice, if there were several choice boxes (for m h dow dom moa) within whiptail window possible.

**Comment by Fourdee** [comment]
@d5c0d3 

> dietpi-cron and added /etc/cron.minutely. Up to @Fourdee (and you?) to decide wether it would enhance DietPi.

Yep, love this, great work 👍 

I'll take a indepth/look and test once v6.3 is released.

**Comment by Fourdee** [comment]
@d5c0d3 

Great work, i'll merge for testing 👍

**Comment by Fourdee** [comment]
🈯️ Verified with testing:

@d5c0d3 
Legend, great addition to ```DietPi-Cron```, many thanks 👍 

```
root@DietPi:~# cat test
Fri 9 Mar 17:27:08 GMT 2018
Fri 9 Mar 17:28:01 GMT 2018
Fri 9 Mar 17:29:01 GMT 2018
```

**Comment by d5c0d3** [comment]
@Fourdee , thank you for considering and merging!

**Pull request merged**
