### PR TITLE
DietPi-Software | Deluge: Fix listening port on Bullseye

### PR DESCRIPTION
**Pull request by Joulinar**
- fix LISTEN port for deluge application

### CODE REVIEW

**Comment by MichaIng** [comment]
As said, actually the port change should work. I'm currently testing this.

**Comment by MichaIng** [comment]
Very strange, indeed the port range feature seems to be broken. Probably it's also the mechanism Deluge obtains the "free" port within the range on individual startup. The range is used as default setting, but also random port is enabled by default, in which case the listen port setting has no effect, of course.

**Comment by MichaIng** [comment]
Working well on Buster (Deluge v1) btw:
```
# ss -tulpn | grep :68
udp    UNCONN  0       0                                         0.0.0.0:6881                 0.0.0.0:*            users:(("deluged",pid=1873,fd=12))
udp    UNCONN  0       0                                            [::]:6881                    [::]:*            users:(("deluged",pid=1873,fd=13))
tcp    LISTEN  0       5                                         0.0.0.0:6881                 0.0.0.0:*            users:(("deluged",pid=1873,fd=10))
tcp    LISTEN  0       5                                            [::]:6881                    [::]:*            users:(("deluged",pid=1873,fd=9))
```
It uses the first port in the range, as it is free. If I now install qBittorrent and start it first:
```
# ss -tulpn | grep :68
udp    UNCONN  0       0                                         0.0.0.0:6881               0.0.0.0:*          users:(("qbittorrent-nox",pid=2782,fd=30))
udp    UNCONN  0       0                                         0.0.0.0:6882               0.0.0.0:*          users:(("deluged",pid=2792,fd=13))
udp    UNCONN  0       0                                            [::]:6881                  [::]:*          users:(("qbittorrent-nox",pid=2782,fd=31))
udp    UNCONN  0       0                                            [::]:6882                  [::]:*          users:(("deluged",pid=2792,fd=14))
tcp    LISTEN  0       5                                         0.0.0.0:6881               0.0.0.0:*          users:(("qbittorrent-nox",pid=2782,fd=29))
tcp    LISTEN  0       5                                         0.0.0.0:6882               0.0.0.0:*          users:(("deluged",pid=2792,fd=12))
tcp    LISTEN  0       5                                            [::]:6881                  [::]:*          users:(("qbittorrent-nox",pid=2782,fd=28))
tcp    LISTEN  0       5                                            [::]:6882                  [::]:*          users:(("deluged",pid=2792,fd=10))
```
It uses the second port in the range, since the first is used by qBittorrent already. This nice little feature does not work anymore with a single fixed port. On the other hand, a single well known port per application is clearer to handle, in firewalls and router port forwarding.

Probably we should use `6882` for Deluge, since qBittorrent listens on `6881` explicitly (for whatever reason we do not set an upper port range there which means single port only)?

**Comment by Joulinar** [comment]
interesting, might be an upstream issue on the Bullseye package?

**Comment by MichaIng** [comment]
I think so. However, not such a big issue if we use a different port on each Torrent server. Do you agree with `6882`? qBittorrent uses `6881`, Transmission uses `51413` and rTorrent uses `49164`, all three a single port, so this makes it consistent, and all of them could be theoretically used concurrently 😄.

**Review by MichaIng — APPROVED** [review]

**Comment by Joulinar** [comment]
fine with me to use `6882`. 👍

**Pull request merged**
