### PR TITLE
DietPi-Software | Add Roon Extension Manager

### PR DESCRIPTION
**Pull request by JanKoudijs**
**Status**: Testing
Already tested on: Virtual Machine (x86_64)

**Reference**: [Roon Extension Manager Wiki](https://github.com/TheAppgineer/roon-extension-manager/wiki)

**Commit list/description**:

- DietPi-Software | Add Roon Extension Manager

Hi Dan,

I created this pull request to get the Roon Extension Manager included in DietPi. At this moment users have to perform [quite some steps](https://github.com/pluggemi/roon-web-controller/wiki/Diet-Pi-Installation-Extension-Manager#roon-extension-manager) to get this up and running, this request would change it into a simple:

    dietpi-software install 170

I had a look at your instructions and hope my changes are in the form you like. If you have suggestions for improvements, please let me know.

I hope you are willing to include my change.

Best regards,
Jan Koudijs

### CODE REVIEW

**Comment by MichaIng** [comment]
@JanKoudijs 
Many thanks for this PR 👍. As I don't know anything about Roon, I will just do some formal review:

```
root@VM-Stretch:~# dietpi-software list | grep null
id 2 | =0 | null:  |
id 86 | =0 | null:  |
```
- Software IDs 2 and 86 are currently free, thus could be used.
- Hard limit does not need to be increased then.

So the main benefit for end users is the automated Git and NodeJS installation, right? I mean why not, as we already offer roon bridge and server, makes sense to offer the full package.

Can verify the installation runs through nicely on VM Stretch.

Do I get it right that this is an extension to the roon server, thus it would make sense to automatically select roon server for installation then?

**Review by MichaIng — COMMENTED** [review]
@JanKoudijs 
Many thanks for this PR 👍. As I don't know anything about Roon, I will just do some formal review:

```
root@VM-Stretch:~# dietpi-software list | grep null
id 2 | =0 | null:  |
id 86 | =0 | null:  |
```
- Software IDs 2 and 86 are currently free, thus could be used.
- Hard limit does not need to be increased then.

So the main benefit for end users is the automated Git and NodeJS installation, right? I mean why not, as we already offer roon bridge and server, makes sense to offer the full package.

🈯️ Can verify the installation runs through nicely on VM Stretch.

Do I get it right that this is an extension to the roon server, thus it would make sense to automatically select roon server for installation then?

**Comment by JanKoudijs** [comment]
Hi @MichaIng,

I switched to ID 86, thanks for the suggestion.

> So the main benefit for end users is the automated Git and NodeJS installation, right?

That, but also the actions to download and run the install script get automated. Also by having it in the DietPi install menu, users are more likely to notice the possibility to run extensions.

> Do I get it right that this is an extension to the roon server, thus it would make sense to automatically select roon server for installation then?

Indeed, extensions need access to the server via the network (it doesn't have to be on the same device). Since the Roon Server is pretty resource hungry it will probably not run on the typical DietPi device and therefor I propose to leave automatic selection out.

**Comment by MichaIng** [comment]
@JanKoudijs 
> Also by having it in the DietPi install menu, users are more likely to notice the possibility to run extensions.

Good point. It is always nice to show users the full range of possibilities.

> access to the server via the network

Ah okay. Quite nice modular system, like it. Yes then of course installation should not be done automatically. Maybe there is a way to check for and in case configure available roon servers within the network, using whiptail menu e.g.?

But yeah, as said, I don't know much about roon so far, need to play around with the configuration apps etc. to see what is possible and where we could make things easier for end users.

Btw.: The configuration part within `dietpi-software` is not needed, if empty. But it doesn't hurt to have it as place holder for possible additions.

**Comment by Fourdee** [comment]
@JanKoudijs 

Impressive 👍 
Many thanks for the PR, much appreciated.

I'll merge for testing.

**Pull request merged**
