### PR TITLE
V116 NETDATA

### PR DESCRIPTION
**Pull request by rhkean**
added RPi 1 support

### CODE REVIEW

**Comment by Fourdee** [comment]
@rhkean 
Excellent :+1: 

I may change the filename (and link) to *armv6.tgz. Thats just the naming convention I've always used for RPi v1.

RPi 1 = ARMv6
RPi 2 = ARMv7 (backwards compatible with ARMv6)
RPi 3 = ARMv8 (backwards compatible with ARMv7, not sure about ARMv6)

**Comment by rhkean** [comment]
I've seen binaries and packages refer to armel when talking about RPi, but while watching the package installs last night, on the Rpi 1 B+, it was installing armhf packages... so, I wasn't sure what to call the tarball... :smile: 

Whatever matches your naming conventions is best, though.  :)

**Comment by Fourdee** [comment]
@rhkean 
Yep, when the RPi was first released, it only supported software emulated float (if i remember correctly). Now that device (and all other SBC's DietPi supports) support hard float (armhf).

As all devices we support are armhf, I tend to use armv6 armv7 armv8 arm64 instead.

Basically, floating point calculations (eg: `1.124f * 2.4f`) can be on by the ARM, rather than being emulated. Vastly improves performance.

**Comment by rhkean** [comment]
aha!  :bulb: 

makes sense... I definitely support renaming to meet your existing standards.

**Pull request merged**
