### PR TITLE
DietPi-Software | ownCloud/Nextcloud: Improve installation and configuration - Phase II

### PR DESCRIPTION
**Pull request by MichaIng**
https://github.com/Fourdee/DietPi/issues/1067

- [x] Installation and setup of redis-server + PHP module for transactional file locking
- [x] Setting up cron for background jobs
- [x] Create occ command (will be "ncc", while "occ" will be used by ownCloud) shortcut
- [x] Put Nextcloud/ownCloud into maintenance mode during several DietPi maintenance tasks, updates etc.
- [x] Add database 4-bit character support
- [x] Do whole installation and configuration sensitive to already existing/possibly manually changed files. 
- [x] Add database dump to owncloud/nextcloud-data directory on uninstallation to preserve all information of the instances.

### CODE REVIEW

**Comment by MichaIng** [comment]
Decided to give Redis priority, since it produces warnings on admin panel of ownCloud and the benefit is obvious: I see quite often questions/reports about wrong locked files on [help.nextcloud.com](help.nextcloud.com) where file locking is left to database.

Do we want this also on dietpi-update? We could do the whole procedure, or "simply" reinstall Nextcloud and ownCloud. At the moment webserver configs would be overwritten and, more problematic, beta versions of Nextcloud/ownCloud, that got installed from zip or internal updater (on beta branch) would be overwritten. The latter could least to problems, as downgrading is not supported because of possibly changed database table structure. I could/should do the installation case sensitive, based on existence of ownCloud/Nextcloud folder. For a clean reinstallation, user would need to uninstall first.
All other config files etc. are changed case sensitive already.

**Comment by Fourdee** [comment]
@MichaIng 

>  At the moment webserver configs would be overwritten and, more problematic, beta versions of Nextcloud/ownCloud, that got installed from zip or internal updater (on beta branch) would be overwritten.
For a clean reinstallation, user would need to uninstall first.

In these cases, where stable patching existing installations is too risky (outside of our control, too many possibilities that we simply cant test all of them for), the only thing we can do is mention it in the changelog eg:
- DietPi-Software | NextCloud: Resolved an issue with X. This applies to fresh installations only, as patching existing installations poses risk factors. Existing installations of this software title, will need to uninstall the software, then install again, to benefit from this fix.

**Comment by MichaIng** [comment]
@Fourdee 
Is there a way to include sudo and arguments into alias in /etc/bash.bashrc to shorten ownCloud/Nextcloud occ command execution?
Otherwise I realized it on my machine by:
`echo -e '#!/bin/bash\nsudo -u www-data php /var/www/nextcloud/occ $*' > /usr/local/bin/occ && chmod +x /usr/local/bin/occ`

_€: Answered it by myself:
`echo "alias occ='sudo -u www-data /var/www/nextcloud/occ'" >> /etc/bash.bashrc && source /etc/bash.bashrc` works well 🙂._

**Comment by MichaIng** [comment]
**Added:**
MySQL 4-byte support. But especially on Nextcloud + MariaDB secure database conversion of existing installations is a step by step procedure with unknown outcome: https://docs.nextcloud.com/server/12/admin_manual/configuration_database/mysql_4byte_support.html

We will adjust MySQL settings to be prepared for potential 4-byte support in every case. At least ownCloud will then enable 4-byte support via config.php automatically on occ installation/first run. If installation was really fresh (no ownCloud/Nextcloud database existed) before occ installation, we will ensure use of 4-byte support afterwards.

To check: Might there be any other application that has problems with MySQL barracuda table format? But I am pretty sure, that this is just an internal thing that does not influence 'external' database requests.

**Comment by MichaIng** [comment]
**Added:**
Respect and do not overwrite existing instance or configuration files, in case user installed beta/daily versions or copied manual changed files from old instance. This also allows `dietpi-software reinstall` without producing potential table version incompatibilities or destroying manual adjustments.
- On the other hand this prevents some installation/configuration improvements for existing installations. User needs to uninstall first, to completely remove the existing instance, including all configuration files, and install again.

**Comment by MichaIng** [comment]
**Added:**
mysqldump to userdata dir, before uninstall. That way the old instance will be totally recoverable.

**Comment by MichaIng** [comment]
**Added:**
Put ownCloud/Nextcloud into maintenance mode during DietPi maintenance tasks. As DietPi already controls services accordingly, we just need to enable maintenance before `dietpi-services stop/restart` and disable it after `dietpi-services restart/start`.

**Comment by MichaIng** [comment]
@Fourdee 
If you find time and agree to the changes, please add the PR for testing. Everything I thought of is done.
Could be finished for v159, I could intensively test everything again after merge.

**Comment by Fourdee** [comment]
@MichaIng 

> If you find time and agree to the changes, please add the PR for testing. Everything I thought of is done.
Could be finished for v159, I could intensively test everything again after merge.

I'am going to focus/finish up v159 this week (Stretch RPi), aim for release Sunday. If you can confirm your able to do all required testing for this PR, before Sunday, let me know and i'll merge?

**Comment by MichaIng** [comment]
@Fourdee:
Jep will do until at latest thursday. Have a bid time tomorrow :).

**Comment by Fourdee** [comment]
@MichaIng 

Legend 👍

**Comment by Fourdee** [comment]
@MichaIng 

We need to check for file exist before running grep:
```
if [ -f /var/www/owncloud/config/config.php ] || [ -f /var/www/nextcloud/config/config.php ]; then

    grep xxxxxxxxxx

fi
```

```
root@DietPi:~# dietpi-services stop

 DietPi-Services
─────────────────────────────────────────────────────
 Mode: stop
 Please wait...

grep: /var/www/owncloud/config/config.php: No such file or directory
grep: /var/www/nextcloud/config/config.php: No such file or directory
 [Ok] stop : cron

root@DietPi:~#
```

**Comment by MichaIng** [comment]
@Fourdee 
Fixed in https://github.com/Fourdee/DietPi/pull/1272

Check is included in grep there but with &> /dev/null:
If maintenance=true pattern is found (and therefore file exists), we do occ command now. Same other way round for service starts.

**Pull request merged**
