### PR TITLE
NanoPi R5S/R5C/6 series | Update kernel to v5.10.160

### PR DESCRIPTION
**Pull request by MichaIng**
- NanoPi R5S/R5C/6 series | An update of the kernel to Linux 5.10.160 will be applied as part of the DietPi update. Many thanks to @HeyMeco for informing us about this opportunity: https://dietpi.com/forum/t/new-kernel-for-nanopi-s-5-10-160/17325

### CODE REVIEW

**Comment by HeyMeco** [comment]
Wrong tag but thank you! :)
Looking forward to the update

**Comment by MichaIng** [comment]
Ah right, I forgot to code tag the forum user name, to not accidentally ping wrong GitHub users. However, pinging the correct GitHub user is even better 🙂.

**Comment by Averell7** [comment]
Do you think this will allow - at last - to compile the missing wireguard module, and our own TLS module ? When we tried with 5.10.110, everything failed.

**Comment by MichaIng** [comment]
Nope, not yet. But in the meantime Armbian has support for both boards, so I'll test an in case build new images with their kernel and bootloader builds. Then we also have access to boot configs,  kernel command-line etc.

**Comment by MichaIng** [comment]
Nice, because mainline Linux support is there: https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/rockchip/rk3568-nanopi-r5s.dts

U-Boot as well: https://github.com/u-boot/u-boot/blob/8999257f219d1e371c2fd66f255b8782897944d9/configs/nanopi-r5s-rk3568_defconfig#L11

I'll work on this ASAP. Anyone who finds time earlier to build and test those earlier would be highly welcome.

**Pull request merged**
