### PR TITLE
DietPi-Software | Ampache - change Composer 

### PR DESCRIPTION
**Pull request by Joulinar**
**Status**: Ready
- [x] check installation
- [x] check re-installation

**Reference**: https://dietpi.com/phpbb/viewtopic.php?t=8367

According Ampache wiki, Composer version 1.x is required

https://github.com/ampache/ampache/wiki/Installation

> **Composer**
Since 3.8.1, Composer is used to manage dependencies. You should download it and install it (e.g: mv composer.phar /usr/local/bin/composer), then run composer install --prefer-source --no-interaction on Ampache directory. Attention: Composer version 2.x is not compatible to Ampache. Take care to use the latest 1.x version.

**Commit list/description**:
- DietPi-Software | Ampache - change Composer version to version 1.x as Composer version 2.x is not compatible to Ampache
- DietPi-Software | Ampache - change to manual downlad of Composer

### CODE REVIEW

**Comment by Joulinar** [comment]
@MichaIng 
I would need your thoughts on the implementation. Basically there are 2 option to get this done

Option 1: download `composer` file manually

```
G_EXEC curl -sSfL https://getcomposer.org/composer-1.phar -o /usr/local/bin/composer
G_EXEC chmod +x /usr/local/bin/composer
```

Option 2: create `composer` file with a specific version
`$PHP_NAME composer-setup.php --version=1.10.19`

atm I keep both options inside the change. Will be adjusted depending on your ideas.

**Comment by MichaIng** [comment]
`$PHP_NAME composer-setup.php --1` would work as well, see: https://getcomposer.org/download/

But actually, the installer script is quite some overhead:
> This installer script will simply check some php.ini settings, warn you if they are set incorrectly, and then download the latest composer.phar in the current directory.

I like the manual download much more, lets do it that way (will change the other cases as well).

**Comment by Joulinar** [comment]
Ok I removed the Composer install part in favour of the manual download

**Review by MichaIng — DISMISSED** [review]

**Comment by MichaIng** [comment]
Works fine here. Ready from my side.

**Review by MichaIng — APPROVED** [review]

**Comment by Joulinar** [comment]
yep seems to be working fine on my side as well

**Pull request merged**
