### PR TITLE
dietpi-imager | Sanetize list of selectable drives

### PR DESCRIPTION
**Pull request by sal666**
Filter out disks with currently mounted partitions and also RO drives. If the resulting list is empty then exit and print an error message.

### CODE REVIEW

**Comment by MichaIng** [comment]
@sal666 
Many thanks for this.

What do you think about allowing mounted devices and as well loop devices? E.g. user mounted the device already before for some reason, or ran dietpi-drive_manager which mounts them automatically. We could then simply add `-o remount` to the mount command to umount and remount to the tmp mountpoint. It fails if the device is in use, e.g. is root device or such, so no real risk.

**Comment by sal666** [comment]
> What do you think about allowing mounted devices and as well loop devices? E.g. user mounted the device already before for some reason, or ran dietpi-drive_manager which mounts them automatically. We could then simply add `-o remount` to the mount command to umount and remount to the tmp mountpoint. It fails if the device is in use, e.g. is root device or such, so no real risk.

Maybe when working with .img files or cloning with dd, but AFAIK Clonezilla is not able to work with .img files, loop devices or mounted partitions. Before making the image we need to assure that the source device is a physical drive and has no mounted partition.

**Comment by MichaIng** [comment]
@sal666 
> Maybe when working with .img files or cloning with dd, but AFAIK Clonezilla is not able to work with .img files, loop devices or mounted partitions. Before making the image we need to assure that the source device is a physical drive and has no mounted partition.

As mentioned on the other comment: Images are mounted as loop devices and those should not behave any different then physical drives, since both are presented as "generic" block devices.

> or mounted partitions

Ah, it requires the drive to be unmounted? Okay however should still work the same with e.g. `/dev/sda` and `/dev/loop0`, at least worth to test? The loop devices are present as block devices and can be handled in any way as physical drives, AFAIK, regardless if mounted or not.

**Comment by sal666** [comment]
But for some reason Clonezilla don't support them :(

**Comment by MichaIng** [comment]
@sal666 
Hmm, what is the error you get when attempting it? Probably I find time for some test tomorrow as well.

However then it is maybe best to indeed have a separate initial selection for Clonezilla images to stay most flexible:
- Choose between Image/Disk/Clonezilla
- In case of Clonezilla hide show attached disks, but hide loop devices. Most interactive selection code can be shared, but the loop devices excluded if Clonezilla was selected, e.g.:
```
if [[ $G_WHIP_RETURNED_VALUE == 'Drive' || $G_WHIP_RETURNED_VALUE == 'Clonezilla' ]]; then
...
    if [[ $G_WHIP_RETURNED_VALUE == 'Drive' ]]; then
        G_WHIP_MENU_ARRAY=($(lsblk -dnpo NAME,SIZE))
    else
        G_WHIP_MENU_ARRAY=($(lsblk -dnpo NAME,SIZE | grep -v '^/dev/loop'))
    fi
...
```
- Then unmount all partitions of the selected drive by default, which is required anyway to allow fsck, partitioning etc.

Btw good idea to show error and exit if array is empty. whiptail menus in such cases exit by default but without any error message.

Further idea would be to add a "refresh" option, e.g. drive was not attached correctly or forgotten or something which would then prevent the need to restart the whole script.

**Comment by sal666** [comment]
> Hmm, what is the error you get when attempting it? Probably I find time for some test tomorrow as well.

If you run Clonezilla interactively it already filters the list of selectable devices, so you won't be able to test loop devices.
The command-line version gets the device as an argument but only admits the device name to be passed without the '/dev/' prefix. When tried with loop0 (after mounting any image with kpartx) the error returned was 'No input device!'.

> However then it is maybe best to indeed have a separate initial selection for Clonezilla images to stay most flexible:
> 
> * Choose between Image/Disk/Clonezilla
> * In case of Clonezilla hide show attached disks, but hide loop devices. Most interactive selection code can be shared, but the loop devices excluded if Clonezilla was selected, e.g.:
> 
> ```
> if [[ $G_WHIP_RETURNED_VALUE == 'Drive' || $G_WHIP_RETURNED_VALUE == 'Clonezilla' ]]; then
> ...
>     if [[ $G_WHIP_RETURNED_VALUE == 'Drive' ]]; then
>         G_WHIP_MENU_ARRAY=($(lsblk -dnpo NAME,SIZE))
>     else
>         G_WHIP_MENU_ARRAY=($(lsblk -dnpo NAME,SIZE | grep -v '^/dev/loop'))
>     fi
> ...
> ```
> 
> * Then unmount all partitions of the selected drive by default, which is required anyway to allow fsck, partitioning etc.

Sounds good to me, will take it into account.

> Btw good idea to show error and exit if array is empty. whiptail menus in such cases exit by default but without any error message.
> 
> Further idea would be to add a "refresh" option, e.g. drive was not attached correctly or forgotten or something which would then prevent the need to restart the whole script.

Good idea, added to my to do list.

**Comment by MichaIng** [comment]
@sal666 
> When tried with loop0 (after mounting any image with kpartx) the error returned was 'No input device!'.

```
losetup -f /path/to/image.img
partprobe /dev/loop0
```
should usually work. `kpartx` however is an alternative to `partprobe`, another one is `partx -u /dev/loop0`, but all after the losetup has created the block device. But probably Clonezilla checks other /dev /sys /proc paths that only list physical block devices. Perhaps we can send this in as feature request.

**Comment by MichaIng** [comment]
Okay I re-allowed mounted and loop device selection for now (to stay flexible) but added a step to unmount all found mounted file systems of source drive.
Additionally added a hint to initial source selection menu that Clonezilla does neither support image files nor loop devices currently.

@sal666 
Rechecked the wording and currently having three different initial selections does not fit really good, since it is about the input OS source and not yet about the output type. So I think with the hint in this menu, it is then okay to check for `[[ $FP_SOURCE != '/dev/loop'* ]]` to offer Clonezilla output image or skip that. Long term it would be beneficial if we could get it to work with loop devices (thus image files) as well, but probably we need to ask the Clonezilla devs about that. I simply cannot imaging any technical reason why this should not work 🤔.

Finally I'd like to have a single initial selection menu from where you can select input type, output type + file name (or even offer to not create an image file but leave things on source drive), show detected partition table type and select root partition, all from one menu. So one has a nice overview to accept before doing any further steps.

**Comment by sal666** [comment]
> Okay I re-allowed mounted and loop device selection for now (to stay flexible) but added a step to unmount all found mounted file systems of source drive.
> Additionally added a hint to initial source selection menu that Clonezilla does neither support image files nor loop devices currently.

@MichaIng 
Do you exclude the current root drive? If the user booted from 'sda' then he/she shouldn't be allowed to use 'sda' as source drive.

Until this unique menu is implemented, we can change the way the different selections are done:
1. Ask for "Drive/Image"
2. If "Drive", ask for tool "dd/Clonezilla"
    2a. If "dd", get list of drives as usual
    2b. If "Clonezilla", get list of drives excluding loop devices
    2c. Select source drive
3. If "Image", select image and create loopback device

**Comment by sal666** [comment]
I've just uploaded my updated [dietpi-imager](https://github.com/sal666/DietPi/blob/dev/.meta/dietpi-imager) script. It's still in WIP state, it needs some extra testing plus all the changes we're talking about.
It's functional though, it should produce a working .7z with an .img (for dd) or .iso (for Clonezilla) file.

**Comment by MichaIng** [comment]
@sal666 
Jep your solution sounds great.
Indeed the root device should be excluded in any case:
```
findmnt -no source /
```

**Comment by MichaIng** [comment]
Mounting this PR now since all changes make sense regardless of further plans 😉.

**Pull request merged**
