### PR TITLE
RPi | Remove "config.txt" from non-RPi devices

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready for review/testing
- [x] Remove `config.txt` from DietPi-PREP for non-RPi devices
- [x] Adjust `config.txt` to use `gpu_mem`
- [x] Patch `gpu_mem` use and `config.txt` removal
- [x] Changelog entry

**Reference**: https://github.com/Fourdee/DietPi/issues/1816

**Commit list/description**:
+ DietPi-Set_Software | Move all "config.txt" adjustments into RPi check statements
+ DietPi-Set_Software | RPi: Switch from "gpu_mem_256/512/1024" to "gpu_mem"
+ DietPi-Set_Software | Use G_CONFIG_INJECT where possible for failure/duplicate safer file edit
+ DietPi-Set_Software | General code improvements
+ DietPi-PREP | Move "config.txt" in place only for RPi systems
+ RPi | "config.txt": Switch from "gpu_mem_256/512/1024" to "gpu_mem"
+ DietPi-Patchfile | Remove config.txt for non-RPi devices and switch from "gpu_mem_256/512/1024" to "gpu_mem" setting
+ CHANGELOG | Removed unused "/DietPi/config.txt" form non-RPi devices and switched from "gpu_mem_256/512/1024" settings to single "gpu_mem" setting
+ CHANGELOG | Minor wording on "initial_turbo" removal

### CODE REVIEW

**Comment by Fourdee** [comment]
@MichaIng 

Great work, legend 👍 

> RPi: Switch from "gpu_mem_256/512/1024" to "gpu_mem"

This needs testing on all RPi memory models. If I remember correctly, we originally had ```gpu_mem``` but it did not effect some of the memory models (cant remember which).

**Comment by Fourdee** [comment]
Note: 
Would be great if we could? When both scrape and value entries are the same?
```
G_CONFIG_INJECT 'snd-soc-pcm5102' /etc/modules
```

**Comment by MichaIng** [comment]
@Fourdee
I have no nice idea how the function should know if $2 should be handled as setting or file then, without implementing some exact_match option/variable or something. But this would not reduce usage code then, just increase G_CONFIG_INJECT code.
Maybe check [[ -f $2 ]] && file=$2 || file=$3, but then the setting must never be a file path only,  although I am not aware where this could be the case.

About gpu_mem: https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md
- Should work for all RPi with current firmware.
- But the memory specific values overwrite it, thus if users add them manually, our setting is without effect. Maybe then it's best to revert this change, so memory setting it's effective in every thinkable case.

**Comment by mfeif** [comment]
I think some unplanned casualties have occurred here :-)

I have a Sparky SPC, and I upgraded to 6.10, and I can now not configure my device with dietpi-config. I've also lost access to my soundcard as per here: https://github.com/Fourdee/DietPi/issues/1894

**Pull request merged**
