### PR TITLE
Release v8.0

### LINKED ISSUE #5137: Open Beta v8.0 | Please help testing and hardening the upcoming release
RC version | v8.0.2
---------- | -------
v8.0.0 PR | #5101
v8.0.1 PR | #5141
v8.0.1 PR | #5147
Raw changelog | https://github.com/MichaIng/DietPi/blob/beta/CHANGELOG.txt
Code changes | https://github.com/MichaIng/DietPi/compare/master...beta
Release date | **2022-01-08**

#### Related/solved issues: https://github.com/MichaIng/DietPi/issues?q=is%3Aissue+milestone%3Av8.0
____
### Beta v8.0.2
_(2022-01-08)_

#### Stretch support
- Support for Debian Stretch has now been removed, which allowed us to do a major code cleanup and migrate to some newer methods in different areas which are only available on Buster and above.

#### Changes
- Network | For new images, the default DHCP timeout is not reduced to 10 seconds anymore. This could have been too short, in which case network targets of the boot sequence are reached before an IP has been actually assigned. Especially in case of AUTO_SETUP_AUTOMATED=1 this could have lead to connection test timeouts and hence abortion of the automated first run setup. Many thanks to @jpeg2600 for reporting such a case: https://github.com/MichaIng/DietPi/issues/5143
- DietPi-Config | When configuring a first WiFi slot via scanning for SSIDs, the WiFi adapter is now not brought up via "ifup" but "ip l dev wlanX up". This way no DHCP and WPA client starts are triggered, which are doomed to fail when the WiFi adapter is not connected to any access point yet. Especially in case of the default 60 seconds DHCP timeout, this would otherwise cause an unnecessary long delay.
- DietPi-Dashboard | Added an option to view multiple dashboard nodes from one frontend web interface. Related to this, the backend can now be installed only, reducing memory usage and making it impossible to manually access the node outside of the backend API.
- DietPi-Print_large | This new script has been added which can be executed or sourced from /boot/dietpi/func/dietpi-print_large to print the string passed via first argument in large figlet style fonts. It currently only supports the characters a-z, A-Z, 0-9, dot and dash, i.e. those commonly allowed in hostnames.
- DietPi-Banner | Added an option to print the system's hostname in large figlet style fonts, right below the banner header. In case it is enabled as well, the regular/small hostname line will then be skipped. Many thanks to @matellis for implementing this feature: https://github.com/MichaIng/DietPi/pull/5113
- DietPi-Software | Mono: "mono-complete" won't be installed anymore but only "mono-devel" instead. This skips the XSP4 webserver service, which listens on port 8084 by default where it conflicts with File Browser. This only affects new instals. You can manually apply this change via "apt-mark manual mono-devel && apt --autoremove purge mono-complete". Many thanks to @jaguar489 for reporting this issue: https://github.com/MichaIng/DietPi/issues/5093
- DietPi-Software | FuguHub: The outdated official installer has been replaced with a fully automated own setup, removing the obsolete or even harmful interactive dialogues. On fresh installs, an admin account "dietpi" with global software password is created as well.
- DietPi-Software | myMPD: Installation is now done via official APT repository, which means quicker install compared to compiling from source, fewer dependencies and easier updates via "apt upgrade": https://github.com/MichaIng/DietPi/issues/5115
- DietPi-Software | Airsonic: Since the project has been archived by its maintainer and suffers from the critical Log4Shell security vulnerability, we moved to the advertised fork "Airsonic-Advanced" which also enables compatibility with Java 17 and hence Debian Bullseye. Airsonic will be reinstalled as part of the DietPi update to apply the migration. All data and settings will be preserved and migrated automatically.

#### Fixes
- Raspberry Pi | Resolved an issue where unintentionally the turbo mode was enabled. This got backported to v7.9, to our existing RPi images and via live patch. Many thanks to @ayo-x and @whyisthisbroken for reporting this issue: https://github.com/MichaIng/DietPi/issues/5088
- DietPi-FS_partition_resize | Resolved an issue where in some cases the boot partition failed to mount on first boot since after the partition resize the system in some cases didn't get sufficient time to fully apply the change before continuing with the boot mount attempt. Many thanks to @Mausy5043 and @sistemicorp for reporting this issue: https://github.com/MichaIng/DietPi/issues/5006
- DietPi-Config | Resolved an issue where on Raspberry Pi, when the full KMS display driver is used, the sound card selection could have been falsely applied. With full KMS enabled, for each HDMI port an additional HDMI sound card appears (replacing the regular firmware HDMI sound device), even when no HDMI device is attached and with onboard audio disabled. This lead to an incrementation of external sound card indices. The appearance of the KMS HDMI sound cards is now aligned with the onboard firmware HDMI sound cards, i.e. if not onboard "auto" or HDMI is selected in dietpi-config, now the KMS HDMI sound devices are disabled as well, making use of the "noaudio" device tree overlay parameter.
- DietPi-Software | Resolved an issue where on first boot, choice and preference menu selections triggered an error as the install state file did not exist yet. Many thanks to @bsheeres for reporting this issue: https://github.com/MichaIng/DietPi/issues/5080
- DietPi-Software | Resolved an issue where the deprecated AUTO_SETUP_FILE_SERVER_INDEX dietpi.txt option was applied inverted. "-1" should have installed ProFTPD and "-2" Samba, while it was done the opposite way. However, note that this setting is not present on current images and deprecated. Use AUTO_SETUP_INSTALL_SOFTWARE_ID instead to mark any one or multiple file servers for automatic install. Many thanks to @bsheeres for reporting this issue: https://github.com/MichaIng/DietPi/issues/5081
- DietPi-Software | Browsers: On the ARMv6 Raspberry Pi models Raspberry Pi 1 and Zero (1) since Bullseye, Chromium and Firefox fail to start due to hardware and build limitations which are outside of our control. Since those are currently the only two browser available from dietpi-software, they have been disabled together with the browser preference menu for those systems, until we find and implement a good additional compatible browser. Further info: https://github.com/RPi-Distro/chromium-browser/issues/21
- DietPi-Software | Kodi: Resolved an issue where subsequent Kodi reinstalls created duplicates of the CMA parameter for the KMS overlay setting in config.txt. The duplicates are patched out during DietPi update.
- DietPi-Software | Docker: Resolved an issue where the install was aborted due to an incorrect check for missing kernel modules. Many thanks to @dragonandy for reporting this issue: https://github.com/MichaIng/DietPi/issues/5061
- DietPi-Software | Pi-hole: Resolved an issue where the teleporter import log was not shown but denied by the X-Frame-Options header: https://discourse.pi-hole.net/t/unable-to-restore-teleporter-backup-fresh-install-no-funky-changes-made/51573
- DietPi-Software | Blynk Server: Resolved an issue on ARMv6 RPi models where the install failed as the latest Blynk Server release does not contain a Java 8 build. Since the older Java 8 build does not contain a native Log4Shell vulnerability mitigation, it is added server-wise on these systems.
- DietPi-Software | Mycroft AI: Resolved an issue on Bullseye (and above) systems where "mycroft-cli-client" command fails with a permissions issue, even as root user. Many thanks to @berndverhofstadt for reporting this issue: https://github.com/MichaIng/DietPi/issues/5100
- DietPi-Software | Nukkit: Resolved an issue where the install failed due to a changed download URL. The Jenkins instance has moved to ci.opencollab.dev, where also the Geyser and Floodgate projects are hosted.
- DietPi-Software | FuguHub: Resolved an issue where the uninstall failed as the process was not stopped as intended. Many thanks to @kd9352 for reporting this issue: https://github.com/MichaIng/DietPi/issues/5058
- DietPi-Software | myMPD: Resolved an issue where the installation failed due to an updated dependency. Many thanks to @supersexy for reporting this issue: https://github.com/MichaIng/DietPi/issues/5115
- DietPi-Software | Python 3: Worked around an issue where the pip reinstall failed. Many thanks to @hueppinr for reporting this issue: https://github.com/MichaIng/DietPi/issues/5117
- DietPi-Software | Unbound: Resolved an issue where the "unbound-resolvconf" service applied localhost automatically as local nameserver, if the "resolvconf" package was installed. Since often Unbound is installed in combination with Pi-hole or AdGuard Home, and those are usually used by network clients only, not the server itself, "unbound-resolvconf" is disabled now on Unbound installs. If Unbound is wanted as local resolver as well, it should be explicitly configured, e.g. via dietpi-config network options. Many thanks to @Ianszh for reporting this issue: https://github.com/MichaIng/DietPi/issues/5133
- DietPi-Software | Mosquitto: Applied a workaround on ARMv6 where the latest Mosquitto packages from the official APT repository are not ARMv6-compatible. Many thanks to @thomasmockridge for reporting this issue: https://github.com/MichaIng/DietPi/issues/5140

### PR DESCRIPTION
**Pull request by MichaIng**
### v8.0
_(2022-01-08)_

#### Stretch support
- Support for Debian Stretch has now been removed, which allowed us to do a major code cleanup and migrate to some newer methods in different areas which are only available on Buster and above.

#### Changes
- DietPi-Dashboard | Added an option to view multiple dashboard nodes from one frontend web interface. Related to this, the backend can now be installed only, reducing memory usage and making it impossible to manually access the node outside of the backend API.
- DietPi-Print_large | This new script has been added which can be executed or sourced from /boot/dietpi/func/dietpi-print_large to print the string passed via first argument in large figlet style fonts. It currently only supports the characters a-z, A-Z, 0-9, dot and dash, i.e. those commonly allowed in hostnames.
- DietPi-Banner | Added an option to print the system's hostname in large figlet style fonts, right below the banner header. In case it is enabled as well, the regular/small hostname line will then be skipped. Many thanks to @matellis for implementing this feature: https://github.com/MichaIng/DietPi/pull/5113
- DietPi-Automation | The automatic login on first boot, when AUTO_SETUP_AUTOMATED=1 is set, is now deferred until all network interfaces have been fully configured, including DHCP. In case of slower DHCP servers it was otherwise possible that network checks timed out, aborting the automated first run setup. Many thanks to @jpeg2600 for reporting such a case: https://github.com/MichaIng/DietPi/issues/5143
- DietPi-Software | Mono: "mono-complete" won't be installed anymore but only "mono-devel" instead. This skips the XSP4 webserver service, which listens on port 8084 by default where it conflicts with File Browser. This only affects new instals. You can manually apply this change via "apt-mark manual mono-devel && apt --autoremove purge mono-complete". Many thanks to @jaguar489 for reporting this issue: https://github.com/MichaIng/DietPi/issues/5093
- DietPi-Software | FuguHub: The outdated official installer has been replaced with a fully automated own setup, removing the obsolete or even harmful interactive dialogues. On fresh installs, an admin account "dietpi" with global software password is created as well.
- DietPi-Software | myMPD: Installation is now done via official APT repository, which means quicker install compared to compiling from source, fewer dependencies and easier updates via "apt upgrade": https://github.com/MichaIng/DietPi/issues/5115
- DietPi-Software | Airsonic: Since the project has been archived by its maintainer and suffers from the critical Log4Shell security vulnerability, we moved to the advertised fork "Airsonic-Advanced" which also enables compatibility with Java 17 and hence Debian Bullseye. Airsonic will be reinstalled as part of the DietPi update to apply the migration. All data and settings will be preserved and migrated automatically.

#### Fixes
- Raspberry Pi | Resolved an issue where unintentionally the turbo mode was enabled. This got backported to v7.9, to our existing RPi images and via live patch. Many thanks to @ayo-x and @whyisthisbroken for reporting this issue: https://github.com/MichaIng/DietPi/issues/5088
- DietPi-FS_partition_resize | Resolved an issue where in some cases the boot partition failed to mount on first boot since after the partition resize the system in some cases didn't get sufficient time to fully apply the change before continuing with the boot mount attempt. Many thanks to @Mausy5043 and @sistemicorp for reporting this issue: https://github.com/MichaIng/DietPi/issues/5006
- DietPi-Config | Resolved an issue where on Raspberry Pi, when the full KMS display driver is used, the sound card selection could have been falsely applied. With full KMS enabled, for each HDMI port an additional HDMI sound card appears (replacing the regular firmware HDMI sound device), even when no HDMI device is attached and with onboard audio disabled. This lead to an incrementation of external sound card indices. The appearance of the KMS HDMI sound cards is now aligned with the onboard firmware HDMI sound cards, i.e. if not onboard "auto" or HDMI is selected in dietpi-config, now the KMS HDMI sound devices are disabled as well, making use of the "noaudio" device tree overlay parameter.
- DietPi-Software | Resolved an issue where on first boot, choice and preference menu selections triggered an error as the install state file did not exist yet. Many thanks to @bsheeres for reporting this issue: https://github.com/MichaIng/DietPi/issues/5080
- DietPi-Software | Resolved an issue where the deprecated AUTO_SETUP_FILE_SERVER_INDEX dietpi.txt option was applied inverted. "-1" should have installed ProFTPD and "-2" Samba, while it was done the opposite way. However, note that this setting is not present on current images and deprecated. Use AUTO_SETUP_INSTALL_SOFTWARE_ID instead to mark any one or multiple file servers for automatic install. Many thanks to @bsheeres for reporting this issue: https://github.com/MichaIng/DietPi/issues/5081
- DietPi-Software | Browsers: On the ARMv6 Raspberry Pi models Raspberry Pi 1 and Zero (1) since Bullseye, Chromium and Firefox fail to start due to hardware and build limitations which are outside of our control. Since those are currently the only two browser available from dietpi-software, they have been disabled together with the browser preference menu for those systems, until we find and implement a good additional compatible browser. Further info: https://github.com/RPi-Distro/chromium-browser/issues/21
- DietPi-Software | Kodi: Resolved an issue where subsequent Kodi reinstalls created duplicates of the CMA parameter for the KMS overlay setting in config.txt. The duplicates are patched out during DietPi update.
- DietPi-Software | Docker: Resolved an issue where the install was aborted due to an incorrect check for missing kernel modules. Many thanks to @dragonandy for reporting this issue: https://github.com/MichaIng/DietPi/issues/5061
- DietPi-Software | Pi-hole: Resolved an issue where the teleporter import log was not shown but denied by the X-Frame-Options header: https://discourse.pi-hole.net/t/unable-to-restore-teleporter-backup-fresh-install-no-funky-changes-made/51573
- DietPi-Software | Blynk Server: Resolved an issue on ARMv6 RPi models where the install failed as the latest Blynk Server release does not contain a Java 8 build. Since the older Java 8 build does not contain a native Log4Shell vulnerability mitigation, it is added server-wise on these systems.
- DietPi-Software | Mycroft AI: Resolved an issue on Bullseye (and above) systems where "mycroft-cli-client" command fails with a permissions issue, even as root user. Many thanks to @berndverhofstadt for reporting this issue: https://github.com/MichaIng/DietPi/issues/5100
- DietPi-Software | Nukkit: Resolved an issue where the install failed due to a changed download URL. The Jenkins instance has moved to ci.opencollab.dev, where also the Geyser and Floodgate projects are hosted.
- DietPi-Software | FuguHub: Resolved an issue where the uninstall failed as the process was not stopped as intended. Many thanks to @kd9352 for reporting this issue: https://github.com/MichaIng/DietPi/issues/5058
- DietPi-Software | myMPD: Resolved an issue where the installation failed due to an updated dependency. Many thanks to @supersexy for reporting this issue: https://github.com/MichaIng/DietPi/issues/5115
- DietPi-Software | Python 3: Worked around an issue where the pip reinstall failed. Many thanks to @hueppinr for reporting this issue: https://github.com/MichaIng/DietPi/issues/5117
- DietPi-Software | Unbound: Resolved an issue where the "unbound-resolvconf" service applied localhost automatically as local nameserver, if the "resolvconf" package was installed. Since often Unbound is installed in combination with Pi-hole or AdGuard Home, and those are usually used by network clients only, not the server itself, "unbound-resolvconf" is disabled now on Unbound installs. If Unbound is wanted as local resolver as well, it should be explicitly configured, e.g. via dietpi-config network options. Many thanks to @Ianszh for reporting this issue: https://github.com/MichaIng/DietPi/issues/5133

### CODE REVIEW

**Comment by Joulinar** [comment]
@MichaIng 
we definitely need to keep the workaround for `pip3 setuptools`. Otherwise `pip/pip3` will be brocken completely on reinstall. 

Python3 reinstall **with** workaround

<details>
  <summary>Install log attached. Click to expand!</summary>

```
root@DietPi4:~# dietpi-software reinstall 130
[  OK  ] DietPi-Software | Initialised database
[  OK  ] DietPi-Software | Reading database

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Automated reinstall

[  OK  ] DietPi-Software | Reinstalling Python 3: Runtime system, pip package installer and development headers
[  OK  ] DietPi-Software | DietPi-Userdata validation: /mnt/dietpi_userdata

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Checking for conflicts and missing inputs


 DietPi-Software
─────────────────────────────────────────────────────
 Step: Checking for prerequisite software

[  OK  ] DietPi-Software | Checking network connectivity
[  OK  ] DietPi-Software | Checking DNS resolver
[  OK  ] Network time sync | Completed
[ SUB1 ] DietPi-Services > unmask
[  OK  ] DietPi-Services | unmask : cron
[ SUB1 ] DietPi-Services > stop
[  OK  ] DietPi-Services | stop : cron
[ INFO ] DietPi-Software | APT update, please wait...
Hit:1 https://deb.debian.org/debian bullseye InRelease
Hit:2 https://deb.debian.org/debian bullseye-updates InRelease
Hit:3 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:4 https://deb.debian.org/debian bullseye-backports InRelease
Hit:5 https://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists...
[  OK  ] DietPi-Software | APT update
[  OK  ] DietPi-Software | mkdir -p /mnt/dietpi_userdata/Music /mnt/dietpi_userdata/Pictures /mnt/dietpi_userdata/Video /mnt/dietpi_userdata/downloads /var/www /opt /usr/local/bin
[  OK  ] DietPi-Software | chown dietpi:dietpi /mnt/dietpi_userdata/Music /mnt/dietpi_userdata/Pictures /mnt/dietpi_userdata/Video /mnt/dietpi_userdata/downloads
[  OK  ] DietPi-Software | chmod 0775 /mnt/dietpi_userdata/Music /mnt/dietpi_userdata/Pictures /mnt/dietpi_userdata/Video /mnt/dietpi_userdata/downloads

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Installing Python 3: Runtime system, pip package installer and development headers

[  OK  ] DietPi-Software | pip3 uninstall -y setuptools
[  OK  ] DietPi-Software | cd /tmp/DietPi-Software
[  OK  ] DietPi-Software | Checking URL: https://bootstrap.pypa.io/pip/get-pip.py
[ INFO ] DietPi-Software | G_THREAD_START_0 | curl -sSfL https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
[ INFO ] DietPi-Software | APT install for: python3-dev, please wait...
[  OK  ] DietPi-Software | APT install for: python3-dev
[  OK  ] DietPi-Software | G_THREAD: All threads finished
[ INFO ] DietPi-Software | python3 ./get-pip.py, please wait...
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Collecting setuptools
  Using cached setuptools-60.3.1-py3-none-any.whl (953 kB)
Installing collected packages: setuptools, pip
  Attempting uninstall: pip
    Found existing installation: pip 21.3.1
    Uninstalling pip-21.3.1:
      Successfully uninstalled pip-21.3.1
Successfully installed pip-21.3.1 setuptools-60.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[  OK  ] DietPi-Software | python3 ./get-pip.py
[  OK  ] DietPi-Software | rm get-pip.py

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Finalising install

[  OK  ] DietPi-Software | systemctl daemon-reload
2022-01-08 00:26:38 [ INFO ] DietPi-RAMlog | Storing /var/log to /var/tmp/dietpi/logs/dietpi-ramlog_store...
2022-01-08 00:26:38 [  OK  ] DietPi-RAMlog | Stored /var/log to /var/tmp/dietpi/logs/dietpi-ramlog_store.
[ SUB1 ] DietPi-Services > dietpi_controlled
[  OK  ] DietPi-Services | dietpi_controlled : cron

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Install completed

[  OK  ] DietPi-Survey | Purging survey data
[ SUB1 ] DietPi-Services > restart
[  OK  ] DietPi-Services | restart : cron
root@DietPi4:~#
```
</details>

`pip/pip3` are working fine.

Python3 reinstall **without** workaround

<details>
  <summary>Install log attached. Click to expand!</summary>

```
root@DietPi4:~# dietpi-software reinstall 130
[  OK  ] DietPi-Software | Initialised database
[  OK  ] DietPi-Software | Reading database

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Automated reinstall

[  OK  ] DietPi-Software | Reinstalling Python 3: Runtime system, pip package installer and development headers
[  OK  ] DietPi-Software | DietPi-Userdata validation: /mnt/dietpi_userdata

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Checking for conflicts and missing inputs


 DietPi-Software
─────────────────────────────────────────────────────
 Step: Checking for prerequisite software

[  OK  ] DietPi-Software | Checking network connectivity
[  OK  ] DietPi-Software | Checking DNS resolver
[  OK  ] Network time sync | Completed
[ SUB1 ] DietPi-Services > unmask
[  OK  ] DietPi-Services | unmask : cron
[ SUB1 ] DietPi-Services > stop
[  OK  ] DietPi-Services | stop : cron
[ INFO ] DietPi-Software | APT update, please wait...
Hit:1 https://deb.debian.org/debian bullseye InRelease
Hit:2 https://deb.debian.org/debian bullseye-updates InRelease
Hit:3 https://archive.raspberrypi.org/debian bullseye InRelease
Hit:4 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:5 https://deb.debian.org/debian bullseye-backports InRelease
Reading package lists...
[  OK  ] DietPi-Software | APT update
[  OK  ] DietPi-Software | mkdir -p /mnt/dietpi_userdata/Music /mnt/dietpi_userdata/Pictures /mnt/dietpi_userdata/Video /mnt/dietpi_userdata/downloads /var/www /opt /usr/local/bin
[  OK  ] DietPi-Software | chown dietpi:dietpi /mnt/dietpi_userdata/Music /mnt/dietpi_userdata/Pictures /mnt/dietpi_userdata/Video /mnt/dietpi_userdata/downloads
[  OK  ] DietPi-Software | chmod 0775 /mnt/dietpi_userdata/Music /mnt/dietpi_userdata/Pictures /mnt/dietpi_userdata/Video /mnt/dietpi_userdata/downloads

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Installing Python 3: Runtime system, pip package installer and development headers

[  OK  ] DietPi-Software | cd /tmp/DietPi-Software
[  OK  ] DietPi-Software | Checking URL: https://bootstrap.pypa.io/pip/get-pip.py
[ INFO ] DietPi-Software | G_THREAD_START_0 | curl -sSfL https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
[ INFO ] DietPi-Software | APT install for: python3-dev, please wait...
[  OK  ] DietPi-Software | APT install for: python3-dev
[  OK  ] DietPi-Software | G_THREAD: All threads finished
[ INFO ] DietPi-Software | python3 ./get-pip.py, please wait...
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.3.1
    Uninstalling pip-21.3.1:
      Successfully uninstalled pip-21.3.1
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[  OK  ] DietPi-Software | python3 ./get-pip.py
[  OK  ] DietPi-Software | rm get-pip.py

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Finalising install

[  OK  ] DietPi-Software | systemctl daemon-reload
2022-01-08 00:27:59 [ INFO ] DietPi-RAMlog | Storing /var/log to /var/tmp/dietpi/logs/dietpi-ramlog_store...
2022-01-08 00:27:59 [  OK  ] DietPi-RAMlog | Stored /var/log to /var/tmp/dietpi/logs/dietpi-ramlog_store.
[ SUB1 ] DietPi-Services > dietpi_controlled
[  OK  ] DietPi-Services | dietpi_controlled : cron

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Install completed

[  OK  ] DietPi-Survey | Purging survey data
[ SUB1 ] DietPi-Services > restart
[  OK  ] DietPi-Services | restart : cron
root@DietPi4:~#
```
</details>

And this is how `pip/pip3` looks like afterwards

```
root@DietPi4:~# pip3
-bash: /usr/local/bin/pip3: No such file or directory
root@DietPi4:~# pip
-bash: /usr/local/bin/pip: No such file or directory
root@DietPi4:~#
```

as well I have seen

```
root@DietPi1:~# pip3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
root@DietPi1:~# pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
root@DietPi1:~#
```

Not sure what pypa.io guys did with `setuptools`

Python3 uninstall is failing as well now

<details>
  <summary>Uninstall log attached. Click to expand!</summary>

```
[  OK  ] DietPi-Software | Initialised database
[  OK  ] DietPi-Software | Reading database

 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Automated uninstall

[  OK  ] DietPi-Software | Uninstalling Python 3: Runtime system, pip package installer and development headers

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Uninstalling Python 3: Runtime system, pip package installer and development headers

[ INFO ] DietPi-Software | pip3 uninstall -y pip setuptools wheel, please wait...
Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
[FAILED] DietPi-Software | pip3 uninstall -y pip setuptools wheel
```
</details>

**Comment by MichaIng** [comment]
Ayayay, luckily I did not recognise that v60.3.x has been released 😄. Okay, really not a big problem to keep this simple and quick workaround in place and give the `setuptools` devs some more time to have it properly fixed. Has this already been reported?

**Comment by Joulinar** [comment]
I did not checked back. I just stumble across while checking an issue from forum and Python3 brock during reinstall. I hope nobody will do a reinstall on a version below DietPi v8. 🙄

**Comment by MichaIng** [comment]
Good that we release tomorrow 🙈.

**Comment by Joulinar** [comment]
and we have a hardcore workaround for users who already broke Python

```
rm -rf /usr/local/lib/python3.9/dist-packages/setuptools*
```

**Comment by MichaIng** [comment]
Ah nice, simple when this is all (manual `setuptools` "uninstall").

**Comment by Joulinar** [comment]
yes, only chance to get it back working because `pip3 uninstall -y setuptools` is failing as well with same error and there is no other way to get `setuptools` removed. Let's hope that we will not have to much issues on older versions.

**Comment by MichaIng** [comment]
We do not install an older version, but only uninstall it before running `get-pip.py`. Upgrading `setuptools` outside of `get-pip.py` seems to not cause issues 🙂.

**Comment by Joulinar** [comment]
ah I was not clear enough. I mean older DietPi versions below v8. As there we do not remove `setuptools`  leading to actual issue😉

**Comment by MichaIng** [comment]
Ah yes, that is true. Good that we have a simple repair step, and another argument to keep DietPi updated.

**Comment by MichaIng** [comment]
There have been two further releases of `setuptools` in the meantime, now being v60.5.0. Probably this has solved the issue.

**Comment by Joulinar** [comment]
Will do some testing this week on this.

**Comment by Joulinar** [comment]
installation seems to be brocken still 

 DietPi-Software
─────────────────────────────────────────────────────
 Step: Installing Python 3: Runtime system, pip package installer and development headers

```
[  OK  ] DietPi-Software | cd /tmp/DietPi-Software
[  OK  ] DietPi-Software | Checking URL: https://bootstrap.pypa.io/pip/get-pip.py
[ INFO ] DietPi-Software | G_THREAD_START_0 | curl -sSfL https://bootstrap.pypa.io/pip/get-pip.py -o get-pip.py
[ INFO ] DietPi-Software | APT install for: python3-dev, please wait...
[  OK  ] DietPi-Software | APT install for: python3-dev
[  OK  ] DietPi-Software | G_THREAD: All threads finished
[ INFO ] DietPi-Software | python3 ./get-pip.py, please wait...
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple/
Collecting pip
  Using cached https://www.piwheels.org/simple/pip/pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.3.1
    Uninstalling pip-21.3.1:
      Successfully uninstalled pip-21.3.1
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Successfully installed pip-21.3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[  OK  ] DietPi-Software | python3 ./get-pip.py
[  OK  ] DietPi-Software | rm get-pip.py
```

**Comment by MichaIng** [comment]
Reported: https://github.com/pypa/pip/issues/10742#issuecomment-1008830783

**Pull request merged**
