### PR TITLE
CI | DietPi-Software: Check services and ports automatically after software installs

### PR DESCRIPTION
**Pull request by MichaIng**
Die service und port liste kann man auch hier übernehmen und/oder consequent in die docs: https://github.com/MichaIng/DietPi/wiki/DietPi-Software-list

### CODE REVIEW

**Comment by Joulinar** [comment]
we should store it on a single place. Best would be of all other sides; docs would grep port information from that single source. Otherwise, we would have multiple areas where we would need to maintain it.

**Comment by MichaIng** [comment]
> we should store it on a single place. Best would be if all other sides; docs would grep port information from that single source. Otherwise, we would have multiple areas where we would need to maintain it.

Same thought here. We already thought about this in the past, basically Petru was coming up with the idea and a draft: https://github.com/MichaIng/DietPi-Docs/pull/194/files
We could even add a GitHub workflow which automatically updates (via PR) those info in `dietpi-software` and `dietpi-software.html`, and other places, when the JSON files change. I'd then store them in a dedicated repository. Of course it doesn't need to be added with all information right from the start. We could start small, with just port numbers in docs, and hopefully there is a way to automate the Wiki update accordingly.

**Comment by Joulinar** [comment]
This is the way.

**Comment by MichaIng** [comment]
The way, this is

**Comment by ravenclaw900** [comment]
This would also give DietPi Dashboard a way to automatically have links to installed software, as mentioned in https://github.com/ravenclaw900/DietPi-Dashboard/issues/169#issuecomment-1054430629.

**Comment by MichaIng** [comment]
Another good point.

**Pull request merged**
