### PR TITLE
add id 69 for nanopi neo plus 2

### PR DESCRIPTION
**Pull request by aliosa27**
**Status**: 

**Reference**: 

**Commit list/description**:

- ...

### CODE REVIEW

**Comment by MichaIng** [comment]
@aliosa27 
Thanks for your PR. Some more words/explanation why you think this is needed would be nice generally 😉.

We do not officially offer an image for this device, nor do we do some special handling, right?
In this case I would not add it to DietPi-PREP list. This would give end user a wrong idea about what is supported and DietPi optimized for an what not.

There are other devices in the list, that we do not support any more, but the code that handles configuration and software installations special for them, is still within DietPi, thus it is okay to keep them.

If we really, e.g. for statistical reason (dietpi-survey) want to add otherwise unsupported devices to the list, this should be clearly marked and then moved to a higher index range, e.g.: `'100' 'NanoPi NEO Plus 2 - not (yet) supported!'`
Then it also needs to be added to https://github.com/Fourdee/DietPi/blob/master/dietpi/func/dietpi-obtain_hw_model, otherwise you will just face `NULL` entries outside of DietPi-PREP.

**Comment by aliosa27** [comment]
Yep, i forgot to check in my change to obtain_hw_model, aside from that it built and functions/wifi/etc,etc.

I will change this to 100. I didn't realize this device would be considered unsupported as I thought that policy was more driven towards the orange pi/boards with horrid bsp support side of things.

**Comment by MichaIng** [comment]
@aliosa27 
Generally running DietPi-PREP without error, it should work and we will answer and help on errors/bug reports. But based on the unlimited possible pre-image/build possibilities it is impossible to guarantee this. Only for images we offer, where we know which base/pre-image we used and could test it, we know that it should work and will force fixes in case of bugs.

But more important is the point, that if the SBCs name can be selected from within the list, Me as user would suggest it has some effect on how the image is applied and configured on/after boot. If this really has no effect anywhere in the code, for my impression it is more consistent to then not (yet) list it. `Generic device` can then be used and clearly implies that nothing special is being applied for this device.

Reference: https://github.com/Fourdee/DietPi/issues/1143
- Great would be indeed, if we could add the device to our official images. Which base image did you use/apply DietPi-PREP on?

**Comment by Fourdee** [comment]
@aliosa27 

Hi thanks for the PR 👍 

Generally speaking, unless we officially release images and support for the device in question, use of 'Generic Device' should be sufficient for end users needs.

If we get can our hands on the device, we'll add the ```G_HW_MODEL``` index's as needed, until then, please simply use 'Generic Device' during PREP as mentioned above.

I'll mark this as closed. Please reopen if required.

**Comment by aliosa27** [comment]
Armbian

**Comment by Fourdee** [comment]
@aliosa27 

> Generic device can the be used and clearly
 implies that nothing special is being applied for this device.

Somewhat incorrect. 

The ```G_HW_MODEL``` index on its own, does nothing except add the board info.

When WE implement devices and images, we use the ```G_HW_MODEL``` index to specify WiFi modules, soundcard options, GPU options (if available) and more etc. All of which are tested and verified to be working off the bat.

The CPU core count and ```G_HW_ARCH``` is automatic detection, so, some optimizations (eg: software installations) are applied automatically.

Generally speaking, if you are using the device headless, for server usage without GPU/audio, ```Generic device``` should offer a good experience for any board.
To get the most from the board (in terms of features and support in DietPi), we need to implement the ```G_HW_MODEL``` index and code in the supported features. Which also implies, we create and support an official DietPi image.

---

In regards to PREP. The OPi devices (and a few others) have been left in, as we still have some ```G_HW_MODEL``` specific code in DietPi for those devices. Left over, before we removed them from our lineup.

**Pull request closed without merging**
