### PR TITLE
Quartz64 | Enable RAID modules

### PR DESCRIPTION
**Pull request by dano6**
This PR should enable linux software raid modules for Quartz64 devices

### CODE REVIEW

**Comment by MichaIng** [comment]
Many thanks for contributing this. Is it intentionally still a draft? If you want to test it, I can quickly build a kernel package with this change.

Btw, I tend to lookup details about configs here: https://www.kernelconfig.io/config_md_linear?arch=arm64

And then I check how it is implemented on RPi and Debian's kernel, just to get an idea how it is commonly done:
```sh
root@micha:~# zgrep CONFIG_MD_LINEAR /proc/config.gz
CONFIG_MD_LINEAR=m
root@dietpi:~# grep CONFIG_MD_LINEAR /boot/config-6.1.0-7-amd64
CONFIG_MD_LINEAR=m
```
Debian sets those settings all as well, on RPi the last 3 are unset (which default to "no" then), but I think it is fine to add them here as modules.

**Review by MichaIng — DISMISSED** [review]

**Comment by dano6** [comment]
Yes, it is a draft, because  I wanted to test it. Can you please start build action? 
What kernel are using other devices, upstream kernel from debian?

**Comment by MichaIng** [comment]
Ah, I cannot trigger our CI on forks, as they have no access to secrets. Let me merge it. If it does not work, we can patch if afterwards. It does not overwrite the packages currently downloaded on Quartz64 updates and image generations, which needs to be still manually done, so is safe to do.

**Review by MichaIng — APPROVED** [review]

**Comment by dano6** [comment]
Thanks for the merge, but for some reason I don't see built packages there.

**Comment by MichaIng** [comment]
I see them here 🤔. However, e.g. for Quartz64 A:
```sh
cd /tmp
curl -O 'https://dietpi.com/downloads/binaries/testing/firmware-quartz64a.deb'
dpkg -i firmware-quartz64a.deb
rm firmware-quartz64a.deb
```
resp. `firmware-quartz64b.deb` and `firmware-soquartz.deb`.

**Comment by dano6** [comment]
Thanks, it works fine, i didn't have time to test it earlier.

**Pull request merged**
