### PR TITLE
DietPi-NordVPN | Add CLI command "apply"

### PR DESCRIPTION
**Pull request by theAkito**
**Status**: WIP | Testing | Ready | ?
- [x] Ready

**Reference**: Is an issue needed? Not sure. If one is needed, I can make one to make this pull request more complete.

**Commit list/description**:

- Port "Apply" from GUI to CLI.

With `dietpi-nordvpn apply` the "Apply" as known from the GUI menu is ported to the CLI.
So there there is no need anymore for entering the GUI to effectively apply settings and implicitly (re-)connect to NordVPN.

This makes it possible to issue cronjobs that want to "Apply" the settings, which couldn't be done while the option was available in GUI, only. Or you can just quickly `dietpi-nordvpn apply` manually to quickly connect after a disconnect that happened some time ago. No need to enter the GUI just to do this.

### CODE REVIEW

**Comment by MichaIng** [comment]
Many thanks for this idea.

There are currently a few issues:
- `Import_DietPi_Globals` is always called now. The idea was to not load it for "`status`" since it takes a recognisable time and hence delays the login banner where this NordVPN status print is used.
- And it is loaded after `G_WHIP_YESNO` usage in `init`.
- `Update_Wan_Ip` is not required here since it is only used to print the WAN IP within the interactive menu.

But let me first understand the exact use case for this feature:
- For reconnecting the VPN, one can and should use: `systemctl restart dietpi-nordvpn`
- The "apply" button only makes a difference if one changes the the NordVPN server or login credentials. Without the GUI this means manually editing `/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/settings_dietpi.conf`.

Do you want a cron job that rotates the NordVPN server? This is the most reasonable use case I can currently think of. But then me might want to instead implement this natively as of this request: #3083

**Comment by theAkito** [comment]
>     * `Import_DietPi_Globals` is always called now. The idea was to not load it for "`status`" since it takes a recognisable time and hence delays the login banner where this NordVPN status print is used.

Yes, I see, mixed up the places, after putting stuff into functions. Will take care of that.



>     * And it is loaded after `G_WHIP_YESNO` usage in `init`.

I checked the installation proposal, by inducing the error to check if it still works, but I apparently did that before the latter modifications. Will fix that.



>     * `Update_Wan_Ip` is not required here since it is only used to print the WAN IP within the interactive menu.

Okay, will remove that.



>     * For reconnecting the VPN, one can and should use: `systemctl restart dietpi-nordvpn`

Didn't work for me when I tried it a couple of times. Sometimes it did not even find the service file. Then I looked at the `dietpi-nordvpn` script and saw that there is more than just restarting a static service, when you are using "Apply" in the menu. That said, restarting just the service manually feels kind of hacky, especially if you don't want to know how the script actually works and a normal user shouldn't be forced to know. So using the familiar `dietpi-nordvpn` API would circumvent this issue, as well.


> Do you want a cron job that rotates the NordVPN server? This is the most reasonable use case I can currently think of. But then me might want to instead implement this natively as of this request: #3083

I do not want to rotate servers. I want to connect to a server, since the automatic (re-)connection doesn't work properly and my service restarting trial has repeatedly failed. Yes, one should ideally fix the underlying issue of that, but I am sure that this will be different from user to user, so I rather create a fix that works for everybody and doesn't require gathering data about so many different use cases, where for some it works fine, for others it never works.

Additionally, there was a `status` command already, so why not implement the real "Apply" from the GUI menu, too? Especially, since it is easily understandable for users who know the "Apply" from the GUI menu already, so they don't have to think in a different way, when they use the CLI version of connecting to the VPN service.

However, there is a really good point in the referenced issue:
>Next step could be that Dietpi-NordVPN automatically selects a new server if the current one is/gets down and/or test the servers initially selected to see if they are up before connecting.

This is indeed something important and I already had trouble with that, as well. So I would be interested in fixing this issue, too, in another Pull Request. In the process of doing that, the server rotation thing can be implemented, like a wished for side effect.

All that said, thank you very much for your feedback. Much appreciated.

**Comment by theAkito** [comment]
>     * `Import_DietPi_Globals` is always called now. The idea was to not load it for "`status`" since it takes a recognisable time and hence delays the login banner where this NordVPN status print is used.

I now found the time to actually look at the source code again and notice that this is no mistake. The function is called, but it only contains what is run on every script usage. It differentiates between empty input and non-empty input, just as before. So it is correct, that this function is run on every program run, because that is what it did before. The whole DietPi environment is only loaded when the GUI ist loaded, just as before. Nothing changed about that behaviour.

**Comment by MichaIng** [comment]
> It differentiates between empty input and non-empty input, just as before.

Ah your right, sorry I was not recognising.

> I do not want to rotate servers. I want to connect to a server, since the automatic (re-)connection doesn't work properly and my service restarting trial has repeatedly failed.

Hmm that is strange, because really the script does nothing else. It prepares the ovpn file and creates the service file based on chosen/changed server or credentials or drop-in configs. As long as nothing of that changes, `systemctl restart dietpi-nordvpn` is the only relevant step, everything is only overwriting files with identical ones and the attempt to alter settings which is skipped with "desired setting already present". Ah there is one difference that might play a role: `systemctl stop dietpi-nordvpn` and then `systemctl daemon-reload` leads to ~1 second where the service is down. Probably `systemctl restart dietpi-nordvpn` can fail if the connection is dropped and reconnected to quickly.

Probably we should add `RestartSec=2s` so that a restart always has 2 seconds delay.

**Comment by theAkito** [comment]
> Probably `systemctl restart dietpi-nordvpn` can fail if the connection is dropped and reconnected to quickly.

This reminds me of the Docker systemd service that pretty much became infamous for its inability to start at all, if restarted "too quickly". You always had to stop the service, wait 5-10 seconds, then start the service. I think this is still the case, today.



> Probably we should add `RestartSec=2s` so that a restart always has 2 seconds delay.

Should I add this to this PR, too?
If yes, should it be more than 2 seconds, to be sure?

**Comment by MichaIng** [comment]
Yes please try it and see if `systemctl restart dietpi-nordvpn` works reliable then to reconnect on connection loss. We could also add some auto-restart to the systemd unit, but actually I'm not big fans of this, at least it should be limited to a small number of attempts then.

I compared our unit with the generic upstream OpenVPN client unit and added some security hardenings and better process handling. You could try those all together:
```
cat << _EOF_ > /etc/systemd/system/dietpi-nordvpn.service
[Unit]
Description=NordVPN (DietPi)
Wants=network-online.target
After=network-online.target dietpi-boot.service

[Service]
Type=notify
ExecStart=$(command -v openvpn) --suppress-timestamps --nobind --config /etc/openvpn/ovpn_udp/<config_name>.ovpn
RestartSec=2s
KillMode=process
# Hardenings
PrivateTmp=true
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE
LimitNPROC=10
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw
ProtectSystem=true
ProtectHome=true

[Install]
WantedBy=multi-user.target
_EOF_
systemctl daemon-reload
```

**Comment by theAkito** [comment]
After a couple of tries it started to work.

First try:
```
scs dietpi-nordvpn.service

● dietpi-nordvpn.service - NordVPN (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-nordvpn.service; enabled; vendor preset: enabled)
     Active: deactivating (stop-sigterm) since Wed 2020-09-16 20:04:15 CEST; 1min 9s ago
# ....

Sep 16 20:03:41 4nPi openvpn[25973]: RTNETLINK answers: File exists
Sep 16 20:03:41 4nPi openvpn[25937]: Wed Sep 16 20:03:41 2020 ERROR: Linux route add command failed: external program exited with error status: 2
Sep 16 20:03:41 4nPi openvpn[25937]: Wed Sep 16 20:03:41 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.0.1
Sep 16 20:03:41 4nPi openvpn[25937]: Wed Sep 16 20:03:41 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.0.1
# ....
# ....
Sep 16 20:03:59 4nPi systemd[1]: dietpi-nordvpn.service: Current command vanished from the unit file, execution of the co
mmand list won't be resumed.
Sep 16 20:04:15 4nPi systemd[1]: Stopping NordVPN (DietPi)...
```
Which is an error related to `systemd`, you were already aware of.

Second try:
```
● dietpi-nordvpn.service - NordVPN (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-nordvpn.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2020-09-16 20:07:51 CEST; 1min 19s ago
   Main PID: 27048 (code=exited, status=203/EXEC)

Sep 16 20:07:51 4nPi systemd[1]: Started NordVPN (DietPi).
Sep 16 20:07:51 4nPi systemd[27048]: dietpi-nordvpn.service: Failed to execute command: Permission denied
Sep 16 20:07:51 4nPi systemd[27048]: dietpi-nordvpn.service: Failed at step EXEC spawning # .... #.ovpn: Permission denied
Sep 16 20:07:51 4nPi systemd[1]: dietpi-nordvpn.service: Main process exited, code=exited, status=203/EXEC
Sep 16 20:07:51 4nPi systemd[1]: dietpi-nordvpn.service: Failed with result 'exit-code'.
```

Third try it worked.
Then I tried stopping it, but got a timeout:
```
● dietpi-nordvpn.service - NordVPN (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-nordvpn.service; enabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Wed 2020-09-16 20:11:12 CEST; 10s ago
    Process: 27373 ExecStart=/usr/sbin/openvpn --suppress-timestamps --nobind --config /etc/openvpn/ovpn_udp/# ...(code=killed,
 signal=KILL)
   Main PID: 27373 (code=killed, signal=KILL)
     Status: "Pre-connection initialization successful"

# ... #
# ... #
# ... #
Sep 16 20:09:18 4nPi sudo[27398]: pam_unix(sudo:session): session closed for user deluge
Sep 16 20:09:42 4nPi systemd[1]: Stopping NordVPN (DietPi)...
Sep 16 20:11:12 4nPi systemd[1]: dietpi-nordvpn.service: State 'stop-sigterm' timed out. Killing.
Sep 16 20:11:12 4nPi systemd[1]: dietpi-nordvpn.service: Killing process 27373 (openvpn) with signal SIGKILL.
Sep 16 20:11:12 4nPi systemd[1]: dietpi-nordvpn.service: Main process exited, code=killed, status=9/KILL
Sep 16 20:11:12 4nPi systemd[1]: dietpi-nordvpn.service: Failed with result 'timeout'.
Sep 16 20:11:12 4nPi systemd[1]: Stopped NordVPN (DietPi).

```

Starting worked fine, afterwards.
Restarting again, works fine, too.

During all trials the new service file was already pasted and loaded. Nothing changed in the service file between all the trials.

Despite all of this, it seems to work now. Seems to work at least as good as the previous service and now the restarting of the service only, works for me, too.

I'll update the `dietpi-nordvpn` script, accordingly.

**Comment by theAkito** [comment]
I have no idea, how that is possible, but sometimes the `command` command does not expand and the openvpn bin is not put into the service file:
```
● dietpi-nordvpn.service - NordVPN (DietPi)
     Loaded: bad-setting (Reason: Unit dietpi-nordvpn.service has a bad unit file setting.)
     Active: failed (Result: timeout) since Thu 2020-09-17 00:06:31 CEST; 59s ago
   Main PID: 13566 (code=killed, signal=KILL)
     Status: "Pre-connection initialization successful"

Sep 17 00:05:01 4nPi openvpn[13617]:     fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
Sep 17 00:05:01 4nPi openvpn[13617]: builtins.TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
Sep 17 00:05:01 4nPi sudo[13612]: pam_unix(sudo:session): session closed for user deluge
Sep 17 00:06:31 4nPi systemd[1]: dietpi-nordvpn.service: State 'stop-sigterm' timed out. Killing.
Sep 17 00:06:31 4nPi systemd[1]: dietpi-nordvpn.service: Killing process 13566 (openvpn) with signal SIGKILL.
Sep 17 00:06:31 4nPi systemd[1]: dietpi-nordvpn.service: Main process exited, code=killed, status=9/KILL
Sep 17 00:06:31 4nPi systemd[1]: dietpi-nordvpn.service: Failed with result 'timeout'.
Sep 17 00:06:31 4nPi systemd[1]: Stopped NordVPN (DietPi).
Sep 17 00:06:33 4nPi systemd[1]: /etc/systemd/system/dietpi-nordvpn.service:8: Executable "-suppress-timestamps" not found in path "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/
sbin:/bin", ignoring
Sep 17 00:06:33 4nPi systemd[1]: dietpi-nordvpn.service: Service has no ExecStart=, ExecStop=, or SuccessAction=. Refusing.
```

**Comment by MichaIng** [comment]
Okay, something is very flaky there, one time permission to access the `.ovpn` is denied, one time not, one time `command -v` does not print a result (it does expend, but without output) in the other case it does. However this has nothing to do with the service changes or with the restart success.

I hope you agree that the `apply` is not a real fix for something, it is only a large overhead around the actual service restart and the time delay only might make a difference while the many other obsolete steps might even create issues if something with this fails, like the wrong re-written service file. So instead of adding something that might or might not work in some cases, while we are not even sure why it does, I'd like to check the essence of why the usual service restart actually fails in your case, as this seems to be some deeper system issue.

**Comment by theAkito** [comment]
> I hope you agree that the `apply` is not a real fix for something, it is only a large overhead around the actual service restart and the time delay only might make a difference while the many other obsolete steps might even create issues if something with this fails, like the wrong re-written service file. So instead of adding something that might or might not work in some cases, while we are not even sure why it does, I'd like to check the essence of why the usual service restart actually fails in your case, as this seems to be some deeper system issue.

Yes, correct, but I wanted to avoid a long lasting exploration into these depths by having something that works immediately just as reliably, as before or perhaps better. (Not saying, that it worked reliably before -- everything is relative.)

Additionally, in my case, I need to apply the `up.sh` and `down.sh`. It's not enough in my use case to just restart the connection itself. So I thought, instead of doing a lightweight and different "Apply", I might just port the whole original one to the CLI, to at least try to improve things enough to make it work a little better.

That said, I have seen that you are very thorough and don't want to implement half-baked stuff without it clearly fitting into the context. Therefore, I understand your concerns and where you are coming from. Technically, I never disagreed with you right from the start, the difference just is, that I wanted to try a quicker fix while you want to fix the actual issue behind the symptoms, which is of course a legitimate approach and I fully respect that.

We can agree on a different approach:
For now, I'll keep this version as an alternative without pushing it to the actual DietPi project and we can change the actual purpose of this Pull Request (or make a new one) to fixing the actual issue. Alright?

**Comment by MichaIng** [comment]
I had a little rethink about all this topic and generally I like the idea to have a real CLI for this script. What I am thinking of is adding command options to apply server and login credentials as well, so that basically one is able to skip the GUI and do things via scripts, e.g. via `AUTO_SETUP_CUSTOM_SCRIPT_EXEC` `dietpi.txt` setting.

I'm currently not too happy to add it as is, since this `apply` command does really nothing on it's own aside of a restart/reconnect, as we already discussed. Of course it re-creates the service as well but that does not change as long as one did not create an up/down script manually before or manually changed the settings files. And in this case one can as well manually re-create or alter the service manually as well.

**Comment by MichaIng** [comment]
We're doing a larger rework of that script: #4180
Adding a complete CLI is another task I definitely aim to add, but that should be done as new commit, when the linked PR has been finished and merged.

**Pull request closed without merging**
