### PR TITLE
DietPi-Software | Nextcloud: Fixed terminal installation

### PR DESCRIPTION
**Pull request by MichaIng**
+ DietPi-Software | Nextcloud: Fixed terminal installation and added filename to sed correct CLI URL

### CODE REVIEW

**Comment by MichaIng** [comment]
Hmm, wanted to use naming of @Fourdee commits, but overview of PR page gets lost by this 😆. Which method is preferred?

**Comment by MichaIng** [comment]
Ah bad, I introduced dropping of parent database user also on update. That broke db access for all common instances. I need to be more careful on testing, wonder why I didn't face this. Maybe because database user stayed in place after uninstall...

So bugpatch removed of course, but I am thinking how to handle this best: Guessing all effected users solved this by themself, or recreating that db user with privileges on update?

**Comment by Fourdee** [comment]
@MichaIng 

> Hmm, wanted to use naming of @Fourdee commits, but overview of PR page gets lost by this 😆. Which method is preferred?

For PR's, its probably best to put the info in title, instead of the version number.

> Ah bad, I introduced dropping of parent database user also on update. That broke db access for all common instances. I need to be more careful on testing, wonder why I didn't face this. Maybe because database user stayed in place after uninstall...
So bugpatch removed of course, but I am thinking how to handle this best: Guessing all effected users solved this by themself, or recreating that db user with privileges on update?

No worries, i've done much worse 👍
Although patches should be thoroughly tested with existing installations (and their targeted software), before the PR is committed, to avoid future cases. Just as much my fault for not testing.

So for existing installations that are effected by this, it may be advisable to inform only those users to reinstall manually (+uninstall to drop the DB)?:
```
dietpi-software uninstall 114
dietpi-software install 114
```

**Comment by MichaIng** [comment]
I just answered to issue in forum. Simplest solution is indeed to just grant oc_admin@localhost directly privileges on database, who inherited them from droped oc_admin@% before.

User should indeed NOT uninstall, as this will drop all contacts, calendars, shares, comments, tags, previews etc etc with their database. Indeed we should somehow enable users to decide what to do with database, same as data folder, on un/reinstall, as they might want to preserve that.

**Comment by Fourdee** [comment]
@MichaIng 
Legend, many thanks 👍

**Pull request merged**
