### PR TITLE
Revamp the README

### PR DESCRIPTION
**Pull request by MirisWisdom**
This pull request updates the README with additional information, typo fixes, and a prettier layout. The existing contents have been minimally changed; instead, the main changes are mostly cosmetic.

In a nutshell:

- Prominent centered header;
- An introductory section to the project;
- Simplified layout for the contributors & software list;
- Improved maintainability of the README.

As always, any suggestions are welcome!

# Screenshot

New README layout screenshot

### CODE REVIEW

**Comment by MichaIng** [comment]
@yumiris 
Looks really great. Love the new design 😃.
Please give a hint when you are done.

**Review by MichaIng — COMMENTED** [review]
Little suggestions:
- I see `****` in front of "find out more" link. Is this wanted?
- In contributors section, maybe merge all "contributions" or one contributor into a single line? Reduces line count a bid (scrolling need). But not sure if it really looks better 🤔.

**Comment by MirisWisdom** [comment]
@MichaIng, the `****` was accidental, oops!

I merged the contributions into one line. Can easily revert if the list looked better 😛 let me know what you think.

**Review by MichaIng — APPROVED** [review]
For me it's okay like this, with contributions in one line. Great work 👍!

**Comment by MirisWisdom** [comment]
Excellent, looks like it's ready to be merged in. Cheers!

**Comment by MichaIng** [comment]
@yumiris 
Let's wait for Fourdees opinion/suggestions, not nothing to complain from my side 😃.

**Comment by Fourdee** [comment]
@yumiris 

Stunning work 👍 🥇 💘 

A much needed improvement, and, long overdue. Thank you for doing this!

Please email me your address and i'll post you some DietPi stickers 👍

**Review by Fourdee — APPROVED** [review]

**Pull request merged**
