### PR TITLE
DietPi-Config | Remove deprecated max_usb_current option

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready
- https://github.com/raspberrypi/documentation/pull/1456#issuecomment-653539252
- https://github.com/raspberrypi/documentation/issues/1655

### CODE REVIEW

**Comment by MichaIng** [comment]
Due to missing verification from kernel devs, I'll defer this to next release. Nothing urgent anyway I just want to remove an ineffective option, or show it only for the models where it has an effect, so users do not play with or suspect this as solution or culprit for any power-related issues.

**Comment by danrneal** [comment]
This still makes a difference on my pi.  With this option set manually in config.txt, my hdd can run, without it, it cannot.  While I know it is deprecated in newer pis and in the main raspi os, it still is relevant.

**Comment by MichaIng** [comment]
Many thanks for letting us know. Which RPi model is it and are you running the latest official kernel version (`raspberrypi-kernel` package) on a new Buster-based image? I'm wondering since this statement from the kernel/firmware developer was very clear: https://github.com/raspberrypi/documentation/issues/1655#issuecomment-681853018

**Comment by danrneal** [comment]
─────────────────────────────────────────────────────
 DietPi v6.34.3 : 13:48 - Wed 12/30/2020
 ─────────────────────────────────────────────────────
 - Device model : RPi 3 Model B (armv7l)

uname -a
Linux DietPi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux


I believe that is the latest kernel and image

**Comment by danrneal** [comment]
I also tried this on Raspberry Pi OS with the same results so this is not DietPi specific.

**Comment by danrneal** [comment]
My response in https://github.com/raspberrypi/documentation/issues/1655#issuecomment-753247066_

> I'm afraid I must be mistaken because I cannot reproduce it despite running into this issue several times this week.  I imaged with Raspberry Pi OS twice (and sudo apt update right after as well) and had this issue.  Then I had the issue once again with DietPi, but now..... no issue.  My thoughts are that DietPi must have updated something that was causing my specific Pi wasn't updating with Rasperry Pi OS. :shrug:

**Comment by MichaIng** [comment]
First of all, happy new year 🎆🙂.

As of your posts above, kernel and firmware was successfully updated. I guess it was some coincidence that it worked with the setting while it did not without. Note that powering a 2,5" drive (as well SSD) via RPi USB power only is not a reliable option. The theoretical 5W (1A) that all USB ports together share, is quite close when you consider usage and voltage peaks. I always recommend to use a docking station/case with a dedicated power supply.

At least you should have a look at the kernel error log, if there are any voltage, power or I/O related messges:
```
dmesg -l emerg,alert,crit,err
```

**Pull request merged**
