### PR TITLE
DietPi-Software | Roon Server: Separate install and data dir

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Software | Roon Server: Resolved an issue where the internal updater purged all Roon Server data and configs, since the data directory was located within the install directory. Roon Server will now be installed to /opt/roonserver while the data directory remains at /mnt/dietpi_userdata/roonserver. This change will be applied via DietPi update as well, your data and configs will remain untouched. Many thanks to @JanKoudijs for reporting this issue and providing a solution: https://github.com/MichaIng/DietPi/pull/4897
+ DietPi-Software | Roon Server: Merge install and config code blocks

### CODE REVIEW

**Comment by JanKoudijs** [comment]
I repeated my test steps with the latest changes. It turns out than the moving approach still triggers the login and unauthorize stuff, I don't know why :(

The moving does take care that the version that was installed before the update remains after the update.

> The only last concern is that older Roon Server versions may contain other files. I only know the URL for the latest version

The approach taken by Roon Labs is that only the latest version can be downloaded and only the latest version is supported. This is because of backend stuff in the cloud and keeping control on the support requests.

**Comment by MichaIng** [comment]
> The approach taken by Roon Labs is that only the latest version can be downloaded and only the latest version is supported. This is because of backend stuff in the cloud and keeping control on the support requests.

We do it exactly the same way, for the same reasons, so no offence. I will turn the notification about the migration into a whiptail prompt and encourage users to report it here when facing any issues, i.e. the Roon Server service is not starting after the update. We should then be able to find the additional file/dirs that need to be moved, in case.

The authorized Roon server probably implies the file path as well. Another thing is that I added `ROON_ID_DIR` to the systemd unit, following the one installed by the official installer. I'm not sure if it has any effect when matching `ROON_DATAROOT`, but will do some tests now. Probably previously the root user home was used for user/ID data. In case we need to move those files as well. Makes sense to have everything in one place, especially since I aim to run the service as dedicated `roon` service user on a future version, or probably with a later commit for DietPi v7.8 already.

**Comment by MichaIng** [comment]
Indeed, only commenting or uncommenting the `ROON_ID_DIR` triggers the requirement to again login and in case unauthorize, also without moving or reinstalling the server. The thing is, what is it by default? I cannot find any files of the Roon Server (with `roon` in their name) outside of install and data dir 🤔.

Found out now that a file named `.rmembid` is created in the `ROON_ID_DIR` which contains a UUID style hex string. But it doesn't match `/mnt/dietpi_userdata/roonserver/RAATServer/Settings/unique_id`. When not setting the `ROON_ID_DIR`, the `.rmembid` is not created anywhere, but restarting the Roon Server doesn't break the apps authorization. So the question is how/where the info stored in `.rmembid` is saved when `ROON_ID_DIR` isn't set at all 🤔.

**Comment by MichaIng** [comment]
Probably someone can shed some light on this variable/file: https://community.roonlabs.com/t/what-is-roon-id-dir-rmembid-used-for/175688

I'll verify now that skipping this variable (like it was before) keeps the login/authorization state of the app intact.

**Comment by MichaIng** [comment]
Just received an email about the upcoming release which requires additional dependencies for .NET core: https://help.roonlabs.com/portal/en/kb/articles/linux-performance-improvements#Whats_happening
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libicu
Same as for Radarr/Lidarr/Jackett .NET core variants.

**Comment by MichaIng** [comment]
Okay it works fine now, no login and unauthrize steps required after the update. Would be still good to find out what `ROON_ID_DIR` is used for, respectively the implication of leaving it out and how to preserve authorization states when setting/changing it: https://community.roonlabs.com/t/what-is-roon-id-dir-rmembid-used-for/175688

**Pull request merged**
