### PR TITLE
DietPi-Banner/VPN | Move to more reliable WAN IP + location API service

### LINKED ISSUE #4211: WAN IP in dietpi-banner has a tendency to not resolve
#### Required Information
- DietPi version | v7.0.2
- Distro version | buster
- Kernel version | 5.10.17-v8+
- SBC model | RPi 4 Model B (aarch64)
- Power supply used | random usb c phone charger (5V/3A)
- SDcard used | SanDisk Plus 16gb (iirc)

#### Additional Information (if applicable)
- Can this issue be replicated on a fresh installation of DietPi? Yes

#### Steps to reproduce

1. Enable WAN IP in bietpi-banner
2. Either reload it several times or just wait for it to fail naturally.
(Reloading rapidly probably hits some ratelimiter, to be fair)

#### Expected behaviour

- WAN IP should display

#### Actual behaviour

- WAN IP has a tendency not to display, or hangs for a notable amount of time (~1/2s)

#### Extra details

- Could be resolved with storing the output of the last successful WAN IP attempt, then using that value if no WAN IP is returned from ifconfig.co. A date displaying the time this IP was stored could be appended to prevent confusion as to why it may be outdated.

### LINKED ISSUE #4393: dietpi-banner:  WAN IP : curl: (22) The requested URL returned error: 503
Recently dietpi-banner gives an Http 503 error for WAN IP.

```
root@M-DNS:~# dietpi-banner
 ─────────────────────────────────────────────────────
 DietPi v7.1.2 : 13:19 - Wed 05/19/21
 ─────────────────────────────────────────────────────
 - Device model : NanoPi NEO2 (aarch64)
 - Uptime : up 43 minutes
 - CPU temp : 34'C : 93'F (Cool runnings)
 - FQDN/hostname : M-DNS
 - LAN IP : 192.xxx.xxx.xxx (eth0)
 - WAN IP : curl: (22) The requested URL returned error: 503
 - Freespace (RootFS) : 23G
 - MOTD : Did you know that you can run "dietpi-banner" to change its content?
 ─────────────────────────────────────────────────────
```

### PR DESCRIPTION
**Pull request by MichaIng**
**Status**: Ready

**Commit list/description**:
+ DietPi-Banner | Move to more reliable WAN IP + location API service
+ DietPi-VPN | Move to more reliable WAN IP + location API service

### CODE REVIEW

**Comment by MichaIng** [comment]
We should make this a DietPi-Globals function by times.

**Comment by Joulinar** [comment]
hmm got this one

`- WAN IP : curl: (7) Failed to connect to freegeoip.app port 443: Connection refused`

**Comment by MichaIng** [comment]
Lol, is it one the default list??

**Comment by Joulinar** [comment]
```
 Match found in https://v.firebog.net/hosts/AdguardDNS.txt:
   freegeoip.app 
```

**Comment by ravenclaw900** [comment]
It's also on https://dbl.oisd.nl/.  Seems like lots of malware uses it for IP checking.

**Comment by MichaIng** [comment]
Déjà vu, as we had the exact same issue with another provider, which was part of the reason we used ifconfig.co, if I remember right. So great, either the provider is small, so that it's potentially unreliable as well, small capacities etc, but unknown to blocklists as well, or the provider is large and reliable, with great server capacities, but then on blacklists. It seems like we have to live with downsides.

But actually I do not understand at all how such an IP/location service on a blocklist helps to block ads, malware or anything such at all. Those send the IP and location to the client, not to the website/ad provider (which naturally have your IP anyway). In the latter case the website itself does the request (e.g. use a location provider to get the location of your IP), so the blocklist does not help at all. The only thing that such an entry could prevent is a widget or such on a website which shows your IP/location, but that is not an ad and I don't know any case where you wouldn't want to see it, e.g. as part of the websites that you visit to get your IP and location info via browser.

**Comment by Joulinar** [comment]
This sum it up I guess. Personally I think we should go with your current solution as we are aware on this challenge and can react on it if needed. Furthermore people might not even notice as Pihole will run on same server as the WAN IP should be displayed. On a default set-up, the server themselves will not use Pihole as it is connected to global upstream DNS. If there are to many reports or noise we could switch again or think on our own service 😄

**Comment by MichaIng** [comment]
> On a default set-up, the server themselves will not use Pihole as it is connected to global upstream DNS.

Good point as well.

Probably a blocklist maintainer can answer the question whether/why it makes sense to block those domains: https://github.com/lightswitch05/hosts/issues/281
Else we can report those as false-positives to get them removed from the most commonly used lists.

**Comment by MichaIng** [comment]
Okay, JavaScripts loaded from the website and executed on your browser can do such API calls, and when those are bad scripts, they can misuse the info of course, send it to 3rd parties or make decisions against you, like not applying strict privacy rules when you're not living in EU with strict GDPR. The info, if wanted, can be derived from any 3rd party server-side as well, but it saves the server some load when it's done by the client and e.g. send together with other data, like the tracker request or so.

I was looking through a few cases, and never found a misuse, but instead a lot of websites which show your IP and sometimes location for your own info. The call is done in the middle of the HTML with a function callback that prints the output at the particular location in the HTML, all only client-side, so not tracking but only for visitor information. But I guess there are other particular cases, why they made it into the blocklists.

But in last consequence it means that public APIs must be blocked, as they _can_ be misused, and hence no user can easily get his/her own IP easily anymore, but every tracker/ads provider can still easily get your IP (anyway) and location by doing the request server-side or running an own database, which is what most advertising providers do anyway (like Google ads etc.). But it doesn't count what I think and we have to live with the situation that some of our users will have to manually whitelist the domain or cannot see their WAN IP.

... whitelist ... `pihole -w freegeoip.app`, that should do it, right? 😃🥳

**Pull request merged**
