### PR TITLE
Links in dietpi-software changed from phpBB to dietpi.com/docs

### PR DESCRIPTION
**Pull request by StephanStS**
**Status**: Ready
- [x] Links in dietpi-software.sh were changed from <https://dietpi.com/phpbb/> to <https://dietpi.com/docs/>.

@MichaIng:
Open point: The mechanism with "readonly FP_ONLINEDOC_URL='https://dietpi.com/phpbb/viewtopic.php?'" (see line 258 in dietpi-software.sh) need also to be changed to direct to dietpi.com/docs instead of phpBB.

### CODE REVIEW

**Comment by Joulinar** [comment]
> Open point: The mechanism with "readonly FP_ONLINEDOC_URL='https://dietpi.com/phpbb/viewtopic.php?'" (see line 258 in dietpi-software.sh) need also to be changed to direct to dietpi.com/docs instead of phpBB.

This will impact each and every software title as there is a link on each software title
`aSOFTWARE_ONLINEDOC_URL[$software_id]='p=2072#p2072'`

OnlineDocs are shown on command line
```
root@DietPi1:~# dietpi-software list |grep docker
id 162 | =0 | docker: build, ship, and run distributed applications | | https://dietpi.com/phpbb/viewtopic.php?p=9120#p9120
id 185 | =0 | portainer: simplifies container management in docker (standalone host) | | https://dietpi.com/phpbb/viewtopic.php?p=29377#p29377
root@DietPi1:~#
```

**Comment by MichaIng** [comment]
What do you think:
- Change `readonly FP_ONLINEDOC_URL='https://dietpi.com/phpbb/viewtopic.php?` to `readonly FP_ONLINEDOC_URL='https://dietpi.com/docs/software/'` and `aSOFTWARE_ONLINEDOC_URL[$software_id]='p=2072#p2072'` to `aSOFTWARE_ONLINEDOC_URL[$software_id]='desktop/#gnustep'`?
- Or `aSOFTWARE_ONLINEDOC_URL[$software_id]='https://dietpi.com/docs/software/desktop/#gnustep'` and skip that prefix variable? I think, while its a few bytes more code, it's much clearer for contributors and when adding a new software title, until the new docs have been created and uploaded our side, the official website or documentation can be added instead. E.g. for most "Additional" software titles (programming languages, editors, audio/video backends, networking tools) there are currently docs missing, which could then be added.

**Comment by Joulinar** [comment]
Option 2 might be more clear indeed.

**Comment by MichaIng** [comment]
Are you okay with the small changes I did? I think it's okay to show one install docs URL only, the other one is the next/belog page anyway. It's a bit strange to link install documentation at a stage where DietPi has been installed already. Probably it makes more sense to link the DietPi-Software documentation itself? https://dietpi.com/docs/dietpi_tools/#dietpi-software

I also switched the software list link to point to the new docs. In most cases this shortens the way of users to the information they seek. Not sure about the future of https://dietpi.com/dietpi-software.html, if it makes sense to maintain two lists forever, but that is a different topic.

I'll open a new PR to replace the individual software docs URLs.

**Comment by StephanStS** [comment]
> What do you think:
> 
>     * Change `readonly FP_ONLINEDOC_URL='https://dietpi.com/phpbb/viewtopic.php?` to `readonly FP_ONLINEDOC_URL='https://dietpi.com/docs/software/'` and `aSOFTWARE_ONLINEDOC_URL[$software_id]='p=2072#p2072'` to `aSOFTWARE_ONLINEDOC_URL[$software_id]='desktop/#gnustep'`?
> 
>     * Or `aSOFTWARE_ONLINEDOC_URL[$software_id]='https://dietpi.com/docs/software/desktop/#gnustep'` and skip that prefix variable? I think, while its a few bytes more code, it's much clearer for contributors and when adding a new software title, until the new docs have been created and uploaded our side, the official website or documentation can be added instead. E.g. for most "Additional" software titles (programming languages, editors, audio/video backends, networking tools) there are currently docs missing, which could then be added.

Like Joulinar I also prefer option 2.

**Comment by MichaIng** [comment]
Haha, many thanks for the "bid" => "bit" fix Stephan. I often see it myself now, probably 50% of cases, but hard to wean off such a long "learned" mistake 😄.

**Pull request merged**
